### ISSUE TITLE
Static theme preview not available on theme product page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10279] opened 2018-12-31 11:20 UTC
**STR:**

Open the following static theme: https://addons.mozilla.org/de/firefox/addon/future-blue/

**Actual result:**
The first theme preview size was not generated: see also the details api - https://addons.mozilla.org/api/v4/addons/addon/future-blue/

**Expected result:**
Theme preview is rendered correclty

Notes:
- reproduced on AMO prod with FF64, Win10x64
- no issues with the other preview sizes

![image](https://user-images.githubusercontent.com/31961530/50559339-9a367f00-0cfe-11e9-8a2a-497abb435fdc.png)

**Comment by eviljeff** [comment] 2019-01-08 17:21
I can't see why this happened from the logs and it works fine if I resubmit it on -dev.  I'm pretty sure it would work as a new version too

**Comment by eviljeff** [comment] 2019-01-08 17:36
pretty sure this is a dupe of #9608 given the thumbnail url is another xx000.png file (i.e. would be the first file in the xx folder)

**Closed by eviljeff** 2019-01-08 17:36 UTC
Labels: project: static themes

**Comment by AlexandraMoga** [comment] 2019-01-11 09:00
@eviljeff shouldn't the fix for #9608 have caused the preview for the theme mentioned above to be displayed now, or is there a re-index necessary in order for the fix to take effect?

**Comment by eviljeff** [comment] 2019-01-15 07:45
No, it's just a fix to stop it happening in the future.  #10391 should fix them.
