### ISSUE TITLE
WebExtension without "gecko" section is not validated in Add-on Compatibility Checker page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3806] opened 2016-10-19 13:26 UTC
Steps to reproduce:
1. Load Add-on Compatibility Checker page https://addons.allizom.org/en-US/developers/addon/check-compatibility
2. Set "Application" to Firefox and "Version" to `*`
3. Select a valid .xpi, .zip or .crx webextension archive format (that has no "gecko" section)

Expected results:
The webextension is validated.

Actual results:
Validation fails with "No Mozilla products listed as target applications" message.

Notes/Issues:
Verified on FF49(Win 7).
Screenshot for this issue: 
![2016-10-19_1550](https://cloud.githubusercontent.com/assets/15685960/19520134/ccc75102-9617-11e6-8533-0d14d69d25a1.png)

Attaching one of the used archive.
[Disconnect.zip](https://github.com/mozilla/addons-server/files/539124/Disconnect.zip)

**Comment by andymckay** [comment] 2016-10-28 22:01
Do WebExtensions with a gecko section? My last understanding was that we don't do compatibility checks on WebExtensions because all the checks are legacy add-on specific. Things could have changed since then though.

**Comment by jvillalobos** [comment] 2016-10-31 15:42
We don't do any compat checks for WebExtensions, but the compatibility checker should pass them all instead of fail.

**Comment by diox** [comment] 2017-09-25 17:54
Dupe of https://github.com/mozilla/addons-server/issues/5950

**Closed by diox** 2017-09-25 17:54 UTC
Labels: component: web extensions, triaged
