### ISSUE TITLE
Recently updated add-ons are sorted incorrectly (temporarily) in search

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9383] opened 2018-09-07 17:23 UTC
Moved over from https://github.com/mozilla/addons-frontend/issues/6148

STR:
1. Go to https://addons.mozilla.org/firefox/search/?sort=updated&type=extension
2. Click through a few of the top results and look at their update time on their product page.

You'll probably find some results that are incorrectly sorted, where they appear higher on the results list when they are not more recently updated than others that appear after them.

This appears to be a temporary problem, because they will appear correctly sorted later on. The original issue has some examples, but they're probably invalid by now.

**Comment by jvillalobos** [comment] 2018-09-07 17:54
Seemingly related to this, it looks like some add-ons don't appear on the search results right away. I was going to file a separate issue for this, but after looking at the examples that were failing before, they are working now.

**Comment by diox** [comment] 2018-09-25 14:18
I've seen this too. I wonder if it's related to the way our ES cluster is set up maybe ? @EnTeQuAk might have an idea.

**Comment by diox** [comment] 2018-10-31 13:07
I think this was a duplicate of https://github.com/mozilla/addons-server/issues/9811 so I'll close it. If you see it again after this week's push, please re-open.

**Closed by diox** 2018-10-31 13:07 UTC
Labels: component: search, priority: p3, triaged

**Comment by FatOrangutan** [comment] 2019-06-26 20:10
>it looks like some add-ons don't appear on the search results right away

I believe this is still happening.
