### ISSUE TITLE
Implement review reply in Dev Tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3147] opened 2016-07-21 20:07 UTC
This is part of #3143. The recommended UX can be seen in mozilla/addons#152.

A developer should be able to reply in the Review History of the latest version of the add-on. This is either the version pending review (if there is one), or the last version that isn't a beta.

A textbox and a Reply button should appear beneath the last message in the Review History. The developer can reply as many times as they want. The replies should appear in the history for the version in the reviewer tools, labeled as Developer Reply. The reply should be emailed to the amo-editors list and to the reviewer who sent the Info Request (if there is one).

There should also be a way to open the Status & Versions page with the Review History of the latest version open and the Reply textbox focused. Something like developers/addon/slug/versions#reply

**Comment by ValentinaPC** [comment] 2016-09-20 07:40
Verified on AMO-dev FF48.0.2(Win 7)
The "Reply" blue button is available for last version (approved or awaiting) of an addon in "Manage Status & Versions page".
Reviewer/Developer can write as many replies as he want.
Comments can be seen in Add-on review Logs page and add-on review page from Editor Tools.

Note: The add-on review pages can be broken, by entering a reply longer than the field (without spaces) - I know is unlikely to happen.
@eviljeff : what do you think? is a valid case? should we fix this?
Screenshots:
![awaiting](https://cloud.githubusercontent.com/assets/15685960/18661460/98f321e0-7f1e-11e6-96e7-8fab7b83accd.png)
![editor_tools](https://cloud.githubusercontent.com/assets/15685960/18661462/98f3f476-7f1e-11e6-866b-9b1be0e52f2f.png)
![reply](https://cloud.githubusercontent.com/assets/15685960/18661461/98f3fb74-7f1e-11e6-9dd1-2fd3547ac5eb.png)
![review_page](https://cloud.githubusercontent.com/assets/15685960/18661463/98f695a0-7f1e-11e6-9fb8-540f9826c251.png)

**Comment by eviljeff** [comment] 2016-09-20 09:36
The existing review tools being broken was logged as #3447

**Comment by ValentinaPC** [comment] 2016-09-20 11:41
Then, I can say that, the same issue is reproducing for "Reply" option.

**Comment by eviljeff** [comment] 2016-09-20 11:47
well, yes - it's the same log.

**Comment by ValentinaPC** [comment] 2016-09-26 14:09
Verified on AMO-dev FF48.0.2(Win 7)
The "Reply" blue button is **NO longer available** for last version approved or awaiting, of an add-on in "Manage Status & Versions" page.
Please see the screenshots: 
![2016-09-26_1703](https://cloud.githubusercontent.com/assets/15685960/18837178/81a4bfc0-840b-11e6-9556-dd670e7f8bae.png)
![awaiting](https://cloud.githubusercontent.com/assets/15685960/18837190/899c4806-840b-11e6-896a-e562da1006a9.png)

Reopening.

**Comment by eviljeff** [comment] 2016-09-28 14:11
The reply button is now behind the `	activity-email` waffle as the emails it would generate would contain reply-to headers and other information that isn't valid unless `activity-email` is enabled

**Comment by ValentinaPC** [comment] 2016-09-28 14:53
Oh... I thought it could be an waffle, but didn't see any ...because I was looking in the wrong place.
Thanks for clearance.

**Comment by eviljeff** [comment] 2016-09-29 16:35
Closing this again.  To keep the milestone making sense please open a fresh issue if there are any problems with this (though it may be easier to test everything together once the email gateway is available)

**Closed by eviljeff** 2016-09-29 16:35 UTC
Labels: pull request ready

**Comment by ValentinaPC** [comment] 2016-10-25 11:11
If enabling the activity-email waffle, things work as expected.
Marking this as verified-fixed.
