### ISSUE TITLE
iCloud Bookmark extension for firefox

### ISSUE THREAD

**Issue by naakavi** [mozilla/addons-server#3065] opened 2016-07-11 09:48 UTC
ICloud needs "iCloud Bookmark extension for firefox".

When I tried to download I get a message "iCloud Bookmark extension for firefox" NOT FOUND
Please help

**Comment by wagnerand** [comment] 2016-07-11 09:54
Dupe of #3027

The add-on was removed from the site due to stability problems.

**Closed by wagnerand** 2016-07-11 09:54 UTC
