### ISSUE TITLE
Cannot reject a previously approved theme

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13072] opened 2019-12-09 14:20 UTC
### Describe the problem and steps to reproduce it:

A previously approved theme version needs to be rejected (there is only one version in this case).

### What happened?

There is no open to reject.

### What did you expect to happen?

A _Reject_ or _Reject multiple versions_ button

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment] 2019-12-10 10:21
It's probably just removing this line https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/utils.py#L423 (and possibly adjusting/adding a test)

**Comment by Shivansh2407** [comment] 2020-01-12 05:52
@eviljeff @muffinresearch which of the tests need change can you please review and let me know so that I can continue to fix that too.

**Comment by eviljeff** [comment] 2020-01-13 09:06
the line number changed since I wrote the comment.  

The first step is writing something and **running it locally** to verify the change works.

**Comment by junngo** [comment] 2020-03-15 14:58
Hello @eviljeff 
I'd like some advice about test code.
I saw test case related `reject_multiple_versions`  in test_views.py.
So, Dose it just check if `Reject Multiple Versions`label is shown on the screen?
Let me know if there's a better direction.

**Comment by diox** [comment] 2020-03-15 15:43
@junngo heads up, https://github.com/mozilla/addons-server/pull/13720 will change a lot of things around reviewer actions and might inadvertently fix this issue, so I wouldn't try to fix it right now if I were you.

Once this is merged, update local environnement, and test manually by creating a theme, approving it in reviewer tools and checking if it can be rejected after that. Once you've confirmed whether the issue is still present locally or not you can work on a fix and proper test - it's likely the best approach for this would be to add a test in `reviewers/tests/test_utils.py`, and testing that the `reject` action is set to `'available': True` for a public static theme.

**Comment by junngo** [comment] 2020-03-16 11:47
Thank you :)
I gonna work on it by referring content.

**Closed** 2020-03-23 17:05 UTC
Labels: component: reviewer tools, contrib: welcome, priority: p3

**Comment by AlexandraMoga** [comment] 2020-03-24 09:33
Verified fixed on -dev. 
There is now an option to Reject multiple versions for previously approved themes:

![image](https://user-images.githubusercontent.com/31961530/77409890-b2426480-6dc2-11ea-90df-95f25def305b.png)
