### ISSUE TITLE
Average Daily Users stats is unreliable 

### ISSUE THREAD

**Issue by jzav** [mozilla/addons-server#6974] opened 2017-11-21 17:46 UTC
Because too many days end with 0 users. Can you please look into it?
Stats also are not available daily. Sometimes it takes up to three days to show new data.
It would also be nice if data are ready at the same time every day.
Other suggestion: add some legends at stats page. As to what exactly is daily user, how is this number counted etc.
What does the Downloads mean? Is clicking Add to Firefox button enough to increase this number or is this process more elaborate?
And what are Top Applications/Languages/Platforms figures? How are they counted? How is it possible that sum number of one category differs from other? And from daily users number?

**Comment by jvillalobos** [comment] 2017-11-21 21:01
Closing as duplicate of https://github.com/mozilla/addons/issues/510

**Closed by jvillalobos** 2017-11-21 21:01 UTC

**Comment by jzav** [comment] 2017-12-12 21:48
Thank you for reference to https://github.com/mozilla/addons/issues/510.
But my post is not a complete duplicity. See other suggestions:
Add some legends at stats page. As to what exactly is daily user, how is this number counted etc.
What does the Downloads mean? Is clicking Add to Firefox button enough to increase this number or is this process more elaborate?
And what are Top Applications/Languages/Platforms figures? How are they counted? How is it possible that sum number of one category differs from other? And from daily users number?
So can you please reopen? If this is right place to discuss this, of course.

**Comment by jvillalobos** [comment] 2017-12-13 15:51
You can use the forum for discussion: https://discourse.mozilla-community.org/c/add-ons
