### ISSUE TITLE
Search results will not return searched collection

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6137] opened 2017-08-09 16:02 UTC
Steps to reproduce:
1. Search for a collection using it's exact name i.e. "Webdev Toolbox - Ivan Krstić"

Expected results:
The collection is listed as first result.

Actual results:
Collection is listed through results, but is hard to be found. 

Notes/Issues:
Verified on FF54(Win 7). Issue is reproducing on all servers.
Video for this issue:
![coll](https://user-images.githubusercontent.com/15685960/29131325-38c3627e-7d35-11e7-963c-247ac0aa829c.gif)

**Comment by EnTeQuAk** [comment] 2017-08-18 17:58
This is about boosting exact matches more, this got better with recent fixes but we still ignore exact matches mostly. I'll work on this next week with other issues.

**Comment by muffinresearch** [comment] 2018-02-02 19:22
Maybe a duplicate of https://github.com/mozilla/addons-server/issues/6837 ?

**Comment by eviljeff** [comment] 2018-07-19 20:00
We dropped searching for collections all together so I think this is a wontfix now.

**Closed by eviljeff** 2018-07-19 20:00 UTC
Labels: component: search, priority: p3, triaged
