### ISSUE TITLE
Server error when trying to make a contribution

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3182] opened 2016-07-27 12:24 UTC
### Steps to reproduce:
1.  Open https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular
2. Click on the Contribute button
3.  Check the one time contribution option an click the Make Contribution button.

### Expected results:
The user can complete a contribution.

### Actual results:
The contribution can't be completed, the request is failing with a 500 error.

### Notes/Issues:
Verified in FF47(Win7) issue can be reproduced in amo-dev and amo-stage
Screenshot for this issue:
![contribution](https://cloud.githubusercontent.com/assets/15685441/17175049/0bb94cfe-540e-11e6-8ddd-954b8093e5f9.png)

**Comment by muffinresearch** [comment] 2016-07-28 08:36
This was raised earlier but marking this one a dupe since the newer bug has sentry info. 

Duplicate of #3188

**Closed by muffinresearch** 2016-07-28 08:36 UTC
