### ISSUE TITLE
Add-on count in 'featured-personas' collection on the new frontend is wrong

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8669] opened 2018-06-27 09:50 UTC
STR:

1. Visit the featured-personas collection on AMO - https://addons.mozilla.org/en-US/firefox/collections/mozilla/featured-personas/
2. Observe the add-on count
3. Go to the next page
4. Check the add-on count again

Actual result:
The count is broken when the user first lands on the collection details page (a higher number than the actual number is displayed)

Expected result:
The correct number of add-ons is displayed when the user first lands on the featured-personas collection details page

Notes:
- the count seems to be broken at the api level. When sendig the below request, the response returns `addon_count`:`61` while the actual number of add-ons listed on the site is 30.
```
https://addons.mozilla.org/api/v3/accounts/account/mozilla/collections/featured-personas/?with_addons
```
 The results in the api seem to be duplicated. The same add-on id's can be found on the next pages as well. 
- the legacy site shows the correct number of add-ons
- reproduced on all AMO servers with FF60, Win10x64

![wrong count](https://user-images.githubusercontent.com/31961530/41966580-24937fc0-7a08-11e8-95d6-eb6af81d2345.gif)

**Comment by diox** [comment] 2018-06-27 15:33
See also https://github.com/mozilla/addons/issues/740

**Comment by diox** [comment] 2018-06-27 15:35
Dupe of https://github.com/mozilla/addons-server/issues/8065 actually

**Closed** 2018-11-12 18:59 UTC
Labels: component: api, component: collections, priority: p3, state: duplicate
