### ISSUE TITLE
Do not display hidden or disabled add-ons in collections

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2971] opened 2016-06-22 19:52 UTC
If an add-on is disabled or hidden (or even deleted), we should not show it in any collections as they are not accessible anyway.

**Comment by EnTeQuAk** [comment] 2016-10-06 14:22
Do you have any specific examples for this @wagnerand? According to our code at least it seems we filter them properly.

**Comment by wagnerand** [comment] 2016-10-06 15:28
Hm, this is quite old. We used to have an example on prod (with the featured add-ons collection) but that has been worked around by removing the add-on from the collection.

**Comment by ValentinaPC** [comment] 2016-11-09 14:51
Hidden or disabled add-ons can be found in Edit Information - Technical details section from Dev Hub, while searching for "required add-ons" (but changes cannot be saved)
Please see the screenshot for a hidden add-on: 
![2016-11-09_1650](https://cloud.githubusercontent.com/assets/15685960/20142263/abfb844e-a69c-11e6-8875-53693f6ecd3d.png)

**Comment by wagnerand** [comment] 2016-11-09 15:25
@ValentinaPC this issue is about hiding (or at least marking) hidden or disabled add-ons *in the edit collection* view.

**Comment by ValentinaPC** [comment] 2016-11-09 15:43
**I know** what this issue is about.
I've added the comment, in the ideea that, maybe, here too is the same root cause and wanted to help improve how AMO works.

**Comment by wagnerand** [comment] 2016-11-09 15:48
Ah now I understand, thanks. I think it would be better to open a separate issue for that, it's a bit confusing.
Given your screenshots it seems unlikely they have the same root cause. Thank you for letting us know though, I didn't even know that's an issue.

**Comment by muffinresearch** [comment] 2018-02-02 16:34
@eviljeff is this already handled in the collections API? If so we can probably think about wont-fixing this on the basis it won't happen in the new UI.

**Comment by eviljeff** [comment] 2018-02-02 17:31
The API supports both excluding deleted add-ons, and including them (default is to exclude).  

However, it's an open question if the _edit collection_ UI should display them or not.  (The subject and first comment of the issue implies it's about collection view, but in https://github.com/mozilla/addons-server/issues/2971#issuecomment-259440985 @wagnerand says it's about editing collections.)

**Comment by davidhedlund** [comment] 2018-03-21 16:43
I think a background color should be used to indicate obsoleted add-ons.

### Describe the problem and steps to reproduce it:
Edited my [WebExtensions](https://addons.mozilla.org/en-US/firefox/collections/DavidHedlund/webextensions/) collection.

I discovered that [Nano Defender](https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/) has been removed from addons.mozilla.org, removed add-ons should be indicated with a pink background when I edit my collection so I can maintain them properly.

### What happened?
![screenshot from 2018-03-04 23 36 49](https://user-images.githubusercontent.com/6416073/36951504-eec9fd4a-2004-11e8-8f24-840574a2cf64.png)

### What did you expect to happen?
![demo](https://user-images.githubusercontent.com/6416073/36951551-85402d1c-2005-11e8-9629-e185f7a198bc.png)

**Comment by eviljeff** [comment] 2018-03-21 18:00
I'm going to close this issue as addon-server API is functional, and the legacy frontend collection edit screens are deprecated.  If something needs addressing in addons-frontend for the new edit collection screens it's best to file a new issue there.

**Closed by eviljeff** 2018-03-21 18:00 UTC
Labels: component: collections, component: legacy frontend, needs: info, priority: p3, triaged

**Comment by davidhedlund** [comment] 2018-04-04 13:56
@eviljeff 
>  If something needs addressing in addons-frontend for the new edit collection screens it's best to file a new issue there.

Where do I submit that?

**Comment by eviljeff** [comment] 2018-04-04 14:18
@davidhedlund https://github.com/mozilla/addons-frontend/ but I'm not sure if the collection edit implementation is finished there yet.

**Comment by davidhedlund** [comment] 2018-04-04 14:28
@eviljeff Thanks. I'll file it much later then just to make sure.
