### ISSUE TITLE
Mark user as being deleted from AMO

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18853] opened 2022-02-17 13:46 UTC
Followup for https://github.com/mozilla/addons-server/issues/18773#issuecomment-1042955228

1. fxA users are being recognized when they're being deleted into the admin Activity Log. It should be the same for users deleted from AMO

deleted from fxA:

![deleted from fxA](https://user-images.githubusercontent.com/33448286/154494405-e6dd25e8-4038-43ee-be9b-591b711dff0d.png)

deleted from AMO: 

![deleted from AMO](https://user-images.githubusercontent.com/33448286/154494453-e63feaa7-3e3e-4a01-bdb4-c646e2548641.png)

**Comment by eviljeff** [comment] 2022-02-17 14:50
"Neither of these users are marked as deleted on AMO. We should follow up on that." @wagnerand apparently the issue is the text description of the activity?  (not that the user account itself is marked/updated to be deleted)

These are the text strings used:
https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/activity.py#L400:L407

(I didn't update the activty for deleting from AMO directly as it seemed like the default?  But we can?)

**Comment by wagnerand** [comment] 2022-02-17 14:55
@eviljeff sorry what I meant is that the user is not actually deleted (`UserProfile.deleted` is 0), according to the django admin userprofile page.

**Comment by eviljeff** [comment] 2022-02-17 15:30
Selected logs:

> 2022-02-17 12:46:27.388 GMT
User (11687476: test1: <deletethis1@mailinator.com>) is being anonymized.
>
> 2022-02-17 12:46:27.400 GMT
Anonymizing username for 11687476
>
> 2022-02-17 12:46:27.441 GMT
Account pk [11687476] deleted from FxA on 2022-02-17 12:46:27.062277
>
> 2022-02-17 12:48:41.453 GMT
Re-created deleted user 11687476: anonymous-f3a3966632a23962d6b55b4d81a95944 from FxA
>
> 2022-02-17 12:48:41.454 GMT
Updating user info from FxA for 11687476. Old deletethis1@mailinator.com 15da41122b724bdbadfde6a2a7360232 New deletethis1@mailinator.com ee44d403413f48c3a84ec09452a0a661
>
> 2022-02-17 12:48:41.463 GMT
Logging in user 11687476: anonymous-f3a3966632a23962d6b55b4d81a95944 from FxA

i.e. looks what happened is:
- FxA was deleted which triggered the AMO to be deleted (it was)
- FxA account was recreated using the same email, and was logged in to AMO, which caused the AMO account to be re-created and effectively undeleted.

**Comment by ioanarusiczki** [comment] 2022-02-17 15:32
@eviljeff I might be guilty for that, I've done lots of testing around fxA today , deleted stuffs.

**Comment by diox** [comment] 2022-02-24 10:57
Is there an actual bug here or should this be closed ?

**Comment by eviljeff** [comment] 2022-02-24 11:00
I don't think there's a bug, from what I could see from the logs

**Closed** 2022-02-24 11:02 UTC
