### ISSUE TITLE
prevent info requests on deleted addons, or addons without versions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#4760] opened 2017-02-23 18:33 UTC
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/381332/

ActivityMail fails if there isn't a version on the addon, or the addon is deleted.

#3726

**Comment by ValentinaPC** [comment] 2017-02-24 08:00
I've also logged this yesterday: #4754 . Are you talking about the same thing? Thanks!

**Comment by eviljeff** [comment] 2017-02-24 09:56
yeah, same thing.

**Comment by ValentinaPC** [comment] 2017-04-26 11:47
Verified this on AMO-dev FF53(Win 7).
On the review page of a deleted add-on there are 2 options:
- Request super-review
- Comment
The first one, still replies a 500 error page.
The same happens for add-ons with no versions.
Please see the video:
![500](https://cloud.githubusercontent.com/assets/15685960/25432910/1a64e08a-2a8f-11e7-8b55-5ddab24b46d6.gif)

Reopening.

**Comment by diox** [comment] 2017-04-26 11:51
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/381333/

**Comment by eviljeff** [comment] 2017-04-26 12:00
well, I only fixed __info requests__ as per this issue

**Comment by ValentinaPC** [comment] 2017-04-26 12:25
I've reopened this only because https://github.com/mozilla/addons-server/issues/4754 was marked as dupe of this one, and that bug mentioned both requests (info and super).
Thanks for you quickly reply! :)

**Closed** 2017-05-04 11:17 UTC
Labels: component: reviewer tools, state: pull request ready, triaged

**Comment by eviljeff** [comment] 2017-05-05 14:52
I'm not sure if it's intended or not - the behaviour of review pages for deleted add-ons has never been defined - but it's as now on prod as far as I can see.  One thing is the comment is always counted as listed, even if you do the comment via the review-unlisted page.  
You can log a follow-up issue if you want... though given it's priority I'm not sure if it'll ever be fixed.

**Comment by ValentinaPC** [comment] 2017-05-08 08:03
Marking this verified-fixed.
