### ISSUE TITLE
[traceback] UndefinedError: 'olympia.addons.models.Addon object' has no attribute 'persona'

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-server#2501] opened 2016-04-25 23:47 UTC
https://addons.allizom.org/en-US/firefox/collections/ValS/weird-collection/ throws an HTTP 500:

UndefinedError: 'olympia.addons.models.Addon object' has no attribute 'persona'
  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "olympia/amo/decorators.py", line 240, in wrapper
    return f(request, username, *args, **kw)
  File "olympia/bandwagon/views.py", line 247, in collection_detail
    'tags': tags, 'user_perms': user_perms})
  File "olympia/bandwagon/views.py", line 132, in render_cat
    return render(request, template, data, **extra)
  File "django/shortcuts.py", line 50, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "jingo/__init__.py", line 99, in render
    return super(Template, self).render(context_dict)
  File "newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/olympia/src/olympia/bandwagon/templates/bandwagon/collection_detail.html", line 196, in top-level template code
    <p>{{ _('My favorite add-ons') }}</p>
  File "/data/olympia/src/olympia/../../src/olympia/templates/base.html", line 128, in top-level template code
    {% block main_content %}
  File "/data/olympia/src/olympia/../../src/olympia/templates/base.html", line 131, in block "main_content"
    {% block content %}{% endblock %}
  File "/data/olympia/src/olympia/bandwagon/templates/bandwagon/collection_detail.html", line 96, in block "content"
    {% cache addons.object_list %}
  File "olympia/amo/ext.py", line 18, in _cache_support
    return caller()
  File "/data/olympia/src/olympia/bandwagon/templates/bandwagon/collection_detail.html", line 106, in template
    {{ persona_grid(addons.object_list) }}
  File "jingo/__init__.py", line 225, in wrapper
    t = get_env().get_template(template).render(context)
  File "jingo/__init__.py", line 99, in render
    return super(Template, self).render(context_dict)
  File "newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/olympia/src/olympia/addons/templates/addons/persona_grid.html", line 4, in top-level template code
    {{ persona_preview(addon.persona, size='small', details=True) }}
  File "jingo/__init__.py", line 224, in wrapper
    context = f(*args, **kw)
  File "olympia/addons/helpers.py", line 266, in persona_preview
    preview_map = {'large': persona.preview_url,

Sentry: https://sentry.prod.mozaws.net/operations/olympia-stage/issues/323218/

**Comment by EnTeQuAk** [comment] 2016-04-27 15:49
This is very probably happening because of us upgrading to Jinja 2.8 somehow. I'll investigate.

**Comment by andymckay-limited-access** [comment] 2016-04-27 16:43
This has been happening for a long time, I don't think its Jinja 2.8, check in sentry to see how long its been going on. I think it was the getpersonas migration.

**Comment by EnTeQuAk** [comment] 2016-04-27 16:52
Oh really? Last time I looked it looked like it started happening after
dj17 but maybe I'm messing things upup.
 
 
On Wed, Apr 27, 2016, at 06:43 PM, andymckay-limited-access wrote:
> This has been happening for a long time, I don't think its Jinja 2.8,
> check in sentry to see how long its been going on. I think it was the
> getpersonas migration.
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/mozilla/addons-server/issues/2501#issuecomment-215143276

**Comment by andymckay** [comment] 2016-05-03 18:43
Duplicate of #1282.

**Closed by andymckay** 2016-05-03 18:43 UTC
Labels: duplicate, triaged
