### ISSUE TITLE
Image Gallery for previously submitted versions is not displayed for the reviewer

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7868] opened 2018-03-21 10:41 UTC
STR:
1. Load AMO dev and submit a static theme.
2. Approve the first version and then submit another one. 
3. Go to the Listed Review page.
4. Check for Image Gallery.

Expected result:
An Image gallery with screenshots of previous submitted versions is available for the reviewer.

Actual result:
Only the last screenshot of the last submitted version is available. 

Notes:
This issue is reproducible on AMO dev with FF59 (Win10).

![image gallery](https://user-images.githubusercontent.com/33448286/37705535-091a03cc-2d05-11e8-8a5c-3d4c3cac4cac.png)

**Comment by eviljeff** [comment] 2018-03-21 12:16
It's not a bug per se  - I didn't intend the review page to show the previews for previous versions, only the one under review.

**Comment by eviljeff** [comment] 2018-03-21 15:13
@jvillalobos to comment/close

**Comment by jvillalobos** [comment] 2018-03-21 18:44
The current theme review tool doesn't allow to look at past versions or diff, and generally a theme diff wouldn't be that useful, so I think we can close this.

**Closed by jvillalobos** 2018-03-21 18:44 UTC
Labels: needs: info, needs: product, priority: p4, project: static themes, type: bug
