### ISSUE TITLE
Recently popular and Newest collections are displayed in the exactly same order

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1830] opened 2016-03-03 13:13 UTC
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0

Steps to reproduce:
1.Compare Recently Popular(https://addons.allizom.org/en-US/firefox/collections/?sort=popular) with Newest(https://addons.allizom.org/en-US/firefox/collections/?sort=created) collections

Expected results:
Recently popular should display only collections with recently followers or votes and Newest should show collections based on creation date

Actual results:
Both sections will display collections based on creation date

**Comment by eviljeff** [comment] 2016-06-28 16:23
is this reproducible on prod?

**Comment by vcarciu** [comment] 2016-06-29 14:59
@eviljeff  : no , this is not reproducible on prod

**Comment by EnTeQuAk** [comment] 2016-07-05 19:51
I cannot reproduce this on stage now too. Clicking both links show exactly the expected result (sorted by creation date and sorted by some kind of popularity). Am I missing something or is this a wont-fix?

**Comment by EnTeQuAk** [comment] 2016-07-07 08:50
Closing as "works for me" but please feel free to reopen at any time if the issue persists.

**Closed by EnTeQuAk** 2016-07-07 08:50 UTC

**Comment by vcarciu** [comment] 2016-07-07 09:53
I can confirm that this is not reproducible anymore on stage. Thanks

**Comment by eviljeff** [comment] 2016-07-07 16:14
Any sort based on popularity is going to be potentially broken on dev and stage because there aren't any users downloading/using the addons/collections from those sites, unlike prod.  And/or the daily cron jobs that calculate the popularity doesn't run.
