### ISSUE TITLE
Icloud Bookmark

### ISSUE THREAD

**Issue by jhferguson5** [mozilla/addons-server#3158] opened 2016-07-24 16:33 UTC
I'm following a link in iCloud for the iCloud Bookmark extension for Firefox, however I end up receiving a page with an error message that the page I'm looking for can't be found.  Is the iCloud Bookmark extension no longer available?

**Comment by muffinresearch** [comment] 2016-07-25 10:31
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by muffinresearch** 2016-07-25 10:31 UTC
