### ISSUE TITLE
File browser still not showing all files

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#4316] opened 2017-01-17 10:59 UTC
### What happened?
* Visit https://addons.mozilla.org/en-US/firefox/files/browse/565054/
* Not all files are visible, e.g. install.rdf, chrome.manifest

### What did you expect to happen?
* All files should be visible

<img width="1058" alt="image" src="https://cloud.githubusercontent.com/assets/607198/22017801/1246e488-dcac-11e6-974c-443223464950.png">

See also #3579.

**Comment by EnTeQuAk** [comment] 2017-01-17 16:11
Short term idea I came up with (won't make it till the tag though, that's just too close):

We still have a cache in front of the extracted file-list despite the fact that the whole file-browser is cached too. Let's remove this and rely solely on the http-cache to get more reproducability.

Long term idea:

Maybe we should start thinking about exposing a file-list from amo-validator and addons-linter to have a 2-factor verification for the file list if this keeps bugging us.

**Comment by EnTeQuAk** [comment] 2017-01-17 16:14
@jasonthomas I couldn't find any error either in sentry or in kibana for this extraction, only that it apparently succeeded. But something had to go wrong. I do have https://sentry.prod.mozaws.net/operations/olympia-prod/issues/367360/ which is for another add-on and doesn't show any usable data but maybe it's hint for something. Are

**Comment by EnTeQuAk** [comment] 2017-01-17 16:26
More ideas for improvements to make this more stable: At the moment there is a potential problem, edge-case, time-window of us doing a i/o operation in code, that i/o being committed the python code resumes, fetches the file-list but EFS or so didn't yet finish all the operations and returns half-ready things which we are caching for ~2 hours then. The short term idea above will help with this but long term it needs more intelligent locking and potentially a actual file-system lock since explicit is better than implicit.

**Comment by EnTeQuAk** [comment] 2017-01-18 19:01
We talked about this for a bit and we agreed to try to move the locking mechanism out of the cache and to the file-system. I do not expect any performance related problems and even so it's probably better than the potential security bummer that we're facing right now.

This will be pushed next week, we don't want to change too many things at once to make sure we can debug this easier and better week-by-week and problem-by-problem. Since what we are seeing isn't reproducable at all locally that appears to be the only reasonable way at the moment unfortunately.

**Closed** 2017-01-23 17:28 UTC
Labels: in progress, priority one, reviewer tools, triaged
