### ISSUE TITLE
iCloud issue - broken download and/or link

### ISSUE THREAD

**Issue by Drakonix-S** [mozilla/addons-server#3159] opened 2016-07-24 17:47 UTC
iCloud claims yo need to download something which then takes me to a broken link and ends up asking me to report the issue.

![icloud issue](https://cloud.githubusercontent.com/assets/20628025/17085407/fc87bbc6-51ce-11e6-886e-9e7cd24cef16.png)

**Comment by muffinresearch** [comment] 2016-07-25 10:32
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by muffinresearch** 2016-07-25 10:32 UTC
