### ISSUE TITLE
Enable customs in production

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13059] opened 2019-12-06 12:16 UTC
This issue does not have a patch attached to it because it is only a config change. We need to run this command:

```
./manage.py waffle_switch enable-customs on
```

**For QA:** the `customs` scanner has been enabled in stage on December 6th, and will be enabled in prod after the push (December 12th). This means new submissions will be scanned by `customs` and there should be scanner results with scanner=customs in the admin.

**Comment by AlexandraMoga** [comment] 2019-12-09 16:00
I've verified the `customs` scanner on stage by submitting various add-on types,  doing some load testing (including large file submissions) and the scanner admin functionality as a whole.

@willdurand also helped with investigating an issue with add-on version not being created when using the signing API to submit large add-ons (~20Mb) and we concluded that the issue was not caused by `customs` or other scanner but by a timeout from the linter.

**Comment by muffinresearch** [comment] 2019-12-18 16:30
Closing this out because it's on prod now.

**Closed by muffinresearch** 2019-12-18 16:30 UTC
Labels: component: scanners, priority: p1
