### ISSUE TITLE
Don't block legacy add-ons to be submitted as updates to WebExtensions for unlisted

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3599] opened 2016-09-23 16:26 UTC
#3061 introduced a blocking error that makes sense for listed add-ons, but not necessarily for unlisted. I've been contacted by a developer who has two unlisted update branches, using the same ID, one of which is a WebExtension. Trying to update the non-WebExtension showed the error and they can't update that branch now. Let's just show a warning for unlisted add-ons.

**Comment by ValentinaPC** [comment] 2016-10-04 14:19
An add-on cannot be added as an upgrade to an unlisted web-extension.
Verified on AMO-dev FF49 (Win 7).

An error message is displayed when "Add version" button is clicked and the web console shows a 404.
![add](https://cloud.githubusercontent.com/assets/15685960/19077654/28a5a384-8a56-11e6-93f1-ee0fc70fb78d.png)

Reopening.

**Comment by markus-hartung-avira** [comment] 2016-10-04 15:20
You are correct, an addon can't update from web extensions to something else, but our use case was different. We currently have both a web extensions and bootstrapped version of our add-on on the same id but with different update URLs, the problem was that after a recent update of the addons-server we weren't able to sign our bootstrapped build anymore. We are only migrating users from bootstrapped to web extensions, but did not want to migrate everyone at once.

**Comment by EnTeQuAk** [comment] 2016-10-04 19:02
Hmm, I'm pretty sure neither is related to this ticket or the upgrade warning / error in general. But I'm not yet sure what's the actual problem

**Comment by ValentinaPC** [comment] 2016-10-05 08:08
The web-extension had no ID and I've added to the upgrade add-on the automatically generated id....maybe that's the case of 404.

I'll attach used web-extension and add-on. 
Web-extension: 
[Love-O&#39;Clock_v1.0.7.zip](https://github.com/mozilla/addons-server/files/510373/Love-O.39.Clock_v1.0.7.zip)
Add-on:
[vk_music_downloader-1.0.3-fx.zip](https://github.com/mozilla/addons-server/files/510375/vk_music_downloader-1.0.3-fx.zip)

**Comment by EnTeQuAk** [comment] 2016-10-28 13:34
It could be that this is being fixed with the pull request for https://github.com/mozilla/addons-server/issues/3679 - let's wait for it to land and verify.

**Comment by wagnerand** [comment] 2016-11-08 18:14
This looks like it's fixed.

**Comment by ValentinaPC** [comment] 2016-11-09 09:06
This issue is still reproducing.
Used the same extensions attached above, with another automatically generated ID on AMO-dev FF49.0.2 (Win 7) and I am receiving the same error when I click "Add version" button.
Please see the screenshot: 
![2016-11-09_1103](https://cloud.githubusercontent.com/assets/15685960/20132626/828a45bc-a66c-11e6-8f44-00be03c5d6b2.png)

**Comment by markus-hartung-avira** [comment] 2016-11-09 12:00
For our usecase this issue is now resolved using the API we can sign both bootstrapped and webext versions now.

**Comment by wagnerand** [comment] 2016-11-09 12:44
@ValentinaPC What does the install manifest for the add-on you tried to upload look like?

**Comment by ValentinaPC** [comment] 2016-11-09 13:44
@wagnerand Both, add-on and webext, are attached in my comment from Oct 5.

**Comment by markus-hartung-avira** [comment] 2016-11-09 13:47
Unfortunately it seems that we were only able to sign one build, now it is failing again, might have had something to do with the manual signing that was done before.

**Comment by wagnerand** [comment] 2016-11-09 13:53
@ValentinaPC `vk_music_downloader-1.0.3-fx.zip` has an invalid `minVersion` in its `install.rdf`. A `minVersion` must always be a precise version (no wildcards).

**Comment by ValentinaPC** [comment] 2016-11-09 15:27
@wagnerand : Changing the `minVersion` to `25.0` and the `maxVersion` to `52.0` returned the exactly same results.

**Comment by jvillalobos** [comment] 2017-01-25 23:10
I just ran into this problem with an unlisted add-on. Worse, the validator only showed warnings, so it wasn't obvious what the reason was behind the failure. The Continue button was still enabled, and only after clicking on it a generic error message appeared.

**Comment by muffinresearch** [comment] 2017-02-08 11:28
@EnTeQuAk when you have a moment could you investigate these new reports pls?

**Comment by EnTeQuAk** [comment] 2017-02-08 12:02
I'll take a look at this

**Comment by wagnerand** [comment] 2017-03-01 17:05
Fixed, see #4810.

**Closed** 2017-03-01 17:05 UTC
Labels: triaged

**Comment by ValentinaPC** [comment] 2017-03-02 10:11
Verified as fixed on AMO-dev FF51(Win 7).
Updates for unlisted from webext to legacy add-on work as expected.
Postfix screenshot:
![webext-to-legacy](https://cloud.githubusercontent.com/assets/15685960/23502666/46d08396-ff41-11e6-9132-efa9abbd3d97.png)


Also, tried updates from:
- listed webext to listed legacy add-on - does not work - expected
- listed webext to unlisted legacy add-on - works - expected?
- unlisted webext to listed legacy add-on - works - expected?

@wagnerand : I need confirmation for last two case. Thanks!

**Comment by ValentinaPC** [comment] 2017-03-02 10:15
Marking this verified-fixed based on #4810 fixing.
Thanks!

**Comment by wagnerand** [comment] 2017-03-02 10:36
> listed webext to listed legacy add-on - does not work - expected
> listed webext to unlisted legacy add-on - works - expected?
> unlisted webext to listed legacy add-on - works - expected?

Yes, all of that is expected.
