### ISSUE TITLE
"Confirm approval" button not available

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#6960] opened 2017-11-20 11:40 UTC
I reviewed an e-mail notification for an updated add-on, and when I visit [the review link](https://reviewers.addons.mozilla.org/en-US/editors/review/open-tab-count-resurrected), I see that the add-on had been updated from a SDK add-on to a WebExtension, and that it was auto-approved (with weight 0).

### What happened?
There is no "Confirm approval" button (only "Reject Multiple versions").

### What did you expect to happen?
I should see a "Confirm approval" button, just like any other extension that I can review.

**Comment by diox** [comment] 2017-11-20 11:45
That add-on is in a weird state... somehow its current version is not the last approved one. 

Another side-effect is that its public listing page marks it as incompatible with Firefox 57, since it's still displaying the older version. The public versions page displays the webextension (3.0) correctly though.

**Comment by ValentinaPC** [comment] 2017-11-20 13:18
I observed the absence of this button for an add-on that had the last version disabled.

Not completely sure, but I think this is tracked somewhere - found it: https://github.com/mozilla/addons-server/issues/6545

Example:
https://reviewers.addons-dev.allizom.org/en-US/editors/review/no-confirm-approval

**Comment by ralli007** [comment] 2017-11-20 14:03
approval button missing.

https://reviewers.addons.mozilla.org/en-US/editors/review-content/goodreads-ratings-for-amazon

**Comment by diox** [comment] 2017-11-20 14:47
For add-ons that have their latest version disabled, it's different. That's probably https://github.com/mozilla/addons-server/issues/6894

**Comment by ValentinaPC** [comment] 2017-11-21 07:44
> For add-ons that have their latest version disabled, it's different. That's probably #6894

Not seeing the button, I described the observed situation. 
Different....and no so different - because the "Confirm Approval" option is not available in both cases. 
Also, the example I gave is from Auto-Approval queue, not from Content Review, as the issue you mentioned.

**Comment by diox** [comment] 2017-11-28 18:32
Closing as a dupe of #6962 which was submitted a tiny bit after this one but has more info.

**Closed by diox** 2017-11-28 18:32 UTC
