### ISSUE TITLE
Uploaded an addon

### ISSUE THREAD

**Issue by fireinnti** [mozilla/addons-server#3885] opened 2016-10-27 20:55 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Tried to upload addon
### What happened?
when trying to download it it went to page not found
### What did you expect to happen?
installation of addon
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/firefox/mnt/efs/addons.mozilla.org/files/744863/task_creator-1.311-an%2Bfx-windows.xpi

**Comment by andymckay** [comment] 2016-10-27 21:25
Dupe of #3883

**Closed by andymckay** 2016-10-27 21:25 UTC
