### ISSUE TITLE
[needs STR] Account missing associated content after FxA migration

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1613] opened 2016-02-03 19:50 UTC
One of the accounts which had multiple add-ons and themes associated with it lost all the associated content after migrating to FxA.
## account:
krupa.mozbugs+90@gmail.com - https://addons-dev.allizom.org/en-US/firefox/user/anonymous-15f2917e5d7f2c2f4040bd2837bdc836/

All the add-ons associated with that account now show up with no dev info:
* https://addons-dev.allizom.org/en-US/firefox/addon/bookmark-manager/
* https://addons-dev.allizom.org/en-US/firefox/addon/shutterstock-tab/?src=cb-dl-created
* https://addons-dev.allizom.org/en-US/firefox/addon/downthemall1/?src=cb-dl-created

## screenshots:
fake email showing add-ons associated with the email id: https://www.dropbox.com/s/5ppmpv7sd0f0dpe/Screenshot%202016-02-03%2011.42.33.png?dl=0

I will add STR once I figure out what happened to this specific account.

**Comment by vcarciu** [comment] 2016-02-04 16:41
We tried the migration with many accounts, with addons, themes, webext , collections and different settings attached to the account, but we were not able to reproduce what you saw in this bug.

We also tried the migration without changing anything in the Account Settings, and adding just some add-ons. But still cannot reproduce your issue and developer is seen as "Anonymous".

**Comment by mstriemer** [comment] 2016-02-04 16:50
I looked in the database and the user and the add-ons have no authors, as expected.

I see the shutterstock-tab add-on was created `2016-01-11 11:45:43` and the user was created `2016-02-02 19:36:11`. Is this expected?

Looking through the logs I see that the add-on was created by a user with a username `gloriaaaaaa` who I found later logged out as `User (10620996: gloria esteban) logged out`. There is no user with the id `10620996` in the database currently.

Looking for the logs for the `gloriaaaaaa` user I see that it was created as an AMO account and then later I see a few `Conflict finding user during FxA login. request.user: 10620996, identity_user: 10621016`. Then I see the user log out and back in a few times.

I don't see anything deleting the user, so this is pretty strange. I'm not sure how the user disappeared.

**Comment by krupa** [comment] 2016-02-04 21:22
I see the shutterstock-tab add-on was created 2016-01-11 11:45:43 and the user was created 2016-02-02 19:36:11. Is this expected?

yes. I migrated to Fxa recently which is when I saw that the account was missing all related info.

**Comment by andymckay** [comment] 2016-02-04 21:38
Confused how the account is created after the add-on. But it sounds like the reliability of -dev is letting us down here. Maybe see if we can reproduce on stage where things are more stable?

**Comment by mstriemer** [comment] 2016-02-04 21:44
I don't see these add-ons ever having anything to do with user `10621372 - krupa.mozbugs+90@gmail.com`. I agree that this seems like some sort of data issue. The user that created these add-ons seems to have vanished without a trace.

**Comment by vcarciu** [comment] 2016-02-09 15:27
Please note that we were not able to reproduce this on Stage too

**Comment by andymckay** [comment] 2016-02-09 17:14
Closing based on last comment.

**Closed by andymckay** 2016-02-09 17:14 UTC
Labels: 47.3, FxA
