### ISSUE TITLE
theme update service should serve details of static theme xpi for migrated LWT

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7976] opened 2018-04-04 16:53 UTC
The LWT update service should - in addition to serving updated metadata for installed themes - return a link to replacement static theme when LWT has been migrated to a static theme.

The expectation is that a LWT itself would be deleted as part of the migration so typically the update would _either_ return the existing LWT JSON response _or_ some JSON detailing the new static theme xpi.

#7223 will replace the existing RDF format extension update service with a JSON response but as this will come from theme update it doesn't need to be the same.

e.g.
```
 {
     "converted_theme": {
        "url": "https://blah/blah/newtheme.xpi",
        "hash": "abcd"
    }
}
````

We're going to have to maintain this until - at least - ESR60 goes out of support because potentially those users would have LWT that we want to update (eventually!)

**Comment by aswan** [comment] 2018-04-04 17:36
The sibling browser-side work is tracked at:
https://bugzilla.mozilla.org/show_bug.cgi?id=1430276

**Comment by eviljeff** [comment] 2018-04-05 06:26
@aswan Ideally this would be supported in Firefox release at the point we start mass-migrating LWT so users are migrated locally at the same time AMO migrates.  Do you know when the browser-side work is expected to land?

**Comment by aswan** [comment] 2018-04-05 16:40
> @aswan Ideally this would be supported in Firefox release at the point we start mass-migrating LWT so users are migrated locally at the same time AMO migrates. Do you know when the browser-side work is expected to land?

We haven't scheduled it but really its just a choice between 61 or 62.  61 releases on 6/26 and 62 releases on 8/21.  Should we make this a priority for 61?

**Comment by eviljeff** [comment] 2018-04-06 07:52
62 is fine - that coincides with when 52ESR goes out of support so when we were planning to do the migration.

**Comment by eviljeff** [comment] 2018-07-10 12:15
QA:
* Select two LWT from addons-dev.  (Or more - we need at least one we are going to migrate, and at least one we aren't.)
* Install them both on:
  * a Firefox that supports the LWTheme->STheme upgrade - Firefox62
  * a Firefox that doesn't - e.g. release Firefox 61
  * (any other Firefoxes you routinely check for regressions in update service code)
* There will likely be a few config settings you need to change to allow LWT installation from -dev
* notify us (e.g. me) with the one or more lwt you want migrating so we can have the `migrate_lwt` command used on them.
* with the LWT you _aren't_ migrating - update it by changing the background image
* trigger update checks in your Firefoxes (again, likely needs some config settings so it correctly updates from dev)
  * Firefox62 should update the migrated LWT to a static theme, and update the un-migrated LWT to the latest background
  * Firefox61, (and any earlier Firefoxes you're testing too), should update the un-migrated LWT to the latest background, but leave the migrated LWT as is - and not throw any errors.

**Comment by vcarciu** [comment] 2018-07-13 15:10
I re-verified the issue after fix of https://github.com/mozilla/addons-server/issues/8837 and updates worked in FF>62 from a lwt theme to a migrated theme.

Also I can confirm that LWT was not updated to a migrated theme in FF61.

The non migrated LWT updates testing is blocked in -dev by https://github.com/mozilla/addons-server/issues/8835 , but because the main scope of the bug was achieved I will close the issue, but the final "verified fixed" label will be added only when the blocker is fixed.

**Closed by vcarciu** 2018-07-13 15:10 UTC
Labels: priority: p3, project: static themes, qa: extra, size: L, triaged

**Comment by vcarciu** [comment] 2018-07-24 14:11
#8835 was fixed. Adding the verified-fixed label.
