### ISSUE TITLE
UI issues for cyrillic languages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5217] opened 2017-04-20 14:59 UTC
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/bg/developers/addons (Same for Russian)
2.Observe the header

Expected results:
No UI issues in Cyrillic languages

Actual results:
There are overlaying issues for Cyrillic languages

Notes:
I know that there are small overlaying issues for other non Cyrillic languages and we agreed that these will not be fixed, but in this case the UI issues are very obvious

Please see screenshot for this issue :
![cirillyc](https://cloud.githubusercontent.com/assets/1583842/25237353/1107174c-25f3-11e7-8dad-08fbe7941d53.png)

**Comment by EnTeQuAk** [comment] 2017-04-28 10:18
We'll have to work on this given that it's in our devhub which won't be replaced by addons-frontend anytime soon. It's low-priority though imho.

**Comment by eviljeff** [comment] 2017-10-03 17:23
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. mentor me

**Comment by gponimansky** [comment] 2018-03-10 22:14
Seems like a duplicate issue with #7298

**Comment by muffinresearch** [comment] 2018-05-30 15:50
Duplicate of #7298

**Comment by wagnerand** [comment] 2018-05-30 15:50
Yep, thank you.

**Closed** 2018-05-30 15:50 UTC
Labels: component: devhub, contrib: good first bug, contrib: mentor assigned, priority: p4, triaged
