### ISSUE TITLE
When uploading a WebExtensions version over a jetpack addon, the label jetpack is retained

### ISSUE THREAD

**Issue by Smile4ever** [mozilla/addons-server#8882] opened 2018-07-15 13:41 UTC
### Describe the problem and steps to reproduce it:
I had a jetpack addon. I uploaded a WebExtensions version over it.

### What happened?
The label "jetpack" stayed, I expected it to go away. Since I cannot remove it myself, I wonder whether the "upgrade to WebExtensions" could be detected, removing the label?

### What did you expect to happen?
jetpack label is automatically removed

### Anything else we should know?
I used this addon when I found out about this bug:
https://addons.mozilla.org/en-US/firefox/addon/delete-tab

**Comment by eviljeff** [comment] 2018-07-16 07:40
@jvillalobos thoughts?
Easiest solution is we remove the code that adds `jetpack` to uploads and delete the tag - including from existing addons.

**Comment by jvillalobos** [comment] 2018-07-16 17:52
Yeah, we can get rid of that tag.

**Comment by diox** [comment] 2019-01-18 19:13
Duplicate of https://github.com/mozilla/addons-server/issues/7189

**Closed by diox** 2019-01-18 19:13 UTC
Labels: component: feature deprecation, priority: p3
