### ISSUE TITLE
User admin search

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#979] opened 2015-11-26 00:05 UTC
We need an admin user search tool that is available for more than full admins. Here's what we need so we don't depend so much on direct DB access:
- Search by name (could be username or display name) or email address.
- The search results should link either to the users's profile page or a special user admin page. This page should include:
  - All add-ons by this user, regardless of their status or visibility.
    - There should be an option to mass-download all versions pending review for add-ons by this developer (yes, this is very specific, but needed).
  - All themes by this user, regardless of their status.
  - All collections by this user, public and private.
  - All of these should be paginated, since they can be numerous.
  - This page should have a button to delete the user.

This tool should be available to users with Addons:Review permission, with two exceptions: search by email address (for privacy reasons) and deleting a user. Those two should require Users:Edit also.

**Comment by wagnerand** [comment] 2016-11-14 16:48
@mstriemer can you update what parts of this have been done?

**Comment by mstriemer** [comment] 2016-11-14 17:52
There is no API for this yet so I don't think any of this is done. The API is tracked in https://github.com/mozilla/addons-server/issues/3138.

**Comment by diox** [comment] 2017-07-31 12:17
Note that we removed indexing users in #6017 because no code was using it. If we ever end up implementing this, we'll need it back.

**Comment by diox** [comment] 2018-09-06 18:16
Duplicate of https://github.com/mozilla/addons-server/issues/7268

**Closed by diox** 2018-09-06 18:16 UTC
Labels: component: admin tools, component: api, priority: p3, triaged
