### ISSUE TITLE
Process all email templates with the same template language, harmonize their paths

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14044] opened 2020-04-23 10:19 UTC
Most or our email templates are being processed with Django Template Language instead of Jinja2, but not all. For consistency, and to help fix the config for extraction in https://github.com/mozilla/addons-server/issues/12879, we want to make them all use the same engine and harmonize their paths - have them all under `emails/` and not `email/`.

~~**Edit:** because of issues with localization we're going to process them all using Jinja, not Django.~~

**Comment by diox** [comment] 2020-04-23 14:44
QA: make sure all emails we send out are still working properly. This includes:
- api key revocation/confirmation
- successful submission
- confirmation of an author added to an add-on
- confirmation of an author removed from an add-on
- user rating email notification
- reviewer & developer replies
- reviewer rejection/approval

**Comment by willdurand** [comment] 2020-04-24 15:47
I think https://github.com/mozilla/addons-server/issues/14057 is a regression caused by this issue. I don't really understand why but there are missing newlines (`\n`) in many localized strings..

**Comment by diox** [comment] 2020-04-24 16:02
Why would missing newlines break the build ?

**Comment by willdurand** [comment] 2020-04-24 16:04
> Why would missing newlines break the build ?

I don't know. Maybe Pontoon does not keep newlines that are before any content after the content? The missing newlines are those ones.

**Comment by willdurand** [comment] 2020-04-24 16:07
Maybe this issue does not have anything to do with #14057 but some localized strings looked like emails so..

**Comment by diox** [comment] 2020-04-24 16:07
The difference is one thing. But why does it break the build to have newlines or not ?

**Comment by diox** [comment] 2020-04-24 16:08
The email changes did have an impact on newlines. I'm trying to understand why this would be an issue though. Worst case scenarios the translation doesn't match until it's updated ?

**Comment by willdurand** [comment] 2020-04-24 16:09
See all the builds on both circle and travis for the last 12h. Circle-ci breaks before it is able to push the docker image and the travis job fails, so it is red everywhere.

**Comment by diox** [comment] 2020-04-24 16:11
I saw the failures but didn't realize dennis actually cared about the newline differences :(

**Comment by diox** [comment] 2020-04-24 16:12
So the problem is, if we revert this patch, then the extraction no longer works (`PUENTE` config would need to be updated to match) so we end up in a similar situation...

**Comment by willdurand** [comment] 2020-04-24 16:17
Pontoon seems to handle newlines correctly, though: https://pontoon.mozilla.org/sv-SE/amo/LC_MESSAGES/django.po/?search=You%27re+rece&string=209807. Localizers removed the trailing newlines, though.

**Comment by AlexandraMoga** [comment] 2020-04-27 14:29
I've verified (hopefully) most of the actions that would trigger an email (see complete list below). The email templates are working the same as before.

<details>
<summary>Email triggering actions tested</summary>

- new user submits first add-on
- user submits new version to listed add-on -  auto-approval email
- user submits unlisted add-on -  auto-approval email
- user submits theme -  approval email
- user generates API keys
- user revokes API keys
- user adds new author
- user edits the ownership status of another author
- author is removed from add-on
- a review is added to add-on
- a dev reply is added to user review
- an add-on is deleted
- reviewer manually approves an extension
- reviewer rejects an extension
- reviewer approves a theme
- reviewer rejects a theme (with canned response)
- reviewer sends a reviewer reply
- developer replies to reviewer
- reviewer is notified for a new version submission
- reviewer weekly reports


</details>

I'm marking this issue as verified fixed on -dev.

**Comment by diox** [comment] 2020-04-28 13:58
Because of issues with localization we're going to process them all using Jinja, not Django. Patch in progress in https://github.com/mozilla/addons-server/pull/14087, this will require QA to re-verify once it's done.

**Comment by diox** [comment] 2020-04-28 16:08
This is more complex than we thought.

Puente [monkeypatches jinja to replace their `{% trans %}` block with its own](https://github.com/mozilla/puente/blob/4379a7717d28a2490d47939800f5d6e695b70def/puente/utils.py#L4-L60) at extraction time. At rendering time we load [puente's version](https://github.com/mozilla/puente/blob/4379a7717d28a2490d47939800f5d6e695b70def/puente/ext.py#L26) as well.

Puente's version does automatic collapsing of whitespace inside `{% trans %}` blocks with no options to change this.

But in emails, we do want the newlines... 

A few way to work around this:
- Remove that requirement. Maybe translate each individual sentence separately in emails or something, so that the collapsing of newlines is no longer an issue. Bonus: this makes it easier for translators not to mess up.

- Build an extension that adds a custom `{% noncollapsingtrans %}` or whatever that would call jinja's `{% trans %}` behind the scenes. Might need some support at extraction time too.

- Make a patch to puente to make whitespace collapsing optional inside `{% trans %}` blocks.

**Comment by diox** [comment] 2020-04-29 10:48
We're going to try another option: keep Django Template Language for emails for now, but remove leading and trailing newlines from emails.

**Closed** 2020-04-29 11:56 UTC
Labels: component: code quality, priority: p3
