### ISSUE TITLE
Confirming approval for an add-on redirects to updates queue

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#6480] opened 2017-09-21 22:49 UTC
I reviewed an add-on from the post-review queue, and afterwards ended up on the updates queue.

I would have expected to land back in the post-review queue, since that is where I started. Not doing so means I need an extra click each time I've reviewed an add-on.

**Comment by EnTeQuAk** [comment] 2017-09-22 09:16
is this a duplicate of https://github.com/mozilla/addons-server/issues/6479?

**Comment by diox** [comment] 2017-09-22 09:44
No. We need to change the redirect url on the review page when we're confirming an approval.

**Comment by kewisch** [comment] 2017-09-22 11:06
Same with rejecting multiple versions please :)

**Comment by ValentinaPC** [comment] 2017-09-22 11:08
...or any other action made from review page of an auto approved add-on. :)

**Closed** 2017-09-26 15:52 UTC
Labels: component: reviewer tools, in progress, project: auto approval, state: pull request ready, triaged

**Comment by vcarciu** [comment] 2017-09-26 16:48
Verified as fixed for all actions from review page of auto approved add-on(but added video only for confirm approval) :
![confirmapproval](https://user-images.githubusercontent.com/1583842/30872715-b422d772-a2f3-11e7-9eb8-9bd002000a4a.gif)
