### ISSUE TITLE
Theme user counts broken since Aug 31

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#3427] opened 2016-09-06 18:00 UTC
Background themes uploaded from Aug 31 onward show 0 users.
https://addons.mozilla.org/firefox/themes/?sort=created

**Comment by MaDonnasPersonas** [comment] 2016-09-06 18:04
Thanks, Amy.

**Comment by andymckay** [comment] 2016-09-06 19:24
Duplicate of #3406.

**Closed by andymckay** 2016-09-06 19:24 UTC

**Comment by MaDonnasPersonas** [comment] 2016-09-08 15:52
Has this problem been closed or am I reading this wrong? Because there is still no user count since Aug. 31st.

**Comment by atsay** [comment] 2016-09-08 16:10
It was closed because it was a duplicate of issue [3406](https://github.com/mozilla/addons-server/issues/3406)--it's not resolved yet but we're working on it!
