### ISSUE TITLE
Add-on source code not viewable for non-reviewers even with devhub source code viewing checked

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#5481] opened 2017-05-23 22:07 UTC
Title.

Could only view the source after logging in. Not sure why this page suddenly requires review permission to view.

STR (in a private tab/window/while not being logged into AMO):
1. Open ABPs version [page](https://addons.mozilla.org/addon/adblock-plus/versions)
2. Click on [View the source](https://addons.mozilla.org/files/browse/541651/) for any version
3. "Not allowed" page shows up.

**Comment by jvillalobos** [comment] 2017-05-23 22:12
Closing as a dupe of mozilla/addons-server#5135. See also mozilla/addons-server#5431, which should land this week.

**Closed by jvillalobos** 2017-05-23 22:12 UTC
