### ISSUE TITLE
Support pre-filling in data required to list an addon, without needing to upload an addon as listed at the same time

### ISSUE THREAD

**Issue by Callek** [mozilla/addons-server#8181] opened 2018-05-04 15:03 UTC
During release engineering's process right now, we have langpacks that we submit as "unlisted" on beta, and then on release (release candidates) we submit them as listed.

This has the downside that for any language pack that has not been listed prior to now, we have a human-effort blocked process in the release pipeline.

We should either be able to populate that metadata via API at first listed submission time, or have a way via website to fill out the required information ahead of "listed" (since the addon+version is created as part of release process itself).

I'm imagining the ability to enter License, Summary, URL-path, etc. (all the required bits that are unavailable to edit in unlisted versions).

Bonus points if we can "reserve" an addonID for a limited time in order to support a future where all submissions are listed, and/or a future where we can add them for Nightly as well (so that we could, for example, prepare AMO's interface prior to even having our first version ready, e.g. en-CA is new, lets prep AMO for it)

**Comment by diox** [comment] 2018-05-29 11:36
This is really a duplicate of https://github.com/mozilla/addons-server/issues/7811

**Closed by diox** 2018-05-29 11:36 UTC
Labels: component: api, priority: p3
