### ISSUE TITLE
Add-on submission is stuck in validation state

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7594] opened 2018-02-19 10:13 UTC
STR:

1. Log into Developr Hub
2. Submit a new extension 
3. Wait for your validation results

Actual result:
Extension is stuck in validation mode and no results are triggered

Expected result:
Validation is successfully completed for the submitted extension

Notes:
- it is also happening at theme submission, when using the theme generator wizard (submission is stuck in upload mode)
- reproduced on AMO-dev, FF58 (Win10x64)

![image](https://user-images.githubusercontent.com/31961530/36372534-ff959ea0-156d-11e8-8bdc-fa5eb4c3df0a.png)
=======================================================
![image](https://user-images.githubusercontent.com/31961530/36372544-08848d1e-156e-11e8-8f77-ec80c3302733.png)

**Comment by diox** [comment] 2018-02-21 12:39
Working for me locally but not on dev, so I suspect it's an ops issue.

**Comment by diox** [comment] 2018-02-21 21:39
Which fixed itself - apparently it was a temporary connection error on dev.

**Comment by AlexandraMoga** [comment] 2018-02-22 08:09
This is still reproducing intermittently especially with add-ons that are supposed to trigger warnings or errors. 
This only happens on -dev.

**Comment by diox** [comment] 2018-02-22 11:25
Assigning ops to look into this instability

**Comment by philipcristiano** [comment] 2018-02-22 14:42
Is there information about how the backend part of this process works in development? I don't know much about this. 

The previous case was an intermittent problem connecting to RabbitMQ. According to Sentry, that hasn't happened today (only yesterday). Due to our access model scheme, I can't look into this much without recreating the RabbitMQ instances first.

**Comment by diox** [comment] 2018-02-22 14:57
The flow is:
- The developer uploads an add-on
- The view responsible for this parses the manifest inside the uploaded add-on, and queues a celery task to do the validation
- Celery workers pick up that task and process it. This marks the file upload as processed.
- While all this was happening, the developer upload page was polling an API. When the file is finally marked as processed that polling loop stops and the developer can see the result of the validation.

I can link code if necessary but I was under the impression @AlexandraMoga was just referencing intermittent problems with the validation in general, not specifically today. @AlexandraMoga when was the last time this happened exactly? Did it happen today?

**Comment by AlexandraMoga** [comment] 2018-02-22 15:56
@diox @philipcristiano Yes, I was reproducing the issue this morning, this is why I've re-opened the case.
However, now the submission seems to be working. Maybe it needed a bit more time.
I guess we can close the issue for now and we'll keep monitoring -dev to see if this will happen again.

**Comment by ioanarusiczki** [comment] 2018-02-26 09:49
I tried to make submissions this morning but this issue is still reproducible.  One static theme sample passed validation but all the other types did not.  This issue is reproducible on AMO dev with FF58 (Win10).

![not working lang pack](https://user-images.githubusercontent.com/33448286/36663615-cdca3a16-1aea-11e8-93bf-07d47a71ddd4.gif)

The wizard also has problems, it won't pass through the uploading state 

![not working](https://user-images.githubusercontent.com/33448286/36663642-dc6616c6-1aea-11e8-93a0-9c85aa1bc02a.gif)

**Comment by philipcristiano** [comment] 2018-02-26 19:16
This appears to be intermittent even with the same file. I was able to get a validated extension but when trying again it hung. I don't yet know the cause and this may take some time to dig into.

**Comment by vcarciu** [comment] 2018-02-27 15:27
@philipcristiano  : I can reproduce the issue right now

**Comment by diox** [comment] 2018-02-27 15:36
FWIW there was a deploy earlier today right after @philipcristiano commented but before @vcarciu did, so maybe it's related.

**Comment by philipcristiano** [comment] 2018-02-27 21:11
The logs in Kibana show only a single log line mentioning the upload file, in either the working or broken case. There are no errors listed in the Kibana or Sentry when I've uploaded something. 

The deploy case is a good lead that I'll take a look into. I'll be out tomorrow so I'll pick this up again on Thursday.

**Comment by philipcristiano** [comment] 2018-03-01 16:54
I've looked through it a bit and diving through the code to try and figure out what is going on in the process. 

The logging for this process is pretty sparse and would be helpful if more can be added about when events are sent to celery and what decisions are being made for whether to validate. 

For a broken case the only logs are:

```
FileUpload created: 88e72b27f8e64afe8e654d2ae35cb2d8
UPLOAD: '88e72b27f8e64afe8e654d2ae35cb2d8_Archive.zip' (4224 bytes) to '/mnt/efs/addons-dev.allizom.org/files/temp/3677a7e7baf14c27937ea52077d602ef.xpi'
````

Can someone add more logging throughout the process? From the UI things look broken, but in the logs there is nothing obviously wrong ... or even happening.

**Comment by philipcristiano** [comment] 2018-03-02 18:45
With @bqbn's help to get onto the RabbitMQ nodes, I restarted RabbitMQ and the nodes seem to be happily clustered. They previously thought they were clustered but didn't see each other running :/ 

I've tested validation again and it seems to be working. There are now logs from the Celery instances tracking task time. It looks like this is now fixed.

**Comment by vcarciu** [comment] 2018-03-05 16:49
@philipcristiano : then can we mark this as closed?

**Closed** 2018-03-07 01:02 UTC
Labels: component: devhub, priority: p3, triaged

**Comment by AlexandraMoga** [comment] 2018-03-07 11:43
Confirmed as fixed (for good hopefully :wink:)

**Comment by niktaxi** [comment] 2023-04-08 16:20
I am facing the exact same issue right now.
