### ISSUE TITLE
Add to Collection/ Share this add-on links are missing

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2013] opened 2016-03-28 23:35 UTC
Looks like the new details page is missing the following links:

1. Add to Collection: As long as we have Collections, we should probably have an easy way for users to add to collections.
2. Share this add-on 

Just wanted to make sure if this was by design or just an oversight.

**Comment by designakt** [comment] 2016-03-29 14:06
This is intentional to focus the details page more and simplify.
For collections users still can add add-ons in the collections section of AMO.
I am not sure if those feature are used enough to justify the prominent placement.

**Comment by tofumatt** [comment] 2016-03-29 14:26
Sounds like this is working as expected, so I'll close this as "by design"; feel free to reopen if I'm mistaken.

**Closed by tofumatt** 2016-03-29 14:26 UTC
Labels: style refresh

**Comment by smayer97** [comment] 2016-04-14 22:40
If you do not use collections, then I think you are missing the significance of what removing the 2 "simple" links does (Add to Favorites and Add to Collection). It has made it EXTREMELY difficult to manage collections without them. I think it is a great lack of appreciation of how useful collections are and the way they need to be accessed (by collection creators/managers).

Also, given the amount of info on the pages anyway, 2 links on this page are not going to make a UI difference BUT they do add HUGE value. 

Please see my 3 comments here:  
https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/12?u=smayer97

https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/13?u=smayer97

https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/14?u=smayer97

Please seriously reconsider this. Please do not alienate users of collections.

**Comment by mikhoul** [comment] 2016-05-01 02:58
@smayer97   Really stupid, I was thinking it was an error but it's an HORROR!

Wow reality surpass fiction !

Mozarella is going deep in the Dumb Browser Game, with this move they are clearly the leader for the in that field. :(

I really hope Vivaldi will improve a little bit and add sync system soon this way I will run away with my userscripts and userstyles.
 
Here's a fix with a Userstyle that improve a lot AMO and make it usable at least:  https://userstyles.org/styles/126536/amo-ez-on-the-eyes

**Comment by SW1FT** [comment] 2016-05-01 12:32
Just add the damn button, is it so hard to do?

**Comment by tofumatt** [comment] 2016-05-01 13:01
This is a duplicate of #2264, which is open. Looks like the plan is to add back to "Add to favourites" button.

I'm locking this issue; there's no need for swearing or name-calling.
