### ISSUE TITLE
add-on install fails: incorrect file hash for mediathread 0.1.4

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1111] opened 2015-12-18 17:14 UTC
When trying to install mediathread 0.1.4 from [AMO](https://addons.mozilla.org/en-us/firefox/addon/mediathread/) I get this error in Firefox:

```
1450456117390   addons.xpi  WARN    Download of https://addons.mozilla.org/firefox/downloads/file/377175/mediathread-0.1.4-fx.xpi?src=dp-btn-primary failed: Downloaded file hash (d0ef41a44fb30e55e51352627989044eee36385cabb38b5f0cac1ca581abe334) did not match provided hash (fba21a4f2d88baaba81f58653428896dc2570d1bdd8836e6b022ab3cd49d13b6)
```

I can confirm this same hash mismatch using curl.

This is what the server response looks like:

```
$ curl -I 'https://addons.mozilla.org/firefox/downloads/file/377175/mediathread-0.1.4-fx.xpi?src=dp-btn-primary'
HTTP/1.1 302 FOUND
Content-Type: text/html; charset=utf-8
Date: Fri, 18 Dec 2015 17:09:59 GMT
Location: https://addons.cdn.mozilla.net/user-media/addons/669813/mediathread-0.1.4-fx.xpi?filehash=sha256%3Afba21a4f2d88baaba81f58653428896dc2570d1bdd8836e6b022ab3cd49d13b6
Server: nginx
X-Backend-Server: ip-172-31-12-254
X-Target-Digest: sha256:fba21a4f2d88baaba81f58653428896dc2570d1bdd8836e6b022ab3cd49d13b6
...
```

This hash is stored in the `files` table and the code adds it to the response [here](https://github.com/mozilla/olympia/blob/master/apps/versions/views.py#L112).

The first thing to check is to see what's in the prod DB:

```
select f.hash, f.original_hash, a.slug, v.version from addons a join versions v on v.addon_id=a.id join files f on f.version_id=v.id where a.slug='mediathread' and v.version='0.1.4';
```

**Comment by kumar303** [comment] 2015-12-18 17:34
ok, looks like db has the wrong hash:
````
+-------------------------------------------------------------------------+-------------------------------------------------------------------------+-------------+---------+ 
| hash                                                                    | original_hash                                                           | slug        | version |
+-------------------------------------------------------------------------+-------------------------------------------------------------------------+-------------+---------+ 
| sha256:fba21a4f2d88baaba81f58653428896dc2570d1bdd8836e6b022ab3cd49d13b6 | sha256:875f1f8de118c73b1baa6d906d8894f070395d6b08c433131e1da5c227895da3 | mediathread | 0.1.4   |
+-------------------------------------------------------------------------+-------------------------------------------------------------------------+-------------+---------+
````

**Comment by kumar303** [comment] 2015-12-18 23:03
I'm currently using this script to see how many other add-ons have incorrect hashes: https://gist.github.com/kumar303/1adadf9b887fb2eb04ca

**Comment by kumar303** [comment] 2015-12-18 23:56
This was the output on stage:
````
{'checked': 156518,
 'exceptions': 14419,
 'hash_mismatch': 547,
 'hash_ok': 139320,
 'signed_hash_mismatch': 7,
 'skipped_algorithms': 2238,
 'unlisted_hash_mismatch': 4}
````
I'll check prod on Monday.

**Comment by kumar303** [comment] 2015-12-21 18:12
Using a new version of the script that only checks valid add-ons (i.e. ones that can be installed), here are the new stage results. It includes a separate count of files that were created in 2015 or above.
````
{'2015_hash_mismatch': 154,
 'checked': 127636,
 'exceptions': 5769,
 'hash_mismatch': 341,
 'hash_ok': 120756,
 'signed_hash_mismatch': 7,
 'skipped_algorithms': 775,
 'unlisted_hash_mismatch': 3}
````

**Comment by kumar303** [comment] 2015-12-23 19:43
Prod results:
````
{'2015_hash_mismatch': 474,
 'checked': 151705,
 'exceptions': 6618,
 'hash_mismatch': 724,
 'hash_ok': 143596,
 'signed_hash_mismatch': 57,
 'skipped_algorithms': 772,
 'unlisted_hash_mismatch': 119}
````

**Comment by kumar303** [comment] 2015-12-23 19:53
production log: 
[check_file_hashes.txt](https://github.com/mozilla/olympia/files/71190/check_file_hashes.txt)

**Comment by kumar303** [comment] 2015-12-23 22:59
I'm going to try and trace everywhere that a hash is changed so I can make sure all originating views are in transactions.

**Comment by BurkeKnight** [comment] 2015-12-31 23:17
Another addon also having this issue, per:

https://discourse.mozilla-community.org/t/webapp-tabs-for-thunderbird-install-issue/6292

WebApp Tabs 2.1.1-let-fixed on Thunderbird 38.5.0

**Comment by kumar303** [comment] 2016-01-25 20:38
This hopefully won't happen again to any extension created after 2016-01-14, which was when we turned on transactions everywhere (https://github.com/mozilla/olympia/issues/1154). We have not yet fixed any historic data. I will run my script again to check for mismatches beyond this deployment date.

**Comment by wagnerand** [comment] 2016-02-08 20:00
#1639 could cause a hash mismatch as well.

**Comment by Indomian** [comment] 2016-02-12 10:29
Same problem with my addon for last review from 2016-02-11 https://addons.mozilla.org/en-US/firefox/addon/seoquake-seo-extension/, version 3.4.4 was reviewed but is undownloadable. I checked hash after download - it seems to be ok.

**Comment by gorhill** [comment] 2016-02-13 11:08
I have many reports of the same issue for my add-on:
- https://github.com/gorhill/uBlock/issues/1373
- https://discourse.mozilla-community.org/t/support-ublock-origin/6746/11
- https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/

**Comment by RDL-github** [comment] 2016-02-15 01:30
Any chance this one (for NoScript) is connected?

InformAction Forums • View topic - 2.9.0.4 AMO download is corrupt.
https://forums.informaction.com/viewtopic.php?f=7&t=21609&sid=49979b592c51f66647a2cdc957b6cc0b

Some of us are being delivered, from AMO, an unsigned version, accompanied by the SHA256 CRC for the signed version. Is it possible is that we're being dealt an xpi from a pre-signing repository?

**Comment by kumar303** [comment] 2016-02-16 17:03
> version 3.4.4 was reviewed but is undownloadable. I checked hash after download - it seems to be ok.

That sounds like an unrelated issue

**Comment by RDL-github** [comment] 2016-02-18 22:11
No reply yet here but, in case anyone is interested, I have now submitted my problem as:

1249402 – AMO Server at 54.230.196.197 Delivers Unsigned Download of NoScript 2.9.0.4 xpi File
https://bugzilla.mozilla.org/show_bug.cgi?id=1249402

**Comment by andymckay** [comment] 2016-02-18 23:31
Can't reproduce, every copy of that add-on I get is signed.

**Comment by andymckay-limited-access** [comment] 2016-02-18 23:49
None of this is making much sense to us. Could you maybe send me that file
that you are getting from AMO, I think it says in the forum that it has a
hash of 7c65095..., I'd be curious to see whats in it. You can email me at
amckay at mozilla dot org.

**Comment by RDL-github** [comment] 2016-02-19 00:15
>  andymckay commented 35 minutes ago

> Can't reproduce, every copy of that add-on I get is signed.

What IP do you see if you ping addons.cdn.mozilla.net?

As I said in the bug report, I get 54.230.196.197
People who got 52.84.3.72 as the server address (including me when I forced that route using 'hosts' file) got the proper signed version.

Since, by default, from my location in UK, I get 54.230.196.197 as my server, I get the incorrect file every time.

**Comment by andymckay** [comment] 2016-02-19 01:06
I've tried all the IPs mentioned in the thread. Example: https://dpaste.de/JfTG

**Comment by RDL-github** [comment] 2016-02-19 01:07
> andymckay-limited-access commented an hour ago
> None of this is making much sense to us. Could you maybe send me that file
> that you are getting from AMO, I think it says in the forum that it has a
> hash of 7c65095..., I'd be curious to see whats in it. You can email me at
> amckay at mozilla dot org.

I've just now sent it to you by email as requested.

**Comment by andymckay** [comment] 2016-02-19 01:30
Sorry, that should have been amckay at mozilla dot com. Sometimes I get confused myself.

**Comment by RDL-github** [comment] 2016-02-21 20:28
>  andymckay commented 3 days ago
> Sorry, that should have been amckay at mozilla dot com. Sometimes I get confused myself.

Since you received the file and responded, I see this addition to the bug report.

1249402 – AMO Server at 54.230.196.197 Delivers Unsigned Download of NoScript 2.9.0.4 xpi File
https://bugzilla.mozilla.org/show_bug.cgi?id=1249402#c2

**Comment by andymckay** [comment] 2016-02-29 20:40
We think these issues are: https://bugzilla.mozilla.org/show_bug.cgi?id=1251017

**Comment by andymckay** [comment] 2016-03-01 00:28
We believe with a clear of the CDN cache this is now resolved.

**Comment by RDL-github** [comment] 2016-03-01 21:49
>  andymckay commented a day ago
> We think these issues are: https://bugzilla.mozilla.org/show_bug.cgi?id=1251017

That looks very similar to me and, although that reporter thought I could install from the corrupt xpi, we know I could not.

By "these" do you also mean the ones originally raised in this topic or have I unintentionally hijacked it?

>  andymckay commented 21 hours ago
> We believe with a clear of the CDN cache this is now resolved.

As I replied in the bug report, I obtained good downloads on three separate days since Sunday, so I believe you are correct.

Thank you.

**Comment by Quicksaver** [comment] 2016-03-02 20:29
I just had a user report this problem a few minutes ago. Here's a copy of the message the user saw in the console:

> 1456947675255    addons.xpi    WARN    Download of https://addons.cdn.mozilla.net/user-media/addons/308417/findbar_tweak-2.1.9-fx.xpi?filehash=sha256%3A2eaf4fd6071dea122eaf977e01f9cb7b0f3f22655b822cb7f80bb08691ef88e7 failed: Downloaded file hash (465c345024d68bb670c6698b202e4f2dc1ead665e404f5ad3adf99595d6d58fe) did not match provided hash (2eaf4fd6071dea122eaf977e01f9cb7b0f3f22655b822cb7f80bb08691ef88e7)

Of note, I can't reproduce it myself...

**Comment by Quicksaver** [comment] 2016-03-03 19:10
So apparently reloading the page **can** fix it: https://github.com/Quicksaver/FindBar-Tweak/issues/245#issuecomment-191917400

**Comment by kumar303** [comment] 2016-03-03 19:28
Sounds like it could be cache invalidation issue or something like that

**Comment by wagnerand** [comment] 2016-03-03 19:33
@jasonthomas did some work under the hood recently. That could have been it as well.

**Comment by Quicksaver** [comment] 2016-03-03 19:43
Cache issue seems very likely, quoted from https://github.com/Quicksaver/FindBar-Tweak/issues/245#issuecomment-191927290
> I'm using very long Firefox sessions [...] I have already tried to update this add-on via "about:addons" some days ago. So I guess all other requests for the newer version during the last hours were actually using the cached old version.

> Only now I went to the add-on page on "addons.mozilla.org" and [...] I thought "maybe first clearing cache" so I reloaded the page with [CTRL]+[F5].
So I guess only now after clicking the "Add to Firefox" button I actually got the non-corrupted xpi since there was no cached version available.

**Comment by kumar303** [comment] 2016-03-03 19:55
> so I reloaded the page with [CTRL]+[F5] ... and got the non-corrupted xpi

It should not even be possible to get a cached version of that link though. This might be something we need to fix in how we serve the files.

**Comment by muffinresearch** [comment] 2017-02-20 16:58
I'm going to close this, but feel free to re-open this if it's still an issue.

**Closed by muffinresearch** 2017-02-20 16:58 UTC
Labels: triaged
