### ISSUE TITLE
New profile picture cannot be added

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3661] opened 2016-10-03 07:23 UTC
STR:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/firefox/
2. Go to Edit Profile page https://addons.allizom.org/en-US/firefox/users/edit
3. Add/Change your profile picture

ER:
The profile picture is added/changed.

AR:
The profile picture is not added/changed.

Notes/Issues:
A message that the profile was updated is displayed, even if no changes were made.
Verified on FF49(Win 7). Issue is only reproducing on stage.
Video for this issue:
![profpic](https://cloud.githubusercontent.com/assets/15685960/19029989/6ce90954-8953-11e6-888e-4f32a2d1745f.gif)

**Comment by mstriemer** [comment] 2016-10-03 13:39
Seems like this is likely a regression from https://github.com/mozilla/addons-server/pull/3629.

**Comment by mstriemer** [comment] 2016-10-03 14:33
Actually this is working for me locally and it appears that the photo is updated on stage, but it is returning a 404. Could be a config issue?

**Comment by ValentinaPC** [comment] 2016-10-03 14:42
I am not able to add a profile picture in AMO-stage or to change and existing one...
The default one seems to be displayed as expected:
![default](https://cloud.githubusercontent.com/assets/15685960/19041433/aef0ec94-8990-11e6-9973-b09155073582.png)

**Comment by mstriemer** [comment] 2016-10-03 14:48
That's odd, I don't see a photo at https://addons.allizom.org/en-US/firefox/user/ValS/. It links to https://addons-stage-cdn.allizom.org/user-media/userpics/11/11380/11380864.png?modified=1475505734 for me which is a 404.

**Comment by muffinresearch** [comment] 2016-10-03 15:35
@mstriemer I've just pull the latest changes and it's working fine locally for me too. I think there's been some permissions related issues wrt containerization so it would be worth checking with ops if this is related to that.

**Comment by mstriemer** [comment] 2016-10-03 16:27
This definitely can't be a regression from https://github.com/mozilla/addons-server/pull/3629 since that isn't merged yet... I pinged Wei and he's looking into it.

**Comment by muffinresearch** [comment] 2016-10-03 18:03
@bqbn yep, it's working fine now thanks.

**Closed by muffinresearch** 2016-10-03 18:03 UTC
Labels: triaged

**Comment by ValentinaPC** [comment] 2016-10-04 05:54
Verified as fixed on AMO-stage FF49(Win 7)
Postfix screenshot: 
![profile_pic](https://cloud.githubusercontent.com/assets/15685960/19064000/0e05b71c-8a10-11e6-8307-3bab39d7e4be.png)
