### ISSUE TITLE
Add log activity when slug is changed

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21174] opened 2023-09-11 10:57 UTC
When the add-on slug is changed, we should log an activity containing:
* Add-on the slug was changed for
* User account that changed the slug
* Old slug
* New slug

**Comment by wagnerand** [comment] 2023-09-11 11:08
Is `clean_slug` in `src/olympia/addons/models.py` the right place to do this?

**Comment by eviljeff** [comment] 2023-09-11 12:46
dupe of https://github.com/mozilla/addons-server/issues/18980 - please close one of them

**Closed** 2023-10-02 08:36 UTC
Labels: component:api, component:operations, component:developer_hub, priority:p3

**Comment by ioanarusiczki** [comment] 2023-10-05 08:45
@GregSherman @wagnerand 

This is verified on AMO dev

![changing the slug](https://github.com/mozilla/addons-server/assets/33448286/05845a7a-15ba-4fe7-97a6-0dcfeafc4bd8)

**Comment by KevinMind** [comment] 2024-05-04 19:30
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-491
