### ISSUE TITLE
Celery instability (validation is hanging)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1653] opened 2016-02-09 17:03 UTC
Since the module refactor, we've been seeing celery instability on dev and stage. Jason describes it as: validation fails/stalls and lots of tasks are generated in the default and celery queue (about 100K in 30 minutes). There are some mysterious error like this https://sentry.prod.mozaws.net/operations/olympia-stage/group/230181/

**Comment by kumar303** [comment] 2016-02-09 17:05
Whoops, not AWS related. This most likely seems like a code issue.

**Comment by diox** [comment] 2016-02-09 17:08
We also had weird celery issues tied to the validation tasks in https://github.com/mozilla/addons-server/issues/1552 when post request task was enabled, and I had to back it out - it still hasn't been enabled back because I could never figure it out...

Our validation tasks seem over engineered and quite complex, but damn our celery setup is really fragile...

**Comment by kumar303** [comment] 2016-02-10 16:27
The root cause seems to be https://github.com/mozilla/addons-server/issues/1658 which triggers an edge case in celery that causes many tasks to fill up the queue. This is maybe a bug in celery (a [chord unlocking problem](https://github.com/celery/celery/issues/1700)) but it could be just that we're using the amqp results backend which is not recommended due to its lack of atomicity. There are some workarounds and solutions starting at https://github.com/celery/celery/issues/1700#issuecomment-167681185

**Comment by kumar303** [comment] 2016-02-10 22:59
I think we have a workaround in https://github.com/mozilla/addons-server/issues/1662 that will stop triggering the celery issue

**Comment by andymckay** [comment] 2016-02-15 17:42
It looks like this got fixed in the last few changes? Please re-open if that's not the case.

**Comment by ValentinaPC** [comment] 2016-03-16 15:45
This was reproducing today, 16.03.2016, around 1.30 PM (GMT) and around 5.30 PM (GMT) on AMO-stage FF45(Win 7) for listed/unlisted, normal or web, extensions, slowing us a bit.
Please see the screenshot: 
![2016-03-16_1741](https://cloud.githubusercontent.com/assets/15685960/13818397/670064ae-eb9e-11e5-9f57-8c51a74f9cad.png)

**Comment by EnTeQuAk** [comment] 2016-09-14 06:01
Is this still happening? With a bit of luck this got fixed with https://github.com/mozilla/addons-server/issues/1934 and many of our latest changes. If it still happens, please feel free to re-open.

**Closed by EnTeQuAk** 2016-09-14 06:01 UTC
Labels: triaged
