### ISSUE TITLE
The new frontend pages are not displayed when the back button of the browser is used 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7576] opened 2018-02-15 13:23 UTC
STR:
1.  Load AMO stage and click on an ad-on to open it's detail page.
2. Open read reviews link.
3. From the reviews page click on View classic desktop site.
4. Click the back button of your browser and observe the address bar.
5. Click the back button one more time and observe the page displayed.

Expected results:
The pages from the address bar are displayed.

Actual results:
The Reviews page in classic desktop view continues to be displayed.

Notes:
The classic view is still used for deleting reviews. 
This issue is reproducible on AMO stage with FF58 (Win10).

![back button does not work](https://user-images.githubusercontent.com/33448286/36258507-95174540-1263-11e8-8e18-f8c6e953c4f5.gif)

**Comment by eviljeff** [comment] 2018-02-16 15:17
dupe of #5894

**Closed by eviljeff** 2018-02-16 15:17 UTC
Labels: type: bug
