### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 154: ordinal not in range(128)

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3920] opened 2016-11-02 21:01 UTC
### Describe the problem and steps to reproduce it:
1. Load https://addons-dev.allizom.org/en-US/firefox/
2. Notice the main header menu

### What happened?
HTML is visible

### Anything else we should know?
<img width="1432" alt="screenshot 2016-11-02 13 54 31" src="https://cloud.githubusercontent.com/assets/301317/19947152/107a6550-a104-11e6-8061-153d92119e36.png">

### traceback details:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 154: ordinal not in range(128)
(6 additional frame(s) were not displayed)
...
  File "olympia/addons/views.py", line 364, in home
    'src': 'homepage', 'collections': collections})
  File "olympia/amo/utils.py", line 77, in render
    rendered = render_to_string(request, template, ctx)
  File "olympia/amo/utils.py", line 73, in render_to_string
    return template.render(get_context())

### sentry link: 
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/364618/

**Comment by krupa** [comment] 2016-11-02 21:02
more logs @ https://irccloud.mozilla.com/pastebin/GdMfyYsF/

**Comment by wagnerand** [comment] 2016-11-02 21:59
@EnTeQuAk is our new encoding expert (and it might actually be related to a change he made 😄 )

**Comment by mstriemer** [comment] 2016-11-02 22:43
I tried reproducing this locally but I can't get it to happen. I'm guessing there's some data on -dev that is triggering it. Perhaps something to do with the cron job update in #3880? I tried uploading an add-on with unicode in the path to see if it got messed up locally but it seems to work.

I can't tell from the stack trace what is causing this, it looks pretty limited and the data we see is just `<CachingQuerySet ...>` so that's not much help.

**Comment by muffinresearch** [comment] 2016-11-02 22:53
Some deps updates were landed today: https://github.com/mozilla/addons-server/pull/3893 but updating to the latest code and deps (via docker image updates) locally it doesn't appear to be reproducible.

Fwiw: I did notice changing locale from en-US to en-GB the first request was ok, and then the next request was broken.

**Comment by EnTeQuAk** [comment] 2016-11-03 06:05
This is interesting as it's quite unexpected but certainly unrelated to
the changes I made last week.

I'll take a look at it, might be some dependency update, initially I
thought it's translation related but it doesn't appear to be the case
looking at the last few commits.


On Wed, Nov 2, 2016, at 11:53 PM, Stuart Colville wrote:
> Some deps updates were landed today: #3893[1] but updating to the
> latest code and deps (via docker image updates) locally it doesn't
> appear to be reproducible.
> Fwiw: I did notice changing locale from en-US to en-GB the first
> request was ok, and then the next request was broken.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>

Links:

  1. https://github.com/mozilla/addons-server/pull/3893
  2. https://github.com/mozilla/addons-server/issues/3920#issuecomment-258023945

**Comment by EnTeQuAk** [comment] 2016-11-03 07:57
NIce, it's not related to the dependency upgrades. I was able to reproduce the weird behavior and errors after compiling our static assets, `make update_assets` and it leads to something maybe related to cb925ed91322384c2104210fa587c52ec01404ee since `jingo-minify` is known to do weird git things. Still investigating

**Comment by muffinresearch** [comment] 2016-11-03 10:05
Fwiw: compiling static assets with `make update_assets` doesn't make it reproducible for me locally.

**Comment by muffinresearch** [comment] 2016-11-03 10:33
There also seems to be a problem here with too much escaping, it's unclear to me the exact relationship between the unicode issue and the double-escaping though.

Also note that some locales are 502 bad gateway with the unicode error (e.g. fr) where as `en-US`  always displays albeit broken.

Just now I got a response that's good (for fr) but the second response failed with bad gateway - I thought we had only one instance on -dev so is that caching related?

**Comment by muffinresearch** [comment] 2016-11-03 11:31
My money's on this being a dep. I think python-memcache upgrade might be the culprit see https://github.com/linsomniac/python-memcached/issues/79

I'm going to try downgrading that dep and see if that helps.

**Comment by muffinresearch** [comment] 2016-11-03 12:16
The change in #3923 has landed and -dev looks good now. It was the python-memcached dep so we'll want to tread carefully with future upgrades. I'll add an additional comment to the deps with a link to this issue.

**Closed by muffinresearch** 2016-11-03 12:16 UTC
Labels: triaged
