### ISSUE TITLE
Why it was removed from the extension? It is very useful and used by many.

### ISSUE THREAD

**Issue by MagicDj83** [mozilla/addons-server#3156] opened 2016-07-24 04:32 UTC
Firefox was necessary for the iCloud Bookmarks extension. Enable plug-ins to Firefox bookmarks up to date over your Safari bookmarks on your iPhone, iPad and Mac computer.

**Comment by muffinresearch** [comment] 2016-07-25 10:32
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by muffinresearch** 2016-07-25 10:32 UTC
