### ISSUE TITLE
Tests on Travis intermittenly failing; restarting fixes it

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#1828] opened 2016-03-03 09:42 UTC
A few of my PRs recently have had failing tests; simply restarting travis fixes it. It happened in master as well recently after merging a PR that passed.

Example: https://travis-ci.org/mozilla/addons-server/jobs/113351861

<img width="833" alt="screenshot 2016-03-03 17 41 45" src="https://cloud.githubusercontent.com/assets/90871/13490396/395c2eb6-e167-11e5-865c-ef972586dd59.png">

**Comment by diox** [comment] 2016-03-03 10:53
Yeah, I've seen that too once or twice. Next person who catches it, please note which test is failing and its output :)

**Comment by wagnerand** [comment] 2016-03-03 10:55
@eviljeff had an intermittent test failure this week as well.

**Comment by eviljeff** [comment] 2016-03-03 11:54
this is the one I've had a few times:
https://travis-ci.org/mozilla/addons-server/jobs/112929918#L4670
- I just merged it anyway knowing it was intermittent so that job hasn't been restarted.

**Comment by diox** [comment] 2016-03-03 11:59
For posterity:

```
_____________________ TestBulkValidationTask.test_validate _____________________
self = <olympia.zadmin.tests.test_views.TestBulkValidationTask testMethod=test_validate>

    @attr('validator')
    def test_validate(self):
        self.start_validation()
        res = ValidationResult.objects.get()
        self.assertCloseToNow(res.completed)
        assert not res.task_error
        eq_(res.errors, 1)  # package could not be found
        eq_(res.valid, False)
>       eq_(res.warnings, 0)

E       AssertionError: 9L != 0

res        = <ValidationResult: ValidationResult object>
self       = <olympia.zadmin.tests.test_views.TestBulkValidationTask testMethod=test_validate>

src/olympia/zadmin/tests/test_views.py:720: AssertionError
```

**Comment by diox** [comment] 2016-03-23 13:31
I had this failure a couple times recently so I investigated a little. 

First, I do believe the test is useful, not so much as a unit test, but as a functional one. `TestBulkValidationTask` contains a few tests, but `test_validate` is the only one that really calls the validator, the rest are mocking it. I don't recommend deleting or skipping the test for the moment.

Since it does a `ValidationResult.objects.get()` call, it's unlikely this is related to a transaction issue that would somehow have left the db in an inconsistent state: we'd probably get a `MultipleObjectsReturned` exception if that was the case, or other failures in other tests.

I wasn't able to reproduce the issue locally, so my plan is to add some debugging information to help us understand the problem more. Since the `res.errors` assertion is passing, I'm adding another assertion about the error message itself in #1977.

**Comment by diox** [comment] 2016-03-25 19:40
I played with this more today but I was unable to get it to fail in 10 runs :(

Maybe we should use something like https://github.com/pytest-dev/pytest-rerunfailures to automatically re-run this test once when it fails in the meantime.

**Comment by tofumatt** [comment] 2016-04-04 10:42
https://gist.github.com/tofumatt/fd38c8d073e6cd855269a6debf465a48

There's the output.

**Comment by diox** [comment] 2016-06-16 09:11
Another one I started to see today:

__TestADICommand.test_download_counts_from_file__
```
src/olympia/stats/tests/test_commands.py:184: in test_download_counts_from_file
    date=self.date)
.tox/main/lib/python2.7/site-packages/django/core/management/__init__.py:115: in call_command
    return klass.execute(*args, **defaults)
.tox/main/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py:37: in new_execute
    return original_func(self, *args, **kwargs)
.tox/main/lib/python2.7/site-packages/django/core/management/base.py:338: in execute
    output = self.handle(*args, **options)
src/olympia/stats/management/commands/download_counts_from_file.py:75: in handle
    if get_date_from_file(filepath, sep) != day:
src/olympia/stats/management/commands/__init__.py:97: in get_date_from_file
    with open(filepath) as f:
E   IOError: [Errno 2] No such file or directory: '/home/travis/build/mozilla/addons-server/src/olympia/../../src/olympia/stats/fixtures/files/2014-07-10/download_counts.hive'
```

**Comment by diox** [comment] 2016-06-17 09:54
And another (that should be easy to fix I think, it must be depending on the modified date):

**TestCollectionSearch.test_sort_order_updated**
```
src/olympia/search/tests/test_views.py:870: in test_sort_order_updated
    self.check_sort_links('updated', sort_by='modified')
src/olympia/search/tests/test_views.py:97: in check_sort_links
    assert list(results) == expected
E   AssertionError: assert [<Collection:...ection 2 (0)>] == [<Collection: ...ection 1 (0)>]
E     At index 0 diff: <Collection: Collection 0 (0)> != <Collection: Collection 2 (0)>
E     Full diff:
E     - [<Collection: Collection 0 (0)>,
E     ?                          ^
E     + [<Collection: Collection 2 (0)>,
E     ?                          ^
E     -  <Collection: Collection 1 (0)>,
E     ?                          ^
E     +  <Collection: Collection 0 (0)>,
E     ?                          ^
E     -  <Collection: Collection 2 (0)>]
E     ?                          ^
E     +  <Collection: Collection 1 (0)>]
E     ?                          ^
```

**Comment by wagnerand** [comment] 2016-07-14 21:59
Adding @EnTeQuAk to check whether we can close this after the new bulk validation landed.

**Comment by diox** [comment] 2016-09-22 16:08
This is still happening :(

**Comment by eviljeff** [comment] 2016-09-22 16:12
and more frequent 🙍

**Comment by EnTeQuAk** [comment] 2016-09-22 17:57
I'm still investigating here every now and then especially since I found some very interesting and weird test-dependencies whenever the amo-validator is involved. I also have https://github.com/mozilla/addons-server/issues/1026 in mind and generally the way we call spidermonkey is, uhm, interesting and we have some uncool process terminating issues. Also, we do have some inconsistencies in how we manage fixture-files and how they're linked in our json-fixtures and although I still haven't made any direct connection I fear that all of that might lead to the flakyness. Or at least, it makes the debugging harder.

**Comment by EnTeQuAk** [comment] 2017-05-29 08:44
We launched quite a few improvements over the time, I'm going to close this so that we can create a new issue if there's anything new coming up.

**Closed by EnTeQuAk** 2017-05-29 08:44 UTC
Labels: component: code quality, triaged
