### ISSUE TITLE
Not able to setup development server

### ISSUE THREAD

**Issue by ShivamRawat0l** [mozilla/addons-server#12663] opened 2019-10-19 08:13 UTC
### Describe the problem and steps to reproduce it:

git clone git://github.com/mozilla/addons-server.git
cd addons-server
docker-compose pull  # Can take a while depending on your internet bandwidth.
docker-compose up -d
make initialize  
docker-compose exec web make initialize
(Please include as many details as possible.)
Here when running the make intialize it gives the error.

ERROR: No container found for web_1

### What happened?
ERROR: No container found for web_1 error is coming. 
I did one extra thing which was not there in the instructions and ie I changed the Nginx port to 8002 because my 80 port was being used by firefox. Well, I don't think that it should make any difference but thought it would be better off to mention this. 

### What did you expect to happen?
A superuser account should be created as per the instuctions provided in https://addons-server.readthedocs.io/en/latest/topics/install/docker.html

### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment] 2019-10-19 11:14
This is probably a duplicate of https://github.com/mozilla/addons-server/issues/10856

As a workaround try running `docker-compose up -d` again, then `make initialize`.

**Comment by ShivamRawat0l** [comment] 2019-10-19 11:39
not working. I tried docker-compose up -d several times.BTW i am on linux. Docker does not work on windows home.

**Comment by diox** [comment] 2019-10-19 12:00
It should fine on linux, that's what I'm using as well. I guess something else is wrong, possibly with the way you changed the port ? It's hard to tell without more info.

**Comment by ShivamRawat0l** [comment] 2019-10-19 13:23
@diox Well i opened the docker-compose file and instead of 80:80 changed it to 8002:8002.
I dont know why it mention two ports but should i trying changing only single ?

**Comment by diox** [comment] 2019-10-19 13:34
That would certainly not work: the first port is the local port, the second one is inside the container. Please read https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#port-collisions-nginx-container-fails-to-start for how to change this properly.

**Comment by ShivamRawat0l** [comment] 2019-10-20 03:40
OK i stopped firefox at 80. And used the default ports. It is still showing an error. I dont understand what is web_1 container for which it is showing error. ERROR: No container found for web_1.
I think maybe the name of the container is misspelled somewhere.

**Comment by ShivamRawat0l** [comment] 2019-10-20 03:41
And the container  addons-server_web_1   is there. I think it is refering to this container .

**Comment by ShivamRawat0l** [comment] 2019-10-20 09:04
@diox  I tried setting COMPOSE_PROJECT_NAME environment variable as I thought this might be the issue as mentioned in the install docs.
https://addons-server.readthedocs.io/en/latest/topics/install/docker.html
export COMPOSE_PROJECT_NAME=addons-server
But I am getting the same error. May I know which file is make initialize running ?

**Comment by EnTeQuAk** [comment] 2019-10-21 08:00
What's the folder name you cloned `addons-server` into, is it also named `addons-server`?

Can you post the output of `docker-compose ps` please?

**Comment by eviljeff** [comment] 2019-11-18 13:21
closing because no answer for 4 weeks.

**Closed by eviljeff** 2019-11-18 13:21 UTC
Labels: needs: info
