### ISSUE TITLE
Cannot find the "Merge All Windows" add-on during search

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#6117] opened 2017-08-06 07:12 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Search it or try adding it to my collections on https://addons.mozilla.org/.

### What happened?
It is not there.

### What did you expect to happen?
Actual results.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
i.e. https://addons.mozilla.org/firefox/addon/merge-all-windows/

**Comment by EnTeQuAk** [comment] 2017-08-06 11:28
Could be a duplicate of https://github.com/mozilla/addons-server/issues/6116, leaving this open till I can take a look at this on Monday.

**Comment by diox** [comment] 2017-08-06 12:04
I wonder if search by relevance is broken somehow. Autocomplete does find it.

**Comment by yfdyh000** [comment] 2017-08-06 13:00
> Autocomplete does find it.

It does not appear in the auto-complete results on AMO site.

**Comment by diox** [comment] 2017-08-06 13:10
Mmm. It does appear if you search for "merge". But then again, it also appears in search results if you only search for that. So it seems that the broken part is not relevancy scoring but rather queries with multiple words.

**Comment by yfdyh000** [comment] 2017-08-06 21:23
Ah, you're right. Also occur for ["Close Unused Blank Tabs"](https://addons.mozilla.org/firefox/addon/close-unused-blank-tabs), this [query](https://addons.mozilla.org/firefox/search/?q=close+&platform=windows&appver=57.0&tag=firefox57) including it.

This blocks adding them to my collection. I remember having reported a similar issue on Github or Bugzilla, but I could not find it, it seems related to ignored word.

**Comment by EnTeQuAk** [comment] 2017-08-18 17:40
Alrighty, I finally got this reproduced locally with properly synced public prod data. This is indeed valid, once an add-on only has en-GB (or pt-BR or anything that's not en-US) it's not listed anymore. I'll dig deeper.

**Comment by EnTeQuAk** [comment] 2017-08-18 17:50
Closing as fixed, see screenshots. They're from my local environment, these changes are on -dev and should soon be on -stage and -prod next week.

![screenshot from 2017-08-18 19-50-10](https://user-images.githubusercontent.com/139033/29470919-77f54618-844e-11e7-9efe-21eab9a30df9.png)
![screenshot from 2017-08-18 19-49-49](https://user-images.githubusercontent.com/139033/29470921-782b820a-844e-11e7-9704-4ff75505b628.png)

**Closed by EnTeQuAk** 2017-08-18 17:50 UTC
Labels: component: search, state: in progress, triaged

**Comment by ValentinaPC** [comment] 2017-08-21 07:30
Searched for that extension on AMO-dev using FF57(Win 7) and I was not able to find it.
URL from the bar: https://addons-dev.allizom.org/en-US/firefox/search/?q=merge&appver=57.0&platform=linux
Screenshot:
![merge](https://user-images.githubusercontent.com/15685960/29508024-85b61688-865b-11e7-839f-7ef8ac2433e3.png)

**Comment by EnTeQuAk** [comment] 2017-08-21 11:45
That Extension is not on -dev unfortunately. If you create an add-on with that name (And `Merge Windows` as another one) you should be able to find them.

https://addons-dev.allizom.org/en-US/firefox/addon/merge-all-windows/

**Comment by ValentinaPC** [comment] 2017-08-21 12:46
While submitting an add-on with that name, it can be found during search or added in a collection.
Verified as fixed on AMO-dev FF55(Win 7).
Postfix screenshots:
![merge-s](https://user-images.githubusercontent.com/15685960/29519941-e945fafc-8687-11e7-8593-bd7786da92d4.png)
![mw](https://user-images.githubusercontent.com/15685960/29519942-e9482412-8687-11e7-911c-2b066537a2b0.png)
