### ISSUE TITLE
[RTL]A blank page is opened when trying to reply to a comment

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3526] opened 2016-09-15 15:16 UTC
Steps to reproduce:
1.Load FF Release with a clean profile (if the profile is not clean, comments are not loaded according with https://github.com/mozilla/addons-server/issues/3524)
2.Open any addon with comments (https://addons.allizom.org/ar/firefox/addon/searchwp/reviews/)
3.Try to reply to any comment

Expected results:
Users are able to reply to comments

Actual results:
A blank page is opened

Please see video for this issue:
![replyrtl](https://cloud.githubusercontent.com/assets/1583842/18555431/84145c14-7b70-11e6-8801-563292eb092b.gif)

**Comment by muffinresearch** [comment] 2016-09-15 15:21
I see `uncaught exception: Format string is empty!` in the console.

**Comment by muffinresearch** [comment] 2016-09-15 15:24
Looks like this might be the same thing as https://github.com/mozilla/addons-server/issues/3418

**Comment by muffinresearch** [comment] 2016-09-16 08:42
Duplicate of #3528

**Closed by muffinresearch** 2016-09-16 08:42 UTC
Labels: i18n
