### ISSUE TITLE
Browse deleted version in reviewer API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#12725] opened 2019-10-25 19:47 UTC
### Describe the problem and steps to reproduce it:

As a reviewer, use the review tools to follow a Code Manager link to a deleted version, e.g. one deleted by the developer.

Here is an example API request made by the Code Manager page:

```
https://addons.mozilla.org/api/v5/reviewers/addon/989342/versions/4887355/
```

### What happened?

The API returns a 404 and Code Manager cannot display anything.

### What did you expect to happen?

The API should not return a 404 so that Code Manager can display the deleted version.

### Anything else we should know?

The old File Viewer displays deleted versions.

See https://github.com/mozilla/addons-code-manager/issues/1159

**Comment by bobsilverberg** [comment] 2020-02-20 14:05
@EnTeQuAk Should this be fixed now?

**Comment by EnTeQuAk** [comment] 2020-02-20 20:32
I investigated this and code-wise everything does look fine and with proper permissions (Admin permissions `*:*`) you'll see deleted versions just fine.

Unfortunately I can't access the review mentioned in the original issue in https://github.com/mozilla/addons-code-manager/issues/1159 - maybe @wagnerand can help making sure I'm not missing something here?

**Comment by wagnerand** [comment] 2020-02-21 09:22
I can view the deleted file in the code-manager as well. Closing.

**Comment by AlexandraMoga** [comment] 2020-02-21 09:43
@wagnerand you can see the page with an admin user, but can you access it with a regular reviewer? My understanding of the issue is that regular reviewers should also have view access to deleted files in code manager.
See also https://github.com/mozilla/addons-code-manager/issues/1162#issuecomment-589132568 for more details.

**Comment by wagnerand** [comment] 2020-02-21 10:13
Reopening because of https://github.com/mozilla/addons-code-manager/issues/1162#issuecomment-589132568 until we know whether this is a permission/server issue, or a code-manager issue.

**Comment by bobsilverberg** [comment] 2020-02-21 11:12
@wagnerand I'm not seeing an answer here to the question of whether a non-admin should be able to see a deleted version. Should they be able to see one? If so then it sounds like there's still an issue here. @EnTeQuAk are you able to test with a non-admin account?

**Comment by wagnerand** [comment] 2020-02-21 11:35
@bsmedberg Users that have the permission `Addons:ViewDeleted` should be able to view deleted files, and that worked for me on prod. @AlexandraMoga is currently re-testing on her side to see if she can confirm.

**Comment by AlexandraMoga** [comment] 2020-02-21 12:48
@bobsilverberg @wagnerand I've retested with other examples and I can no longer reproduce the issue either. If the reviewer also has the `Addons:ViewDeleted` permission, the contents of the deleted versions were loaded in code manager. 

This is another example - https://code.addons-dev.allizom.org/en-US/browse/618827/versions/1690268/

I'm closing the issue based on that.

**Closed by AlexandraMoga** 2020-02-21 12:48 UTC
Labels: component: api, component: code manager, component: reviewer tools, priority: mvp, priority: p3

**Comment by EnTeQuAk** [comment] 2020-02-24 18:58
Thanks a lot for testing this @AlexandraMoga - I wonder if issues like https://github.com/mozilla/addons-code-manager/issues/1130 are also similarly fixed right now. I haven't checked yet, might do so later tomorrow.

**Comment by bobsilverberg** [comment] 2020-02-25 12:45
@EnTeQuAk It looks like https://github.com/mozilla/addons-code-manager/issues/1130 is not yet fixed. See https://github.com/mozilla/addons-code-manager/issues/1130#issuecomment-590785551
