### ISSUE TITLE
Downloading my webextension gives 404 error

### ISSUE THREAD

**Issue by merijndejonge** [mozilla/addons-server#6797] opened 2017-10-30 21:07 UTC
I created a new version of my web extension and signed it at AMO. After the extension got signed:
* I'm redirected to a page with a button to download the extension
* I receive an email stating that the extension has been approved and is now available for download in our gallery 
* I see the new version appear on the "Manage Status & Versions" page. If I click on the version, I am navigated to a webpage describing that version. This page contains a link to download the extension.

_Now, whether I click on the link in the email, the download button, or the link on the version page, the extension is not available in either case. I receive an 404 error message instead._

In my case, it took literally hours before the links started to work. This happened a couple of times now.

**Comment by wagnerand** [comment] 2017-10-30 21:19
Duplicate of https://github.com/mozilla/addons/issues/324.

**Closed by wagnerand** 2017-10-30 21:20 UTC

**Comment by merijndejonge** [comment] 2017-10-30 21:39
I don't see how this is related to mozilla/addons#324:

- My issue doesn't have anything to do with an addon set to "invisible"
- mozilla/addons#324 doesn't address that the link eventually becomes valid as is the case in my situation. 

My issue is really about a broken link for a signed web extension that eventually (after hours) becomes valid.

**Comment by wagnerand** [comment] 2017-10-30 21:51
No worries, it is the exact same issue.

> My issue doesn't have anything to do with an addon set to "invisible"

Since you only have self-hosted versions, your add-on is implicitly set to *Invisible*.

> mozilla/addons#324 doesn't address that the link eventually becomes valid as is the case in my situation.

It does. See the many linked issues.
