### ISSUE TITLE
icloud bookmark extension

### ISSUE THREAD

**Issue by mjlass11** [mozilla/addons-server#3039] opened 2016-07-05 00:42 UTC
I was linked here from icloud. I was trying to sync my bookmarks from Firefox, and the link was not found. I tried searching for it, but couldn't find it. Thanks

Mike Lasser
mjlass@aol.com

We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.

**Comment by jvillalobos** [comment] 2016-07-05 14:51
Dupe of #3027

The add-on was removed from the site due to stability problems.

**Closed by jvillalobos** 2016-07-05 14:51 UTC
