### ISSUE TITLE
Use "fastclick" on AMO desktop 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5417] opened 2017-05-16 10:43 UTC
Steps to reproduce:
1. Load details page for any add-on i.e. https://addons-dev.allizom.org/en-US/firefox/addon/tab-notifier/?src=cb-dl-featured
2. Click on "Add-on Review"

Expected results:
User is redirected to Reviewer Tools page.

Actual results:
Nothing happens.

Notes/Issues:
- I've logged this as a follow up for https://github.com/mozilla/addons-frontend/issues/1883 on desktop.
- not reproducible every time
- reproducible also for other buttons

Verified on AMO-dev FF53(Win 7).
Video for this issue:
![fastclick](https://cloud.githubusercontent.com/assets/15685960/26102218/c65b7586-3a3c-11e7-90c3-a902672f279d.gif)

**Comment by muffinresearch** [comment] 2017-05-16 11:24
@ValentinaPC I not sure how this is related to the fastclick issues on addons-frontend. 

This is just a link and you're using a desktop browser, I don't think there should be anythying else interfering with the link, though you could check the console + browser console to be sure.

* Can you confirm if this is a clean profile with no addons that might intercept clicks?
* Can you show the full window with the status bar in the screencast.
* Does this repro on windows 10 too?

**Comment by ValentinaPC** [comment] 2017-05-16 13:32
Maybe I misunderstood that bug, or I've checked it...wrong?
Anyway, on desktop, there is an intermittent issue related to clicks, as described above.
- I can confirm that this is reproduced on a clean new profile (now happened while clicking on Admin Manage button )
- Attaching the video including the status bar of the window (new clean profile was used this time)
- And, yes, I can be reproduced on Win10 too.

![clicks](https://cloud.githubusercontent.com/assets/15685960/26108428/2a56528c-3a55-11e7-857e-9ece13c1cd9e.gif)

**Comment by eviljeff** [comment] 2017-06-07 14:52
I managed to reproduce this after a while... but then after the button not working for multiple clicks it suddenly worked again.  (After I cleared the console; coincidence unknown).  

The buttons don't have any event listeners on them (according to devtools inspect) that could be blocking the click but the top-level page div, and the body tag itself both have click listeners from raven.min.js.  (difficult to debug locally because raven isn't enabled there, and it's minified too.)

**Comment by EnTeQuAk** [comment] 2017-06-14 06:02
I'm marking this as `triaged` since it appears to be valid from the looks of it but I am guessing this is very low priority given that it's an edge-case and very hard to reproduce.

**Comment by eviljeff** [comment] 2018-01-30 10:03
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new

**Closed by eviljeff** 2018-01-30 10:03 UTC
Labels: component: legacy frontend, needs: info, triaged
