### ISSUE TITLE
Add a link to allow users to try the new frontend.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6566] opened 2017-10-02 20:31 UTC
This should be a prominent notification on the header of the legacy frontend - this will allow users to checkout the new site more easily. 

This should be waffled off so we can flip it on in production when we're ready.

It will need a paragraph containing a link, which will set the mamo cookie to the value "on" the same as the link in the footer.

We'll need editorial and UX for what this should look like. If it's prominent and/or shown on more than say the homepage we might want to make it something that can be dismissed.

/cc @jvillalobos for input on functionality.

**Comment by jvillalobos** [comment] 2017-10-03 20:34
I'm in favor of showing the notification on all pages and making it easy to dismiss.

**Comment by pwalm** [comment] 2017-10-09 16:16
Hey @devaneymoz, are you able to provide copy for this so I build this next week? 👍

**Comment by devaneymoz** [comment] 2017-10-09 17:03
I'm guessing we want to keep this messaging strip pretty light and tight? If so how does this look...

**AMO is getting a new look. Would you like to see it?** 

_[LINK] Visit the new AMO [LINK]     [DISMISS BUTTON]_

**Comment by pwalm** [comment] 2017-10-09 17:16
Love it! SHIP IT

Thanks @devaneymoz!

**Comment by muffinresearch** [comment] 2017-10-10 12:55
@pwalm do you have an ETA on the visuals for this? Would be nice if we could land this for next week's push so we can toggle it on as soon as soon as we're ready.

**Comment by pwalm** [comment] 2017-10-10 15:52
When is push? I was going to design it next week, but can try to bump it up.

**Comment by muffinresearch** [comment] 2017-10-16 09:38
@pwalm we need this ASAP, since our tag for the Thursday push is on Tuesday (tomorrow).

**Comment by diox** [comment] 2017-10-16 11:00
What's the expected behavior if the notification is dismissed? Should it disappear forever?

FWIW, we already have a global notification system in place that would allow this. Out of the box it looks like this:

![notification](https://user-images.githubusercontent.com/187006/31608772-de7f6ff2-b271-11e7-9fdc-24bbe779274c.png)

I'll need to tweak it because a) the message is not translatable b) the dismissal only work for the current page, so it's not very useful. But maybe I can just keep that design for the initial push. Let me know.

**Comment by diox** [comment] 2017-10-16 14:13
(removed my earlier comment since I've made some progress since then)

I've implemented this locally using the existing notification system, with some fixes to make it work on all legacy frontend pages. The notification is dismiss-able (never appears again once you have dismissed it). The result is this:

![notification_implementation4](https://user-images.githubusercontent.com/187006/31616383-e0a75964-b28c-11e7-9ec6-aba9e6ba1fd3.png)
![notification_implementation3](https://user-images.githubusercontent.com/187006/31616384-e0c0d7b8-b28c-11e7-997b-585d8e632fe0.png)
![notification_implementation2](https://user-images.githubusercontent.com/187006/31616385-e0d5905e-b28c-11e7-99fa-e6e1be7ee751.png)
![notification_implementation1](https://user-images.githubusercontent.com/187006/31616386-e0edba1c-b28c-11e7-97db-57599cdd6582.png)

**Comment by diox** [comment] 2017-10-16 16:35
In the pull request @EnTeQuAk suggest to tweak the copy slightly:
> So… naming wise I'd suggest not using the word AMO but something more human like, "We are getting a new look", "This site is getting a new look" or something similar.

I agree, and this is why in my implementation I went with "Visit the new site" at the end ; but I had left the beginning of the text intact. @devaneymoz any ideas? Maybe just:

We're getting a new look! Would you like to see it? Visit the new site

?

**Comment by pwalm** [comment] 2017-10-16 21:14
Here we go:
![screen shot 2017-10-16 at 2 08 02 pm](https://user-images.githubusercontent.com/6797635/31635571-1142a148-b27c-11e7-93a1-194a4f5dc21f.png)

Specs are here:
![screen shot 2017-10-16 at 2 11 07 pm](https://user-images.githubusercontent.com/6797635/31635585-1e299cfe-b27c-11e7-9f74-d8c9ee8b256c.png)

And [backgrounds are here](https://github.com/mozilla/addons-frontend/tree/master/assets/promo%20banner)!

**Comment by diox** [comment] 2017-10-17 10:15
@pwalm do we want this only on the homepage? If not, on the other pages, where should the banner be? (In the add-on detail page, the main add-on details are included in the blue header, then continued below, it feels kinda weird to break this with the banner)

**Comment by diox** [comment] 2017-10-17 11:18
Also:
- Do we want Fira Sans in there? The legacy frontend does not have it, so that's an additional asset to download for clients.
- I can't find this close button in our assets. The legacy frontend have some dark grey close buttons, but not a white one like this one.

**Comment by diox** [comment] 2017-10-18 10:26
Closing to get QA to test this, we can tweak further if necessary. It's behind a "try-new-frontend" waffle, on every legacy frontend page (so no reviewer tools, no devhub, but pretty much everything else)

**Comment by ValentinaPC** [comment] 2017-10-18 14:42
Verified this on AMO-dev FF56(Win 7).

Banner is added but some dimensions don't correspond.
1. Size of the banner:
Specs say: 960x60 px
We have: 960x75.2 px
2. Closing mark:
Specs say: 13x13 px
We have: 25x25 px 

Also, looks a bit unaligned. Please see screenshot:
![unaligned](https://user-images.githubusercontent.com/15685960/31724754-45bac97c-b42b-11e7-972a-e8970be8e9dc.png)

And, the background of the x mark is undetectable, intended?
Please see screenshot:
![x_mark_backgr_color](https://user-images.githubusercontent.com/15685960/31724813-63639ef4-b42b-11e7-9f8b-986970d931d0.png)

**Comment by diox** [comment] 2017-10-18 15:18
I'll adjust the height and position in a follow-up commit, but the closing mark is intended for now as I don't have any other image at my disposal for it.

**Comment by pwalm** [comment] 2017-10-18 15:56
"x" svgs are in this zip, sorry about not including those before

[x.zip](https://github.com/mozilla/addons-server/files/1395345/x.zip)

**Comment by ValentinaPC** [comment] 2017-10-19 15:40
Verified the banner position on AMO-dev FF56(Win 7).
Postfix screenshot:
![2017-10-19_1839](https://user-images.githubusercontent.com/15685960/31779894-ed1ad47e-b4fc-11e7-9001-b4bb13a3ed31.png)

Is there anything else we fix here, or this can be marked as verified-fixed?
Thanks!

**Comment by diox** [comment] 2017-10-20 13:40
Latest version should:
- only be shown on homepage
- use Fira Sans Semi Bold as per spec
- use the correct close button image and position

**Closed** 2017-10-20 13:39 UTC
Labels: component: legacy frontend, needs: editorial, needs: product, needs: ux, triaged

**Comment by ValentinaPC** [comment] 2017-10-23 08:07
Verified this on AMO-dev FF56(Win 7)
- the banner is only shown in homepage
- close mark is positioned as per mocks
![2017-10-23_1044](https://user-images.githubusercontent.com/15685960/31878312-58a579e6-b7e2-11e7-9f43-7b16d0b075bf.png)

Is the font family ok?
![font](https://user-images.githubusercontent.com/15685960/31878123-a6a0d574-b7e1-11e7-82ff-12961893de4b.png)

**Comment by diox** [comment] 2017-10-23 09:21
@ValentinaPC : you are not looking at the right element to test the font (highlight the paragraphs or the link). Furthermore, it's better to use the "Fonts" tab of the inspector, which tells you directly which font is being used, regardless of what the css rule says. It should say Fira Sans SemiBold.

**Comment by ValentinaPC** [comment] 2017-10-23 12:42
Oops...
Font is like expected:
![fonts](https://user-images.githubusercontent.com/15685960/31889435-7f3088fa-b808-11e7-82a5-7b531a3dacc7.png)

Marking this verified fixed.
