### ISSUE TITLE
apparent dead link from softonic website

### ISSUE THREAD

**Issue by johncolv** [mozilla/addons-server#6848] opened 2017-11-06 14:57 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
this link doesn't work
https://en.softonic.com/download/betterprivacy/windows/post-download?ext=1

### What did you expect to happen?
download softonic better privacy add on

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

![image](https://user-images.githubusercontent.com/32726165/32447020-6203eef2-c2d0-11e7-8e19-6beff1ca84bb.png)

**Comment by jvillalobos** [comment] 2017-11-06 18:39
That needs to be fixed on the softonic website. The issue is that they're missing the `platform` bit in the URL.

**Closed by jvillalobos** 2017-11-06 18:39 UTC
