### ISSUE TITLE
Problems with uploading screenshots for add-ons on AMO dev 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7700] opened 2018-03-02 14:06 UTC
STR:
1. Load AMO dev and from Dev Hub go to a submitted add-on from the list.
2. From Edit information click on Edit Images and add some screenshots/images.
3. Click Save changes.
4. Observe the screenshot section.

Expected results:
Screenshots are displayed.

Actual results:
Image changes being processed state is not changing. The loading state or another picture instead the one uploaded is visible.

Notes:
This issue is reproducible on AMO dev with FF58 (Win10).
The add-on detail's page screenshot section is also affected.

![state processed -dev](https://user-images.githubusercontent.com/33448286/36902486-48c18666-1e33-11e8-8f92-786709fa103e.gif)

![screenshot not working](https://user-images.githubusercontent.com/33448286/36902492-4e9d4098-1e33-11e8-8f27-c4868a448613.png)

**Comment by diox** [comment] 2018-03-02 18:36
I can't reproduce right now. Do you still see this? Do you also see this on stage? Since I can't reproduce I'm tempted to blame the weird worker issues we've seen on dev recently...

**Comment by diox** [comment] 2018-03-02 18:50
https://github.com/mozilla/addons-server/issues/7594#issuecomment-370015342 was closed by ops so I'm closing this one, working under the assumption that it was the same core issue.

**Closed by diox** 2018-03-02 18:50 UTC
Labels: component: devhub, type: bug
