### ISSUE TITLE
DevHub unbroken strings are not wrapped

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#6698] opened 2017-10-17 07:48 UTC
Steps to reproduce:

1. Log into AMO and go to Developer Hub (i.e. https://addons-dev.allizom.org/en-US/developers/)
2. Click on Edit Listing for one of your submitted add-ons
3. In the Basic Information section, click on Edit and insert a long unbroken text in the Summary field
4. Click on Save Changes and observe the page layout

Expected result:
Text is wrapped in sections containing longer strings

Actual result:
Long strings spread too wide, causing layout issues

Notes:
Unbroken text added in the Description field will not be wrapped either
Reproduced on all AMO servers with FF56 (Win10)
Related to [#3517](https://github.com/mozilla/addons-frontend/issues/3517#issuecomment-337056605)

![image](https://user-images.githubusercontent.com/31961530/31652526-1887e74a-b328-11e7-84cf-77794187eb31.png)

**Comment by AlexandraMoga** [comment] 2017-10-30 15:37
This issue will also reproduce if the extension/theme has a long string name.
See how this is affecting the DevHub landing page...
![image](https://user-images.githubusercontent.com/31961530/32179206-7eee3a6a-bd97-11e7-84df-f75420db7ba1.png)
...and the Edit listing for themes page:
![image](https://user-images.githubusercontent.com/31961530/32179399-0129fba4-bd98-11e7-87a4-7ff099c37c0c.png)

**Comment by jvillalobos** [comment] 2018-04-18 15:37
@AlexandraMoga Can you please split the DevHub landing page issue into a separate one? The theme edit issue isn't worth fixing now, since we're moving to static themes.

**Comment by eviljeff** [comment] 2018-05-02 15:40
(I edited the issue to remove the references to the theme edit page)
mentor: me

**Comment by AlexandraMoga** [comment] 2018-05-03 13:57
I have filed #8166 for the DevHub landing page issue

**Comment by rihbyne** [comment] 2018-08-06 22:06
Hey all, I will take a look at this issue and update you on the progress.

**Comment by rihbyne** [comment] 2018-08-08 09:15
@caitmuenster I have local instance setup and running, I am on developer hub, from where can I submit dummy addon to fulfill step 2 to reproduce this issue ?

**Comment by EnTeQuAk** [comment] 2018-08-08 10:07
> @caitmuenster I have local instance setup and running, I am on developer hub, from where can I submit dummy addon to fulfill step 2 to reproduce this issue?

That's correct. You may have to edit the add-ons names to reproduce this issue more properly. Also make sure that you edit the names for the locale you're testing, e.g `fr` (French) since the problem only occurs for some locales.

**Comment by rihbyne** [comment] 2018-08-08 10:40
@EnTeQuAk I used web extension generator to get an addon installed. I am running firefox 61.x, is it required to run specific version mentioned by the bug reporter ? Because even in version 61.x the unbroken text is not wrapped. 

![firefox_1st_bug](https://user-images.githubusercontent.com/2492182/43832577-c2027a02-9abc-11e8-8d0e-2d598a6b77d5.png)

**Comment by eviljeff** [comment] 2018-08-08 14:41
@rihbyne yes, that's the issue - "DevHub unbroken strings are **not** wrapped"

**Comment by rihbyne** [comment] 2018-08-11 00:40
@caitmuenster @EnTeQuAk I have submitted a fix for this issue. Please review and let me know if I need to make any changes. Thank you.

**Comment by EnTeQuAk** [comment] 2018-08-28 17:06
This got actually fixed but I missed that it wasn't mentioned as such in the PR.

Closing.

**Closed by EnTeQuAk** 2018-08-28 17:06 UTC
Labels: component: devhub, contrib: assigned, contrib: good first bug, contrib: mentor assigned, priority: p4, triaged, type: papercut
