### ISSUE TITLE
Changing the file ID on web-based actions is causing numerous complications

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#1419] opened 2016-01-17 15:34 UTC
The review system has been having time-out problems for a while which is hampering the review process.

One of the causes is reassigned of file ID (and/or creating new file?!!) on web actions.

Example:
- New version of an addon is uploaded
- Addon gets an file ID
- User decides to add "Notes for Reviewers"... somehow AMO creates a new file and new file ID

Addon:
`https://addons.mozilla.org/en-US/editors/review/realtime-ip-check`

File ID after upload:
`https://addons.mozilla.org/en-US/firefox/files/browse/386698/`

File ID after adding notes via the web interface (the XPI has NOT changed)
`https://addons.mozilla.org/en-US/firefox/files/browse/386700/`

And again ..... (facing Not Found in the middle of a review)
`https://addons.mozilla.org/en-US/firefox/files/browse/386705/`

A review posted during these changes causes timeout-, lost review (and points), and on occasion review ending on a separate version which doesn't exist thus making the update impossible for the users.

Another similar situation which happens alarmingly regularly is when user changes the review type (eg from Full to Prelim) which causes similar complications.
Example:
`https://addons.mozilla.org/en-US/editors/review/toggle-web-developer-toolbar`
`https://addons.mozilla.org/en-US/editors/review/facebook-sidebar`

Why should the file IDs change when the actual XPI has not changed and there have only been changes to the web-based detail of the addon?

**Comment by diox** [comment] 2016-01-19 12:20
I can't reproduce this issue locally or on dev. Adding notes for reviewers doesn't create a new File for me, and the id does not change. I also can't find in the code what would cause this.

Are you sure this isn't the developer deleting and recreating files ? or maybe it only happens with specific types of addons - hard for me to say at the moment as I don't have reviewer permissions on prod.

**Comment by erosman** [comment] 2016-01-19 16:07
I am not an admin reviewer so I have limited access to certain areas.

I am not sure but it didnt feel like a delete-upload new version. They often happen in such a short space of time which makes it unlikely but I can not verify it.

When the upload is an update, AMO usually displays the record if it was deleted and reuploaded which makes the above scenario even less likely.

**Comment by erosman** [comment] 2016-01-22 08:18
Another example ,.. just happened now:

    https://addons.mozilla.org/en-US/editors/review/flex-confirm-mail
    https://addons.mozilla.org/en-US/firefox/files/compare/389152...387260/
    https://addons.mozilla.org/en-US/firefox/files/compare/389152...378175/

**Comment by diox** [comment] 2016-01-22 11:10
Can anyone reproduce on dev or stage ? It's much harder to investigate something like that on prod as many of us don't have the right permissions for it.

**Comment by jvillalobos** [comment] 2016-01-22 18:25
I tried a few things on -dev and couldn't reproduce the problem.

**Comment by erosman** [comment] 2016-01-22 18:38
I uploaded my own addons today and made some Web changes....
Sadly, I could not see if anything happened due to the "Self-review" :(

**Comment by erosman** [comment] 2016-01-23 15:20
Another observation:

ref: `https://addons.mozilla.org/en-US/editors/review/whatsapp-launcher`

Why and how does the version 4 upload time?
Supposedly, 4 file IDs were created (one for each)
```
Version 0.1 · January 23, 2016 · Awaiting Review
By iTon on Jan 23, 2016 5:28:15 AM
By iTon on Jan 23, 2016 6:24:27 AM
By iTon on Jan 23, 2016 6:25:52 AM
By iTon on Jan 23, 2016 6:27:04 AM
```

**Comment by wagnerand** [comment] 2016-01-23 15:28
What are those four file IDs?

**Comment by erosman** [comment] 2016-01-23 15:35
I don't have those IDs... I said, supposedly, 4 IDs were created. Olympia server log (if there is one) should/could have the info.

**Comment by wagnerand** [comment] 2016-01-23 15:38
How do you know several file IDs have been created then?

**Comment by erosman** [comment] 2016-01-23 15:47
No I dont.
I was wondering if the above mentioned anomaly is also a symptom of the same issue that I reported in this thread.

Some processes have been carried out on each of these reported time, but what?
```
By iTon on Jan 23, 2016 5:28:15 AM
By iTon on Jan 23, 2016 6:24:27 AM
By iTon on Jan 23, 2016 6:25:52 AM
By iTon on Jan 23, 2016 6:27:04 AM
```

Once again, in the case of the following I found the file ID changed in between the time I loaded the review page and and I opened the compare page:
```
https://addons.mozilla.org/en-US/editors/review/new-find-toolbar-with-alert
https://addons.mozilla.org/en-US/firefox/files/compare/389751...259112/
https://addons.mozilla.org/en-US/firefox/files/compare/389755...259112/
```
File ID 389751 changed to 389755 ... finding out how and why is the purpose of this thread.
The time gap was really too short for the dev to upload a version, delete the version, and upload a new version.

**Comment by wagnerand** [comment] 2016-01-23 15:58
I suspect the upload/validation process is not completed yet as you tend to
start reviewing right after an add-on appears in the queue. Maybe just wait
a couple of minutes?

**Comment by EnTeQuAk** [comment] 2017-01-09 17:26
I'm marking this as triaged but I don't know what priority this should be. It seems this can be a rabbit-hole to debug.

**Comment by EnTeQuAk** [comment] 2018-01-30 13:40
I'm actually closing this. We might have fixed this when we enabled django-post-request-task which makes asynchronous tasks much much more reliable. The bug is quite old so if there are more problems like this please feel free to create a new issue about this.

**Closed by EnTeQuAk** 2018-01-30 13:40 UTC
Labels: component: reviewer tools, triaged
