### ISSUE TITLE
Some pages still have gradient sections

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2199] opened 2016-04-05 12:54 UTC
Steps to reproduce:
1. Sign in to AMO-dev page https://addons-dev.allizom.org/en-US/
2. Go to "Collections"
3. Make a search 
4. Observe the results page layout

Expected result:
There are no display or layout issues.

Actual results:
Search results header still has a gradient.

Notes/Issues:
The issue is also reproducible in other pages like: My Themes, Collections I've Made, Collections I'm Following, Search Tools, any themes categories pages.
Screenshot for this issue: 
![2016-04-05_1541](https://cloud.githubusercontent.com/assets/15685960/14282317/83d744c8-fb46-11e5-8202-b75538596026.png)

**Comment by madalincm** [comment] 2016-04-06 12:23
Reproducing also in https://addons.allizom.org/en-US/firefox/themes/?sort=up-and-coming page
![upandcomingthemes](https://cloud.githubusercontent.com/assets/15685441/14316409/7ecbc696-fc0b-11e5-8be0-13fe2b25ab90.png)

**Comment by eviljeff** [comment] 2016-05-17 17:55
mentor @tofumatt 
Can you add steps to get started?

**Comment by wagnerand** [comment] 2016-07-26 17:49
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by muffinresearch** [comment] 2017-02-20 17:16
Going to mark this as wontfix since it will be covered by the upcoming changes in addons-frontend.

**Closed by muffinresearch** 2017-02-20 17:16 UTC
Labels: contrib: good first bug, project: style refresh, triaged
