### ISSUE TITLE
MySQL error "Out of sort memory, consider increasing server sort buffer size" on -dev

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15970] opened 2020-11-10 17:50 UTC
See: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/9984890/

Looks like it is raised when an admin visits https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/

**Comment by willdurand** [comment] 2020-11-10 17:51
It seems to be -dev only but let's make sure that's the case (because otherwise that'd be bad). cc @bqbn

**Comment by bqbn** [comment] 2020-11-11 18:56
The default [sort_buffer_size](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sort_buffer_size) is 256 KB for both v5.7 and v8.0. In -dev environment, we have been using the default value before and after the DB upgrade.

We upgraded the DB engine on Nov 2, and I see the error only started to happen on Nov 9, i.e. there is one week time between DB upgrade and the first appearance of this error. Is there any code change around Nov 9 that could result in the app needing more memory to sort?

That being said, in order to unblock this, we've bumped up the value of sort_buffer_size to 1 MB in -dev environment.

**Comment by willdurand** [comment] 2020-11-11 20:20
> Is there any code change around Nov 9 that could result in the app needing more memory to sort?

Yes, we changed the mysql client libs afaik

**Comment by bqbn** [comment] 2020-11-11 23:09
Hmm, new client lib causes more memory for sorting? The sorting happens in the database though, in what circumstance can a client lib affect how much memory the database allocates for sorting?

Are there any db query changes that demand more sorting buffers?

**Comment by willdurand** [comment] 2020-11-12 07:16
> new client lib causes more memory for sorting? 

I'd say "no" but I am not sure.. We didn't land a lot of mysql related changes.

**Comment by diox** [comment] 2020-11-12 10:57
We haven't landed any changes that would affect the queries the scanners admin is making since October.

**Comment by willdurand** [comment] 2020-11-12 11:03
> That being said, in order to unblock this, we've bumped up the value of sort_buffer_size to 1 MB in -dev environment.

AFAICT, that didn't help.. :/

**Comment by diox** [comment] 2020-11-12 11:17
Our investigations so far:
- The query to reproduce it is simply `SELECT * FROM `scanners_results` ORDER BY `scanners_results`.`created` DESC LIMIT 10;`
- The problem is that `created` is not indexed - we thought it was
- That forces MySQL to do a `filesort` for this query. Because some rows are quite large (they contain raw json) MySQL needs a lot of space to do the sorting
- We're hoping an index would fix it. We're going to try to reproduce locally.
- It's still possible it was caused by the upgrade, but it could just be bad luck, just caused by one big row added to the table recently.

**Comment by diox** [comment] 2020-11-12 13:03
- It also applies to the scanners API (only available through internal host + auth)
- Sorting by `-pk` instead of `-created` locally seems to fix it, so maybe we don't need the index

**Comment by bqbn** [comment] 2020-11-12 23:35
> > That being said, in order to unblock this, we've bumped up the value of sort_buffer_size to 1 MB in -dev environment.
> 
> AFAICT, that didn't help.. :/

Do we need to bump the sort_buffer_size again, or wait and see if sorting by `-pk` helps?

Does any one know why the 256 KB `sort_buffer_size` is good enough in v5.7, but even 1 MB is not enough in v8.0? 

Is it because of the way how MySQL sorts changed, or is it not related to the DB version but is because we're sorting by the wrong column, or because we're not using index?

**Comment by willdurand** [comment] 2020-11-13 09:09
> Do we need to bump the sort_buffer_size again, or wait and see if sorting by `-pk` helps?

I don't think so because it seems to use the index correctly with `pk`.

> Does any one know why the 256 KB `sort_buffer_size` is good enough in v5.7, but even 1 MB is not enough in v8.0?
> 
> Is it because of the way how MySQL sorts changed, or is it not related to the DB version but is because we're sorting by the wrong column, or because we're not using index?

We don't know but I plan to try to reproduce on stage today. If I can't reproduce with the same STR I used on -dev/local dev, I guess that will mean it's a problem with MySQL 8 (or before, but after v5.7). If we can reproduce, well... it means we are lucky.

**Comment by willdurand** [comment] 2020-11-13 09:44
I created a WAT scanner result on -stage (which should be the only one, really) with a large JSON result (~1MB) just like I did locally. I cannot reproduce the problem. An `EXPLAIN` shows that it uses `filesort` but it does not seem to be a problem so far.

**Comment by willdurand** [comment] 2020-11-13 09:44
I'm going to add more WAT results to see if that changes anything.

**Comment by willdurand** [comment] 2020-11-13 10:08
Given that I could not replicate locally, I started to look elsewhere. It turns out that -stage and -prod have a bigger `sort_buffer_size` value than we thought: it is actually `20971520` and it is configured here: https://github.com/mozilla-services/cloudops-deployment/blob/9e6e6a553c7af274102c93df005983c483809437/projects/addons-server/ansible/templates/parameter-groups-mysql-v5.7-prod.yml#L56

-dev value is `1048576` currently, which is what @bqbn deployed earlier this week. Local dev has `26214` for some reasons (maybe the default value in the docker image).

I believe we should configure MySQL 8 with most of the custom values we have for 5.7. It won't prevent us to change our code a bit but the problem comes from a slight misconfiguration (I suppose this `sort_buffer_size` value was increased for other purposes than the scanners table).

**Comment by diox** [comment] 2020-11-30 13:34
No longer a p2 since this was just dev and it's been fixed by a config change. It would be nice to do https://github.com/mozilla/addons-server/issues/15970#issuecomment-726064548 to avoid the `filesort` though.

**Comment by willdurand** [comment] 2020-12-01 10:31
> No longer a p2 since this was just dev and it's been fixed by a config change. It would be nice to do [#15970 (comment)](https://github.com/mozilla/addons-server/issues/15970#issuecomment-726064548) to avoid the `filesort` though.

I filed https://github.com/mozilla/addons-server/issues/16068.

**Closed** 2020-12-01 10:32 UTC
Labels: component: scanners, priority: p3, qa: not needed

**Comment by rajkananirk** [comment] 2022-02-20 15:38
get this help full query just run and error solved instant https://laratuto.com/out-of-sort-memory/
