### ISSUE TITLE
outgoing.prod.mozaws.net eats "&"

### ISSUE THREAD

**Issue by JustOff** [mozilla/addons-server#3929] opened 2016-11-03 16:52 UTC
Redirector, used on AMO, eats "&" in urls, making the links broken.

For example, at [here](https://addons.mozilla.org/addon/cookies-exterminator/), near the end of description, link to forums.mozillazine.org.

**Comment by muffinresearch** [comment] 2016-11-03 16:59
Duplicate of https://github.com/mozilla/addons/issues/146 

A patch has landed we're just waiting for it to be deployed.

**Closed** 2016-11-03 16:59 UTC
Labels: duplicate
