### ISSUE TITLE
Some layout issues on admin tools in promoted add-ons and secondary hero shelves 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20686] opened 2023-05-11 13:31 UTC
From https://github.com/mozilla/addons-server/issues/20651

Promoted add-ons module, the Images section -> the alignment used to be more robust, now they're displayed one by one 

![broken1](https://github.com/mozilla/addons-server/assets/33448286/c3f3305a-0eeb-486e-a2c1-db0386be1f21)

the svg format is not displayed correctly - icons are not visible with the exception of the first section 
![broken2](https://github.com/mozilla/addons-server/assets/33448286/a0738a48-c89e-41a7-b96b-6410942bfba8)

![broken3](https://github.com/mozilla/addons-server/assets/33448286/e41d07cc-98bc-4177-95d6-d321ef75806e)

**Comment by eviljeff** [comment] 2023-06-28 09:05
there's some crossover (one is probably a partial dupe of the other) between this and #20761

**Closed** 2023-06-29 14:26 UTC
Labels: component:admin_tools, priority:p3

**Comment by ioanarusiczki** [comment] 2023-06-30 16:34
@eviljeff Both layout issues have been fixed on AMO Dev.

**Comment by KevinMind** [comment] 2024-05-04 19:21
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-353
