### ISSUE TITLE
icloud bookmarks extension for firefox

### ISSUE THREAD

**Issue by bryanvanwyk** [mozilla/addons-server#3131] opened 2016-07-20 12:14 UTC
i am trying to sync my bookmarks on firefox with icloud. when i click on the download link from icloud it takes me to firefox add-ons page where i get told the link is wrong.

**Comment by jvillalobos** [comment] 2016-07-20 14:14
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by jvillalobos** 2016-07-20 14:14 UTC
