### ISSUE TITLE
Display issue for "Hebrew" lang pack title

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1700] opened 2016-02-17 14:46 UTC
Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/firefox/
2. Go to "More" - "Dictionaries & Language Packs"
3. Load details page for the "Hebrew" lang pack (https://addons.allizom.org/en-US/firefox/addon/hebrew-il-language-pack/)

Expected results:
There are no display or layout issues.

Actual results:
The name of the add-on is not displayed correctly.

Notes/Issues:
**The add-on looks the same in AMO-prod**. _Also, the majority of lang packs have no "summary" or "category" (fields mandatory at add-on submission)_.
Verified on FF44(Win 7). Issue is reproducing in AMO-stage, AMO-dev and AMO-prod.
Please see the screenshot: 
![2016-02-17_1522](https://cloud.githubusercontent.com/assets/15685960/13112770/fa96417c-d594-11e5-9bfd-5434b5934795.png)

**Comment by muffinresearch** [comment] 2016-02-29 18:24
Looks to be because the title has been localized by the author to Hebrew (which is RTL) despite the text seemingly being English. This is expected behaviour from AMO so going to close this as it's not a bug.

**Closed by muffinresearch** 2016-02-29 18:24 UTC
Labels: invalid
