### ISSUE TITLE
Verification fails with “Invalid file name in archive”

### ISSUE THREAD

**Issue by elijaholmos** [mozilla/addons-server#19762] opened 2022-10-05 22:48 UTC
### Describe the problem and steps to reproduce it:
Hey, I ran into a very odd error where my extension zip file would not pass verification when I attempted to upload it to the firefox add-on store. Here's a screenshot of the validation results page:
![image](https://user-images.githubusercontent.com/35435704/194174494-807a34f4-b8ff-4f41-bd22-da5a3eecca86.png)

I could only find one other person who had a similar issue, and it appears to have happened very recently. [Here's](https://discourse.mozilla.org/t/verification-fails-with-invalid-file-name-in-archive/106160) their Mozilla forum post. I followed the steps that seemed to resolve his issue: zipping the extension myself using the built-in Windows compression tool (select multiple files, right click, choose Send To > Compressed Folder). When I submitted the manually zipped file to the Firefox add-on store, it successfully passed verification with no errors.

The extension I developed is actually open source, and I'll link the GitHub repository so the build process can be inspected in detail:
https://github.com/elijaholmos/halo-notion-extension
pnpm is the package manager. `pnpm build:firefox` executes a Rollup command, which begins the extension build process by referencing my Rollup configuration file (https://github.com/elijaholmos/halo-notion-extension/blob/main/rollup.config.js#L75). The majority of the build process is probably irrelevant, because I've had this work with another (more complex) extension that I was able to manually upload to the addon store without errors. Recently, I switched the tool that I use to compress my files into an archive, and I think that is the most probable culprit. If you jump to line [132](https://github.com/elijaholmos/halo-notion-extension/blob/main/rollup.config.js#L132) of my Rollup config file, you'll see I reference an external plugin `zip`, which is a custom plugin located in the same repository.

https://github.com/elijaholmos/halo-notion-extension/blob/main/plugins/zip.plugin.js uses the npm package [`fflate`](https://www.npmjs.com/package/fflate) to zip all files from the Rollup output directory into a single archive file. I don't know the technical details of how `fflate` works, but since I switched to it, my Firefox addons have failed validation. I tested this with another addon I've developed, and the `fflate`-compressed archive was rejected, but the manually compressed archive was not.

Please let me know if you'd like any other information from me to help resolve this issue!

**Comment by diox** [comment] 2022-10-06 11:54
Hi,

As the discourse thread implies, the problem is that the package you're using to generate the zip creates files that use backslashes instead of forward slashes as the path separator for directories. This is not a bug: we don't accept this on purpose to avoid potential compatibility issues. This should be fixed on your side, either by switching to a different library or finding a way to make the one you're using generate a zip using forward slashes.

**Closed by diox** 2022-10-06 11:54 UTC

**Comment by diox** [comment] 2022-10-06 15:49
In the actual structure of the zip itself. You can see in the error message it's complaining about a `popup\index.html` file - the filename would be valid if it was `popup/index.html`.
