### ISSUE TITLE
icloud

### ISSUE THREAD

**Issue by Brumbear52** [mozilla/addons-server#3119] opened 2016-07-19 15:07 UTC
will bookmarks plugin in firefox to synchronise bookmarks ???

**Comment by jvillalobos** [comment] 2016-07-19 20:02
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by jvillalobos** 2016-07-19 20:02 UTC
