### ISSUE TITLE
Add-on in Content/Post Review Queue cannot be approved if latest version is disabled

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6894] opened 2017-11-13 10:47 UTC
https://reviewers.addons.mozilla.org/en-US/editors/review-content/middle-click-to-go-back cannot be approved because the latest version has been disabled, the current public version has been approved by a technical reviewer.

**Comment by diox** [comment] 2017-11-24 11:04
Note: this also happens for post-review, not just content-review.

**Comment by diox** [comment] 2017-11-24 12:27
So, a simple fix is this:
```diff
diff --git a/src/olympia/reviewers/views.py b/src/olympia/reviewers/views.py
index c01b4db..e5fadd5 100644
--- a/src/olympia/reviewers/views.py
+++ b/src/olympia/reviewers/views.py
@@ -831,7 +831,7 @@ def review(request, addon, channel=None):
             request, addon, channel, content_review_only=content_review_only)
 
     version = addon.find_latest_version(
-        channel=channel, exclude=(amo.STATUS_BETA,))
+        channel=channel, exclude=(amo.STATUS_BETA, amo.STATUS_DISABLED))
 
     if not settings.ALLOW_SELF_REVIEWS and addon.has_author(request.user):
         amo.messages.warning(
```

But I need to check the impact of doing this.

**Comment by diox** [comment] 2017-11-24 12:53
This code was last changed in 9b624546997a84862d0137f7fdb3203db11969e0 but even before then, we didn't exclude disabled versions so could end up in a similar situation, but with legacy add-ons.

Best I can tell excluding the disabled version here (`find_latest_version` default behavior is already to exclude `(amo.STATUS_BETA, amo.STATUS_DISABLED)` so the final patch is actually even shorter) makes sense, I'll submit a PR.

**Comment by ValentinaPC** [comment] 2017-11-27 09:48
Verified as fixed on AMO-dev FF57(Win 7).
An add-on can be content approved and confirm approval even if the last version is disabled.
Postfix screenshots:
![ac](https://user-images.githubusercontent.com/15685960/33260529-c71b6e16-d368-11e7-881e-17a812584120.png)
![conf_ap](https://user-images.githubusercontent.com/15685960/33260530-c739746a-d368-11e7-88e9-7e4377535bab.png)

**Comment by eviljeff** [comment] 2017-12-05 22:05
Alas, the fix caused mozilla/addons#576 which was deemed to be worse

**Comment by diox** [comment] 2018-01-03 15:28
Summary of IRC discussion:
We want 2 things that kinda contradict one another: in this issue, allowing approval confirmation (content or not) to ignore the disabled version, and in mozilla/addons#576, not ignoring it for other actions.

Excluding any big UI changes that would let reviewer choose which version to apply the action to, that leaves 2 choices:
- Either we carefully pick which actions are ignoring disabled versions and which don't
- Or we try to separate user-disabled from admin/amo-disabled, and *then* ignore user-disabled versions for all actions

I'm leaning towards the latter. However as @wagnerand pointed out, there are still uncertainties. If a reviewer submit a reviewer reply or comment, it's hard to say which version they want to have it attached to. This requires some testing to understand what edge cases this could cause, and maybe some styling to make it obvious which version is going to be affected by actions. We don't want to hide the user-disabled versions, but maybe just style them in a different way.

**Comment by eviljeff** [comment] 2018-01-03 15:40
I can still see a lot of edge cases where reviewers went to reply to, or comment on, disabled versions. Overall we should limit what actions apply to disabled versions - i.e. approving content only. If we go down the route of having actions apply to disabled versions (whether user disabled or not) one problem is activity mail tokens explicitly don't work with disabled versions, by design.

**Comment by diox** [comment] 2018-01-08 12:06
> I can still see a lot of edge cases where reviewers went to reply to, or comment on, disabled versions. Overall we should limit what actions apply to disabled versions - i.e. approving content only. If we go down the route of having actions apply to disabled versions (whether user disabled or not) one problem is activity mail tokens explicitly don't work with disabled versions, by design.

I agree but... I'm confused about something. Wasn't the whole point of reverting the change to allow comments/replies on disabled versions ? As I understand it that's what's going on in mozilla/addons#576, which prompted for the revert.

**Comment by diox** [comment] 2018-01-09 14:26
Spent a lot of time trying to figure out the best thing to do here, and I'm still unsure. My new plan is to always apply confirm approval action (for both content and post review) to the `current_version`, ignoring the latest submitted version (`current_version` always point to the latest public version). One caveat is that any comments by reviewers won't follow that and instead will still go to the last submitted version, which might not be the same - but we can't have it both ways without completely overhauling the UI/review flow.

**Comment by diox** [comment] 2018-01-09 16:06
Aaand I found another potential contradiction :) 

A few months ago, https://github.com/mozilla/addons-server/issues/5604 requested that the confirm approval action should not be available if the latest version is pending. That breaks if we start ignoring the latest submitted version as described above...

@wagnerand what should we do here? Do we really want to make a special case just for disabled versions, just for the confirm approval action?

**Comment by wagnerand** [comment] 2018-01-09 20:21
Recap from IRC:

* All actions should ignore beta versions.
* All actions should ignore all files that are in a different distribution channel than the current view. (This means that if the reviewer is on the listed-review page, all unlisted versions should be ignored and vice-versa.)

* `Approve Content` and `Approve` should apply to the current public version (for logging).
* `Reject multiple versions` should apply to all selected versions.
* `Reviewer Reply` should apply to the latest submitted version.
* `Request Super Review` should apply to the latest submitted version.
* `Comment` should apply to the latest submitted version.

**Comment by eviljeff** [comment] 2018-01-09 22:50
The Recap is all for post-review reviews I assume?  For non-webextensions Approve will have to relate to the most recent STATUS_AWAITING_REVIEW version (havn't thought through the other actions)

**Closed** 2018-01-11 13:06 UTC
Labels: component: reviewer tools, priority: p2, triaged

**Comment by AlexandraMoga** [comment] 2018-01-12 12:53
Verified on AMO-dev, FF57 (Win10).
- 'Confirm Approval' and 'Approve Content' buttons are now present in the review pages of add-ons having their last submitted version disabled. Approval actions will apply to the current listed version.
- Review actions such as 'Reviewer reply', 'Request super review' and "Comment' will apply to the latest submitted version, even when disabled.

Postfix screenshot:

![image](https://user-images.githubusercontent.com/31961530/34875805-7db588c0-f7a7-11e7-89aa-c896dc532449.png)
![image](https://user-images.githubusercontent.com/31961530/34875815-85265c42-f7a7-11e7-84fc-71e5145bcca4.png)

@diox I suppose this was not applied to the Legacy queue. Here, if an add-on has a disabled version, approval is no longer possible. Is this expected?

**Comment by diox** [comment] 2018-01-12 13:56
> @diox I suppose this was not applied to the Legacy queue. Here, if an add-on has a disabled version, approval is no longer possible. Is this expected?

Yes.
