### ISSUE TITLE
The sponsored shelf API returns a 500 error on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16267] opened 2021-01-06 13:16 UTC
### Describe the problem and steps to reproduce it:
Call the sponsord shelf api on stage: https://addons.allizom.org/api/v5/shelves/sponsored/

### What happened?
A 500 error is returned

### What did you expect to happen?
The sponsored shelf contents are returned

### Anything else we should know?
Not reproduced on -dev and prod

**Comment by diox** [comment] 2021-01-06 13:34
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/10361983/?query=is%3Aunresolved

Looks like there aren't any decisions returned by Adzerk, and we don't handle that.

**Comment by eviljeff** [comment] 2021-01-06 13:51
I've a feeling this is due to the campaign settings in Adzerk (now known as "kevel" apparently) specifying an end date of 31 Dec 2020.

**Comment by AlexandraMoga** [comment] 2021-01-06 14:05
This issue seems to affect the homepage as whole, which will fail to load sometimes and returns a Server error page.

**Comment by eviljeff** [comment] 2021-01-06 14:34
I bumped the end date for the stage (and local dev) campaigns, so lets see if that helps.  (caching tho)

**Comment by bobsilverberg** [comment] 2021-01-06 14:40
Even if changing the date fixes it, shouldn't we be handling that possibility and just returning an empty set of add-ons, as opposed to throwing a 500?

**Comment by AlexandraMoga** [comment] 2021-01-06 14:54
The 500 API error no longer reproduces, however the homepage is still throwing intermittent server errors. I'll file a separate issue on the frontend for this to be investigated further.

**Comment by AlexandraMoga** [comment] 2021-01-06 15:06
Actually, the issue seems to be back now.

**Comment by bobsilverberg** [comment] 2021-01-06 15:46
I am seeing it on stage still as well.

**Comment by jvillalobos** [comment] 2021-01-06 15:51
Wouldn't be a bad time to disable the shelf, but that should be confirmed with @atsay

**Comment by bobsilverberg** [comment] 2021-01-06 15:53
> Wouldn't be a bad time to disable the shelf, but that should be confirmed with @atsay

I was thinking the same thing, but wasn't sure if we can just do that now. I also have another fix that needs to be cherry-picked for the shelf, so removing it now could kill two birds with one stone.

**Comment by atsay** [comment] 2021-01-06 17:13
Please hold, a decision on how the shelf will evolve is pending.

**Comment by eviljeff** [comment] 2021-01-22 17:14
The sponsored shelf is gone (in mozilla/addons-frontend#9991) so closing

**Closed by eviljeff** 2021-01-22 17:14 UTC
Labels: component: api, env: stage, priority: p3
