### ISSUE TITLE
File browser omits various files from the xpi

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#3579] opened 2016-09-22 08:31 UTC
### Describe the problem and steps to reproduce it:
- Go to https://addons.mozilla.org/en-US/firefox/files/browse/498777/
### What happened?
- For me, the only files visible are three files in the content directory and some css files in data/css. All remaining files are missing
- The add-on looks fine when downloading it and contains much more files
### What did you expect to happen?
- All files should be visible in the file viewer

**Comment by kewisch** [comment] 2016-09-22 10:15
I'm getting this with other add-ons now too, seemingly in the middle of the review. I was on https://addons.mozilla.org/en-US/firefox/files/browse/502870/ and when I clicked on popup.css it didn't load. Reloading https://addons.mozilla.org/en-US/firefox/files/browse/502870/file/config/css/popup.css#top gave me a not found error.

**Comment by eviljeff** [comment] 2016-09-22 11:18
I wouldn't assume that missing privacy policy is connected to missing files (given it's stored in the database and the file view is generated from the xpi).  Can you log it separately?

**Comment by kewisch** [comment] 2016-09-22 12:10
Ok, opened https://github.com/mozilla/addons-server/issues/3580 for the privacy policy and will edit comment 0 to remove those bits for better readability

**Comment by erosman** [comment] 2016-09-22 12:45
Note: The validator is working fine in above cases.

**Comment by kewisch** [comment] 2016-09-22 13:03
It seems now that even some files are 404'ing. https://addons.mozilla.org/firefox/downloads/file/507119/note_board-3.0.2-fx+an.xpi?src=editor has issues, even though the file is not marked as deleted.

**Comment by erosman** [comment] 2016-09-23 11:49
Another example:
https://addons.mozilla.org/en-US/firefox/files/browse/507789/file/background.js#top

**Comment by wagnerand** [comment] 2016-10-10 21:11
This might be happening due to concurrently running extraction processes. What we should do is before extracting a file, check whether that same file is already being extracted.

Extraction is ultimately happening in `src/olympia/files/utils.py:552`. We'd need to add the check somewhere in that callstack.

**Comment by wagnerand** [comment] 2016-10-10 21:12
As this has come up several times, now, I'm flagging this with a higher priority.

The impact is that reviewers might miss serious issues because some files don't appear in the file viewer.

**Comment by wagnerand** [comment] 2016-10-10 21:20
I'd suggest adding the check in `extract_xpi` in that same file (`src/olympia/files/utils.py:573`).

I'm not sure what would be a good way to remember which files are currently being extracted...

**Comment by muffinresearch** [comment] 2016-10-17 14:11
@EnTeQuAk could you look into this please and see if you can find a cause for why this is happening?

**Comment by EnTeQuAk** [comment] 2016-10-18 11:12
I'm still trying to reproduce the issues properly locally. Regarding the idea of concurrent access - that could be a factor. There are a few minor locks already around extraction so it appears that might not be the actual problem here.

One thing I noticed, there's some weirdness in how `extract_xpi` is implemented and it appears to only extract up to 10 times deep or 10 times in total, so is the size or count of folders maybe something those add-ons have in common?

**Comment by EnTeQuAk** [comment] 2016-10-18 11:22
There is a `cleanup` method that potentially removes the extracted files but it appears that it's never called.

**Comment by EnTeQuAk** [comment] 2016-10-18 11:25
Nevermind, they are being deleted and the fact that we are using always the same folder (because it's based on the file-id) might lead to some weirdness. Not sure though if it's the exact problems we see here.

**Comment by wagnerand** [comment] 2016-10-18 12:03
> One thing I noticed, there's some weirdness in how extract_xpi is implemented and it appears to only extract up to 10 times deep or 10 times in total, so is the size or count of folders maybe something those add-ons have in common?

That is, so that inner XPIs (unlikely) and JARs (more likely) are extracted as well. The occurrences I noticed didn't hit that limit though.

**Comment by EnTeQuAk** [comment] 2016-10-18 12:52
This could be a regression of our EFS switch which doesn't appear to update `atime` anymore which leads to a hard-delete of already extracted folders and thus maybe to those in-between-deletions mentioned above (or weird behaviors at least).

**Comment by EnTeQuAk** [comment] 2016-10-18 17:38
More recent findings: It has nothing to do with EFS, it's just silly code, improperly working caches and the fact that actual files can be deleted if someone is still looking at them. I'm fixing this, making it more predictable and reasonable but it won't land before next week's tag so we can get some more testing.

**Comment by EnTeQuAk** [comment] 2016-10-25 10:33
Alrighty, it's time for an update.

It's reproducable on dev, stage and production and I have an add-on locally that reproduces it there perfectly, uploading it shows that only a few files get extracted and we see ` Error ('ascii' codec can't decode byte 0xd0 in position 8: ordinal not in range(128)) extracting /mnt/efs/addons.allizom.org/files/618225/nr-1.0.11-fx.xpi :/data/olympia/src/olympia/files/helpers.py:107` in kibana.

The relevant code-line that raises this error is a `shutil.copytree` which is prone to unicode errors depending on how file-names get passed in. But apparently it looks like it's handled quite good everywhere or I can't see the actual problem, even worse, I just can't reproduce it locally. Not via a unittest, not via django runserver and not via the uwsgi setup we are using on production.

It's completely irrelevant of any time-outs or crons that delete files. That part is bad and could be improved but isn't the actual problem.

😞

**Comment by diox** [comment] 2016-10-25 11:05
I have no idea, but it sounds suspiciously like mozilla/addons/issues/132 which I can't reproduce either locally :(

**Comment by EnTeQuAk** [comment] 2016-10-25 11:22
Yeah, I have the feeling that it's the same-ish problem like mozilla/addons#132 which makes it even worse and more wide-spread :(

**Comment by muffinresearch** [comment] 2016-10-26 19:17
Moving this to this week's milestone with a view to cherry-picking and putting this out tomorrow.

**Comment by EnTeQuAk** [comment] 2016-10-27 05:56
The patch now results in a 500 server error, because the fix works and now fails at another code block. https://sentry.prod.mozaws.net/operations/olympia-dev/issues/362937/

A bit more investigation, I added a print https://github.com/mozilla/addons-server/blob/master/src/olympia/files/helpers.py#L286 and now I finally see a difference between my local system and our dev/stage/prod environment.

local: ``('/code/src/olympia/../../tmp/file_viewer/1/skin/img', 'logo - \xd0\xba\xd0\xbe\xd0\xbf\xd0\xb8\xd1\x8f.png', <type 'str'>, <type 'str'>)``

remote: ``('16x16.png', u'/mnt/efs/addons-dev.allizom.org/shared_storage/tmp/file_viewer/1/skin/img', <type 'str'>, <type 'unicode'>)``

Investigating more...

**Comment by EnTeQuAk** [comment] 2016-10-27 06:37
Alrighty, so **the** difference between our local environments and our servers is the following:

```python
In [16]: from django.conf import settings

In [17]: settings.NETAPP_STORAGE
Out[17]: '/code/src/olympia/../../tmp'
```

```python
In [3]: from django.conf import settings

In [4]: settings.NETAPP_STORAGE
Out[4]: u'/mnt/efs/addons-dev.allizom.org/shared_storage'
```

which leads to passing unicode strings for paths around but our filenames are usually bytecode-encoded which clashes and leads to our UnicodeDecodeError.

**Comment by EnTeQuAk** [comment] 2016-10-27 06:48
to finally make unittests fail, https://gist.github.com/EnTeQuAk/24f755d7dc006a27a7c054a963c65667

I'm honestly not sure whether to patch things or to just remove the `u'` prefix from our configs :-/

**Comment by EnTeQuAk** [comment] 2016-10-27 06:53
This got introduced for another fix in 86365f36490d5ca2a4a7b726200e93a1bf9d1b01 so I'm guessing, let's see what breaks running unittests with unicode paths and fix it.

**Comment by EnTeQuAk** [comment] 2016-10-27 16:19
![page-shot-2016-10-27 file viewer __ editor tools](https://cloud.githubusercontent.com/assets/139033/19775797/e182b158-9c71-11e6-8e0d-0007988e7489.png)

**Comment by erosman** [comment] 2016-11-25 14:45
Another example:
https://addons.mozilla.org/en-US/firefox/files/browse/540557/

**Comment by wagnerand** [comment] 2016-11-25 14:48
Thanks!

The file viewer misses a lot of files, afaics, all filename are ascii only.

**Comment by wagnerand** [comment] 2016-11-25 15:05
I can't reproduce with on localhost, dev, stage or prod with the exact same file.

@EnTeQuAk is looking at the log files currently to see whether something went wrong during extraction...

**Comment by EnTeQuAk** [comment] 2016-11-25 16:22
I couldn't find anything obvious for now and will have a more in-depth look on Monday. I don't seem to be able to reproduce this locally too.

**Comment by EnTeQuAk** [comment] 2016-11-28 08:37
hmm @wagnerand @erosman I cannot reproduce this on prod anymore so it could just be a temporary glitch.

I tried a few things over the weekend but it worked fine for me all the time.

This is happens again: Try and wait 2 hours, refresh the page and see if this "fixes" it. If it does, please report that! Then the number of potential problems to look for is relatively small.

Any further improvements to the extraction process would require a large-scale refactoring which we don't really have time for at the moment.

**Comment by wagnerand** [comment] 2016-11-28 12:44
@EnTeQuAk the problem is that this issue can appear at any time and we have no way of knowing when we encounter it. You usually don't notice something is missing if you don't know it's supposed to be there.

**Comment by EnTeQuAk** [comment] 2016-11-28 13:49
> @EnTeQuAk the problem is that this issue can appear at any time and we have no way of knowing when we encounter it. You usually don't notice something is missing if you don't know it's supposed to be there.

I completely agree with you. I could imagine that maybe the linter / validator generates a file tree that we can use to verify xpi extraction validity but that's quite a bit of work and also error prone. Generally, let's maybe talk about it in-depth on the all hands to make the reviewer tools more stable anyway.

**Comment by kewisch** [comment] 2016-12-13 14:09
@rafspiny has found another occurrence of this at https://addons.mozilla.org/en-US/firefox/files/browse/542161/

It would be great to get some priority on this, broken reviewer tools is not very great.

**Comment by EnTeQuAk** [comment] 2016-12-13 14:11
Thanks for the report! I'll look into it again, last time it simply
wasn't reproducible and worked again after some time.




On Tue, Dec 13, 2016, at 03:09 PM, Philipp Kewisch wrote:

> @rafspiny[1] has found another occurrence of this at
> https://addons.mozilla.org/en-US/firefox/files/browse/542161/
> It would be great to get some priority on this, broken reviewer tools
> is not very great.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 


Links:

  1. https://github.com/rafspiny
  2. https://github.com/mozilla/addons-server/issues/3579#issuecomment-266747350

**Comment by EnTeQuAk** [comment] 2016-12-13 14:23
Finally some errors in our logs:

```
Error ([Errno 39] Directory not empty: '/mnt/efs/addons.mozilla.org/shared_storage/tmp/file_viewer/542161') extracting /mnt/efs/addons.mozilla.org/files/686634/desktop_weather_channel-0.1.7-fx-linux.xpi :/data/olympia/src/olympia/files/helpers.py:107
[1@None] Error unzipping: [Errno 39] Directory not empty: '/mnt/efs/addons.mozilla.org/shared_storage/tmp/file_viewer/542161' :/data/olympia/src/olympia/files/tasks.py:34
```

I'll look into this but this helps a lot reproducing this.

**Comment by rafspiny** [comment] 2016-12-15 14:27
If it can help, it seems to happen for other add-ons as well.
https://addons.mozilla.org/en-US/firefox/files/browse/547391/

The data directory is not shown but is there.

**Comment by erosman** [comment] 2016-12-15 14:39
PS. Re above:
The data directory shows as **Deleted files** in 'Compare' view and doesn't show at all in 'Contents' view.
Addon is SDK.

**Comment by EnTeQuAk** [comment] 2016-12-15 16:50
thanks @rafspiny for the hint, all these links help a lot since I'm able to extract more and more logs and see how they're all related.

```
Error ([Errno 39] Directory not empty: '/mnt/efs/addons.mozilla.org/shared_storage/tmp/file_viewer/547391') extracting /mnt/efs/addons.mozilla.org/files/708135/harmful_web_contents_cleaner-1.1.0-an+fx.xpi :/data/olympia/src/olympia/files/helpers.py:107
Error ([Errno 2] No such file or directory: '/mnt/efs/addons.mozilla.org/shared_storage/tmp/file_viewer/547391/data/panel/settings_en.html') extracting /mnt/efs/addons.mozilla.org/files/708135/harmful_web_contents_cleaner-1.1.0-an+fx.xpi :/data/olympia/src/olympia/files/helpers.py:107
```

**Comment by erosman** [comment] 2016-12-27 12:57
Another example:
https://addons.mozilla.org/en-US/firefox/files/browse/560701/file/components/tracing_listener.js#top

**Comment by wagnerand** [comment] 2017-01-05 21:28
At this point, the issue is still reproducible with the aforementioned https://addons.mozilla.org/en-US/firefox/files/browse/502870/

I couldn't reproduce for the other links mentioned.

**Comment by wagnerand** [comment] 2017-01-09 14:44
And now it's no longer reproducible using https://addons.mozilla.org/en-US/firefox/files/browse/502870/ .

#heisenbug

**Comment by EnTeQuAk** [comment] 2017-01-09 16:39
The fix from https://github.com/mozilla/addons-server/issues/4218 is on stage and will be deployed tomorrow. Let's see if that makes things better.

**Comment by EnTeQuAk** [comment] 2017-01-10 12:23
Given that this will hopefully be fixed or at least eased with todays deployment I'm going to close this issue for now.

In case there are more, new and other issues related to the file-browser potentially not showing something correctly I think it's best to open up a new issue. We were already fixing two separate issues here so let's split things if possible.

**Closed by EnTeQuAk** 2017-01-10 12:23 UTC
Labels: in progress, reviewer tools
