### ISSUE TITLE
The search API is returning deleted add-ons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#4894] opened 2017-03-09 22:27 UTC
### Describe the problem and steps to reproduce it:

Here is a search:
````
$ curl 'https://addons-dev.allizom.org/api/v3/addons/search/?app=android&q=cheharatime&page=1&lang=en-US' | json_pp
{
   "previous" : null,
   "results" : [
      {
         "average_daily_users" : 0,
         "type" : "extension",
         "review_url" : "https://addons-dev.allizom.org/en-US/editors/review/493880",
         "url" : "https://addons-dev.allizom.org/en-US/firefox/addon/cheharatime/",
         "icon_url" : "https://addons-dev-cdn.allizom.org/static/img/addon-icons/default-64.png",
         "status" : "public",
         "has_eula" : false,
         "description" : null,
         "default_locale" : "de",
         "previews" : [],
         "slug" : "cheharatime",
         "is_experimental" : false,
         "homepage" : "https://outgoing.stage.mozaws.net/v1/cd968bbf3cb7b9356440ff1594fbf57c652b991a75a2ce6564bc64b456d630e9/https%3A//www.cheharatime.com/",
         "public_stats" : false,
         "name" : "CheharaTime",
         "is_disabled" : false,
         "guid" : "{7b3c9f9a-1dcc-4153-89ab-c755c82ee60e}",
         "weekly_downloads" : 0,
         "edit_url" : "https://addons-dev.allizom.org/en-US/developers/addon/cheharatime/edit",
         "support_url" : null,
         "has_privacy_policy" : false,
         "current_version" : {
            "id" : 1531232,
            "files" : [
               {
                  "url" : "https://addons-dev.allizom.org/firefox/downloads/file/251875/cheharatime-0.1-an+fx.xpi?src=",
                  "permissions" : [],
                  "created" : "2017-02-08T11:20:20Z",
                  "platform" : "all",
                  "hash" : "sha256:70e393ac9a369dd90c462b8c2b2a29ab183401b435b412219afafb7203104395",
                  "id" : 251875,
                  "size" : 9791,
                  "status" : "public"
               }
            ],
            "version" : "0.1",
            "reviewed" : "2017-02-08T11:20:49Z",
            "license" : null,
            "url" : "https://addons-dev.allizom.org/en-US/firefox/addon/cheharatime/versions/0.1",
            "compatibility" : {
               "firefox" : {
                  "max" : "*",
                  "min" : "48.0"
               },
               "android" : {
                  "max" : "*",
                  "min" : "48.0"
               }
            },
            "edit_url" : "https://addons-dev.allizom.org/en-US/developers/addon/cheharatime/versions/1531232"
         },
         "categories" : {
            "firefox" : [
               "bookmarks"
            ],
            "android" : [
               "feeds-news-blogging"
            ]
         },
         "last_updated" : "2017-02-08T11:20:49Z",
         "support_email" : null,
         "tags" : [],
         "authors" : [
            {
               "name" : "Andreas Wagner",
               "url" : "https://addons-dev.allizom.org/en-US/firefox/user/andreasw/",
               "id" : 4750720
            }
         ],
         "is_source_public" : true,
         "id" : 493880,
         "current_beta_version" : null,
         "ratings" : {
            "average" : 0,
            "count" : 0
         },
         "summary" : "Capture full-screen or specific application's screen on any HTTPs domain!"
      }
   ],
   "next" : null,
   "count" : 1,
   "page_size" : 25
}
````
Seems fine but when you search for the detail page it's a 404:
````
$ curl 'https://addons-dev.allizom.org/api/v3/addons/addon/cheharatime/?lang=en-US'
{"detail": "Not found."}
````

### What happened?

The add-on detail request is a 404

### What did you expect to happen?

Either the detail request should not be a 404 or the search result should not include the add-on.

### Anything else we should know?

This doesn't happen for all add-ons.

You can see this in the AMO mobile site by going to this link and clicking 'view mobile site' https://addons-dev.allizom.org/en-US/android/search/?q=cheharatime

**Comment by wagnerand** [comment] 2017-03-09 22:32
I deleted this add-on a while ago.

**Comment by kumar303** [comment] 2017-03-09 22:33
Aha, thanks. So it looks like the search API is returning deleted add-ons

**Comment by diox** [comment] 2017-03-09 23:10
That's weird. It looks like the search index has old information about this add-on from before it was deleted - which is why it's showing up, as far as elasticsearch is concerned the add-on is perfectly normal and public. We're supposed to index add-ons when they are deleted with the new deleted status...

**Comment by diox** [comment] 2017-03-17 17:46
I found some inconsistencies on dev using the command I wrote, but was unable to find where they were coming from. I've reindexed dev and will continue to monitor the situation, especially on stage/prod as well.

**Comment by diox** [comment] 2017-04-26 12:15
I've waited a while before running the command to find inconsistencies again. This time, I found nothing, so I believe the issues we saw before came from migrations altering statuses manually without reindexing afterwards, or something similar.

I'm closing this, but leaving the command in the repos for now, it may prove useful if such a problem reappears.

**Comment by cr** [comment] 2017-06-28 17:31
I don't think listing deleted IDs is a problem, but I am still seeing a few deleted web extensions listed as **public** in AMO search:

```
2017-06-28 10:00:30 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/660754/add_to_bookmark_ninja-1.0.0.2-an+fx-mac.xpi?src=`, status code 404
2017-06-28 10:00:30 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/660755/add_to_bookmark_ninja-1.0.0.2-an+fx-windows.xpi?src=`, status code 404
2017-06-28 10:00:34 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/630273/president_toilet-1.0-an+fx.xpi?src=`, status code 404
2017-06-28 10:00:39 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/647403/toster_tools-3.36.18-an+fx-linux.xpi?src=`, status code 404
2017-06-28 10:00:39 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/647404/toster_tools-3.36.18-an+fx-mac.xpi?src=`, status code 404
2017-06-28 10:00:39 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/647405/toster_tools-3.36.18-an+fx-windows.xpi?src=`, status code 404
2017-06-28 10:00:40 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/596548/iosis_news_extension-1.0.1-fx.xpi?src=`, status code 404
2017-06-28 10:00:41 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/561753/heres_your_you-1.2-an+fx-linux.xpi?src=`, status code 404
2017-06-28 10:00:41 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/561754/heres_your_you-1.2-an+fx-mac.xpi?src=`, status code 404
2017-06-28 10:00:41 ERROR MainThread webextaware.amo Unable to download `https://addons.mozilla.org/firefox/downloads/file/561755/heres_your_you-1.2-an+fx-windows.xpi?src=`, status code 404
```

Both the add-on IDs and their individual files have status `public`. The corresponding AMO IDs for the list above are:
* 821036
* 805890
* 796783
* 787923
* 764524

**Comment by diox** [comment] 2017-06-28 17:36
Can you share the search queries (or even the link to the search results directly) that return those add-ons ?

**Comment by cr** [comment] 2017-06-28 17:48
This resulted from crawling all the web extensions among the pages of the search ```https://addons.mozilla.org/api/v3/addons/search/?sort=created&type=extension```.

**Comment by cr** [comment] 2017-06-28 18:05
I have used my tool over the past couple of weeks and seen that list growing over time.

**Comment by diox** [comment] 2017-06-29 18:50
Reasonably sure the problem is that we indexed the add-on before the transaction had been completed (i.e. it happened too fast). The proper solution to this problem is post-request-task, but we could add a hack to delay the indexing by a few seconds to make sure this does not happen.

**Comment by cr** [comment] 2017-06-29 20:05
I am blissed with ignorance of the internal workings here, but fixing race conditions by inserting constant artificial delays to me seems like a brittle work-around that is destined to break again in the future.

**Comment by diox** [comment] 2017-06-29 20:36
Definitely agree ; that's why I mentioned both the proper solution (post-request-task) and a hack (delay). The proper solution is what we want to do, it's just that it's not trivial to make it work. The hack would only help alleviate the problem short-term.

**Comment by diox** [comment] 2017-07-25 09:51
Closing in favor of https://github.com/mozilla/addons-server/issues/5999

**Closed by diox** 2017-07-25 09:51 UTC
Labels: component: api, priority: p2, triaged
