### ISSUE TITLE
Every time that I try to download a plugin that I upload I get redirected to an error page that says file not found.

### ISSUE THREAD

**Issue by SodaGremlin** [mozilla/addons-server#3884] opened 2016-10-27 20:44 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by andymckay** [comment] 2016-10-27 20:46
Dupe of #3883

**Closed by andymckay** 2016-10-27 20:46 UTC
