### ISSUE TITLE
"Transfer ownership" for themes is not working

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1924] opened 2016-03-16 12:20 UTC
Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/firefox/
2. Access Tools-> Submit a New Theme
3. Fill all mandatory fields and click the  "Submit theme" button
4. Go to edit theme page and "Transfer Ownership"
5. Enter a valid e-mail that has an account associated 
6. Click "Save Changes"

**Expected results:**
"Save Changes" button becomes enabled after entering a valid email. The ownership can be transferred.

**Actual results:**
"Save Changes" button stays disabled. User cannot transfer ownership. No error message displayed.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue: 
![2016-03-16_1416](https://cloud.githubusercontent.com/assets/15685960/13812015/14b34b10-eb82-11e5-8de1-53741265580f.png)

**Comment by eviljeff** [comment] 2016-03-16 14:25
dupe of #989

**Closed by eviljeff** 2016-03-16 14:25 UTC
Labels: duplicate
