### ISSUE TITLE
Contributions don't work in production

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3056] opened 2016-07-07 12:31 UTC
Steps to reproduce:
1. Load details page for an add-on with contributions i.e. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular
2. Click on "Contribute" button
3. Type a value to contribute
4. Click on "Make Contribution" button

Expected results:
User is redirected to PayPal account.

Actual results:
After a while a "The Connection has timeout....Try Again" page is displayed as a popup window. User cannot continue.

Notes/Issues:
Verified on FF47 (Win 7 X64, Mac OS X 10.8). Issue is only reproducing on production.
Screencast/screenshot for this issue: 
![contrib](https://cloud.githubusercontent.com/assets/15685960/16653145/c826a056-4457-11e6-9b36-478a79f841d6.gif)
![contrib](https://cloud.githubusercontent.com/assets/15685960/16653156/d1af1c16-4457-11e6-87a6-6ea886624930.png)

**Comment by muffinresearch** [comment] 2016-07-07 13:09
Seems like that's a timeout paypal's end. It's not clear how to find ongoing status of paypal's service at a glance without signing up for notifications.

Can you re-test and see if it's cleared?

**Comment by ValentinaPC** [comment] 2016-07-07 13:46
Nope. Still not working. :(

**Comment by krupa** [comment] 2016-07-07 19:58
This looks ok now.

**Comment by ValentinaPC** [comment] 2016-07-08 09:28
Still able to reproduce it.
Please see the screenshot: 
![contrib](https://cloud.githubusercontent.com/assets/15685960/16683256/777c7d14-4507-11e6-8ac2-38fc745b07f6.png)

**Comment by muffinresearch** [comment] 2016-07-08 09:57
@ValentinaPC is there anything related to paypal in the console?

**Comment by muffinresearch** [comment] 2016-07-08 10:02
I just tried it and it worked fine, I got through to the point of logging in and so on.

**Comment by muffinresearch** [comment] 2016-07-08 10:03
Can anyone else in the QA team reproduce it? Does it still occur with a fresh profile?

**Comment by ValentinaPC** [comment] 2016-07-08 11:34
@muffinresearch : everyone from our QA team reproduces it.
Browser Console JS error - tried with a new Firefox 47 clean profile:
![2016-07-08_1430](https://cloud.githubusercontent.com/assets/15685960/16686169/f79ac102-4518-11e6-922b-93fc89c9c3f5.png)

**Comment by tsl143** [comment] 2016-07-11 10:34
Unable to reproduce!
![screenshot from 2016-07-11 16 02 07](https://cloud.githubusercontent.com/assets/5318732/16727900/0075fe6c-4781-11e6-969c-c568de2056a8.png)

**Comment by andymckay** [comment] 2016-07-11 18:15
Its an error on Paypal's side, if you think its an ongoing concern we should raise an error with Paypal (I have no idea how to do that btw).

**Comment by andymckay-limited-access** [comment] 2016-07-12 17:40
I can't reproduce either. Suggest closing.

**Closed** 2016-07-12 17:40 UTC

**Comment by vcarciu** [comment] 2016-07-13 13:47
We are still able to reproduce this bug on new profiles on Windows
