### ISSUE TITLE
Cannot download my freshly signed addon (404)

### ISSUE THREAD

**Issue by FeanorsCurse** [mozilla/addons-server#3883] opened 2016-10-27 20:03 UTC
### Describe the problem and steps to reproduce it:
I uploaded a private addon, got it signed and got to the screen with the download button. This leads to a 404.

### What happened?
Clicking button "Download myaddon.xpi" isn't working 

### What did you expect to happen?
Download my signed addon

**Comment by FeanorsCurse** [comment] 2016-10-27 20:22
I tried three different versions now, also got an email with "Your add-on, $name 1.2, has passed our automatic tests and is now signed and ready for you to download at ..." and also the links in all emails aren't working either.

**Comment by spoji** [comment] 2016-10-27 20:34
Can reproduce, 
I'm getting the same issues, all XPI returns 404
for example : https://addons.mozilla.org/en-US/firefox/mnt/efs/addons.mozilla.org/files/671241/ad_aware_security_toolbar-4.2.0.1-fx-linux.xpi

**Comment by andymckay** [comment] 2016-10-27 21:40
Could you retry please, the server has been updated.

**Comment by Mathieuu** [comment] 2016-10-27 21:43
It looks like it worked for xpi we updated before the outage. But for the one we signed during the outage, we cannot retrieve it. (We signed it through the API with the node jpm toolset). We are going to try to bump the version and sign a new version, I will keep you posted.

**Comment by andymckay** [comment] 2016-10-27 21:49
You can get to any old add-on you've already signed in the Developer Hub > "Manage My Submissions" > [Your addon] > "Manage Status & Versions" > [Version] and click on the file link (ends in xpi.

If you have a URL like https://addons.mozilla.org/en-US/firefox/mnt/efs/addons.mozilla.org/files/671241/ad_aware_security_toolbar-4.2.0.1-fx-linux.xpi, that should be accessible (to the developer only at) https://addons.mozilla.org/firefox/downloads/files/671241/ad_aware_security_toolbar-4.2.0.1-fx-linux.xpi

**Comment by andymckay** [comment] 2016-10-27 21:54
Apparently the hacking of URL, my second paragraph in the above comment won't work, so please ignore that.

**Comment by Mathieuu** [comment] 2016-10-27 21:56
We managed to sign and download a new version of the extension. But as I mentioned earlier, it seems that addons that have been uploaded and signed during the outage are not available for download. I would suspect they were never uploaded to the storage server ?

**Comment by FeanorsCurse** [comment] 2016-10-28 06:55
Thanks, it's working now :)

**Comment by muffinresearch** [comment] 2016-10-28 09:05
Closing based on https://github.com/mozilla/addons-server/issues/3883#issuecomment-256849941

If anyone else is still having trouble please feel free to file a new issue with the details.

**Closed by muffinresearch** 2016-10-28 09:05 UTC
