### ISSUE TITLE
WebExtension can be downgraded to legacy add-on if update version is lower than previous

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4635] opened 2017-02-08 11:45 UTC
### Describe the problem and steps to reproduce it:

A legacy add-on can be uploaded as an update to a webextension add-on if the legacy update has a lower version number.

STR:
1. Upload a new webextension add-on (with version number 1.0, for example).
2. Approve it.
3. Upload an update using a legacy technology but with a **lower** version number (0.1, for example).

### What happened?

Validation was successful.

### What did you expect to happen?

Validation should have resulted in an error.

### Anything else we should know?

(The reason why the downgrade check fails is that it doesn't take into account when updates have a lower version number, see devhub/utils.py#230)

I don't know how Firefox (or AMO update service) behaves in this case. I assume that ultimately the version check in Firefox will prevent the 'update' since 0.1 is a lower version number than 1.0. But will AMO update service provide 0.1 as an update to 1.0 when Firefox checks for add-on updates? Will it provide 1.0 as an update to 0.1 even though it's an earlier version?

I think the real issue here is that AMO allows updates with a lower version number to be submitted as an update even though Firefox does not support that. We already deny re-using the same version number, I am not sure why we allow lower version numbers. At least for listed add-ons, it might be a good idea to deny this. Reviewers already reject such submissions (if they notice).

Note that this should not apply to unlisted, since developers decide on their own which versions they distribute to what subset of their users and what the migration paths for updates are.

**Comment by ValentinaPC** [comment] 2017-02-08 11:53
Check this: https://github.com/mozilla/addons-server/issues/3670

**Comment by ValentinaPC** [comment] 2017-03-13 09:52
**Note:** 
This is reproducible vice-versa, too: if a webext is added as an update for a legacy add-on, the "WebExtension upgrade" message will not be displayed if the version of the webext is lower than the add-on version.

**Comment by muffinresearch** [comment] 2018-02-02 20:43
Maybe duplicate of https://github.com/mozilla/addons-server/issues/7161

**Comment by EnTeQuAk** [comment] 2018-12-03 12:53
Unless I'm missing an important point here I'm going to close this with the same reason as https://github.com/mozilla/addons-server/issues/3670

> Given that we simply don't accept legacy add-ons anymore I'm going to close this.

**Closed by EnTeQuAk** 2018-12-03 12:53 UTC
Labels: component: devhub, priority: p4, triaged

**Comment by AlexandraMoga** [comment] 2018-12-04 08:07
With the `disallow-legacy-submissions` waffle switch on, legacy submissions are no longer possible, hence the issue will not reproduce anymore:

![image](https://user-images.githubusercontent.com/31961530/49427579-50648280-f7ac-11e8-96a8-ccee07837f70.png)
