### ISSUE TITLE
The unreviewed version of an Add-on cannot be accessed if the first version is disabled

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1811] opened 2016-03-01 18:07 UTC
Steps to reproduce :
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Submit a listed add-on and approve it (i.e. Zen1235)
3. Add a second version for the submitted add-on (without approving it)
4. Disable the first version
5. Access the second version from add-on Edit Listing page (click version number)

Expected results :
Version details page is loaded.

Actual results:
A 404 page is loaded.

Notes/Issues:
The version can be accessed from Manage Status & Versions page. 
Verified on AMO- dev FF44 (Win 7).
Reproducible in AMO-prod.

**Comment by ValentinaPC** [comment] 2016-03-02 10:34
There is another thing that confuses me: why is the add-on status "Preliminary/Fully Reviewed"?
Please see the screencast: http://screencast.com/t/IMkeS4scMX

**Comment by jvillalobos** [comment] 2016-03-02 15:00
After Step 2, the first version and the add-on have a status of Full Review. Note there is a status for the version (the files, really) and a global status for the add-on.

The problem is that after step 4, the first version changes status to disabled, but the global status of the add-on remains the same, leaving the add-on in an inconsistent state. What should happen is that the global status of the add-on should be adjusted depending on the state of the other versions. In this case, it should be changed to pending review.

**Comment by eviljeff** [comment] 2016-03-11 19:15
I can't replicate this on -dev or locally (now)
e.g. https://addons-dev.allizom.org/en-US/developers/addon/sdsds/versions
I've made some changes to addon and version code recently so maybe it was inadvertently fixed.  Reopen otherwise.

**Comment by ValentinaPC** [comment] 2016-03-14 08:38
I guess the changes affected somehow this issue. Check out how things are happening now:
**1. Add-on FULLY REVIEWED**
-> the approved add-on has its status "Fully Reviewed", after step #4 add-on status is turning into "Awaiting PRELIMINARY review". I was expected to see "awaiting FULL review", or this is intended?
(please see the screencast: http://screencast.com/t/4lDhwMDK23)

**2. Add-on PRELIMINARY REVIEWED**
-> the approved add-on has its status "Preliminary Reviewed", after step #4 add-on status is remaining the same ("PRELIMINARY reviewed")
(please see the screencast: http://screencast.com/t/bxlpFBRD)

Verified on AMO-dev FF45(Win 7),

**Comment by jvillalobos** [comment] 2016-03-14 20:03
Those are both buggy behavior, yes.

**Comment by eviljeff** [comment] 2016-03-14 20:40
I had a look into these today as they both seemed like simple fixes.  Unfortunately there is lot of functionality and tests that make assumptions based on the existing behaviour and it turned out (after a number of hours) to be a totally non simple fix.
1. the change for this is only breaking a few tests so should be do-able.  
2. breaks a lot more so I think is best to leave until the status changes (full+prelim->reviewed) happen later in the year.

**Comment by eviljeff** [comment] 2016-09-30 15:49
I can't replicate this any more so looks like it's been fixed by removing preliminary review (or one of the many other fixes since March)

**Closed by eviljeff** 2016-09-30 15:49 UTC
Labels: triaged
