### ISSUE TITLE
icloud extension

### ISSUE THREAD

**Issue by JPLP** [mozilla/addons-server#3129] opened 2016-07-20 10:53 UTC
where can i find the extension to sync my favorites websites between icloud and firefox?

**Comment by muffinresearch** [comment] 2016-07-20 11:02
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by muffinresearch** 2016-07-20 11:02 UTC

**Comment by JPLP** [comment] 2016-07-20 11:06
thanks
