### ISSUE TITLE
Saved ratings are cached too aggressively

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#5006] opened 2017-03-22 18:48 UTC
### Describe the problem and steps to reproduce it:

See https://github.com/mozilla/addons-frontend/issues/2019 for STR

### What happened?

* A new rating/review is posted
* When the page is refreshed, it makes an API request for a saved review by user ID and add-on ID
* The first time you request this, you get 0 results
* The second time, you see the result.

### What did you expect to happen?

It should always return the saved rating since it was just posted/patched.

### Anything else we should know?

When I add `.no_cache()` [right here](https://github.com/mozilla/addons-server/blob/2a210807f6d3bb97924543f7667f563a80832800/src/olympia/reviews/views.py#L413) the problem goes away

**Comment by diox** [comment] 2017-03-27 10:10
It turns out that it's caused by the fact that cache-machine caches `count()` calls for 5 minutes without ever invalidating them. Pagination uses a `count()` call and therefore returns an empty page, not even bothering to evaluate the results queryset (which would work, as its cache is properly invalidated).

I'll have to think of something. Maybe bypass pagination if you're specifying both `user` and `addon` as there can only be one or zero results, or maybe find a way to invalidate specific count caches in this situation.

**Comment by diox** [comment] 2017-03-27 11:42
I have a patch to avoid the `count()` when both `user` and `addon` parameters are set, just fetching one or zero results, but I realized that's wrong: you can have more than one result, as it's possible for a user to leave multiple reviews for the same add-on as long as it's on different versions.

@kumar303 : do you have the version id available in addons-frontend when you make that request ? If so, I could add `version` filtering on the reviews API, and apply my workaround described above only when `addon`, `user` and `version` parameters are set (all 3). As a bonus you could let a user leave a review on a newer version of an add-on, something I suspect you don't do currently.

**Comment by kumar303** [comment] 2017-03-27 14:46
Ha, yeah, I suspected `count()` caching. It has bitten us so many times.

In this particular situation I'm pretty sure we will always have a version ID. However, it would be easy to forget about needing this for future API calls. 

Is there no way to stop doing a `count()` and always rely on the cached query? Or is that buried in the guts of Django?

**Comment by diox** [comment] 2017-03-27 14:58
I'd have to use a different paginator that:
1) does not expose the `count()`
2) does not use the `count()` at all internally (for number of pages calculations and optimization when you request the last page). 

Essentially we'd need to switch to infinite-style pagination (no number of pages / total number of results displayed, just prev/next links). It's doable, but is that what we want ?

**Comment by kumar303** [comment] 2017-03-27 15:05
> It's doable, but is that what we want ?

I'm not really sure if we need page numbers or not. I haven't seen them in any mocks. A custom paginator seems fine as long as it's well tested. Obviously, it's not ideal. 

Maybe this is something we could just punt until we are able to ditch cache machine? The STR to reproduce this bug (https://github.com/mozilla/addons-frontend/issues/2019) is a pretty obscure edge case. I don't think many users will be doing this.

**Comment by kumar303** [comment] 2017-03-27 15:12
@pwalm hi! We discovered a limitation that we can workaround by never showing page 1, 2, 3... links in any paginated screen (search, review list, etc). Do you think we can live without that? I don't recall seeing specific page links in any of the mocks. We would still be able to show a previous / next button.

**Comment by pwalm** [comment] 2017-03-30 01:41
I'd rather we didn't remove the "1 2 4... 18" numbers from pagination. It's a good/quick way to show users how many results they have to sift through. I've designed this for AMO:
<img width="931" alt="screen shot 2017-03-30 at 9 40 38 am" src="https://cloud.githubusercontent.com/assets/6797635/24483779/f45a9e38-152c-11e7-8622-fc26fad83722.png">

If this is a blocker, are there any alternative options that we could use?

**Comment by diox** [comment] 2017-03-30 09:23
We have another workaround that doesn't change pagination. @kumar303 you weren't a fan of my proposal in https://github.com/mozilla/addons-server/issues/5006#issuecomment-289429125 but it's still on the table :)

**Comment by kumar303** [comment] 2017-03-30 15:12
I'm fine with https://github.com/mozilla/addons-server/issues/5006#issuecomment-289429125 (requiring a version ID) but I was just worried we'd forget about it in the future. Maybe the API can raise a 400 error if version is omitted somehow?

**Comment by diox** [comment] 2017-03-30 15:17
Well from an API standpoint you could very well want to omit it, fetching all reviews from a user for a particular add-on (which is something that doesn't work yet, admittedly - atm we only get the latest version anytime an `addon` is passed - but I was planning to fix that and only fetch the latest version if `addon` is passed without other parameters)

**Comment by kumar303** [comment] 2017-03-30 16:11
Alright, I suppose we could make the frontend code throw an error which should help us not accidentally get aggressively cached results.

**Comment by diox** [comment] 2017-04-04 10:19
Closing with qa not needed as it's just the API part ; QA will be needed in https://github.com/mozilla/addons-frontend/issues/2019 once frontend is updated to use the new API parameter.

**Closed by diox** 2017-04-04 10:19 UTC
Labels: component: api, qa: not needed, state: in progress, triaged
