### ISSUE TITLE
Changing your primary email address back to the original email from the FxA page is not reflected in AMO

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8384] opened 2018-05-30 11:10 UTC
Follow up for #7941 

STR:
1. Log in to AMO stage and open your account page (i.e. https://addons.allizom.org/en-US/firefox/users/edit/)
2. Click on Manage Firefox Accounts to open the FxA page in a new tab
3. Add a secondary email to your account
4. Set the secondary email as your primary email address
5. Go back to your AMO account page and refresh the page in order to see the modified results
6. Return to the FxA page and set your primary email back to your original email address
7. Repeat step 5

Actual result:
The primary email setting applied in FxA is not reflected in AMO user account page

Expected result:
The primary email address set up in FxA should be reflected in AMO user account page

Notes:
- the re-set primary email will be visible only after the users logs out and logs back into his account
- reproduced on AMO stage with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40716600-3573e430-6412-11e8-9680-d3e9f3451c68.png)

**Comment by eviljeff** [comment] 2018-05-30 11:14
dupe of #8382

**Closed** 2018-05-30 13:11 UTC
Labels: component: firefox accounts, priority: p3

**Comment by AlexandraMoga** [comment] 2018-05-31 07:00
Verified as fixed on AMO stage with FF60, Win10x64

![sync fxa](https://user-images.githubusercontent.com/31961530/40766769-43e43f22-64b9-11e8-8376-167b8249a098.gif)
