### ISSUE TITLE
Files are not accessible after a rejection

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#3619] opened 2016-09-27 11:01 UTC
### Describe the problem and steps to reproduce it:

When rejecting reviews, the files for the rejected version is no longer correctly accessible. From previous discussion it was suggested that the files are not properly moved to the guarded area, until it is taken care of by a fallback cron job which I believe is going to be removed in #3598.

Steps to (hopefully) reproduce:
1. Put an add-on version into review (my latest case was an update to an existing add-on)
2. Reject the add-on
3. Possibly wait a while until magic happens, might also occur right away
4. Go back to the review page to download the add-on
### What happened?
- The add-on can be downloaded before the review is rejected (step 1)
- The add-on shows the unstyled 404 error from nginx afterwards (step 4)
### What did you expect to happen?
- The add-on should be downloadable even after the review rejection
### Anything else we should know?

I have had this with the following add-ons:

September 22nd, this has fixed itself, presumably through the cron job:
https://addons.mozilla.org/en-US/editors/review/board-notes
https://addons.mozilla.org/firefox/downloads/file/507119/note_board-3.0.2-fx+an.xpi?src=editor

Today, reviewed this morning and accessed with 404 a few minutes ago:
https://addons.mozilla.org/en-US/editors/review/zimrim-search-addons
https://addons.mozilla.org/firefox/downloads/file/504213/zimrim_search_addons-1.2-fx.xpi?src=editor

**Comment by diox** [comment] 2016-09-27 12:16
See also https://github.com/mozilla/addons-server/issues/3598

**Comment by diox** [comment] 2017-03-21 16:45
Same root cause as mozilla/addons/issues/324; will be fixed when we fix https://github.com/mozilla/addons-server/issues/4649

**Closed by diox** 2017-03-21 16:45 UTC
Labels: triaged
