### ISSUE TITLE
Theme header is not displayed correctly after the submission is completed

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#1887] opened 2016-03-10 16:00 UTC
Steps to reproduce:
1. Open addons.allizom.org and submit a new theme
2. After the theme is submitted open its edit listing page (i.e: https://addons.allizom.org/en-US/developers/theme/test89911theme/edit)

Expected results:
There are no display or layout issues. The theme design is correctly displayed.

Actual results:
The theme header is white.

Notes/Issues:
The issue is reproducing intermittently. 
Verified in FF45(Win7) Issue can be reproduced in addons.allizom.org
Screencast for this issue: http://screencast.com/t/5fksdgBXCn2R

**Comment by andymckay-limited-access** [comment] 2016-06-21 16:29
@madalincm: Is this still reproducible? It looks like there is a 404 on the header image.

**Comment by madalincm** [comment] 2016-06-24 07:42
I can't no longer reproduce this issue. It was reproducing intermittently but now it seems I can't reproduce it at all.

**Comment by andymckay** [comment] 2016-06-24 16:18
Based on this happening on March, we'll chalk it up to instability on the servers at that time, closing.

**Closed by andymckay** 2016-06-24 16:18 UTC
