### ISSUE TITLE
Switch nginx config so that the new front-end is the default

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#10428] opened 2019-01-16 17:52 UTC
The current configuration is that all traffic is routed to the legacy Django site and only routes that are specifically configured in nginx are routed to the new front end.

With the user legacy pages no longer used, we would like to reverse this, so all traffic would default to the new front end, and only specifically overridden routes would go to the legacy site.

Some routes that would need to go to the legacy site are:
- /developers/
- /admin/
- /reviewers/

Are there any others that I have missed?

**Comment by diox** [comment] 2019-01-16 18:05
Plenty more :)

https://github.com/mozilla/addons-server/blob/6b06f38de6faf50e73857d70843afd8eb52c2f84/src/olympia/urls.py#L23 has a list of includes, everything included at the root needs to checked as well.

At the very least:
- /api/
- /files/
- /downloads/
- /robots.txt
- /contribute.json
- /services/
- /__version__
- /opensearch.xml

Also need to be careful about URLs that use the locale and/or app name in it.

**Comment by eviljeff** [comment] 2019-01-17 10:16
we could/should move robots.txt, contribute.json and opensearch.xml to addons-frontend. (?)

/developers, /admin and /reviewers could have locale at the front but, afaik, app name is only for frontend pages.

**Comment by diox** [comment] 2019-01-17 11:00
The legacy API does have both locale and app name. /opensearch.xml has it too, optionally (it's not in the list of urls exempted from it in addons-server). /files/ and /downloads/ are not exempted either (though /downloads/ doesn't need the locale)

**Comment by willdurand** [comment] 2019-01-18 09:14
> we could/should move robots.txt, contribute.json and opensearch.xml to addons-frontend. (?)

Quick notes:

- `robots.txt` is generated by addons-server–I don't know if we have enough knowledge to do that on the frontend
- `opensearch.xml` has been added to addons-frontend this week (part of next week's tag) and we use the URL with both the app and locale

**Comment by muffinresearch** [comment] 2019-01-18 10:11
> opensearch.xml has been added to addons-frontend this week (part of next week's tag) and we use the URL with both the app and locale

@willdurand Is the frontend serving opensearch.xml or just pointing to it?

**Comment by muffinresearch** [comment] 2019-01-18 10:14
> we could/should move robots.txt, contribute.json and opensearch.xml to addons-frontend. (?)
> 
> /developers, /admin and /reviewers could have locale at the front but, afaik, app name is only for frontend pages.

Moving anything should be out of scope for this issue, but we can definitely file issues to start thinking about it. I still hope we can continue to move in the direction that at some point addons-server with be just API.

**Comment by willdurand** [comment] 2019-01-18 10:17
> @willdurand Is the frontend serving opensearch.xml or just pointing to it?

Pointing to it.

**Comment by muffinresearch** [comment] 2019-01-18 10:22
@willdurand 👍 I updated the [comment above](https://github.com/mozilla/addons-server/issues/10428#issuecomment-455477895) to clarify.

**Comment by EnTeQuAk** [comment] 2019-01-21 08:49
For old shield study pages, we'll be able to redirect…

* https://addons.mozilla.org/en-US/firefox/shield-study-2
* https://addons.mozilla.org/en-US/firefox/shield_study_3-16

to https://support.mozilla.org/kb/shield

https://github.com/mozilla/addons-server/pull/10468/files#diff-9a87f4a997c3c97f3e8c7768e6dc00d6R1053

**Comment by diox** [comment] 2019-01-24 14:10
@eviljeff suggested to use `manage.py show_urls` to find out the routes. It's a good starting point, I used that to take a first stab at the list we want to continue serving from addons-server. Behold:
- /\_\_version__
- /about
- /addon/<addon_id>/statistics/*
- /addon/<addon_id>/versions/<version_num>/updateinfo/
- /admin/*
- /api/*
- /contribute.json
- /developers/*
- /downloads/*
- /editors/*
- /files/*
- /find-replacement/*
- /google1f3e37b7351799a5.html
- /google231a41e803e464e9.html
- /opensearch.xml
- /pages/*
- /pioneer
- /plugins
- /review_guide
- /reviewers/*
- /robots.txt
- /services/*
- /shield-study*  `# I do mean study* and not study/*`
- /statistics/*
- /user-media/*  `# Should technically be on the CDN`
- /versions/updateInfo/*  `# Redirects to the one at the beginning of the list. We need both right now.`

Note: I'm missing a few redirects and old rss pages that I don't know if we want to continue supporting.

**Comment by eviljeff** [comment] 2019-01-24 15:05
afaik
> * /about
> * /review_guide

are on addons-frontend already.

Later we can move some of the redirects to nginx (or addons-frontend).  E.g.
> * /pages/*
> * /plugins

**Comment by bqbn** [comment] 2019-01-29 05:37
What about the `/search/` endpoint? It should still go to the legacy site, right?

**Comment by eviljeff** [comment] 2019-01-29 08:09
> What about the `/search/` endpoint? It should still go to the legacy site, right?

No

**Comment by bqbn** [comment] 2019-02-05 01:44
@diox, I have a couple questions while configuring this for Nginx.

1. For the listed URLs, which ones should be matched with `<locale>/<firefox|android>/` prefix, which should be matched with just `/<locale>/` prefix, and which should be matched without prefix?
  For example, `/__version__` and `/robots.txt` are obviously matched without prefix, what about others?

2. Regarding 
   > `/versions/updateInfo/*` # Redirects to the one at the beginning of the list.

   How do you suggest we do that? Because the `versions/updateInfo/*` URL doesn't contain an `addon_id`, wherease `/addon/<addon_id>/versions/<version_num>/updateinfo/` needs one.

**Comment by diox** [comment] 2019-02-05 09:21
1. Good point. addons-server behavior is to redirect if the locale and/or app are missing and required. So for instance `/reviewers/` should be served by addons-server, it will redirect to `/en-US/reviewers/`. Similarly, `/addon/tab-counter-plus/versions/2.5/updateinfo/` will redirect to `/en-US/firefox/addon/tab-counter-plus/versions/2.5/updateinfo/`. It's crucial that this continues to work.
The following paths in the list above don't require an app: `admin`, `contribute.json`, `developers`, `editors`, `google1f3e37b7351799a5.html`, `google231a41e803e464e9.html`, `reviewers`, `robots.txt`, `statistics`, `services`, `static`, `user-media`, `__version__`.
The following paths don't require a locale: `contribute.json`, `google1f3e37b7351799a5.html`, `google231a41e803e464e9.html`, `robots.txt`, `services`, `downloads`, `static`, `user-media`, `__version__`.
In addition the following regexp completely bypasses app and locales in the URL: `'^/?api/(?:v3|v4|v4dev)/`. Annoyingly, the legacy API, i.e. `/api/1.5/*`, /does/ require an app & locale.

2. The actual pattern is `/versions/updateInfo/(P<version_id>\d+)` and we deduce the add-on id from the version id. You don't need to care about that though, since addons-server does the redirect.

**Comment by bqbn** [comment] 2019-02-06 02:32
Deployed the changes to -dev environment. I tested a few pages and the submission flow, and all seem to be working. My tests are probably not thorough. Please test and let us know if any issues.

**Comment by willdurand** [comment] 2019-02-06 10:13
> Deployed the changes to -dev environment. I tested a few pages and the submission flow, and all seem to be working. My tests are probably not thorough. Please test and let us know if any issues.

Looks like we have our first regression here: https://github.com/mozilla/addons-frontend/issues/7547. The search URL serves the legacy frontend instead of the new one.

**Comment by bqbn** [comment] 2019-02-07 01:46
#10608 and https://github.com/mozilla/addons-frontend/issues/7547 should have been fixed.

**Comment by willdurand** [comment] 2019-02-08 08:26
So I found a new issue with this URL (found in the Dev Hub): https://addons-dev.allizom.org/en-US/firefox/addon/guarani-paraguay-lang-pack/versions/66.0buildid20190207161357/

The new frontend does not support URLs like this, we only support `/addon/:slug/versions/`.

@bobsilverberg @muffinresearch do you remember any decision about that? (i.e. about not supporting a URL for a specific version of an add-on).

**Comment by AlexandraMoga** [comment] 2019-02-08 09:04
Probably another regression:

If you are logged in on a server page - i.e. `/developers/` , `/reviewers/` - and try to access a page that is served by the new frontend,  you appears logged out:

![2019-02-08_11-01-16](https://user-images.githubusercontent.com/31961530/52468351-24d98c00-2b91-11e9-8a4f-a159c62517f1.gif)

I can file this as a separate issue if it's worth it.

**Comment by eviljeff** [comment] 2019-02-08 09:09
@lexasv the nginx config shouldn't affect the login - can you file an issue?

**Comment by willdurand** [comment] 2019-02-08 09:18
> @bobsilverberg @muffinresearch do you remember any decision about that? (i.e. about not supporting a URL for a specific version of an add-on).

The django view actually implements a redirect: https://github.com/mozilla/addons-server/blob/60dd98e48fb22c7b3ea04d628dacdf9bdac7db87/src/olympia/versions/views.py#L68-L71, that's why we did not have to implement a new page in addons-frontend.

The short-term fix would be to add such a redirect rule at the nginx level but ideally, having proper support in addons-frontend would be nice.

**Comment by eviljeff** [comment] 2019-02-08 10:59
I'm going to close this issue because the change was done.  Follow-up issues should be filed as appropriate.

**Closed by eviljeff** 2019-02-08 10:59 UTC
Labels: needs: ops, priority: p3, project: legacy switch off

**Comment by bqbn** [comment] 2019-02-22 00:08
-stage env is now switched to use the new front-end as its default. Please test it and let us know if there are issues.

**Comment by muffinresearch** [comment] 2019-02-25 12:26
> > @bobsilverberg @muffinresearch do you remember any decision about that? (i.e. about not supporting a URL for a specific version of an add-on).
> 
> The django view actually implements a redirect:
> 
> [addons-server/src/olympia/versions/views.py](https://github.com/mozilla/addons-server/blob/60dd98e48fb22c7b3ea04d628dacdf9bdac7db87/src/olympia/versions/views.py#L68-L71)
> 
> Lines 68 to 71 in [60dd98e](/mozilla/addons-server/commit/60dd98e48fb22c7b3ea04d628dacdf9bdac7db87)
>  if version_num in ids: 
>      page = 1 + ids.index(version_num) / PER_PAGE 
>      to = urlparams(url, 'version-%s' % version_num, page=page) 
>      return http.HttpResponseRedirect(to) 
> 
> That's why we did not have to implement a new page in addons-frontend.
> 
> The short-term fix would be to add such a redirect rule at the nginx level but ideally, having proper support in addons-frontend would be nice.

@willdurand Is there a specific issue filed for this? I think it would be good to have one.

**Comment by willdurand** [comment] 2019-02-25 12:28
@muffinresearch I think this is this one, no? https://github.com/mozilla/addons-server/issues/10645

**Comment by muffinresearch** [comment] 2019-02-25 15:53
> @muffinresearch I think this is this one, no? #10645

Thanks @willdurand, I don't know why I didn't spot that linked above. 🙈

**Comment by AlexandraMoga** [comment] 2019-02-28 14:26
Besides the issues that were reported and verified fixed, we've checked that there are no further broken user flows on -dev or stage.

There is still a confirmation needed for https://github.com/mozilla/addons-frontend/issues/7596#issuecomment-467760930, just to make sure that this is the expected outcome.

**Comment by kumar303** [comment] 2019-03-01 17:38
This deployed to production on 2019-02-28 via https://github.com/mozilla-services/cloudops-deployment/pull/2924
