### ISSUE TITLE
Textarea for release notes is missing in zh-CN

### ISSUE THREAD

**Issue by gera2ld** [mozilla/addons-server#13224] opened 2019-11-26 12:34 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Upload an addon, continue to the details page.

### What happened?

While locale is `zh-CN`, the textarea for *Release Notes* is hidden, only that for *Notes to Reviewer* is visible.
When switched to `en-US`, both textareas are visible.

### What did you expect to happen?

In either locale should both textareas be visible.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Link: https://addons.mozilla.org/en-US/developers/addon/extension_name/versions/submit/a_number/details

Snapshots:

<img width="823" alt="Screen Shot 2019-11-26 at 20 27 01" src="https://user-images.githubusercontent.com/3139113/69633889-0bf08780-108c-11ea-9ef0-85e3414d7b2c.png">
<img width="801" alt="Screen Shot 2019-11-26 at 20 29 58" src="https://user-images.githubusercontent.com/3139113/69633891-0bf08780-108c-11ea-9677-fb88ca49c4fa.png">

**Comment by Shivansh2407** [comment] 2020-01-12 05:41
I would like to take up this issue

**Comment by Shivansh2407** [comment] 2020-01-12 06:00
@muffinresearch please let me know which part of code or file I need to work in.

**Comment by AlexandraMoga** [comment] 2020-01-13 06:59
This issue is a duplicate of #4599 It is noted there that the issue occurs when a new version is uploaded in a locale different than the one used during the submission of the first add-on version.

**Closed by AlexandraMoga** 2020-01-13 06:59 UTC
