### ISSUE TITLE
Add categories for Android Themes

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4766] opened 2017-02-24 02:08 UTC
Related to https://github.com/mozilla/addons-frontend/issues/1723#issuecomment-278793546; there aren't any Android categories for themes even though all Firefox themes (lightweight) work.

We should copy over Firefox persona theme data to Android as well so we don't have to make requests with `app=firefox` for Android.

**Comment by kumar303** [comment] 2017-10-09 15:22
@muffinresearch any ETA on addressing this? It continues to bite us in the frontend. See https://github.com/mozilla/addons-frontend/issues/3408

**Comment by muffinresearch** [comment] 2017-10-10 10:51
@eviljeff what would it take to make requests for themes (type=persona) to ignore the clientApp. Would that be a viable way to solve this issue?

**Comment by diox** [comment] 2017-10-10 11:05
The legacy frontend used to simply [ignore the application when looking for categories for lightweight themes](https://github.com/mozilla/addons-server/blob/eabba4afadababb4d5aba6181886d723e6950fd2/src/olympia/browse/views.py#L263-L264).

That's... not ideal. In the long term we should unify categories between Android and Firefox, and stop having application-specific categories, but in the meantime, if we want an addons-server fix... it would probably be to copy over the categories from Firefox. However the tricky part when doing that is that we'd also need to duplicate the relations between add-ons and categories, and make sure to keep them updated when they change...

**Comment by eviljeff** [comment] 2017-10-10 11:26
agreed on the long term.  In the mean time... how difficult is a frontend fix to do the same as legacy?

**Comment by tofumatt** [comment] 2017-10-10 11:29
Right now the front-end has a hack that sends firefox instead of android when searching for themes: https://github.com/mozilla/addons-frontend/blob/master/src/core/api/search.js#L47, so not that hard 😄

**Comment by eviljeff** [comment] 2017-10-10 11:44
https://github.com/mozilla/addons-server/issues/5989 for unifying categories across Firefox desktop and Firefox android applications.

**Comment by eviljeff** [comment] 2017-10-10 11:45
@muffinresearch which API endpoints specifically would need hacking to do this?

**Comment by muffinresearch** [comment] 2017-10-10 12:03
@eviljeff I think it's anything that involves lightweight themes.

**Comment by eviljeff** [comment] 2017-10-10 12:13
So... if it's every single API endpoint that deals with 'addon' then it's going to be adding hacks to a lot of places and other solutions should be looked at.  (If it was a single API, then perhaps less so)

**Comment by muffinresearch** [comment] 2018-02-02 20:32
I'm thinking we should wait for #5989 unless someone has a better short-term plan?

**Comment by muffinresearch** [comment] 2018-02-02 20:33
Marking as a duplicate of #5989 - feel free to re-open if there are better options.

**Closed by muffinresearch** 2018-02-02 20:33 UTC
Labels: component: api, triaged
