### ISSUE TITLE
[RTL] Close button is missing for the opened screenshots

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3525] opened 2016-09-15 15:10 UTC
Steps to reproduce:
1.Open any add-on details page
2.Open any available screenshot

Expected results:
A close (X) button is available for every screenshot

Actual results:
Close button is missing in RTL

Please see video for this bug : 

![closertl](https://cloud.githubusercontent.com/assets/1583842/18555125/53d2af8e-7b6f-11e6-9179-5ea47ca8da5b.gif)

**Comment by muffinresearch** [comment] 2016-09-15 15:24
Duplicate of #3418

**Closed by muffinresearch** 2016-09-15 15:24 UTC
Labels: maybe good first bug, style refresh
