### ISSUE TITLE
Themes link under Documentation section in Dev Hub page is a 404

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#9812] opened 2018-10-25 18:28 UTC
Steps to reproduce:
1.Go to AMO prod dev hub
2.Click on "Themes" link under Documentation section in the footer of the page (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes/Lightweight_themes)

Actual results:
The link should be functional or replaced with another link

Actual results:
The link is a 404

**Comment by eviljeff** [comment] 2018-10-25 18:42
that page is linked from other MDN pages too, e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-lwtheme so it might be a bug on their side

**Comment by AlexandraMoga** [comment] 2018-10-26 06:02
This is a duplicate of https://github.com/mozilla/addons-server/issues/9809, which I fuiled yesterday before the push.
I'm closing this bug.

**Closed by AlexandraMoga** 2018-10-26 06:02 UTC
