### ISSUE TITLE
Allowing Spam Registration is ruining the AMO experience

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#5625] opened 2017-06-13 04:34 UTC
Recently, there have been a myriad of **Anonymous user 11111** registering on AMO.

These users, spam the reviews, some with good or bad reviews, in order to promote favourable extensions and demote competing ones.

The new system of allowing blank reviews further empowers spammers and trolls at the cost of alienating developers. (ref: #4964 , #4966)

Contrary to what is understood, such reviews are displayed on the graphical display.

What purpose does it serve to allows such spams and trolling?

Front another point of view ...... 
How does a review with content of "." (single dot) differs from a blank review?
Neither provide any content, but as per AMO rule the one with "." (dot) is considered non-review content (and can be deleted) but the blank one is a Review Content.
Is that logical?

**Comment by ParticleCore** [comment] 2017-06-13 05:20
The decision and justification supporting these kinds of reviews has been terrible since day one. Trying to encourage more engagement from mobile users to review add-ons by allowing 0 registration and 0 content review is not worth the toll it is taking to the developers and the reviewers that have to, yet again, 
waste more time to go through the reported reviews just to find out it is yet another mobile review.

Another issue related to this is that mobile users are able to down-rate add-ons that were never submitted as mobile compatible, see [14792](https://discourse.mozilla-community.org/t/amo-allowing-mobile-installation-when-it-is-not-marked-as-compatible/14792).

On top of all of this, it has become an incredibly easy vector for rating manipulation since these are being hidden from everyone's public eye, not even the developers are aware of why the rating of their add-ons is decreasing.

Overall this terrible decision to allow empty and anonymous reviews on AMO brought more problems than benefits and should have never been implemented on the first place. AMO reviews are becoming a poll of empty review trash and developers have no control or knowledge over it and depend on the limited time reviewers have to *maybe* stumble up on "invisible" spam reviews **AND** decide to remove them or not, because empty reviews are being allowed, even if there are 1000 one star empty reviews destroying add-ons, which makes absolutely no sense.

**Comment by jvillalobos** [comment] 2017-06-14 15:39
> Recently, there have been a myriad of Anonymous user 11111 registering on AMO.

These are just normal users. After the move to Firefox Accounts, the username and display name became completely optional, so that name is set by default.

> These users, spam the reviews, some with good or bad reviews, in order to promote favourable extensions and demote competing ones.

What evidence do you have that they are spam? Just the fact that the rating doesn't include a review? Or the "Anonymous" username?

> How does a review with content of "." (single dot) differs from a blank review?

That's just old policy that reviews need to contain some text. If someone writes a review that is essentially blank or gibberish, it should be removed, but users now have the option to post blank reviews.

**Comment by jvillalobos** [comment] 2017-06-14 15:44
Part of the reason we allow empty ratings now is that the system was tilted too much in favor of developers, and was causing a great deal of frustration to users. Users couldn't post negative reviews for an add-on without trying to justify themselves, and the policies made it easy for developers to dismiss those reviews as bug reports and have them deleted. The new system makes it easier for users to say whether they like and add-on or not, without having to write an entire explanation for it.

Determined spammers can accomplish their goals with the old system and the new one in the same way, and the way we identify spammers doesn't change much. Feel free to flag any instances of bad ratings and reviews and we will look into them.

Closing this until there's more evidence about spamming activity. It's pretty much a dupe of #4964.

**Closed by jvillalobos** 2017-06-14 15:44 UTC

**Comment by erosman** [comment] 2017-06-14 16:43
> What evidence do you have that they are spam? 

In fact, I have mentioned a few cases to Andreas, some of which were deleted by the time he got to them. I have HTML sources and screen shots.

There are considerable number of fake users created for marketing. Their purpose is to promote and addon with good reviews and mark bad reviews as spam (a practice that should be blocked IMHO, in other words, only developer should be able to flag a review as spam etc and other users should only be able to flag for bad language).
These fake users also mark down competing addons.

>  Feel free to flag any instances of bad ratings and reviews and we will look into them.

How would you know if the review was valid, if it is blank?!

> Part of the reason we allow empty ratings now is that the system was tilted too much in favor of developers

The pendulum approach of swinging from one extreme to the other, often proves to be counterproductive.
While I agree that developers had an advantage before, disadvantaging them does not balance the scales.

A review by definition has to be constructive, which a blank one isn't.

Users often review based on irrelevant factors, for example:
- They don't know how to work with the addon, 
- They have not read the manual
- They expect features that are not part of the addon

I recently had a 1 star review for a Web_extension that said, "_it doesn't work on addons.mozilla.org_" even-though the description clearly stated that Firefox blocks some function on AMO and even-though a notification comes up when using addon on AMO saying that, the user still said.. _it is no good because it doesn't wok on AMO._

That is a fact that has absolutely nothing to do with the addon and a built-in restriction made by Mozilla.
Allowing an addon to be marked done for a browser restriction is utterly ridiculous.

A similar reaction can cause a blank review and the developer has no recourse to reply to the reviewer and clarify it for them.

I envisage in a not too distant future that this feature ruins the AMO experience and by then there would probably be far too many unhappy developers.

It is worth revisiting the policy before it gets to that point.

**Comment by jvillalobos** [comment] 2017-06-14 19:42
> How legitimate a user can be when they don't even bother or care to set a nickname for themselves?!!!

That doesn't make sense. If we don't require it, why set it? Especially if your only goal is to post one rating.

> There are considerable number of fake users created for marketing.

Sure, but that has always been the case, and writing a review along with the rating isn't a significant hurdle. Thanks for reporting, that helps.

> How would you know if the review was valid, if it is blank?!

The IP address of the poster, for instance, which is the main way in which we catch people stuffing their ratings. It isn't hard to fake a valid review to manipulate an add-on's rating, so allowing blank ones doesn't make that big of a difference.

> A review by definition has to be constructive, which a blank one isn't.

I disagree. A _written_ review needs to be constructive. Ratings (with a written review or not) help prospective users get an idea of how liked or disliked an add-on is.

> Users often review based on irrelevant factors

They are irrelevant to the developer, because maybe there are technical limitations that prevent the add-on from doing something, or the developer just doesn't want to implement a particular feature. That doesn't change the fact that user expectations may be different, and not meeting those expectations can be a problem for those users and others. Not understanding how an add-on works can be the developer's fault as much as the user's. It's not so clear-cut, and the current practice of deleting those reviews does a disservice to users.

I can't think of a solution that works for everyone, but I think this is a more balanced approach.

> It is worth revisiting the policy before it gets to that point.

We will monitor how these new ratings and reviews work and will make sure things don't get out of hand. If it turns out they're causing more problems than they solve, we will go back to require written reviews.
