### ISSUE TITLE
Clear pending rejections button does not reset due dates

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20224] opened 2023-01-23 20:41 UTC
**Note: The due date started showing later, but I'm still documenting this ticket and will update as more details are known**

### Describe the problem and steps to reproduce it:
The due date field in the manual review queue (other pending reviews) shows `--` instead of the due date for the addon that was recently content-approved but had the auto approval flag disabled. This only happened in a specific case when
- an addon that was previously scheduled for content rejection was approved (after clearing of any pending rejections)

### What happened?
- the addon showed up in manual review with an empty due date at the top of the list

### What did you expect to happen?
- the addon shows up with a due date (at the bottom in the default sorting order)

### Anything else we should know?
- As mentioned at the top, when I opened the review queue later in the day, the addon in question had a due date which looked right (right time had elapsed since when it must've first moved into this queue). I had two addons that went from `content review` -> `manual review` queue, and only one of them lacked the due date.

I'll update here if I see it happen again.

**Comment by diox** [comment] 2023-01-23 20:47
Could you clarify the state the add-on was in when it was missing the due date ? Was it content-approved or scheduled for a content rejection ? What what the status of the version and add-on ?

**Comment by abhn** [comment] 2023-01-23 21:02
Yes - 
- The add-on's second to latest version was scheduled for content rejection and the latest version was awaiting review
- I cleared pending rejections and (content) approved the latest version
- The approval message showed up on the second to latest version, while the latest version still stayed in "awaiting review" state
- At this point, the addon showed up in the manual review queue with the latest version awaiting review and missing due date.

Hope that gives you more context

**Comment by diox** [comment] 2023-01-24 11:34
My best guess is a race condition somewhere after step 7: maybe when we check the state of the version/addon to determine if the version should have a due date after the flags have been modified, we were either making a query against the database without having committed the transaction that changes the flags, or making a query against the replica which didn't have the updated data yet. Or both.

**Comment by ioanarusiczki** [comment] 2023-02-13 11:44
@diox 

I tried on AMO dev with this addon 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/624828#review-actions

In my case here, version 8 is the first rejected with delay and version 9 is the latest:

At step 7. I approved content, version 8.0 has been content-approved,  and from the same review-content page I had "Clear pending rejection" button -> clicked it, after I checked the [versions admin page ](https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1698200/change/) -> the date and time were cleared 

Checking queues: The addon was no longer in Pending Rejection or Manual Review queue. Checking the due date in admin -> none of the versions have a due date set. 

For step 9 -> I clicked on "Enable Listed Auto-Approval Until Next Manual Approval" -> Version 9 is auto-approved

**Comment by diox** [comment] 2023-02-13 12:09
There might be something else, but I think the issue is with the `Clear pending rejections` button. It changes `VersionReviewerFlags` with a queryset, so we don't receive a `post_save` signal, so we never update the due dates.

**Comment by diox** [comment] 2023-02-13 13:23
STR:
- As a developer, submit an add-on
- As a reviewer, set a pending rejection on the first version, and disable auto-approval manually (avoid setting `needs_human_review` flag, so avoid scanner actions)
- As a developer, submit another version in the same channel that you disabled auto-approval for (at this point the new version should not be auto-approved, and should be shown in the manual review queue with a due date)
- As a reviewer, submit a pending rejection on that version (at this point, the new version should no longer be shown in the manual review queue, it should have lost its due date)
- Then, as a reviewer, hit the `Clear pending rejections` button, but don't approve the new version.

Expected results:
- The newest version should lose its pending rejection, and regain a due date. It should be shown in the manual review queue

Actual results:
- The newest version does lose its pending rejection as expected but doesn't regain a due date, and isn't shown in the manual review queue.

**Closed** 2023-02-13 14:57 UTC
Labels: priority:p2, component:reviewer_tools

**Comment by ioanarusiczki** [comment] 2023-02-14 14:52
@diox 
I tested on AMO dev the [first](https://github.com/mozilla/addons-server/issues/20224#issuecomment-1401742573) scenario and this time it works as expected -> after the content reviewer approves content and clears the pending rejection the addon is back in the Manual Queue and has a due date set (the 4 days interval). 

I'm going to check the other [scenario](https://github.com/mozilla/addons-server/issues/20224#issuecomment-1427937966) too.

**Comment by ioanarusiczki** [comment] 2023-02-15 11:45
@diox I verified the second scenario for both channels -> works as expected now meaning that the versions regain a due date.

The listed addon: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/624952
The unlisted addon: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/624953

**Comment by KevinMind** [comment] 2024-05-04 19:12
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-217
