### ISSUE TITLE
New rating submitted instead of the previous one being updated

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-server#6955] opened 2017-11-18 21:54 UTC
Two one star ratings were submitted by the same user, then the second rating was updated to a five star rating. The activity feed shows 3 events for the user and they seem to have been registered immediately one after the other. The first one star rating is visible on the rating breakdown.

It seems the user has double-clicked the first star to try out the widget, then updated the rating to 5 stars. Double clicking likely causes duplicate ratings to be submitted, and subsequent updates only update one of the ratings.

First rating (appears as written in the activity feed):
https://addons.mozilla.org/en-US/firefox/addon/search_by_image/reviews/971207/

Second rating (appears as written and updated in the activity feed):
https://addons.mozilla.org/en-US/firefox/addon/search_by_image/reviews/971206/

**Comment by muffinresearch** [comment] 2017-11-20 09:50
@dessant thanks for the report, this appears to be a duplicate of https://github.com/mozilla/addons-server/issues/6952

**Closed by muffinresearch** 2017-11-20 09:50 UTC

**Comment by dessant** [comment] 2017-11-21 17:49
Could you please delete the duplicate review? It shows an error if you load the page, but it's still listed in the rating breakdown, and lowers the overall rating.
https://addons.mozilla.org/en-US/firefox/addon/search_by_image/reviews/971207/
