### ISSUE TITLE
Align correctly the language [] on the admin addon page  

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13599] opened 2020-02-28 12:52 UTC
https://github.com/mozilla/addons-server/issues/13587 introduced the language for localized add-ons 

STR:
1. Go to https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/616630/change/ or https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/503019/change/ and observe the beginning of the second, third or fourth row in the Name, Summary, Description, Homepage or Support (where available). 

Expected result:
The language [] is displayed on the same row with the text fields.

Actual result:
The language [] is displayed on the line above. 

Notes:
Reproducible on admin tools dev - FF73(Win10). 

![languages1](https://user-images.githubusercontent.com/33448286/75550033-af5d8980-5a39-11ea-9b0e-289e91012cbb.png)

**Comment by AlexandraMoga** [comment] 2020-02-28 15:35
Duplicate of #8506 (which also mentioned the missing locale names next to the text fields)

**Closed by AlexandraMoga** 2020-02-28 15:35 UTC
Labels: component: admin tools, type: bug
