### ISSUE TITLE
Collection name and description are not localized in edit page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5383] opened 2017-05-11 07:13 UTC
Steps to reproduce:
1. Go to Collections homepage 
2. Change the language i.e https://addons.mozilla.org/fr/firefox/collections/
3. Create a collection
4. Change the language to `en` or other (not the one used to submit the collection)
5. Click "Edit collection"

Expected results:
Collection has name and description as submitted.

Actual results:
Collection has no name or description.

Notes/Issues:
- while changing the language in collection details page, the name or description is not erased.

Video for this issue:
![collname](https://cloud.githubusercontent.com/assets/15685960/25936931/666531d4-3632-11e7-8f24-f2436f48b4c6.gif)

**Comment by EnTeQuAk** [comment] 2017-06-14 05:56
this is not nice but technically not a bug since that collection does not have an english translation, so we don't show one. I also assume we'll figure out a nicer interface or don't enable collections / translations of collections in the future anyway so I'm going to close this.

**Closed by EnTeQuAk** 2017-06-14 05:56 UTC
Labels: component: i18n, platform: desktop, type: bug
