### ISSUE TITLE
[SUGGESTION] - convert readme.rst to readme.md

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [mozilla/addons-server#6827] opened 2017-11-03 17:09 UTC
## Greetings

**i would like to suggest to:**
- *convert readme.rst to readme.md*

---

**main motivation behind such:**
- *improving easiness to edit markdown*

---

kind regards

<img src="https://avatars2.githubusercontent.com/u/131524?s=200&v=4" width="50"></img> <img src="https://avatars1.githubusercontent.com/u/7303598?s=460&v=4" width="50"></img>

**Comment by tiagomoraismorgado88** [comment] 2017-11-03 17:10
i had already posted something like this in august. my apologies

**Comment by muffinresearch** [comment] 2017-11-03 17:31
Closing as a duplicate of https://github.com/mozilla/addons-server/issues/6231

**Closed** 2017-11-03 17:31 UTC
