### ISSUE TITLE
Let's hook up the add-on detail API

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2262] opened 2016-04-07 18:41 UTC
I would expect a search for: 

https://internalsearch.dev.mozaws.net/search/?q=jid0-uRZpLu7VtYEF3IY7A2TpX21yj3A@jetpack

To return:

https://addons-dev.allizom.org/en-US/developers/addon/sort-tabs-by-url/

Because that's its guid. Instead I get:

![screenshot 2016-04-07 11 40 31](https://cloud.githubusercontent.com/assets/74699/14362705/98c6f8c2-fcb5-11e5-9703-3cf6a452eaa9.png)

Is search by a guid supported? It's a super important feature.

**Comment by diox** [comment] 2016-04-07 18:47
If you know the `guid`, you are supposed to use the detail API, not the search. That's on the client side to implement.

**Comment by andymckay** [comment] 2016-04-07 18:51
Ah ok.

**Comment by diox** [comment] 2016-08-18 15:55
Dupe of https://github.com/mozilla/addons-frontend/issues/808 which was fixed recently.

**Closed by diox** 2016-08-18 15:55 UTC
Labels: API, triaged
