### ISSUE TITLE
"Continue to download" button for experimental add-ons has the wrong color

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3514] opened 2016-09-14 14:21 UTC
Steps to reproduce:
1. Load an experimental add-on with a roadblock contribution option i.e. https://addons-dev.allizom.org/en-US/firefox/addon/foxyproxy-standard/?src=search
2. Observe the "Continue to download" button

Expected results:
The button is blue with white label.

Actual results:
The button is yellow with black label. (as the experimental install button is)

Notes/Issues:
Verified on FF48.0.2(Win 7). Issue is reproducing all around add-ons servers.
Screenshot: 
![contribute-prod](https://cloud.githubusercontent.com/assets/15685960/18515876/833ef8ca-7a9f-11e6-9969-bd7da06786b5.png)

**Comment by ValentinaPC** [comment] 2016-09-15 11:29
May be a regression from #3084 , not sure.

**Comment by ValentinaPC** [comment] 2017-01-04 11:29
The "Continue to Download" button has also a different color inside of a collection - white background with blue label.
Example: https://addons.mozilla.org/en-US/firefox/collections/mozilla/webdeveloper/ - FoxyProxy Standard add-on

**Comment by EnTeQuAk** [comment] 2017-01-09 17:59
I'm adding this to `triaged` since it's a more visible issue potentially for many end-users. It's an edge-case though since everything works as it should be imho.

Could be a good first bug also.

**Comment by wagnerand** [comment] 2017-01-10 18:16
The mentor for this bug is: @EnTeQuAk

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by lavish205** [comment] 2017-02-17 17:21
I would like to work on this.

**Comment by wagnerand** [comment] 2017-02-21 18:26
@lavish205 Go for it!

**Comment by wagnerand** [comment] 2017-03-28 16:50
@lavish205 are you still working on this?

**Comment by lavish205** [comment] 2017-03-29 19:21
yes

**Comment by lavish205** [comment] 2017-03-29 19:21
yes @wagnerand, I'm unable to reproduce it. Can you help me in re-producing this bug.

**Comment by ValentinaPC** [comment] 2017-03-30 08:03
@lavish205 : just click on the add-on link from the first comment and you will be able to reproduce this.
The button should be blue for both "normal" and experimental add-ons.
The confusion is made because of the fact that "Add to Firefox" button for an experimental add-on is yellow.
Hope I helped!

**Comment by lavish205** [comment] 2017-03-30 08:06
@ValentinaPC can you provide me an example, how it should actually look like?

**Comment by ValentinaPC** [comment] 2017-03-30 08:08
Yes, sure -> https://addons-dev.allizom.org/en-US/firefox/addon/leechblock/?src=hp-dl-featured

**Comment by lavish205** [comment] 2017-04-01 09:27
@wagnerand We need to remove class `caution` class from `<a>` from `src/olympia/addons/templates/addons/includes/install_button.html`. but value of class seems to be variable.
Can you help me in locating file from which we are passing value of the class in this template?

**Comment by EnTeQuAk** [comment] 2017-04-03 10:25
@lavish205 thanks for looking into this!

The `caution` class comes from https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/buttons.py#L201-L210 and there's a few tests referring to it in src/olympia/addons/tests/test_buttons.py (lines 238, 248, 260). Let me know if you need more information about this.

**Comment by caitmuenster** [comment] 2017-04-18 17:10
Hey @lavish205 -- how are you doing with this bug?

**Comment by lavish205** [comment] 2017-04-23 08:30
@caitmuenster this is merged.

**Comment by lavish205** [comment] 2017-04-23 08:40
we can close this issue. @ValentinaPC

**Comment by diox** [comment] 2017-04-23 11:28
QA: when verifying this, in addition to checking whether the roadblock "continue to download" button for experimental add-ons is blue, please check whether the regular install button for experimental add-ons with no contribution roadblock set is still displayed using the yellow/black label.

**Comment by diox** [comment] 2017-04-23 11:29
Closing, but I think it may have broke something (see my previous comment). We'll see.

**Comment by ValentinaPC** [comment] 2017-04-24 08:06
Unfortunately, **experimental** add-ons have the same label as the **normal** ones: green/white.
Please see screenshot and video:
![add-ondetails](https://cloud.githubusercontent.com/assets/15685960/25327411/baed470e-28dc-11e7-87e6-8345b6ec4f82.png)
![contribution-exp](https://cloud.githubusercontent.com/assets/15685960/25327739/f56ea516-28dd-11e7-9eaa-c5902376a224.gif)

**Comment by diox** [comment] 2017-04-24 14:26
Once this is reverted:

I think the patch should be to remove the `'caution'` class in the `prepare()` method in the `InstallButton` class, when `self.show_contrib is True` (where it's already removing the download class) and not touch the other classes at all. Test-wise, a new test should be made specifically with an add-on with `addon.annoying = amo.CONTRIB_ROADBLOCK`, `addon.takes_contributions = True` and `addon.is_experimental = True`.

**Comment by wagnerand** [comment] 2017-05-02 17:18
Hey @lavish205 are you still working on this? @diox gave some great guidance in the comment above.

**Comment by lavish205** [comment] 2017-05-02 17:38
yeah I'll push a fix soon.

**Comment by wagnerand** [comment] 2017-05-30 17:33
There hasn't been much activity in some time, so we're opening up that bug for everyone.

**Comment by diox** [comment] 2017-08-01 09:26
The "roadblock" functionality will be removed in #6072 so I don't think it's worth looking into this any further.

**Closed by diox** 2017-08-01 09:26 UTC
Labels: component: legacy frontend, contrib: good first bug, contrib: mentor assigned, triaged
