### ISSUE TITLE
Uploading new Theme version: Older versions are gone ("0 versions").

### ISSUE THREAD

**Issue by AtTheGates** [mozilla/addons-server#4513] opened 2017-01-29 07:17 UTC
Hello,

first sorry for the title. I'm not sure, if it fits correctly. So feel free to change it. :-)

I already wrote with the two AMO editors **Sylvain Giroux** and **Philipp Kewisch**, who advise me to file a bug.

I had problems to upload the new version **6.0** for **FF 51** of my theme [Tangerinefox](https://addons.mozilla.org/firefox/addon/tangerinefox/).

After uploading the new version I was forced to choose a new license. I don't know why. This doesn't happened, when I uploaded the new version **6.0** for **FF 51** of my other similar theme [Tangofox](https://addons.mozilla.org/firefox/addon/tangofox/), which is already reviewed and approved by **Sylvain Giroux**. And never happened in the years before.

So after the license thing, I deleted the version **6.0** of **Tangerinefox** again.

The problem now is, that all my older versions aren't listed under the [Versions page](https://addons.mozilla.org/firefox/addon/tangerinefox/versions/). It shows "0 versions" (see screenshot):

![screen1](https://cloud.githubusercontent.com/assets/9346225/22402482/c088668e-e5f8-11e6-9ca2-70083b1f8a11.png)

But I can see them listed under my developer page "Manage Status & Versions" (screenshot):

![screen2](https://cloud.githubusercontent.com/assets/9346225/22402487/ea4c7d20-e5f8-11e6-94a4-8b19fdf99a1f.png)

Another problem is, that I can't upload the version **6.0** again, although I deleted it before. After the uploading process I get the message "Version 6.0 already exists, or was uploaded before." (screenshot).

![screen3](https://cloud.githubusercontent.com/assets/9346225/22402493/693f542c-e5f9-11e6-8007-3fa17fa1ccf6.png)

If you need further informations or screenshots, please let me know.

Thank you very much in advance.

Regards,
Chris (Haven667)

**Comment by diox** [comment] 2017-01-30 11:11
Hi,

You're describing 3 different issues:
- The license being mandatory is because we made some changes in the upload process. I believe it's not a bug, you should have a license set, and although it didn't care before, it does now. cc @eviljeff to confirm that it's intended even for complete themes.

- The fact that the versions don't show up in https://addons.mozilla.org/en-US/firefox/addon/tangerinefox/versions/ is the main issue. I'm not sure what's going on yet, investigating.

- The fact that you were unable to re-upload a deleted version is normal, that has always been the case, the version delete text warns you about this. You just need to pick a higher version number.

**Comment by ValentinaPC** [comment] 2017-01-30 12:15
@diox : I was able to reproduce the "middle point" from your comment, following the steps from #3256 .
Here is an example of a test Complete Theme: https://addons-dev.allizom.org/en-US/developers/addon/classic-compact-test-ct/versions .
If you access the version history page you will see 0 versions.
Hope I helped.

**Comment by diox** [comment] 2017-01-30 12:22
@ValentinaPC : can you find the minimal STR needed to end up in this state ? The combination of an addon awaiting review with versions set to approved shouldn't happen and that's what's causing the issue, need to understand what's going on here.

**Comment by eviljeff** [comment] 2017-01-30 12:45
> The license being mandatory is because we made some changes in the upload process. I believe it's not a bug, you should have a license set, and although it didn't care before, it does now. cc @eviljeff to confirm that it's intended even for complete themes.

It would have been required on the first upload of the add-on but an old bug resulted in no license if that first version was deleted.  So now we make you set it if it's missing.

**Comment by ValentinaPC** [comment] 2017-01-30 13:07
In my case, the thing that messes up everything is the **"Disable add-on"/"re-enable add-on"** option.

My minimal STR:
1. Find an add-on with many approved versions and disable all versions
2. Re-enable the disabled versions
3. Click "Request Review" for the last one

Example: https://addons-dev.allizom.org/en-US/developers/addon/no-versions/versions
with version history: https://addons-dev.allizom.org/en-US/firefox/addon/no-versions/versions/

**Comment by AtTheGates** [comment] 2017-01-31 05:11
Thank you very much for your answers and help.

@diox:
> The license being mandatory is because we made some changes in the upload process. I believe it's not a bug, you should have a license set, and although it didn't care before, it does now

Ok, I see. I wonder why I hadn't to choose a new license for my other theme **Tangofox**, when uploading the new version **6.0**.? On both themes the same license was set. Just a question. :-)

> The fact that the versions don't show up in https://addons.mozilla.org/en-US/firefox/addon/tangerinefox/versions/ is the main issue. I'm not sure what's going on yet, investigating.

Thank you for investigating. :-)

> The fact that you were unable to re-upload a deleted version is normal, that has always been the case, the version delete text warns you about this. You just need to pick a higher version number.

Alrighty. I uploaded the version as **6.0.1** now.

**Comment by diox** [comment] 2017-01-31 09:59
> Ok, I see. I wonder why I hadn't to choose a new license for my other theme Tangofox, when uploading the new version 6.0.? On both themes the same license was set. Just a question. :-)

I suspect either it had a license already and your other theme didn't by accident, or there is some bug that caused us not to find the license there because of how versions were deleted. I'm not sure, but the main issue that caused your add-on status to be wrong will be fixed in production next Thursday.

I've manually fix your addon status back to "Approved" in the meantime, so https://addons.mozilla.org/en-US/firefox/addon/tangerinefox/versions/ works again.

**Closed** 2017-01-31 09:59 UTC
Labels: pull request ready

**Comment by AtTheGates** [comment] 2017-02-01 13:20
@diox: Thank you very much for your work and the explanations.
