### ISSUE TITLE
The shelf API responds with a 400 Bad Request when a recommended and a query shelf are enabled 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15689] opened 2020-10-09 14:20 UTC
Followup for: 
https://github.com/mozilla/addons-server/issues/15284

STR:
1. Enable the following shelves:
[See more recommended extensions ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/34/change/) ?promoted=recommended&sort=random&type=extension
or
[See more recommended themes](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/37/change/) ?promoted=recommended&sort=random&type=statictheme

with the following shelf:
[Just a query](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/39/change/) with criteria: ?platform=windows&q=roboform

2. make an API request to https://addons-dev.allizom.org/api/v4/shelves/

Expected result:
the content of the 2 active shelves should be displayed.

Actual result:
The API responds with "The \"sort\" parameter \"random\" can only be specified when the \"featured\" or \"promoted\" parameter is also present, and the \"q\" parameter absent."

**Comment by bobsilverberg** [comment] 2020-10-09 14:40
At first glance this sounds like we're adding the params from different shelves together, but I could be wrong about that.

**Comment by eviljeff** [comment] 2020-10-09 18:17
could also be a [en|de]coding problem with the url query parameters.

**Comment by eviljeff** [comment] 2020-10-09 18:20
I'm suspicious about https://github.com/mozilla/addons-server/issues/15688 being the same problem with query params being somehow mangled along the way

**Comment by eviljeff** [comment] 2020-10-12 18:01
I played around with the admin on -dev.  The error only happens when _one_ of the shelves is enabled, but not both.  So, I'm pretty sure the problem is happening because we're re-using `self.context.get('request', None)` and then modifying it to add new query parameters - so the second time `get_addons` for the shelf shelf is called it's keeping the query from the first shelf and then adding to it.  (i.e. double query).

Ideally we'd just copy the request; make the change to the copy; and then pass that.  But HttpRequest is a little tricky and not particularly easy to copy.  
The alternative is taking a copy of the original `request.GET`; making the change to `request.GET`; calling `AddonSearchView(request=request).data` and then resetting the original `QueryDict` before returning from `get_addons`.

**Comment by xlisachan** [comment] 2020-10-26 03:30
Please assign this issue to me when you have a moment, @eviljeff - thanks!

**Closed** 2020-10-26 10:56 UTC
Labels: component: admin tools, component: api, priority: p3

**Comment by ioanarusiczki** [comment] 2020-10-26 13:36
@xlisachan https://addons-dev.allizom.org/api/v4/shelves/ responds with a 200 Accepted status for the scenario above. Also, the content of the shelves are displayed.
