### ISSUE TITLE
"JavaScript syntax error" when submitting a web-extension in AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2174] opened 2016-04-04 13:53 UTC
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/
2. Try to submit the attached web-extension

Expected results:
The web-extension is submitted.

Actual results:
The web-extension fails validations with "JavaScript syntax error" message. 

Notes/Issues:
The web-extension can be submitted on stage.
Screenshots for this issues:
![1](https://cloud.githubusercontent.com/assets/15685960/14250064/7637a7fc-fa85-11e5-8658-d95c3a4dfea6.png)
![2016-04-04_1650](https://cloud.githubusercontent.com/assets/15685960/14250069/7b17815c-fa85-11e5-95b3-1407aa27ee1c.png)

Attaching the web-extension: 
[AVG-Web-TuneUp_v4.2.5.169.zip](https://github.com/mozilla/addons-server/files/202537/AVG-Web-TuneUp_v4.2.5.169.zip)

**Comment by EnTeQuAk** [comment] 2016-04-04 14:58
The `dat.js` appears to be some weird binary code. The old validator generates only a warning here, I'm not really sure what's the best behavior here.

cc'ing @wagnerand @jvillalobos @tofumatt

**Comment by wagnerand** [comment] 2016-04-04 16:58
I guess you could argue either way. If we want to be more lenient, we could change this to a warning, but the add-on will likely be rejected by a reviewer anyway because of that warning.

**Comment by EnTeQuAk** [comment] 2016-04-05 13:36
Let's stay with a warning then if it's going to be rejected either way?

**Comment by wagnerand** [comment] 2016-04-05 15:32
The question is, why not automatically reject it in the first place, if it's going to be rejected by a human later anyway.

**Comment by EnTeQuAk** [comment] 2016-04-06 16:38
uhm, I totally meant error, not warning. Let's stay with a warning then if it's going to be rejected either way.

So, I'm closing this as "expected behavior"

**Closed by EnTeQuAk** 2016-04-06 16:38 UTC
Labels: addons-linter

**Comment by ValentinaPC** [comment] 2016-05-17 10:07
@EnTeQuAk @wagnerand  : I've recently received another JS error when submitting a web-extension in AMO-stage using FF46(Win 7).
Errors: 
![2016-05-17_1303_001](https://cloud.githubusercontent.com/assets/15685960/15318683/dafe2a28-1c2f-11e6-9f87-d16979543f55.png)
![2016-05-17_1303](https://cloud.githubusercontent.com/assets/15685960/15318687/e0f83568-1c2f-11e6-9705-b0110b56bd80.png)

Attaching used web-extension. 
[Office-Editing-for-Docs,-Sheets-&-Slides_v114.1721.1729.zip](https://github.com/mozilla/addons-server/files/267886/Office-Editing-for-Docs.-Sheets-.-Slides_v114.1721.1729.zip)

Let me know if I should track this separately.

**Comment by wagnerand** [comment] 2016-05-17 10:43
It looks a bit weird that the error is reported four times in the first screenshot.

**Comment by EnTeQuAk** [comment] 2016-05-17 10:56
It should only be reported one time once https://github.com/mozilla/addons-linter/pull/672 lands

**Comment by EnTeQuAk** [comment] 2016-05-17 13:19
Actually that's not true, opening a ticket for -linter to merge syntax errors too.

**Comment by andymckay** [comment] 2016-05-17 13:52
I think we should go for the plan outlined here: https://github.com/mozilla/addons-linter/issues/682#issuecomment-219723748
