### ISSUE TITLE
Amazon Wish List Button

### ISSUE THREAD

**Issue by AnimeRocker16** [mozilla/addons-server#3218] opened 2016-08-03 17:43 UTC
I used to use this button every day, but since I upgraded to windows 10 and reformatted my computer, the install isn't popping up. Was it removed? What happened?

**Comment by jvillalobos** [comment] 2016-08-03 20:06
Dupe of #2991 

The add-on has been removed by the author. I think the [Amazon Assistant](https://addons.mozilla.org/addon/amazon-browser-bar/) is the new add-on that should be used instead.

You would have to contact the add-on author for more information.

**Closed by jvillalobos** 2016-08-03 20:06 UTC
