### ISSUE TITLE
Detect if user is a hidden owner / developer of an add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9573] opened 2018-10-02 17:16 UTC
Consider this devhub setup:
* Create an add-on
* Add user1 as an unlisted owner
* Add user2 as an unlisted developer

When user1 or user2 are signed in to addons-frontend, we need a way to tell if they have permission to see a *Reply* button next to each review in the listing.

Is this currently possible? I can't think of a way.

**Comment by diox** [comment] 2018-10-02 18:01
Duplicate of https://github.com/mozilla/addons-server/issues/6863 - this isn't possible yet.

**Closed by diox** 2018-10-02 18:01 UTC
Labels: component: api

**Comment by kumar303** [comment] 2018-10-02 19:12
Hah. Oh, right, that bug I filed.
