### ISSUE TITLE
Error at "Review History" click after changing "Notes for Reviewers" for a version

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4521] opened 2017-01-30 11:56 UTC
Steps to reproduce:
1. Go to manage version page for any submitted add-on i.e.  https://addons-dev.allizom.org/en-US/developers/addon/add-on-wx/versions/1530325
2. Add or change "Notes for Reviewers"
3. Go to "Manage Status & Versions" page and click "Review History" link for that version

Expected results:
There are no display or layout issues. The "Review History" link work as expected.

Actual results:
An error is displayed while "Review History" link is clicked for a version with changed reviewer notes.

Notes/Issues:
- issue is reproducing for listed (awaiting or approved) add-on, unlisted add-on, mixed versions add-on, etc.
- there are no issues if "Notes for Reviewers" are added during submission.
Verified on FF51(Win 7). Issue is reproducing all around AMO-servers.
Video for this issue: 
![long-issue](https://cloud.githubusercontent.com/assets/15685960/22422080/41a69fba-e6f3-11e6-84d7-e60625358893.gif)

**Comment by kewisch** [comment] 2017-01-30 14:27
Not sure if this is the same issue, but it also happens for disabled versions similarly, e.g. for version 2.0.0 on https://addons.mozilla.org/en-US/developers/addon/query-bench/versions

**Comment by ValentinaPC** [comment] 2017-02-03 08:52
This is happening in -prod.

**Comment by eviljeff** [comment] 2017-02-03 14:35
> Not sure if this is the same issue, but it also happens for disabled versions similarly, e.g. for version 2.0.0 on https://addons.mozilla.org/en-US/developers/addon/query-bench/versions

@kewisch it's another version where the developer added/changed approval notes (that the version is disabled isn't connected)

**Comment by ValentinaPC** [comment] 2017-02-08 10:17
Verified thins on AMO-dev FF51(Win 7):
There are still some HTML tags displayed in the `Review history` section while "Notes for Reviewers" are changed. I don't think this is intended.
Add-on review page looks as expected.
Please see the screenshot:
![notes_for_reviewer](https://cloud.githubusercontent.com/assets/15685960/22732788/31231950-edf8-11e6-8d4f-09a8fbfab799.png)
Reopening.

**Comment by eviljeff** [comment] 2017-02-08 11:41
It's as intended to trivially fix the error.  Though a more elegant solution would be better.

**Comment by eviljeff** [comment] 2017-02-16 16:04
Fixed in a better way.

**Closed by eviljeff** 2017-02-16 16:04 UTC
Labels: component: devhub, project: version channel

**Comment by vcarciu** [comment] 2017-02-16 17:27
@eviljeff . This is how it should look now? If yes, I will mark it as verified for listed (awaiting or approved) add-on, unlisted add-on, mixed versions add-on, etc.
![approvalnotes](https://cloud.githubusercontent.com/assets/1583842/23032412/f65def9e-f47c-11e6-99ac-c220bb468521.png)

**Comment by eviljeff** [comment] 2017-02-16 17:29
yep.  the review history will just show the header with no text context below when there isn't any comment.

**Comment by vcarciu** [comment] 2017-02-16 17:35
Thanks!
