### ISSUE TITLE
Addon could not be verified for use in Firefox after full Reviewe

### ISSUE THREAD

**Issue by AnticDroid** [mozilla/addons-server#2438] opened 2016-04-20 07:00 UTC
Addon url: 
https://addons.mozilla.org/en-US/firefox/addon/cloverplay/

After "CloverPlay 1.3 Fully Reviewed" i still get the warning during installation: 
	"CloverPlay could not be verified for use in Firefox. Proceed with caution. More informatoin(https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct)"

**Comment by wagnerand** [comment] 2016-04-20 10:28
This is worrying.

Firefox says
`Download of https://addons.mozilla.org/firefox/downloads/latest/695826/platform:3/addon-695826-latest.xpi?src=dp-btn-primary failed: signature verification failed`

But to me it looks like it has been correctly signed.

@jasonthomas any ideas?

**Comment by jvillalobos** [comment] 2016-04-20 14:38
This is related to #2158. AMO has its ID set to `CloverPlay`, but the files being submitted have a different ID. They are signed, but end up being invalid because of the ID mismatch.

**Comment by AnticDroid** [comment] 2016-04-20 15:15
So, do I need to make changes in addon code?

**Comment by andymckay** [comment] 2016-04-20 16:25
You have a manifest.json (for WebExtensions) and a package.json in your add-on. The parsing of the package.json is a mistake in AMO and something we are removing. If you remove your package.json and bump the version, you should be able to get a new add-on reviewed and signed and quickly.

Bug #2450 is tracking the removal of package.json.

**Comment by jvillalobos** [comment] 2016-04-20 17:31
Not only that, but the ID needs to be changed for the listing so it matches what is being submitted. I tried changing it just now, but I don't know if the change stuck.

**Comment by AnticDroid** [comment] 2016-04-21 06:51
What kind of ID do you mean, from manifest.json file? Ie I have to change it like this ?
  "applications": {
    "gecko": {
      "id": "CloverPlay"
    }
  },

**Comment by jvillalobos** [comment] 2016-04-21 14:55
Yes, if you submit a new version using that ID in your manifest, the signature should work.

**Comment by AnticDroid** [comment] 2016-04-22 07:43
After ID changing to "CloverPlay" addon become invalid - http://storage2.static.itmages.com/i/16/0422/h_1461310681_7557050_c8740cd80a.png

I tried it locally and on Add-on Developer Hub - https://addons.mozilla.org/en-US/developers/addon/validate. On hub addon pass validation but on install i have same error. 
It happens after changes in ID

**Comment by jvillalobos** [comment] 2016-04-22 16:50
Yeah, I can confirm Firefox won't accept the ID. I suggest that you delete that listing and start over using the correct ID.

**Comment by EnTeQuAk** [comment] 2016-05-09 12:51
We removed the parsing related code from AMO which will land on -dev shortly, should land on -stage on Tue and go live on Thu. I'll close this as fixed but please feel free to re-open if there's something still broken.

**Closed by EnTeQuAk** 2016-05-09 12:51 UTC
Labels: triaged
