### ISSUE TITLE
[RTL] Theme is not previewed at hover

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3531] opened 2016-09-16 08:12 UTC
Prerequisites :
_User must be logged in._

Steps to reproduce:
1. Log in to AMO-dev https://addons-dev.allizom.org/
2. Change the language to a RTL one
3. Go to any theme details page i.e. https://addons-dev.allizom.org/ar/firefox/addon/sauter-germany/
4. Hover over theme

Expected results:
Theme is previewed. 

Actual results:
Nothing happens.

Notes/Issues:
If we hover over the "+Add to Firefox" installation button, theme is previewed.
Verified on AMO-dev FF48.0.2(Win 7)

**Comment by muffinresearch** [comment] 2016-09-16 08:41
Duplicate of #3528

**Closed by muffinresearch** 2016-09-16 08:41 UTC
Labels: maybe good first bug

**Comment by ValentinaPC** [comment] 2016-09-21 08:46
Since the #3528 this is no longer reproducing.
Postfix video: 
![themepreview](https://cloud.githubusercontent.com/assets/15685960/18704053/11942dba-7ff1-11e6-8615-c54edd0e6f96.gif)
