### ISSUE TITLE
Update FAQ once prelim review is not an option anymore

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3262] opened 2016-08-11 22:34 UTC
https://addons.mozilla.org/en-US/faq still mentions preliminary reviews. We should update that page since that option will soon be a thing of the past.

**Comment by jvillalobos** [comment] 2016-08-11 23:18
Part of #3083.

**Comment by madalincm** [comment] 2016-09-13 06:24
Verified as fixed in FF48(Win7) in addons-dev.allizom.org
Posrfix screencast: 
![prelimreviewfaq](https://cloud.githubusercontent.com/assets/15685441/18463578/d3785a82-7993-11e6-8bbc-5e857bbfae31.png)

**Comment by madalincm** [comment] 2016-09-13 07:05
I had a second look in the commit and I saw that the desired text is "Experimental add-ons have been marked by their developers as not suitable for a wide audience.  They have been checked by our editors to make sure they" and the title should be "What does it mean if an add-on is "experimental"  I will remove the verified fixed label.

**Comment by eviljeff** [comment] 2016-09-13 11:00
@madalincm this issue isn't closed - the pull request isn't merged.

**Comment by eviljeff** [comment] 2016-09-13 11:43
_now_ it's closed

**Closed** 2016-09-13 11:43 UTC
Labels: pull request ready

**Comment by madalincm** [comment] 2016-09-13 12:19
Verified as fixed in FF48(Win7)
Postfix screencast: 
![prelimremovefaq](https://cloud.githubusercontent.com/assets/15685441/18473385/5e95a8f0-79c5-11e6-8b39-d1339af0b2f0.png)

Sorry for the comment above, I haven't noticed that the issue is not closed yet. Sorry for the spam.
