### ISSUE TITLE
iCloud Bookmarks Extension--where is it?

### ISSUE THREAD

**Issue by mathisbrogers** [mozilla/addons-server#3157] opened 2016-07-24 05:44 UTC
I am using Apple's iCloud on my PC and when I clicked Sync Firefox Bookmarks, I get prompted to "download the extension to keep Firefox bookmarks up to date with Safri bookmarks on your iPhone, iPad, and Mac."

However, when I click Download, Firefox says it can't find one and to post the issue here. 

The link it takes me to is: https://addons.mozilla.org/en-US/firefox/addon/icloud-bookmarks/

I'd hate to have to switch to either IE or Chrome just to be able to get my bookmarks on my devices.

Thanks,
Mathis...

**Comment by muffinresearch** [comment] 2016-07-25 10:32
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by muffinresearch** 2016-07-25 10:32 UTC
