### ISSUE TITLE
Warning about display name and username displayed even if the fields are completed

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#5368] opened 2017-05-10 11:09 UTC
### Steps to reproduce:
1. Register a new account on AMO
2. Confirm the account and go to my account page
3. Complete the username and display name fields
5. Go to the Details field and enter a link in the text box
6. Click the Update Account button

### Expected results:
A warning message that the no links are allowed in the details field is displayed. The warning message about the username and display name is not displayed

### Actual results:
The "Please set your display name or username to complete the registration process." warning message is displayed even if those fields are set

### Notes/Issues
Verified in FF53(Win7) Issue can be reproduced in amo-dev, stage and prod
Screencast for this issue:
![myaccountpagewarning](https://cloud.githubusercontent.com/assets/15685441/25895457/9ff969e2-3588-11e7-8ced-198e647259e4.gif)

**Comment by SVSanta** [comment] 2017-05-18 11:21
Another way to reproduce this is to add an invalid link in the "Homepage" field.

**Comment by muffinresearch** [comment] 2018-02-02 19:36
Superceded by https://github.com/mozilla/addons-frontend/issues/2781 - I'm going to wontfix this because the new UI is due this quarter.

**Closed by muffinresearch** 2018-02-02 19:36 UTC
Labels: platform: desktop, triaged, type: bug
