### ISSUE TITLE
Results for a blank search look squeezed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2123] opened 2016-04-01 08:17 UTC
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Make an empty search

Expected results:
Search results page has no display or layout issues.

Actual results:
The results from the page look squeezed.

Notes/Issues:
Verified on AMO-dev FF45(Win 7).
Screencast for this issue: http://screencast.com/t/dRCtLAsZoO

**Comment by muffinresearch** [comment] 2016-04-01 10:06
This is caused by https://github.com/mozilla/addons-server/issues/2113 the multiple buttons in the results cause the left side to have less space. Closing as a dupe.

**Closed by muffinresearch** 2016-04-01 10:06 UTC
Labels: duplicate, style refresh
