### ISSUE TITLE
Signing of of large google chrome extensions are failing via API

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons-server#2802] opened 2016-05-30 12:42 UTC
This a google chrome extension here - https://chrome.google.com/webstore/detail/mediacore-capture/enddmcjcfojolegmdogekfpfbobmkioo

I download it, and convert it to CRX. I then convert it to XPI. Both files are attached here.

Now when I try to upload this with the signing API, it takes about 10minutes and then I get 401 for "Signature expired". I do a api request to check for this addon with `https://addons.mozilla.org/api/v3/addons/enddmcjcfojolegmdogekfpfbobmkioo%40chrome-store-foxified-3826191121/versions/1.2.0.1/`. 

Is there anyway for the API to upload large files? This one is 20mb.

Aside - This specific addon uses NaCl so I expect it to fail the validation, but the signing API should tell us.

Attachments - 
Please rename the `CRX.zip` to `.CRX` and the `XPI.zip` to `.xpi`. Github wasn't allowing me to upload them.
[MediaCore Capture - Version 1.2.0.1 - UNSIGNED - XPI.zip](https://github.com/mozilla/addons-server/files/289549/MediaCore.Capture.-.Version.1.2.0.1.-.UNSIGNED.-.XPI.zip)

[MediaCore Capture - Version 1.2.0.1 CRX.zip](https://github.com/mozilla/addons-server/files/289548/MediaCore.Capture.-.Version.1.2.0.1.CRX.zip)

**Comment by Noitidart** [comment] 2016-05-30 12:53
I just tested it on the website and it works fine, no version mismatch, it takes awhile but it works. It is 20mb - https://addons.mozilla.org/en-US/developers/addon/mediacore-capture/versions/1871721

**Comment by andymckay** [comment] 2016-05-30 17:39
In what way does it fail? What API are you using? Are you using the HTTPS API or something else? 

20mb isn't a large file in this validates in ~10 seconds for me.

**Comment by Noitidart** [comment] 2016-05-30 20:46
Thanks Andy. I'm using the JWT API. with `https://addons.mozilla.org`: https://github.com/Noitidart/Chrome-Store-Foxified/blob/5f04b7baef3f7ab5a7e985acd15db45a77abccf5/resources/scripts/MainWorker.js#L218-L713

**Comment by andymckay** [comment] 2016-05-30 20:57
So can you describe how it fails? What API responses do you get?

**Comment by Noitidart** [comment] 2016-05-30 20:59
Thanks Andy for fast replies. I'm getting a 401 status code (`Signature
expired`) error on submit. The `PUT` request to upload the file.

Here is the exact call:

```
            var presigned_zip_file = new File([presigned_zip_blob],
'dummyname.xpi');
            var data = new FormData();
            data.append('Content-Type', 'multipart/form-data');
            data.append('upload', presigned_zip_file);
            console.error('doing submit');

            xhrAsync(AMODOMAIN + '/api/v3/addons/' +
encodeURIComponent(xpiid) + '/versions/' + xpiversion + '/', { // only on
first time upload, the xpiversion can be anything
                method: 'PUT',
                data,
                responseType: 'json',
                headers: {
                    Authorization: 'JWT ' + jwtSignOlympia(amo_user.key,
amo_user.secret, getCorrectedSystemTime())
                },
            }, verifyUploaded);
```

**Comment by andymckay** [comment] 2016-05-30 21:05
That's triggered when the JWT you've created has expired.

https://github.com/mozilla/addons-server/blob/040cfd791052cc07efe1791e021f52c7d2c6ff80/src/olympia/api/authentication.py#L75

I didn't follow your code, but are you re-creating the JWT each time before you make an API call, or re-using it? If you do a request that takes a few seconds such as uploading and then trying to make a call using the same token, it could give you this error.

**Comment by Noitidart** [comment] 2016-05-30 22:01
Oh man you're faster then me in replies even though 100x busier, excuse my delay in reply.

Yep I'm creating a new JWT each time, I successfully am uploading smaller files like Pong 2 - https://chrome.google.com/webstore/detail/pong-2/capmpnebnckdpjbjdcgnokjafpdbmadn

Attached are the crx, unsigned xpi, and then signed xpi.


[Pong 2 - Version 4.31 - UNSIGNED.xpi.zip](https://github.com/mozilla/addons-server/files/290106/Pong.2.-.Version.4.31.-.UNSIGNED.xpi.zip)
[Pong 2 - Version 4.31.crx.zip](https://github.com/mozilla/addons-server/files/290107/Pong.2.-.Version.4.31.crx.zip)
[Pong 2 - Version 4.31 - Foxified.xpi.zip](https://github.com/mozilla/addons-server/files/290108/Pong.2.-.Version.4.31.-.Foxified.xpi.zip)

**Comment by andymckay** [comment] 2016-05-30 22:08
So I'm not sure. If we could get to a simple use case that proved that addons-server had a problem, we could work with that. However I would suspect the answer lies in your code for signing, because we now know the error (the 401), I'm going to close this bug.

If there's something we can do on addons-server differently, please re-open or propose in a new bug.

**Comment by Noitidart** [comment] 2016-05-30 22:11
Ah ok got it, I'll try to create a simpler test case. I'll try to show I get 401 on upload of 20mb file, and if less then 1mb it gets status 201 or 202 and works fine.

**Comment by andymckay** [comment] 2016-05-30 22:32
Fwiw I signed a 100MB+ file using JPM on the AMO stage server with no problem. A 400MB+ file caused a HTTP 504 response, so I can say there should probably be a solution for large files at some point and we don't have a good API for that. Can't generate the 401 issue though.

**Comment by Noitidart** [comment] 2016-05-30 22:50
Thanks for testing that! I'm almost done writing the test case will get
back to you in a few moments

**Comment by Noitidart** [comment] 2016-05-30 23:39
Hey there here is the test case.

Please install the addon attached here. Its the same one available here - [GitHub :: Noitidart / AMO-Addon-Signer - AMO-Addon-Signer.xpi](https://github.com/Noitidart/AMO-Addon-Signer/tree/b8a7f2368a811f102425bf78d5b82283e4e9438b)

Steps in an image - http://i.imgur.com/ycuOQ5f.png

### Steps
(1) Install addon 
(2) go to about:debugging
(3) On "chrome://amo-addon-signer/content/MainWorker.js" click "Debug"
(4) Go to "Console" tab
(5) Excecute `signUnsignedXpi(OS.Path.join(OS.Constants.Path.desktopDir, 'mediacap - unsigned.xpi'), 'YOUR_KEY_HERE', 'YOUR_SECRET_HERE');` (this will sign mediacap - unsinged.xpi file which is on desktop, the first argument is an OS file path.

The code is here - https://github.com/Noitidart/AMO-Addon-Signer/blob/b8a7f2368a811f102425bf78d5b82283e4e9438b/MainWorker.js#L174 - the first gets the system time offset from a server, so you can ignore that code. The code for signing starts with `initiateUpload`

**Comment by Noitidart** [comment] 2016-05-30 23:44
Here is a screenshot of me using it on the mediacapture unsigned xpi attached in the OP - 
![](http://i.imgur.com/WqLRCSa.png) I get the 401

**Comment by Noitidart** [comment] 2016-06-14 05:18
Hi all I just wanted to follow up with this. I don't have permissions to re-open this topic as requested. But with the simple test case I provided above, can someone please re-open this.
Thanks

**Comment by Noitidart** [comment] 2016-06-14 15:30
Thank you Jorge! :)

**Comment by mstriemer** [comment] 2016-06-15 10:37
I have a feeling the upload takes more than a minute and then when we verify the JWT it is invalid. [PyJWT](https://github.com/jpadilla/pyjwt/blob/dac1dbab30e9ce2c760179fb2d3dd83192a0702f/jwt/api_jwt.py#L95) will use the time when we verify which I believe is after django has accepted the upload. Perhaps we should skip their check and then do our own with the time the request was received instead of when it was processed (hopefully that data exists somewhere).

**Comment by andymckay** [comment] 2016-06-17 09:00
I wasn't able to reproduce this using jpm-sign with an add-on that took more than a minute to upload.

**Comment by Noitidart** [comment] 2016-06-17 11:31
Yep for me all these uploads take over 1min.

May you please try this addon - https://chrome.google.com/webstore/detail/bliss/bhlhampdgdkffgbbegpeldgeeghdklco

It is 5.6mb compressed. If you convert it to zip, convert to xpi (manfiest.json edit) (i attached the unsigned xpi of it) then try to sign it, it will fail just like the OP with this:
```
Object { status: 401, statusText: "UNAUTHORIZED", response: { detail:"Signature has expired" } }
```

The  simple reproducible test case (code should be easy to follow, its async but the steps are laid out in order) I uploaded above verifies this behavior.

**Comment by Noitidart** [comment] 2016-06-17 11:32
Yep for me all these uploads take over 1min.

May you please try this addon - https://chrome.google.com/webstore/detail/bliss/bhlhampdgdkffgbbegpeldgeeghdklco

It is 5.6mb compressed. If you convert it to zip, convert to xpi (manfiest.json edit) (i attached the unsigned xpi of it) then try to sign it, it will fail just like the OP with this:
```
Object { status: 401, statusText: "UNAUTHORIZED", response: { detail:"Signature has expired" } }
```

The  simple reproducible test case (code should be easy to follow, its async but the steps are laid out in order) I uploaded above verifies this behavior:

![](http://i.imgur.com/NEGo7uG.png)

**Comment by Noitidart** [comment] 2016-06-17 11:34
Yep for me all these uploads take over 1min.

May you please try this addon - https://chrome.google.com/webstore/detail/bliss/bhlhampdgdkffgbbegpeldgeeghdklco

It is 5.6mb compressed. If you convert it to zip, convert to xpi (manfiest.json edit) (i attached the unsigned xpi of it - [bliss.zip](https://github.com/mozilla/addons-server/files/320345/bliss.zip) - had to rename to zip for Github to accept it) then try to sign it, it will fail just like the OP with this:
```
Object { status: 401, statusText: "UNAUTHORIZED", response: { detail:"Signature has expired" } }
```

The  simple reproducible test case (code should be easy to follow, its async but the steps are laid out in order) I uploaded above verifies this behavior:

![](http://i.imgur.com/NEGo7uG.png)

**Comment by Noitidart** [comment] 2016-06-17 11:49
I think with jpm sign you can only sign SDK addons, this is a WebExtension. I suspected it was the long time, but maybe its not the time issue, but something to do with WebExtension that is giving us this wrong error.

**Comment by Noitidart** [comment] 2016-06-17 12:00
I tried `jpm sign` with `--xpi` flag and it can't sign webextensions I think based on the error I get - http://i.imgur.com/pro0DzW.png - `no manifest found`. There is a manifest.json in there though.

**Comment by andymckay** [comment] 2016-06-17 12:32
`jpm` is for signing WebExtensions. There is a new tool for WebExtensions called `web-ext`.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext

See also mozilla-jetpack/jpm#540

**Comment by andymckay** [comment] 2016-06-17 12:35
Oops. `jpm` is for signing SDK Add-ons.

**Comment by Noitidart** [comment] 2016-06-17 12:41
Ah thanks I fixed it up. Installed `web-ext`. I did `web-ext` sign I got an error here to:

```
Sign: Error: Validation took too long to complete; last status: [null]
at Timeout._onTimeout (C:\Users\Mercurius\AppData\Roaming\npm\node_modules\v
eb-ext\node_modules\sign-addon\dist\sign-addon.js:511:l9)
at tryOnTimeout (timers.js:224:ll)
at Timer.list0nTimeout (timers.js:198:5)
```

![](http://i.imgur.com/20TxB2C.png)

**Comment by Noitidart** [comment] 2016-06-17 12:41
Oo thanks I fixed it up. Installed `web-ext`. I did `web-ext` sign I got an error here to:

```
Sign: Error: Validation took too long to complete; last status: [null]
at Timeout._onTimeout (C:\Users\Mercurius\AppData\Roaming\npm\node_modules\v
eb-ext\node_modules\sign-addon\dist\sign-addon.js:511:l9)
at tryOnTimeout (timers.js:224:ll)
at Timer.list0nTimeout (timers.js:198:5)
```

![](http://i.imgur.com/20TxB2C.png)

**Comment by andymckay** [comment] 2016-06-17 12:44
That's a different error, not a 401: Signature expired.

**Comment by ganskef** [comment] 2016-09-23 14:00
Signing my unlisted Mozilla Firefox add-on version 1.0-20160922s (s=standalone **16 KB**) is successfully processed by `jpm`. A second version 1.0-20160922 contains a Jar file including SQLite binaries (**6.5 MB**). Sadly signing this XPI with `jpm` fails with `status: 401, response: {"detail":"Signature has expired."}` after **1 minute 43 seconds**. Signing via the website works well. I argue the JSON Web Token (JWT) provided by jpm times out while uploading more than 60 seconds. 

The AMO-Editors suggests me to file an issue here to investigate. "Maybe we can bump the timeout a bit." I'm confused with the conversation in this issue. Somebody sees a solution?

**Comment by mstriemer** [comment] 2016-09-23 15:00
We've got much longer timeouts on the JWTs for the other API endpoints. Are we okay to bump the timeout up here @kumar303? Alternatively, we could try something with checking against the time we received the request as suggested [above](https://github.com/mozilla/addons-server/issues/2802#issuecomment-226150609).

**Comment by kumar303** [comment] 2016-09-23 22:19
A "Signature has expired" response has nothing to do with the time it takes to sign add-ons. We could increase the timeout but it may not help. This could be a client clock skew problem.

**Comment by mstriemer** [comment] 2016-09-24 03:47
It's not the time that it takes to sign the add-on it's the time that it takes for django to accept the upload.

I was able to reproduce this locally using a proxy that throttles the connection. Uploading without throttling works fine, throttle to take more than a minute and I get `Signature has expired.`.

Since django doesn't call our view until the file upload is in memory by the time we can check the JWT it is already expired.

Increasing the timeout seems the easiest. I don't see anything on the request object that could give us the time. There's a `request._request._start_time` property but it doesn't seem to show the time that we want.

**Comment by kumar303** [comment] 2016-09-24 20:58
> ...django doesn't call our view until the file upload is in memory

oh wow, I didn't know that! This seems terrible, I hope there is a way to fix it so that we authenticate before the upload is complete.

In the meantime, yeah, increasing the timeout will help but only until someone uploads an even bigger file, I suppose.

**Comment by ganskef** [comment] 2016-09-25 22:36
It's been fixed today?
```
...
files: 100% Downloading signed files: 100% Downloaded:
     [exec]     ./mo_cuishle-1.0-20160926-fx+an.xpi
     [exec] JPM [info] SUCCESS

BUILD SUCCESSFUL
Total time: 1 minute 36 seconds
```

**Closed** 2016-10-06 14:30 UTC
Labels: pull request ready

**Comment by kumar303** [comment] 2016-10-06 21:13
To make use of this new extended timeout, please make sure you upgrade whichever signing client you were using:
* [web-ext](https://github.com/mozilla/web-ext/releases/tag/1.5.0)
* [jpm](https://github.com/mozilla-jetpack/jpm/releases/tag/1.2.1)
* [sign-addon](https://github.com/mozilla/sign-addon/releases/tag/0.2.0)

**Comment by Noitidart** [comment] 2016-10-09 19:20
Has this patch reached production yet? Is there any change we have to make if we are using the JWT API? Because I seem to be hitting it still.

**Comment by EnTeQuAk** [comment] 2016-10-10 08:56
@Noitidart this landed last Thursday in production. The only change you'll have to make is to extend the expiration time of your generated JWT token to up to 5 minutes instead of the original 60 seconds we supported. This should fix some or most of the upload problems.

**Comment by kumar303** [comment] 2016-10-10 15:09
@Noitidart if you're rolling your own API client, be sure it is setting a longer expiration when creating the JWT, like this: https://github.com/mozilla/sign-addon/commit/31dd62db8e09381104bec84fea30317f113e772f#diff-cfc13d4468802281382c6305010f597eR429

**Comment by Noitidart** [comment] 2016-10-10 16:47
Oh thanks @kumar303 that works!
