### ISSUE TITLE
Theme preview image not showing up on listing or Dev Hub

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#13597] opened 2020-02-27 23:45 UTC
MaDonna reached out asking why of her newly submitted theme [Rainbow Rose and Butterflies](https://addons.mozilla.org/en-US/firefox/addon/rose-butterflies-by-m-donna/) didn't have a preview image on her Developer Hub Page: 

![Annotation 2020-02-27 140547](https://user-images.githubusercontent.com/23342476/75497079-f84d0980-5977-11ea-87eb-0699f4dc60b6.jpg)

Interestingly the preview image also doesn't show up on the AMO listing page: 

![Screen Shot 2020-02-27 at 3 45 03 PM](https://user-images.githubusercontent.com/23342476/75497136-2599b780-5978-11ea-865c-bf6da8c57d31.png)

But I was able to successfully install the theme.

**Comment by AlexandraMoga** [comment] 2020-02-28 09:19
Looks like the preview is available now. 
In any case, I've uploaded a test theme myself on prod and indeed the preview is not available immediately after submission.

I could not reproduce on dev or stage.

**Comment by EnTeQuAk** [comment] 2020-02-28 14:25
This is most certainly a side-effect of the currently ongoing mass git-extraction that got started on Thursday evening with the push. I'm going to close this issue as theme previews will eventually be produced but might simply be delayed.

**Closed by EnTeQuAk** 2020-02-28 14:25 UTC
Labels: component: themes
