### ISSUE TITLE
Default locale incorrectly set for new add-on

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3899] opened 2016-10-31 17:38 UTC
This came up from the same case as #3868. The developer submitted the add-on working around that issue, but somehow ended up with an incorrect default locale (Danish). Since the developer is using the Danish localization of AMO, our main suspicion at the moment is that we're setting the default locale of new add-ons based on the locale of the site when the add-on was submitted. The default locale should always start as en-US.

**Comment by EnTeQuAk** [comment] 2016-11-02 14:27
That appears to be true and has been that way since forever apparently but I might be wrong about that. So I'll change that behavior to take the language from `install.rdf` or `manifest.json` and if it's not in there set `en-US` and be done with it.

It appears to be an easy enough fix, I'll take it.

**Comment by vcarciu** [comment] 2016-11-07 16:39
I am trying to submit a webextension while AMO is on FR locale and I am not able to finish the submission because name and description are not recognized even if same webextension is perfectly working in en-US . Is this a regression from this issue?

Photo of issue :
![locales](https://cloud.githubusercontent.com/assets/1583842/20066190/64fb2d3a-a519-11e6-9fea-8f927d5bde75.png)

**Comment by diox** [comment] 2016-11-07 16:41
Probably, yes.

**Comment by EnTeQuAk** [comment] 2016-11-08 10:28
Hmm, I'll look into it to see if I acidentally broke it.

**Comment by EnTeQuAk** [comment] 2016-11-08 11:58
@vcarciu can you attach the add-on or send it to me? I tried with two extensions and didn't have a problem submitting them (locally though)

**Comment by vcarciu** [comment] 2016-11-08 12:45
I attached the webextension used for testing: 
[miercurijoi.zip](https://github.com/mozilla/addons-server/files/578155/miercurijoi.zip)

**Comment by EnTeQuAk** [comment] 2016-11-08 15:03
Hmm, interestingly enough I cannot reproduce this locally yet but it fails on -dev. Investigating...

**Comment by EnTeQuAk** [comment] 2016-11-08 16:07
This might block a release on Thursday but is easy to rollback, though I'd prefer a proper fix for it. Still investigating, I found the problem but the solution might be quirky.

**Comment by EnTeQuAk** [comment] 2016-11-08 16:45
I'm reverting the change in https://github.com/mozilla/addons-server/pull/3957 and will effectively close this issue here as "wontfix".

We discussed this on IRC and the forced `default_locale` leads to a ton of problems. On one hand almost all our translation code relies on the user-language. We are not able to toggle that down in a clean way.

Even more important, since legacy add-ons don't have any mechanism to set `default_locale` except for editing it later-on in the add-ons details I'm guessing quite a lot of people rely on it. Even more important, lots and lots of code relies on it and re-uses the user-language to save data like the add-on name so that if a user has a french user-language the addon get's saved with `default_locale` `en-US` but all assigned translations have `locale` set to `fr`.

We might be able to fix that once we don't accept legacy add-ons anymore and take add-on metadata *only* from manifest.json which makes it easier to simply force things the way we want it. Less stuff that depends on it :)

**Closed by EnTeQuAk** 2016-11-08 16:45 UTC
Labels: pull request ready
