### ISSUE TITLE
OSX: Pagination arrows are not of the same size

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2007] opened 2016-03-28 23:04 UTC
## Steps to reproduce on (OSX only):
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/reviews/?page=205
2. Notice the pagination arrows
## observed behavior:

Pagination arrows are not of the same size
## screenshot:

https://www.dropbox.com/s/we4w55p3i6xk1vk/Screenshot%202016-03-28%2016.02.17.png?dl=0

**Comment by muffinresearch** [comment] 2016-04-01 16:00
This is caused by the glyph, and not the font-size - it's the same in prod.

**Comment by eviljeff** [comment] 2016-04-14 17:37
looks like its fixed

**Comment by muffinresearch** [comment] 2016-04-14 17:42
<img width="243" alt="adblock_plus____reviews____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14537834/a0e52446-0270-11e6-8163-872afb4216c6.png">

**Comment by muffinresearch** [comment] 2016-04-14 17:43
You might be getting a different result with the webfont vs the local font.

**Comment by muffinresearch** [comment] 2016-04-14 17:45
Actually scratch that I see the same with box local fonts and the webfont loaded if I turn off the local open sans on OSX.

**Comment by muffinresearch** [comment] 2016-04-14 18:00
Here's the glyphs (note this shows it's not font specific) if you see the left arrow smaller, then you can repro the problem:

◂◂ ▸▸

**Comment by muffinresearch** [comment] 2016-04-14 18:03
As @andymckay suggested on irc let's workaround this by using &laquo; and &raquo;  instead.

**Comment by eviljeff** [comment] 2016-04-28 17:20
mentor: @muffinresearch

**Comment by ValentinaPC** [comment] 2017-01-25 10:14
Verified as fixed with the changes from #4310 on AMO-dev FF50(Win 7).
Postfix screenshots:
![ct](https://cloud.githubusercontent.com/assets/15685960/22286421/bb15f2f6-e2f7-11e6-81b6-f8fb94dab570.png)
![mysub](https://cloud.githubusercontent.com/assets/15685960/22286418/bb1229c8-e2f7-11e6-8743-a7037c2251d3.png)
![reviews](https://cloud.githubusercontent.com/assets/15685960/22286417/bb108a46-e2f7-11e6-89cc-ff243a41a2eb.png)
![rtl](https://cloud.githubusercontent.com/assets/15685960/22286419/bb14cf3e-e2f7-11e6-8ff2-0b735499dbe1.png)
![searchresults](https://cloud.githubusercontent.com/assets/15685960/22286420/bb14becc-e2f7-11e6-89a8-e9030c07f352.png)

**Closed by ValentinaPC** 2017-01-25 10:14 UTC
Labels: good first bug, triaged
