### ISSUE TITLE
https://addons.mozilla.org/en-US/firefox/search/: Add "Sort by: Added"

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#7355] opened 2018-01-21 06:42 UTC
### Describe the problem and steps to reproduce it:
Visited https://addons.mozilla.org/en-US/firefox/search/, I can "Sort by: Recently Updated" but that's not what I'm looking for.

### What did you expect to happen?
I want a "Sort by: Added" so I can follow up newly added add-ons since the last time I evaluated them which is 4 months ago in this case. Unfortunately there's no way to do it so my collections will be outdated because I don't have the chance to do sufficient research on new add-ons.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment] 2018-01-22 10:19
issues for the new frontend are filed on https://github.com/mozilla/addons-frontend/issues
This is a duplicate of https://github.com/mozilla/addons-frontend/issues/3813

**Closed by eviljeff** 2018-01-22 10:19 UTC

**Comment by davidhedlund** [comment] 2018-01-22 12:48
@eviljeff Thanks.

**Comment by davidhedlund** [comment] 2018-01-31 23:28
@eviljeff 

I didn't mean the latest version release, I meant that I want to be able to sort add-ons by the release date of the first version. Example for the three most popular extensions would look like this:
* uBlock Origin: 2015-07-02 (see https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/)
* Video DownloadHelper: 2006-12-12 (see https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/versions/)
* Adblock Plus: 2006-01-17 (see https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/)

Can you please re-open this issue?

**Comment by eviljeff** [comment] 2018-02-01 07:42
That's exactly what mozilla/addons-frontend#3813 was about - and I see you added your comments arguing for it too.

**Comment by davidhedlund** [comment] 2018-02-01 12:32
@eviljeff Yes I did, I want to make sure this issue is taken care of. Well thanks then.
