### ISSUE TITLE
The classic view is not available when a first version is submitted and then rejected by reviewer

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7866] opened 2018-03-21 10:27 UTC
STR:
1. Load AMO dev and submit an extension - I tested with static themes using the wizard
2. From rev tools pages - Listed review Page - reject the first version
3. Go back to the add-on detail page and click on view classic site.

Expected result:
The page is displayed.

Actual result:
We're sorry, but we can't find what you're looking for message is displayed.

Notes:
This issue is reproducible on AMO dev with FF59 (Win10). 
This issue is reproducible for all extension types. 

![first disabled version](https://user-images.githubusercontent.com/33448286/37704937-0d41e688-2d03-11e8-8bf2-8666f2dc7e36.gif)

**Comment by diox** [comment] 2018-03-21 10:44
@ioanarusiczki can you link the add-on? I suspect this is because you're logged in as the author of the add-on or with admin rights.

**Comment by ioanarusiczki** [comment] 2018-03-21 12:24
@diox For the issue above I was logged as the author, and I also have admin rights with that account. 
 I uploaded another one here https://addons-dev.allizom.org/en-US/firefox/addon/v1-rejected-theme/
When I use an account without admin rights the new front end displays Page not found same as for the old page.

**Comment by diox** [comment] 2018-03-21 16:45
Technically a dupe of https://github.com/mozilla/addons-frontend/issues/4244 then (and a wontfix for the legacy frontend because we don't care there)

**Closed by diox** 2018-03-21 16:45 UTC
Labels: type: bug
