### ISSUE TITLE
File viewer comparison marks file as deleted which wasn't actually deleted

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#4148] opened 2016-12-15 16:21 UTC
### Describe the problem and steps to reproduce it:
Visit https://addons.mozilla.org/en-US/firefox/files/compare/547391...460553/file/lib/robinson.js#top

### What happened?
* The file says "That file no longer exists" in the footer and all lines are marked with minus.
* The file size is correctly shown in the footer, 4.3KiB
* Downloading the xpi shows the file still exists and there are two lines different between 1.0.7 and 1.1.0

### What did you expect to happen?
* Show correct diff

**Comment by muffinresearch** [comment] 2016-12-15 16:59
I've filed https://github.com/mozilla/addons-server/issues/4149 to investigate a replacement.

**Comment by diox** [comment] 2017-03-21 11:14
@EnTeQuAk says it's a dupe of another fileviewer bug.

**Comment by wagnerand** [comment] 2017-03-21 11:17
Can we link to the other fileviewer bug, then?

**Comment by EnTeQuAk** [comment] 2017-06-14 05:33
i was sure there was one, I'm marking this as `triaged` since I can't find the other one and this is apparently still a problem some times.

**Comment by muffinresearch** [comment] 2018-02-02 17:09
Associating this with https://github.com/mozilla/addons-server/issues/7171 and since we're unlikely to fix this without the complete replacement I'm going to wontfix this one.

**Closed by muffinresearch** 2018-02-02 17:09 UTC
Labels: component: reviewer tools, triaged
