### ISSUE TITLE
Rapidly posting ratings on the same add-on+version is possible because there is no unique constraint

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6952] opened 2017-11-17 23:31 UTC
### Describe the problem and steps to reproduce it:

Here are three reviews submitted for the same add-on, same version. They were submitted within a couple seconds:

<details>
<summary>Show output

```
curl 'https://addons.mozilla.org/api/v3/reviews/review/?addon=foxyproxy-basic&user=6174808' | jq .
```

</summary>

```json
{
  "page_size": 25,
  "count": 3,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 962825,
      "addon": {
        "id": 15023,
        "slug": "foxyproxy-basic"
      },
      "body": "Works perfectly, unlike the previous proxy switcher addon I used which doesn't support Firefox 57. Thanks for taking the time to update it.",
      "created": "2017-11-16T12:00:08Z",
      "is_latest": true,
      "previous_count": 0,
      "title": "does the job",
      "user": {
        "id": 6174808,
        "name": "foocake",
        "url": null,
        "username": "329sdm0234"
      },
      "rating": 5,
      "reply": null,
      "version": {
        "id": 2230240,
        "version": "5.1.3"
      }
    },
    {
      "id": 962824,
      "addon": {
        "id": 15023,
        "slug": "foxyproxy-basic"
      },
      "body": null,
      "created": "2017-11-16T12:00:07Z",
      "is_latest": true,
      "previous_count": 0,
      "title": null,
      "user": {
        "id": 6174808,
        "name": "foocake",
        "url": null,
        "username": "329sdm0234"
      },
      "rating": 5,
      "reply": null,
      "version": {
        "id": 2230240,
        "version": "5.1.3"
      }
    },
    {
      "id": 962823,
      "addon": {
        "id": 15023,
        "slug": "foxyproxy-basic"
      },
      "body": null,
      "created": "2017-11-16T12:00:05Z",
      "is_latest": true,
      "previous_count": 0,
      "title": null,
      "user": {
        "id": 6174808,
        "name": "foocake",
        "url": null,
        "username": "329sdm0234"
      },
      "rating": 5,
      "reply": null,
      "version": {
        "id": 2230240,
        "version": "5.1.3"
      }
    }
  ]
}
```

</details>

You can also see them listed here https://addons.mozilla.org/en-GB/firefox/user/329sdm0234/

### What happened?

All three reviews were entered into the database.

### What did you expect to happen?

They should have failed the foreign key constraints which only allow one review per user per version.

### Anything else we should know?

Reported here https://twitter.com/albinowax/status/931560141467586562

**Comment by kumar303** [comment] 2017-11-17 23:32
@diox

**Comment by diox** [comment] 2017-11-18 00:35
Looks like I was wrong and there is no unique constraint on `(addon, version, user)`. We should add one, but that'll mean deleting the extraneous ratings first.

**Comment by muffinresearch** [comment] 2017-11-22 16:28
Marking this as a P2 since this is something we should look to fix soon.

**Comment by diox** [comment] 2017-11-22 16:37
To fix:

- Add `unique_together = (('addon', 'version', 'user'),)` to `Rating` model.
- Write a migration that deletes extraneous ratings (this is the tricky part) and then add the unique constraint
- Make sure the API returns a 400 error in that case (shouldn't be hard with DRF, might already be working once the `unique_together` is added).

**Comment by muffinresearch** [comment] 2017-11-22 16:42
> Write a migration that deletes extraneous ratings (this is the tricky part) and then add the unique constraint

Presumably this should just keep the newest rating made in each-case?

**Comment by dessant** [comment] 2017-11-22 16:44
Further updates were applied to the first rating.

**Comment by diox** [comment] 2017-11-22 16:48
>>  Write a migration that deletes extraneous ratings (this is the tricky part) and then add the unique constraint
>
> Presumably this should just keep the newest rating made in each-case?

Yes. We just need to make a choice and stick to it. Also, there could be rating flags attached to the ratings we'll be deleting, so they'll need to be deleted as well.

**Comment by eviljeff** [comment] 2017-11-24 16:34
Complication with using `unique_together` - Ratings are soft deleted, so although there should only be one addon+version+user+(deleted==False) combination, there could be multiple Ratings otherwise.

**Comment by diox** [comment] 2017-11-24 16:54
```
<eviljeff> mat: I'm thinking we just enforce https://github.com/mozilla/addons-server/issues/6952 in the API instead
<mat> eviljeff: mmm, yeah, soft-deletion complicates things :( not having that constraint is going to hurt though :(
<eviljeff> we do like our soft deleting.
<mat> enforcing this in the API is a good starting point
* eviljeff is, for his sins, probably responsible for more than his fair share of making deletion soft in various models.
<mat> way to make this work with soft-deletion would be to have it be a (large) integer instead of boolean, defaulting to 0 (equals not deleted), and generate a random number (equals soft-deleted) when deleting
<mat> then include that in the unique clause
<eviljeff> interesting
<mat> maybe it's worth investigating how complex it would be to implement that solution
<eviljeff> changing a column type from bool to int (even when it's not a lossy conversion) is going to be blocking and break existing code, right?
<mat> well, booleans should already be stored as int behind the scenes 
 so it might work...
<eviljeff> I don't think it's complicated, tbh.  We generally filter out deleted at the ModelManager level
<mat> the tricky part is a) making sure the migration does not take too long b) making sure we can do a query to (soft?)-delete the duplicate ratings
```

**Comment by eviljeff** [comment] 2017-11-24 18:42
For legacy frontend we _do_ allow multiple non-deleted reviews for the same addon and version (the API is supposed to block this, but that's not working probably because db replication lag, etc).  The earlier reviews have is_latest=False set on them in a task.

So, is preventing multiple reviews per addon+version a deliberate change?

**Comment by eviljeff** [comment] 2017-11-24 19:34
Summoning Product @jvillalobos -

Legacy frontend allows multiple Ratings from a single user for a version.  Earlier Ratings are set as `is_latest=False` and are labeled as such in the UI, and excluded for rating calculation,  etc.
The API prevents multiple Ratings per version (in theory - but we have a bug, hence the issue), and new frontend assumes this too I believe.

Which is correct behavior?

**Comment by jvillalobos** [comment] 2017-11-24 22:11
I think there should be a maximum of one rating per user+add-on, and trying to rate again should give the user the option to edit their existing rating rather than create a new one. It's fine that ratings are tied to versions, but that shouldn't allow multiple ratings per add-on.

To really answer the question, I think preventing multiple ratings per version is preferable, and get us closer to where I think we should be.

**Comment by eviljeff** [comment] 2017-11-27 13:31
I didn't add a database constraint because legacy reviews could be many per version, but new replies should be limited via the API.

**Comment by AlexandraMoga** [comment] 2017-11-27 14:45
Has the fix landed in -dev yet?

I'm still able to reproduce the issue by following the steps from [#6955](https://github.com/mozilla/addons-server/issues/6955), for example:


![image](https://user-images.githubusercontent.com/31961530/33272162-0655e272-d392-11e7-956f-e557fa89d85e.png)

![image](https://user-images.githubusercontent.com/31961530/33272073-bc1636da-d391-11e7-9199-95627ec91bb3.png)

**Closed** 2017-11-28 17:07 UTC
Labels: component: ratings and reviews, priority: p2, triaged

**Comment by AlexandraMoga** [comment] 2017-11-29 09:43
Verified as fixed in AMO-dev FF57 (Win 10)
Posting a duplicate rating is no longer allowed 
I've opened a new issue [(#4007)](https://github.com/mozilla/addons-frontend/issues/4007) with regards to the error message displayed
![duplicate ratings](https://user-images.githubusercontent.com/31961530/33368394-41210d00-d4fa-11e7-8540-138c499e0ba8.gif)
