### ISSUE TITLE
Include authors in add-on detail API

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3137] opened 2016-07-20 21:35 UTC
The admin tool would like to show the authors of an add-on but this is not currently exposed by the API. The search and detail APIs should return the authors of the add-on.

https://github.com/mozilla/addons-frontend/issues/809 depends on this.

**Comment by diox** [comment] 2016-07-20 22:42
Dupe of #3022 ; A pull request implementing it has been made and will be merged tomorrow.

**Closed by diox** 2016-07-20 22:42 UTC
Labels: admin tools, API, enhancement, triaged
