### ISSUE TITLE
API endpoint to check JWT authentication and detect client clock skew

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons-server#1461] opened 2016-01-20 21:09 UTC
For the JPM sign API, the JWT is very time dependent.

Could we please get an endpoint that on access it gives us the AMO server time. Of course no token needed on this endpoint please.

Devs can subtract the load time from the time obtained on that page to get an accurate time for use in generating a JWT.

**Comment by andymckay** [comment] 2016-01-20 23:22
I don't see the need for this. All computers should have same time thanks to ntp right?

**Comment by Noitidart** [comment] 2016-01-21 00:30
They should, but for some reason at least my computer keeps losing track I have no idea why. Requiring me to sync again and again. So I thought to use this website `http://currenttimestamp.com/` but thought that it would be nice if AMO could provide that, because its not really NTP but its AMO server time which we hope is NTP.  Seems like these guys had same exact problem and it led to hours of troubleshooting for them:

* https://github.com/mozilla/olympia/issues/1072
* https://github.com/mozilla/olympia/issues/1109


By the way, is the server time returned in the response headers? Or is that some other time?

**Comment by andymckay** [comment] 2016-01-21 00:43
Its the date as per the http protocol: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields which is when the response was generated (which may or may not be similar to your time), but if you are trying to get a precise date time that isn't going to really help you unless you can use it spot a large clock drift between the AMO server and your computer. Perhaps in your case you could send a pull request into jpm to do that automatically?

But then again if you are trying to detect a large clock drift between your computer and what it should be, wouldn't it make more sense to detect it against an NTP server?

5 seconds does seem a bit tight @kumar303 is there a problem with going for up to 60 seconds?

Also, is it possible in JWT to detect the time drift? If so can we return an appropriate message when we do detect it?

**Comment by kumar303** [comment] 2016-01-21 17:38
Sure, we can change the skew time from 5 seconds to 60 seconds. A drift is a drift though. The best way to fix it is to use NTP syncing.

> Also, is it possible in JWT to detect the time drift?

Yes, maybe.

> Could we please get an endpoint that on access it gives us the AMO server time.

FYI, we can't simply expose server time because it can be used as an attack vector. We could provide an API endpoint like /auth-check or something that tells you if your authentication is correct. We could also perhaps add a more detailed error message when your clock is off, as long it doesn't impact security.

**Comment by andymckay** [comment] 2016-01-22 03:10
My other thought there was, allow a date to be sent in a http header, like "JWT-creation-datetime", if there's a failure, check that and raise a polite "hey your clock is out error". That's a super simple fix for anyone to add to jpm or their favourite http api.

**Comment by Noitidart** [comment] 2016-01-22 03:22
Interesting stuff, thanks. I got it working consistently using http://currenttimestamp.com/ but anything to make future devs debugging easier is probably a good idea. Took me a second to realize it was the time that was off.

**Comment by kumar303** [comment] 2016-01-22 16:18
> allow a date to be sent in a http header, like "JWT-creation-datetime"

The JWT itself already declares `iat` (issued at) which is the creation timestamp. I'm going to dig into https://github.com/mozilla/olympia/issues/1071 and see if we can offer a better message. The problem is that an attacker can intercept and replay attacks if we allow too much leeway in clock skew. We have other ways to protect against replays though.

**Comment by EnTeQuAk** [comment] 2017-01-09 17:29
Just reading this, is that something that needs work on AMO? It seems client clock skew detection can happen on the client to some degree, exposing too much information in that regards from the Server might open up funny doors.

If no work needs to be done here, can we close this?

**Comment by Noitidart** [comment] 2017-01-09 17:33
@EnTeQuAk thanks. Client can be used but has intermittent issues depending on the client. If no one else is complaining, then I think we can close this. I got a solution for myself - I started using three servers to get a correct unix time - https://github.com/Noitidart/common/blob/master/all.js#L258-L336

```
async function getUnixTime(opt={}) {
	// retry_cnt is used for times to retry each each server
	opt = {
		timeout: 10000,
		compensate: true, // subtracts half of the xhr request time from the time extracted from page
		...opt
	};

	let servers = [
		{
			name: 'trigger-community',
			xhropt: {
				url: 'https://trigger-community.sundayschoolonline.org/unixtime.php',
				restype: 'json'
			},
			xhrthen: ({response, status}) => {
				if (status !== 200) throw `Unhandled Status (${status})`;
				let unix_ms = response.unixtime * 1000;
				return unix_ms;
			}
		},
		{
			name: 'CurrentTimestamp.com',
			xhropt: {
				url: 'http://currenttimestamp.com/'
			},
			xhrthen: ({response, status}) => {
				if (status !== 200) throw `Unhandled Status (${status})`;

				let extract = /current_time = (\d+);/.exec(response);
				if (!extract) throw 'Extraction Failed';

				let unix_ms = extract[1] * 1000;
				return unix_ms;
			}
		},
		{
			name: 'convert-unix-time.com',
			xhropt: {
				url: 'http://convert-unix-time.com/'
			},
			xhrthen: ({response, status}) => {
				if (status !== 200) throw `Unhandled Status (${status})`;

				let extract = /currentTimeLink.*?(\d{10,})/.exec(response);
				if (!extract) throw 'Extraction Failed';

				let unix_ms = extract[1] * 1000;
				return unix_ms;
			}
		}
	];

	let errors = [];
	for (let { xhropt, name, xhrthen } of servers) {
		try {
			let start = Date.now();
			let xpserver = await xhrPromise({ ...xhropt, timeout:opt.timeout });
			let duration = Date.now() - start;
			let halfduration = Math.round(duration / 2);

			let unix_ms = xhrthen(xpserver.xhr);

			if (opt.compensate) unix_ms -= halfduration;

			return unix_ms;
		} catch(ex) {
			if (typeof(ex) == 'string') ex = ex
			else if (ex && typeof(ex) == 'object' && ex.xhr && ex.reason) ex = 'XHR ' + ex.reason
			else ex = ex.toString();

			errors.push(`Server "${name}" Error: ` + ex);

			continue;
		}
	}

	throw errors;
}
```

**Comment by EnTeQuAk** [comment] 2017-01-09 17:48
Nice, thanks a ton for the snippet! That'll help people if they stumble on this issue.

I'm going to close this for now but if there's any need to add some functionality server wise please feel free to re-open anytime.

**Closed by EnTeQuAk** 2017-01-09 17:48 UTC
Labels: API

**Comment by Noitidart** [comment] 2017-01-09 17:50
Thank you @EnTeQuAk, I really appreciate the nice comments on close :)

**Comment by kumar303** [comment] 2017-01-09 20:07
Nice approach, @Noitidart . Getting this kind of thing to work client side is super hard.

**Comment by Noitidart** [comment] 2017-01-09 23:42
@kumar303 thanks brother! :)
