### ISSUE TITLE
Add button greyed out and clickable

### ISSUE THREAD

**Issue by gene1wood** [mozilla/addons-server#7216] opened 2018-01-04 18:35 UTC
### Describe the problem and steps to reproduce it:
1. Browse to https://addons.mozilla.org/en-US/firefox/addon/search-internet-archive/ in Firefox 57
2. Look at the add button
3. Mouseover the add button and see a circle with a line through it mouse icon
4. Click the Add button

### What happened?
The user is prompted to add the search engine

### What did you expect to happen?
Either for the add button to be non-grey with a normal mouseover icon and clicking the button installed the search engine

or

For the add button to be grey with a circle line through it mouseover icon and clicking the button does not install the search engine

Also, as a side note, since this add-on is just a search engine, and I believe the greyed out button relates to Firefox version compatibility, I don't know why this would be greyed out for a search engine which has no version compatibility requirements of Firefox. This is tangential though to the core UX problem here.

### Anything else we should know?
Here's a screen recording video of the problem

[![Add button greyed out and clickable](https://img.youtube.com/vi/G5bRSQHnXZ4/0.jpg)](https://www.youtube.com/watch?v=G5bRSQHnXZ4)

**Comment by muffinresearch** [comment] 2018-01-04 18:58
@gene1wood thanks for the bug report, this is a duplicate of https://github.com/mozilla/addons-frontend/issues/4047

**Closed by muffinresearch** 2018-01-04 18:58 UTC
