### ISSUE TITLE
API: Filtering addons versions for unlisted leads to 403, even with admin permissions.

### ISSUE THREAD

**Issue by GregSherman** [mozilla/addons-server#21063] opened 2023-08-03 22:03 UTC
### Describe the problem and steps to reproduce it:
1. As someone who has the permissions to filter by all_with_unlisted, use your api key and secret to generate a JWT.
2. Use this JWT to access `addons/addon/ublock-origin/versions?filter=all_with_unlisted`.

### What happened?
You are met with a 403 forbidden error, meaning you do not have the proper permissions.

### What did you expect to happen?
The response should not error. Try this same endpoint (as someone who has viewing deleted versions permissions) `addons/addon/ublock-origin/versions?filter=all_with_deleted`. This will work. However, if you have the deleted perms, you also have the unlisted perms. So there must be something wrong with the handling of the logic for the specific `all_with_unlisted` permission.

### Anything else we should know?
Since this does not always happen, only with certain addons, it's possible that the issue lies when the addon actually doesn't have any unlisted versions, or if any of the versions are blocked.

**Comment by ioanarusiczki** [comment] 2023-08-07 09:54
@GregSherman 

I could reproduce the issue on -dev with an admin account every time I make a request with a guid that doesn't have unlisted versions. 
I used my frontend session id instead of JWT.

**Comment by GregSherman** [comment] 2023-08-10 19:21
Looking into it more, in the file `src/olympia/api/permissions.py` under `AllowUnlistedViewerOrReviewer.has_object_permission()`, my logs show that `has_unlisted_or_no_listed` returns false, which causes the 403 error. In the case where there are only listed versions, this condition is false. @wagnerand @willdurand , It seems like you guys edited this last. I'm not clear on the `has_unlisted_or_no_listed` condition and why it's a requirement for a response. Any context for my next steps here?

```py
  def has_object_permission(self, request, view, obj):
      can_access_because_unlisted_viewer = (
          request.method in SAFE_METHODS
          and acl.action_allowed_for(
              request.user, permissions.REVIEWER_TOOLS_UNLISTED_VIEW
          )
      )
      can_access_because_unlisted_reviewer = acl.is_unlisted_addons_reviewer(
          request.user
      )
      has_unlisted_or_no_listed = obj.has_unlisted_versions(
          include_deleted=True
      ) or not obj.has_listed_versions(include_deleted=True)

      return has_unlisted_or_no_listed and (
          can_access_because_unlisted_viewer or can_access_because_unlisted_reviewer
      )
```

**Comment by wagnerand** [comment] 2023-08-11 09:33
@GregSherman Can you provide the user ID you use on -dev as well as the add-on you're testing with?

**Comment by GregSherman** [comment] 2023-08-11 14:06
@wagnerand UserID 10642600 and the addon slug ublock-origin.

**Comment by wagnerand** [comment] 2023-08-11 14:25
@GregSherman Thanks. Weird that we are hitting this path, the add-on does not have any unlisted versions. What is the request you're sending?

**Comment by GregSherman** [comment] 2023-08-14 18:11
Tinkering with tests to try and see the intention of the view, I'm having trouble understanding fully the purpose of everything. Looking at these two tests:

```py
    def test_object_with_listed_versions_but_no_unlisted_versions(self):
        self.request.user = user_factory()
        self.grant_permission(self.request.user, 'Addons:ReviewUnlisted')
        obj = Mock(spec=[])
        obj.has_unlisted_versions = lambda include_deleted=False: False
        obj.has_listed_versions = lambda include_deleted=False: True

        assert self.permission.has_permission(self.request, myview)
        assert not self.permission.has_object_permission(self.request, myview, obj)

    def test_object_with_listed_versions_but_no_unlisted_versions_viewer(self):
        self.request.user = user_factory()
        self.grant_permission(self.request.user, 'ReviewerTools:ViewUnlisted')
        obj = Mock(spec=[])
        obj.has_unlisted_versions = lambda include_deleted=False: False
        obj.has_listed_versions = lambda include_deleted=False: True

        assert self.permission.has_permission(self.request, myview)
        assert not self.permission.has_object_permission(self.request, myview, obj)
```

They expect the exact same thing, however one has the permissions of view, but the other has permission of review. Should `Addons:ReviewUnlisted` give the user object permissions?

**Comment by eviljeff** [comment] 2023-08-15 09:35
> They expect the exact same thing, however one has the permissions of view, but the other has permission of review. Shouldn't `Addons:ReviewUnlisted` give the user object permissions?

The test is checking the (albeit unlikely) scenario of a user having `Addons:ReviewUnlisted` and no other permissions - i.e. no `Addons:Review`. But it also exposes that the logic in the permission class doesn't really make sense in the scenario it's being used in - if the Addon has a listed version there is now no way to view any unlisted versions because we don't have a filter for _just_ showing unlisted versions, and not listed versions (we have "show all listed versions" and "show all listed and unlisted versions")

Thankfully this isn't a scenario in reality - (afaik) there are no users with _just_ `Addons:ReviewUnlisted`.

Thinking about `AllowUnlistedViewerOrReviewer.has_object_permission`, I believe the `or not obj.has_listed_versions(include_deleted=True)` clause was added to work around the normal case in our code where we're doing `AnyOf(AllowListedViewerOrReviewer, AllowUnlistedViewerOrReviewer)` and want to handle an add-on with no (undeleted) versions - if `AllowListedViewerOrReviewer` only passes when there is a listed version, and `AllowUnlistedViewerOrReviewer` only passes when there is an unlisted version, neither will pass if there are no versions.  In `AddonViewSet.check_permissions` though, we're just using `AllowUnlistedViewerOrReviewer` on it's own so it has the side effect of not allowing any addon with a listed version to pass.  

Maybe the fix for this issue is just to use `GroupPermission(amo.permissions.ADDONS_REVIEW_UNLISTED)` and `GroupPersmission(amo.permissions.REVIEWER_TOOLS_UNLISTED_VIEW)` directly

**Closed** 2023-08-16 16:12 UTC

**Comment by KevinMind** [comment] 2024-05-04 19:29
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-470
