### ISSUE TITLE
iCloud Bookmarks Add-on

### ISSUE THREAD

**Issue by grizzlybear007** [mozilla/addons-server#3126] opened 2016-07-20 00:58 UTC
Hi.
I have just set up on Apple's iCloud after an update to iTunes. At the end I was asked if I wanted to link my Firefox and Chrome bookmarks with iCloud. I clicked yes, upon which I was told I would need to download an add-on for Firefox. Unfortunately, the referral button sent me to a Mozilla page telling me the add-on I was seeking couldn't be found (https://addons.mozilla.org/en-US/firefox/addon/icloud-bookmarks/).
Regards,
Lex Borthwick
grizzlybear007@iinet.com.au
grizzlybear007@mmaramotswerules.com
lexbron@ozemail.com.au

**Comment by andymckay** [comment] 2016-07-20 04:33
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by andymckay** 2016-07-20 04:33 UTC
