### ISSUE TITLE
Firefox add on for iCloud

### ISSUE THREAD

**Issue by stevelloyd192** [mozilla/addons-server#3135] opened 2016-07-20 20:27 UTC
Just updated my iCloud programme and it tells me I need to download a bookmarks extension in order to update my firefox browser/safari browser. However when I follow the supplied link Firefox says it's not there.
![icloud firefox extension link](https://cloud.githubusercontent.com/assets/20565626/17001864/b1e35fb4-4ec0-11e6-85ce-2f7001a89c6b.png)

**Comment by andymckay** [comment] 2016-07-20 20:36
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by andymckay** 2016-07-20 20:36 UTC
