### ISSUE TITLE
`DoesNotExist('FileUpload matching query does not exist.',)` during validation

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12572] opened 2019-10-09 14:17 UTC
We noticed an error during validation that does not happen very frequently but it has been noticed in -dev and prod.

Below is the only error we've seen in production (at the time of writing this issue), raised in [`handle_upload_validation_result()`](https://github.com/mozilla/addons-server/blob/49318f054293ed0a4004e4d43a28c978892b94b5/src/olympia/devhub/tasks.py#L280):

```
 Celery TASK exception: DoesNotExist: FileUpload matching query does not exist.

  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/olympia/src/olympia/amo/decorators.py", line 108, in wrapper
    return f(*args, **kw)
  File "/data/olympia/src/olympia/devhub/tasks.py", line 280, in handle_upload_validation_result
    upload = FileUpload.objects.get(pk=upload_pk)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
<class 'olympia.files.models.FileUpload.DoesNotExist'>
DoesNotExist('FileUpload matching query does not exist.',)
```

In -dev, we noticed this error in `repack_fileupload()`. At least one error in -dev is related to an API-based submission.

**Comment by diox** [comment] 2019-10-09 15:49
The usual suspects for this kind of errors are transactions and database replicas.

However, I've looked into both locally and:
- We do seem to be waiting for the transaction to be committed before triggering the tasks, as expected thanks to https://github.com/mozilla/django-post-request-task/
- We do seem to be running the tasks while being pinned to the primary db, as expected because the tasks are decorated with `@use_primary_db`.

So right now we're a bit stumped...

**Comment by diox** [comment] 2019-10-22 10:17
We've seen the error locally a few times, but it was always hard to make sure we were in a stable environment at the time - often we had just switched branches, etc. Today I just saw it again and I had been on the same branch for a while, no recent celery restarts, it was working fine before and after, even with the same add-on!

From the logs I can see the `FileUpload` creation date is one second before the repack task started (but I don't know when the `COMMIT` happened, and the `created` date is set by Django in Python)

Not much to add besides the fact that it was an API upload, if that helps...

**Comment by diox** [comment] 2019-11-07 15:40
I managed to reproduce 100% of the time locally, with this one weird trick:
- `docker-compose restart web`
- wait a few seconds just to be sure everything is running and you don't get a 502
- submit a new add-on using `web-ext sign --api-url-prefix http://olympia.test/api/v4 ...`

Every time I do this (tried half a dozen times), I don't get a successful validation, and celery logs show this traceback. This only happens for the first submission, subsequent ones work fine. But the weirdest part is that even though the error is occurring inside a celery worker, what triggers it is restarting the `web` container, not the `worker` one. Restarting the `worker` alone doesn't seem to have any effect.

I'm baffled as to what would cause this. `/code` is on a shared volume, but our development images have `PYTHONDONTWRITEBYTECODE=1`. And we've seen this in production as well, with completely separate containers/hosts. Still, it may give us a hint...

**Comment by diox** [comment] 2019-11-07 15:54
Most likely suspect in my eyes: something that would cause `post-request-task` to fire the celery task too early, before the transaction wrapping the request has been committed, *only for the first request* coming to the server.

**Comment by diox** [comment] 2019-11-07 16:07
Logs confirm that theory: for the first request, we don't go through `post_request_task`'s `_append_task` logging. I think this is because by the time we get to `post_request_task`, `request_started` has already been sent for the first request. So for the first request, this is bypassed, and the task is sent to the queue immediately, too soon.

`post_request_task` defaults to not being enabled until it sees `request_started`, and that is useful to make tasks work in non-request contexts, so I'd rather not change that. Instead we need to make sure it sees that signal, maybe by force it to be imported sooner or by re-sending the signal.

**Closed** 2019-11-08 11:57 UTC
Labels: component: devhub, priority: p3
