### ISSUE TITLE
Add-on ID comparison is case-sensitive when new version, case-insensitive when new add-on

### ISSUE THREAD

**Issue by Alien426** [mozilla/addons-server#11174] opened 2019-04-09 20:28 UTC
### Describe the problem and steps to reproduce it:
Critical error when uploading new version: "The add-on ID in your manifest.json or install.rdf (NoticeCase@xxx) does not match the ID of your add-on on AMO (noticecase@xxx)"

Critical error when uploading new add-on: "Duplicate add-on ID found."

### What happened?
Signing of the add-on was prevented in both cases.

### What did you expect to happen?
Either allow a new version of existing add-on or allow a new add-on.

**Comment by dbxnr** [comment] 2019-07-16 20:42
Can I take this one?

**Comment by Alien426** [comment] 2019-07-17 05:52
Take it.

**Comment by dbxnr** [comment] 2019-07-17 12:28
The add-on IDs are meant to be case sensitive (https://github.com/mozilla/addons-server/pull/11847#issuecomment-512222523) so this is perhaps intended behaviour?

**Comment by EnTeQuAk** [comment] 2019-07-19 11:30
> The add-on IDs are meant to be case sensitive (#11847 (comment)) so this is perhaps intended behaviour?

I think I agree, that this doesn't actually seem to be a problem looking at how Firefox handles GUIDs.

I'm going to close the issue with that, correct me if I'm mistaken though

**Comment by EnTeQuAk** [comment] 2019-07-19 12:08
Apologies, @wagnerand correctly noted that the issue is indeed correct. The mentioned problem is that it seems our default compare - because of MySQL - is case insensitive and we want it to be case-sensitive.

Your title mentions that the behavior is different between new add-on submissions and new version submissions but the description states differently. From what I can see in the code the behavior should be identical for both processes, or am I missing something?

**Comment by Alien426** [comment] 2019-07-19 19:30
How does the description differ from the title? Think about it!

I have changed the case of the ID.

A new version of the existing add-on can only fail if the comparison is case-sensitive.

Submitting a new add-on can only fail if the old ID and new ID are recognized as the same. Therefore in this case it must be a case-INsensitive comparison.

**Comment by EnTeQuAk** [comment] 2019-08-01 13:21
I'm closing the PR, last time we discussed this we ended up deciding that the current behavior is perfectly fine for now.

**Closed by EnTeQuAk** 2019-08-01 13:21 UTC
Labels: component: devhub, contrib: welcome, priority: p4

**Comment by Alien426** [comment] 2019-08-02 06:14
"src\olympia\files\utils.py"
line 1036: "if addon and addon.guid != guid:" (standard Python - case-sensitive)
line 1041ff: "Addon.objects.filter(guid=guid).exists()" (Django / MySQL)

"As a convenience when no lookup type is provided [...] the lookup type is assumed to be >exact<."
"In MySQL, a database table’s “collation” setting determines whether >exact< comparisons are case-sensitive. This is a database setting, not a Django setting."
-- https://docs.djangoproject.com/en/2.2/ref/models/querysets/#id4

I see how getting non-case-sensitive behavior in Python is an issue when allowing Unicode (https://stackoverflow.com/questions/319426/).
