### ISSUE TITLE
On uploading a Chrome webext without changing the manifest.json, don't fail validation with an unexpected error

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2754] opened 2016-05-25 22:05 UTC
## steps to reproduce:
1. Download any Chrome extension like https://chrome.google.com/webstore/detail/tubebuddy/mhkhmbddkmdggbhaaaodilponhnccicb
2. Change the filetype of the extension from .crx to .xpi
3. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/2
4. Upload the xpi

## expected behavior:
Validation fails with clear instructions for the developers to fix whatever is blocking successful validation. If target application and GUID are required fields in the manifest.json, we indicate that to the developer when the validation fails.

## actual behavior:
Validation fails with an unexpected error which isn't very useful.

**Comment by andymckay** [comment] 2016-05-25 22:20
```
addons-linter bin/addons-linter ~/Downloads/extension_1_44_183.xpi master  ✭ ✱ 
Error: invalid central directory file header signature: 0xa995d2ce
    at /Users/andy/sandboxes/addons-linter/node_modules/yauzl/index.js:231:70
    at /Users/andy/sandboxes/addons-linter/node_modules/yauzl/index.js:473:5
    at /Users/andy/sandboxes/addons-linter/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:675:17)
```

Because there's gunk in that zip file, because crx's have gunk in them.

This add-on doesn't pass on the current validator either right now either, so I'm not sure how this blocks release to be honest. If you re-zip it as an xpi, it works (well you get other errors).

Having the ability to take a .crx and push it through AMO is something that @tofumatt is working on in #2579 and I would rather have this track that.

**Comment by krupa** [comment] 2016-05-25 22:37
Can we not fail with an "unexpected error" and tell the developer exactly what needs to be changed?
I can see many Chrome extension developers trying to upload the file without having read the documentation just to see if it works.

**Comment by andymckay** [comment] 2016-05-25 22:40
Sure, but then we add code to cope with the error and then like two weeks later @tofumatt adds in .crx support in bug #2579.

**Comment by EnTeQuAk** [comment] 2016-05-26 07:06
Well, imho this isn't neccessarily related to crx support but more about general error handling in the linter/validator although it would probably make sense to catch that in AMO before passing the files to the linter / validator. That would allow for better error messages in case of broken files too. The amount of variations AMO accepts is relatively limited (`.xpi`, `.crx` in the future) so we could add at least some "can we open this file" checks before we forward it to the linter/validator.

@krupa you mentioned "documentation" - is there some regarding porting from chrome to firefox? We could link to it.

**Comment by krupa** [comment] 2016-05-27 01:08
@EnTeQuAk I was referring to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_from_Google_Chrome

**Comment by tofumatt** [comment] 2016-06-08 16:06
I'd say this relates to #2579.

**Comment by tofumatt** [comment] 2016-06-08 16:08
To be clear though things are working as intended, because like mentioned, renaming a `.crx` to `.xpi` isn't valid.

**Comment by tofumatt** [comment] 2016-06-08 20:17
I think this is a dupe of #2726, as renaming one file type to another then uploading it isn't something we should support 😄

**Closed by tofumatt** 2016-06-08 20:17 UTC
Labels: linter, triaged
