### ISSUE TITLE
Add-on not usable for Script-safe versions of Mozilla Firefox, found another OS versions when entering "eid" in the Search box

### ISSUE THREAD

**Issue by rlobet** [mozilla/addons-server#8859] opened 2018-07-12 15:54 UTC
### Describe the problem and steps to reproduce it:
Using the script-safe version of Mozilla, Firefox Add-On Manager looks up for Android versions of the Add-Ons

### What happened?
It can not install https://addons.mozilla.org/en-US/firefox/addon/belgium-eid/?src=search using the search engine https://addons.mozilla.org/en-US/seamonkey/search/?q=eid&cat=1%2C0&appver=&platform=windows

### What did you expect to happen?
Install the plug-in because this will be the only way to access the Belgium eID Smartcard Login on time.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment] 2018-07-12 17:56
Duplicate of #8858

**Closed by jvillalobos** 2018-07-12 17:56 UTC
