### ISSUE TITLE
Uploading a new addon version with sources intermittently (?) results in 500 error

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2828] opened 2016-06-02 09:24 UTC
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/243625/events/7370228/

We have several instances of this traceback, always with the same scenario: a developer uploading a new version of their add-on, with sources included - it seems to work fine when they don't add sources.

I have no idea why it's blowing up like that - It's somewhere in memcached when cache-machine is trying to fetch some `ApplicationsVersions` in `compatible_apps` property. At this point, the `Version` and its `ApplicationsVersions` should definitely exist, having just been created.

`compatible_apps` is a writeable `cached_property` so a workaround could be to manually set it to the `ApplicationsVersions` we just created in `Version.from_upload`.

**Comment by diox** [comment] 2016-06-02 09:25
On IRC, one add-on author confirmed that not including sources initially and then adding them on the second screen worked from him, which is super weird.

**Comment by andymckay** [comment] 2016-06-03 16:05
Maybe a dupe of #1995 ?

**Comment by diox** [comment] 2016-06-03 16:19
Yes. This one has more information though.

**Comment by wagnerand** [comment] 2016-08-03 22:50
Adding @deadsquid to see whether we could re-prioritize this.

**Comment by diox** [comment] 2016-08-19 11:09
Taking this one because the workaround I suggest in the description should be easy and not too risky. That should help reduce the perimeter for mozilla/addons#132

**Closed** 2016-08-22 11:02 UTC
Labels: pull request ready
