### ISSUE TITLE
Preliminary reviewed add-on with signature cannot be installed

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1105] opened 2015-12-17 13:15 UTC
https://addons.mozilla.org/en-US/firefox/addon/contasturbo/

Both 1.4 and 1.4.1 have been (preliminary) approved, but cannot be installed. I downloaded both files and they are correctly signed.

Note that the source viewer shows a 404 if I try to access the contents of the file: https://addons.mozilla.org/en-US/firefox/files/browse/376585/
Downloading the file itself works just fine.

Log output:
```
1450358279157	addons.xpi	DEBUG	Download started for https://addons.mozilla.org/firefox/downloads/file/376585/contas_turbo-1.4.1.xpi?src=dp-btn-primary to file /Users/awagner/Library/Caches/TemporaryItems/tmp-7oj.xpi
1450358279160	addons.xpi	DEBUG	Download of https://addons.mozilla.org/firefox/downloads/file/376585/contas_turbo-1.4.1.xpi?src=dp-btn-primary completed.
1450358279179	addons.xpi	WARN	Download of https://addons.mozilla.org/firefox/downloads/file/376585/contas_turbo-1.4.1.xpi?src=dp-btn-primary failed: signature verification failed
1450358279185	addons.xpi	DEBUG	downloadFailed: removing temp file for https://addons.mozilla.org/firefox/downloads/file/376585/contas_turbo-1.4.1.xpi?src=dp-btn-primary
1450358279185	addons.xpi	DEBUG	removeTemporaryFile: https://addons.mozilla.org/firefox/downloads/file/376585/contas_turbo-1.4.1.xpi?src=dp-btn-primary removing temp file /Users/awagner/Library/Caches/TemporaryItems/tmp-7oj.xpi
```

**Comment by Noitidart** [comment] 2015-12-17 13:46
Validation page seems to work fine too, weird - https://addons.mozilla.org/en-US/developers/addon/contasturbo/file/376585/validation

The other place where we get 404 is if we try to do version compare https://addons.mozilla.org/en-US/firefox/files/compare/376585...373236/

**Comment by jvillalobos** [comment] 2015-12-18 17:34
I tried a local install and Firefox told me the add-on wasn't signed. I see the META-INF directory with the right files, though.

**Comment by andymckay-limited-access** [comment] 2015-12-18 18:50
Is this a problem in the client, or the way that AMO signed it?

**Comment by jvillalobos** [comment] 2015-12-21 17:26
I don't really know how to verify the signature outside of Firefox. Maybe Mossop can help with that.

**Comment by wagnerand** [comment] 2015-12-21 17:48
`openssl pkcs7  -inform der -in META-INF/mozilla.rsa -print_certs -text`

**Comment by jvillalobos** [comment] 2016-04-01 23:21
Looks like we dropped the ball with this issue. I'm closing this as a dupe of #2158, which explains what appear to be the causes of the problem (ignore my initial comment).

**Closed by jvillalobos** 2016-04-01 23:21 UTC
