### ISSUE TITLE
Screenshots navigation is not working for RTL languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3418] opened 2016-09-06 08:40 UTC
Steps to reproduce:
1. Log into AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Change the language to a RTL one i.e. https://addons-dev.allizom.org/fa/firefox/
3. Go to an add-on (must have screenshots) details page (https://addons-dev.allizom.org/fa/firefox/addon/adblock-plus/?src=hp-dl-mostpopular)
4. Navigate between screenshots

Expected results:
User can navigate between screenshots.

Actual results:
User is not able to navigate between screenshots. 

Notes/Issues:
_Not reproducing for logged out users._
While accessing any add-on/theme page (RTL) the error "uncaught exception: Format string is empty!" is listed in the console.
Verified on FF48(Win 7). Issue is happening on AMO-dev, stage and prod.
Video for this issue: 
![screenshots](https://cloud.githubusercontent.com/assets/15685960/18266204/470abfca-7422-11e6-97d7-5970107c4c58.gif)

**Comment by tsl143** [comment] 2016-09-11 15:22
Is this still a bug, I am unable to reproduce it !

**Comment by ValentinaPC** [comment] 2016-09-12 07:48
@tsl143 : Yes. 
Note: don't forget to be logged.

**Comment by tsl143** [comment] 2016-09-12 08:57
Yes it is reproduced , only when logged in.

**Comment by muffinresearch** [comment] 2016-09-16 08:42
Dupe of #3528

**Closed by muffinresearch** 2016-09-16 08:42 UTC

**Comment by ValentinaPC** [comment] 2016-09-21 08:49
Since #3528 is fixed, this is no longer reproducing.
Postfix video: 
![screenshotsnav](https://cloud.githubusercontent.com/assets/15685960/18704146/6fa6f644-7ff1-11e6-8206-7672b4d91ba7.gif)
