### ISSUE TITLE
Add-on ID is valid for AMO but invalid for Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6658] opened 2017-10-11 19:48 UTC
We got [a report](https://discourse.mozilla.org/t/error-downloading-my-accepted-addon/20350/3) of an add-on that was just listed on AMO but can't be installed in Firefox. The error in the console is as follows: `Error: Webextension is signed with an invalid id (FMath-MathML-Extension)`.

Per [the documentation](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#id), Firefox accepts IDs in GUID format or email format, and apparently AMO is more lenient. /cc @andymckay for the regular expression that Firefox uses.

**Comment by andymckay** [comment] 2017-10-11 21:45
Loading extension 'null': Reading manifest: Error processing applications.gecko.id: Value "foo-bar-bingo" must either: match the pattern /^\{[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\}$/i, or match the pattern /^[a-z0-9-._]*@[a-z0-9-._]+$/i

**Comment by andymckay** [comment] 2017-10-11 21:46
See also: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/schemas/manifest.json#430-439

**Comment by eviljeff** [comment] 2017-10-12 15:52
I can't replicate this trying with a random xpi - I get validation errors.  https://addons.mozilla.org/en-GB/developers/upload/00ac291200364c4eb3cefe5dcf70ea34

**Comment by jvillalobos** [comment] 2017-10-12 18:06
The ID that made it through (somehow) is `FMath-MathML-Extension`. I can try asking the developer for more info if you can't reproduce with that one. The add-on was also massive (40Mb), but I'd be surprised if that factors into this.

**Comment by eviljeff** [comment] 2017-10-12 18:32
I can't reproduce with that one.  Or at least one very similar because I tested with prod and that one was already used by the developer.

**Comment by diox** [comment] 2017-10-12 18:38
It would be useful to see the exact manifest of the add-on when it was still causing an issue (the current one does not seem to specify an id)

**Comment by erosman** [comment] 2017-10-12 20:49
re manifest (posted to the discourse topic): Those look like Unicode double quotes.

**Comment by eviljeff** [comment] 2018-03-08 13:19
I'm closing this for now as we apparently asked back in October for more details and no update.  Re-open if we get the info and can still replicate.

**Closed by eviljeff** 2018-03-08 13:19 UTC
Labels: needs: info, priority: p4, triaged
