### ISSUE TITLE
Add a Content Review link to the add-on update e-mail; or auto redirect to the content review page

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#9840] opened 2018-10-30 09:29 UTC
Steps to reproduce:

1) As a content reviewer make a change to an add-on listing.
2) Wait for someone else to make a change which generates an e-mail message.
3) Use the link in e-mail to respond to the change.

For example:
If you want to respond please reply to this email or visit https://addons.mozilla.org/reviewers/review-listed/1005262

Actual:

The link directs to a page that can't be viewed.

For example:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-listed/selkeeper
Oops! Not allowed.
You tried to do something that you weren't allowed to.

(That message is really rude. I didn't try to do something that I wasn't allowed to do. I am allowed to reply, but the web server directed me to a page I can't use.)

### What did you expect to happen?

Either provide separate listed and content review links, or have the link in the message redirect to the appropriate place if the user is a content reviewer.

In this case:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/selkeeper

### Anything else we should know?

This has been a minor annoyance, but upon returning from vacation I had a large number of e-mail messages where I had to manually fix the link.

**Comment by wagnerand** [comment] 2018-10-30 10:07
Duplicate of #6936.

**Closed by wagnerand** 2018-10-30 10:07 UTC
