### ISSUE TITLE
Incompatible add-ons inside a collection have layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3513] opened 2016-09-14 13:27 UTC
Steps to reproduce:
1. Load details page for a collection that contains incompatible add-ons i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/privacy/?page=2
2. Observe the incompatible add-on

Expected results:
There are no display or layout issues.

Actual results:
There is a layout issue in what concerns the availability/incompatibility message.

Notes/Issues:
Also the "View other versions" is not blue as in add-on details page.
Verified on FF48.0.2(Win 7). Reproducing on all add-ons servers.
Screenshots for this issue: 
![coll1](https://cloud.githubusercontent.com/assets/15685960/18513861/d3aa5500-7a97-11e6-9b0c-3c8cf9819ab5.png)
![coll2](https://cloud.githubusercontent.com/assets/15685960/18513862/d3aba676-7a97-11e6-8789-610df0eb0170.png)

#3437

**Comment by EnTeQuAk** [comment] 2016-09-14 14:07
Hmm, is that a regression from one of the recent changes that landed style-related? cc @tofumatt

**Comment by ValentinaPC** [comment] 2016-09-14 14:09
@EnTeQuAk : I don't think so, is like this for a while.

**Comment by vijeth-aradhya** [comment] 2016-09-17 15:10
Is this bug fixed yet? I'm a newbie to open source web dev and since this was a good first bug, I thought of taking it up

**Comment by tofumatt** [comment] 2016-09-17 15:17
This is not fixed yet; feel free to work on the bug and submit a pull request when you have a fix ready.

Please attach before and after screenshots of the fix so we can verify it's working as you intend. Thanks 👍

**Comment by vijeth-aradhya** [comment] 2016-09-18 11:59
I had forked the repository and worked on mine [ 3 commits ]. I have made some changes and uploaded the the images as well.

Link : https://github.com/vijeth-aradhya/addons-server/commit/3376b7f7450c812dc3230e911c946249c84348cd

**Closed** 2016-09-20 10:42 UTC
Labels: maybe good first bug, style refresh, triaged

**Comment by ValentinaPC** [comment] 2016-09-20 12:41
Verified as fixed on AMO-dev FF48.0.2(Win7)
Postfix screenshots: 
![coll1](https://cloud.githubusercontent.com/assets/15685960/18670431/91110198-7f48-11e6-9e40-0d7d16a07f2c.png)
![coll2](https://cloud.githubusercontent.com/assets/15685960/18670432/91136096-7f48-11e6-85a5-5ecfe3927df0.png)
![coll3](https://cloud.githubusercontent.com/assets/15685960/18670433/911737de-7f48-11e6-9313-289a1bd6a0a7.png)
