### ISSUE TITLE
Search by license

### ISSUE THREAD

**Issue by yoasif** [mozilla/addons-server#14068] opened 2020-04-26 21:24 UTC
### Describe the problem and steps to reproduce it:

I'd like to see a dropdown in my filters on my search result pages that let me filter by license type.

### What happened?

There is no filter.

### What did you expect to happen?

Something like 

![image](https://user-images.githubusercontent.com/152493/80320156-b22eed80-87e2-11ea-9612-2e2c1632c2d5.png)

### Anything else we should know?

Discussion here: https://www.reddit.com/r/firefox/comments/g89x5b/dear_mozilla_please_have_an_option_to_prioritize/

**Comment by yoasif** [comment] 2020-04-26 21:27
Refiled to https://github.com/mozilla/addons-frontend/issues/9383

**Comment by bershanskiy** [comment] 2020-04-27 08:12
@yoasif I think server does not support filtering by license. You can see the supported search queries [here](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search). Could you re-open this issue?

I'm not sure what you mean by "and so on" on the UI mock-up. Could you elaborate?

**Comment by yoasif** [comment] 2020-04-27 14:53
> I'm not sure what you mean by "and so on" on the UI mock-up. Could you elaborate?

It isn't my mockup (copied it from reddit), but I would assume that it is all the available licenses on AMO.

**Comment by jvillalobos** [comment] 2020-04-28 22:16
The way we currently store licenses on AMO doesn't lend itself for a very reliable search feature. I also don't think this would be something most of our users would benefit from. The license name is available [through the API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-object), though, so it is possible to implement a custom license-based search from an app or an extension.

**Comment by jvillalobos** [comment] 2020-04-28 22:20
Closing as a dupe of https://github.com/mozilla/addons-frontend/issues/9383

**Closed by jvillalobos** 2020-04-28 22:20 UTC
