### ISSUE TITLE
AMO needs gentler error pages

### ISSUE THREAD

**Issue by Caspy7** [mozilla/addons-server#910] opened 2015-11-12 10:55 UTC
Yesterday there were site outages and I was presented with a plain page that said "Error 503" and that was about it. No formatting or explanation.

We should have gentler pages for our users.
Most larger sites have some sort of custom pages in these instances which are less harsh and more informative.  Let's try and make ours more approachable and informative too.

**Comment by muffinresearch** [comment] 2015-11-12 11:03
@Caspy7 I think this can be covered by #908 - I made a similar suggestion there. Also because the banner in #908 is tricky e.g. if the app is down the only solution is to have something above the app serve a static page to users. Feel free to add this comment to #908 and then this one can be closed.

**Comment by muffinresearch** [comment] 2015-11-12 11:15
Marking as a dupe of #908.

**Comment by muffinresearch** [comment] 2015-11-12 13:51
Here we could use some self-contained static pages served for things like 5xx errors as currently they are blank.

**Comment by muffinresearch** [comment] 2015-11-12 13:52
See also #908 which is related.

**Comment by andymckay** [comment] 2016-05-03 18:05
This hasn't happened since the AWS switch over and is a pretty catastrophic problem that gets ops out of bed. I feel like its not worth investing anything on this with the re-design coming which will have a whole of new error scenarios to worry about.

**Closed by andymckay** 2016-05-03 18:05 UTC
Labels: enhancement
