### ISSUE TITLE
Switch to Terser for JS minification

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13682] opened 2020-03-09 16:48 UTC
This will prevent errors like this one I think:

```
Parse error at /code/src/olympia/../../static/js/debug-all.js:9180,14
              function hue(h) {
              ^
ERROR: In strict mode code, functions can only be declared at top level or immediately within another function.
    at JS_Parse_Error.get (eval at <anonymous> (/deps/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/deps/node_modules/uglify-js/bin/uglifyjs:312:27)
    at run (/deps/node_modules/uglify-js/bin/uglifyjs:255:9)
    at Object.<anonymous> (/deps/node_modules/uglify-js/bin/uglifyjs:173:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
Minifying /code/src/olympia/../../static/js/debug-all.js (using UglifyJS)
Unchanged files skipped for minification: 18
```

But the main benefit is to allow newer JS syntax (and Terser is better maintained that Uglify).

**Comment by willdurand** [comment] 2020-03-10 17:28
This is an error in the `less` (js) library. Since it is only used in debug mode (it seems), I lowered the priority. I don't think we can do much right now.

**Comment by diox** [comment] 2020-03-10 17:36
Maybe we should pin a lower version ? It used to work fine...

**Comment by willdurand** [comment] 2020-03-10 17:44
I can bisect to find what has changed. I am not sure it is the less code and the error is a bit "dumb" because it is still valid js code...

**Comment by eviljeff** [comment] 2020-07-31 09:36
> I am not sure it is the less code 

I can't link to it because it's copied over at build time, but it'd be in /static/js/node_lib/less.js if you look locally.

> and the error is a bit "dumb" because it is still valid js code...

so it _is_ valid to have a function declaration in the middle of another function?  
https://github.com/mishoo/UglifyJS/issues/3286 was closed as not a bug.

**Closed** 2020-07-31 14:24 UTC
Labels: component: code quality, priority: p4, state: pull request ready

**Comment by AlexandraMoga** [comment] 2020-08-06 14:14
@willdurand are we still pushing the Terser upgrade this week or has it been rescheduled for the next milestone? I'm looking at #15193

**Comment by willdurand** [comment] 2020-08-06 14:32
> @willdurand are we still pushing the Terser upgrade this week or has it been rescheduled for the next milestone? I'm looking at #15193

Sorry, next milestone.

**Comment by willdurand** [comment] 2020-08-06 14:32
Ah no, sorry.

**Comment by AlexandraMoga** [comment] 2020-08-06 15:21
Alright, my confusion as well.

In any case, I think I covered the most important parts in Developer Hub, Rev tools and Admin tools and I haven't noticed any JS errors anymore. 

This issue can be marked as verified fixed.
