### ISSUE TITLE
Markup shown in About This Add-on section

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3136] opened 2016-07-20 20:28 UTC
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/firebug/?src=search
2. Notice the About This Add-on section

## observed behavior:
markup is visible for the compatibility info

Prod (https://addons.mozilla.org/en-US/firefox/addon/firebug/?src=search) is fine indicating a regression

## screenshot
<img width="1382" alt="screen shot 2016-07-20 at 1 29 14 pm" src="https://cloud.githubusercontent.com/assets/301317/17001944/095504e8-4e7e-11e6-915f-0c01067c3884.png">

## notes
This is causing our tests to fail - https://webqa-ci.mozilla.com/job/amo.stage.saucelabs/1104/testReport/junit/tests.desktop.test_details_page_against_xml/TestDetailsAgainstXML/test_that_description_text_is_correct/

**Comment by tofumatt** [comment] 2016-07-21 18:03
It appears this was caused by running https://github.com/mozilla-services/svcops/blob/master/services/amo/scripts/update_outgoing_url_in_translations.py#L14 on the servers, when `PurifiedTranslation` should have been used. This explains why `<a>` tags were preserved.

**Comment by tofumatt** [comment] 2016-07-21 18:07
Script was updated and run in -dev; fixed. Closing this now.

**Closed by tofumatt** 2016-07-21 18:07 UTC
Labels: blocks release, in progress, regression

**Comment by madalincm** [comment] 2016-07-22 12:03
Verified as fixed in FF47(Win7) in addons-dev.allizom.org
Postfix screenshot:
![3136fix](https://cloud.githubusercontent.com/assets/15685441/17056654/790c3f9a-501d-11e6-9e0b-874b92b75a65.png)
