### ISSUE TITLE
A 502 is returned when translating a Japanese review

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3575] opened 2016-09-21 15:30 UTC
Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/addon/febe/reviews/690900/
2.Click on "translate" link

Expected results:
The review is correctly translated

Actual results:
A 502 is returned

NOTES:
Not sure about the pattern for this issue , because I found another Japanese reviews which are correctly translated, so I added the exact location of the review in bug description

Please see video for this bug : 
![502](https://cloud.githubusercontent.com/assets/1583842/18717701/67d004a0-8029-11e6-8383-a5a4fca4db6f.gif)

**Comment by muffinresearch** [comment] 2016-09-22 09:10
@vcarciu is this just on stage or prod as well?

**Comment by vcarciu** [comment] 2016-09-22 11:00
I can see this on prod too on page 2 comments : https://addons.mozilla.org/en-US/firefox/addon/febe/reviews/690900/

**Comment by EnTeQuAk** [comment] 2017-01-12 18:42
Closing as duplicate of https://github.com/mozilla/addons-server/issues/3575 - let's follow along there.

**Closed by EnTeQuAk** 2017-01-12 18:42 UTC

**Comment by muffinresearch** [comment] 2017-01-12 19:14
@EnTeQuAk #3575 is this issue - do you have the link to the issue this is a dupe of?

**Comment by EnTeQuAk** [comment] 2017-01-12 19:34
Oops, classic me. It's a dupe of https://github.com/mozilla/addons-server/issues/1583
