### ISSUE TITLE
Add-On submission failure without error message

### ISSUE THREAD

**Issue by elfne** [mozilla/addons-server#4555] opened 2017-02-01 12:00 UTC
I've submitted my add-on, it was validated by all automatic tests but I could not go any further in the submission process. I got stuck on the first validation page: checkbox inputs to select platforms were disabled but the "continue" button was clickable.
![addon2](https://cloud.githubusercontent.com/assets/22885010/22505975/40a3f928-e87e-11e6-996a-efbc6a628b75.png)

When clicking on it, I was redirected on the same submission page (picture) with error message (about the checkbox I could not check...) and this was and endless loop.
![addon](https://cloud.githubusercontent.com/assets/22885010/22505914/0a63776c-e87e-11e6-9eaf-df82b1a3e051.png)

Eventually, I reviewed my manifest.json file and got rid of the "min version" and "max version" fields in the application > gecko part and just left an ID.
It then worked like a charm.
The issue here is I never had error message and passed all validation tests but could not actually complete the add-on submission.

**Comment by diox** [comment] 2017-03-21 11:37
@elfne could you provide the manifest of the add-on causing the problem so we can reproduce the bug again and fix it ?

**Comment by elfne** [comment] 2017-04-10 07:19
Hi,

sorry for this late answer, I was on vacation.
Unfortunately, I don't have a copy of the manifest which caused problem.
Just in case I'll have a look this evening on my personnal laptop but
chances are quite thin...
Regards
Maxime

2017-03-21 12:37 GMT+01:00 Mathieu Pillard <notifications@github.com>:

**Comment by eviljeff** [comment] 2017-09-22 13:01
I think we're going to have to close this if we can't reproduce with the offending manifest.  We can re-open if it's still a problem.

**Closed by eviljeff** 2017-09-22 13:01 UTC
Labels: component: devhub, triaged

**Comment by elfne** [comment] 2017-09-22 13:08
no probs. It's not a problem anymore.
Regards

2017-09-22 15:01 GMT+02:00 Andrew Williamson <notifications@github.com>:

**Comment by ValentinaPC** [comment] 2017-09-25 08:02
I think this one is another thing related to the old https://github.com/mozilla/addons-server/issues/1390 .
