### ISSUE TITLE
[CSP] violation when loading "Firefox for Android" page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1621] opened 2016-02-05 09:31 UTC
Relates to #995 

Steps to reproduce:
1. Load AMO-prod page in a new clean profile - https://addons.mozilla.org/en-US/firefox/ (with web console and security tab opened)
2. Go to "Other Application" menu and select "Firefox fro Android" option 

Expected results:
There are no issues displayed in the console.

Actual results:
There is a CSP violation.

Notes/Issues:
Verified on FF44(Win 7). Issue is only reproducing on AMO-prod.
Please see the csp reporting via network: https://pastebin.mozilla.org/8858714
Screenshot for this issue: 
![2016-02-05_1048](https://cloud.githubusercontent.com/assets/15685960/12842478/ca664a94-cbfb-11e5-81f6-3845fc3c0c8a.png)

**Comment by muffinresearch** [comment] 2016-02-05 09:56
Hmm, I don't seem to be able to reproduce that at all. Following the STRs.

@jasonthomas do you know when this host is used? It doesn't appear to feature in olympia's src at all? If it's something that is going to be used for statics I can easily add it. Are there other hosts that might be used in future too?

**Comment by jasonthomas** [comment] 2016-02-05 14:59
This is our CDN origin and it's unusual that requests are being served from this. There was one reference to it that I saw last week which I thought should have fixed it [1]. I need to take a further look at this.

[1] https://github.com/mozilla/olympia/pull/1549

**Comment by muffinresearch** [comment] 2016-02-08 11:18
@jasonthomas any further thoughts on this? 

Looking on kibana with this query: `blocked-uri:"static.addons.mozilla.net"` we still seem to be getting a bunch of hits to reporting for "static.addons.mozilla.net".

Could the CDN be redirecting to the origin under certain criteria?

It appears to only be for `img-src`, so I'm thinking it might be safest to just add this to the img-src directive to be sure.

**Comment by muffinresearch** [comment] 2016-02-08 11:35
Hmm I found this oddity trawling kibana: https://addons.cdn.mozilla.net/media/img/illustrations/addons-robot.png

For me this is 301'ing to "http://static.addons.mozilla.net:81/static/img/illustrations/addons-robot.png"

Which is not just `static.addons.mozilla.net` but also `http://` not `https://`. You can find this here: https://addons.mozilla.org/en-US/firefox/compatibility_firstrun

**Comment by muffinresearch** [comment] 2016-02-08 11:38
This a similar example page that contains another image redirecting to http / port 81 https://addons.mozilla.org/ja/sunbird

**Comment by muffinresearch** [comment] 2016-02-08 12:37
Fwiw  I've landed a change that added `https:static.addons.mozilla.net` to the CSP config for `img-src`. This is only a band-aid though so leaving this bug open.

**Comment by jasonthomas** [comment] 2016-02-08 15:33
Thanks for investigating, it was very useful.

I was able to find the issue in the nginx configuration and made changes. I will be pushing the changes to prod shortly.

**Comment by jasonthomas** [comment] 2016-02-08 16:16
The nginx fix is now on prod.

We should make sure that we are referencing the correct media path whenever possible. https://addons.cdn.mozilla.net/media/img/illustrations/addons-robot.png is no longer a valid path since we've moved over to using 'collectstatic'. The path should be https://addons.cdn.mozilla.net/static/img/illustrations/addons-robot.png.

**Closed by jasonthomas** 2016-02-08 16:16 UTC

**Comment by ValentinaPC** [comment] 2016-03-15 07:51
Verified as fixed on AMO-prod FF45(Win 7).
Postfix screenshot: 
![2016-03-15_0950](https://cloud.githubusercontent.com/assets/15685960/13770999/6b3c5b24-ea93-11e5-88a7-3bbcd1b86c66.png)
