### ISSUE TITLE
Newly submitted version not in displayed "complete version history", so no way to verify the formatting of its description

### ISSUE THREAD

**Issue by jikamens** [mozilla/addons-server#5646] opened 2017-06-15 17:51 UTC
When I submit a new version of my add-on, it does not show up in the "complete version history" visible to end users until it has been approved. This is new behavior.

As far as I can tell, the only place on the site that the "Version Notes" I enter for the new version are displayed on the site is in the "complete version history." As a result, it's impossible for me to verify that I've formatted the notes correctly, e.g., I haven't put in any bad HTML tags or anything, until the new version is approved.

Previously, when unapproved versions showed up in the complete version history, we could check there immediately after writing version notes to confirm that we looked how we wanted them to. So this is a regression in add-on authors' ability to maintain our add-on listings.

**Comment by jvillalobos** [comment] 2017-06-15 19:00
We stopped showing unreviewed versions on AMO shortly after signing, since it wouldn't be possible to install them easily. You're right that not being able to see the formatted version notes is a bit of a regression, but we're also moving to a different review process where files are published immediately (for add-ons using WebExtensions), so I don't think we'll be doing anything to address this particular issue.

**Closed by jvillalobos** 2017-06-15 19:00 UTC

**Comment by jikamens** [comment] 2017-06-15 19:03
Thunderbird add-ons don't use WebExtensions.

How does "moving to a different review process where files are published immediately (for add-ons using WebExtensions)" solve this problem for Thunderbird add-on authors?

Or is this yet another instance of, "Sorry, Thunderbird add-on authors, we don't care about you anymore. Please go away and stop bothering us"?

**Comment by jvillalobos** [comment] 2017-06-15 20:13
We are talking with the Thunderbird leadership about the future of Thunderbird add-ons. Future feature work on AMO will be focused on add-ons using WebExtensions, so add-ons for Thunderbird and SeaMonkey will need to follow a different path.
