### ISSUE TITLE
Modals can be broken

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2351] opened 2016-04-13 16:03 UTC
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/firefox
2. Go to any add-on details page https://addons.allizom.org/en-US/firefox/addon/tab-notifier/
3. Click the "Report Abuse" link
4. Increase the text field width

Expected results:
There are no display or layout issues.

Actual results:
There are some layout ugly issues.

Notes/Issues:
The issue is also reproducing in "Write a review" window (also the section from themes details), contribution window, etc.
Verified on FF45(Win 7). Issue is reproduced on AMO-stage, dev and prod.
Screenshot for this issue: 
![2016-04-13_1846](https://cloud.githubusercontent.com/assets/15685960/14499906/a88ae7f8-01a8-11e6-818c-6c2cb7f1cc50.png)

**Comment by muffinresearch** [comment] 2016-04-13 16:18
We can probably use something like this:

```css
textarea {
  resize: vertical;
}
```

**Comment by aelawson** [comment] 2016-04-23 23:55
I'd be happy to take this one!

**Comment by tofumatt** [comment] 2016-04-24 09:32
@aelawson Cool, thanks! We can't assign issues to people outside the Mozilla organisation, but feel free to work on this and submit a PR that references this issue number when it's ready. 👍

**Comment by wagnerand** [comment] 2016-07-26 17:50
@aelawson Are you still working on this bug?

**Comment by cosminbadescuSV** [comment] 2016-10-26 15:53
Related to this bug I discovered another issue and that is that the text field can pass under the footer of the webpage.
This issue is reproduced on AMO-stage, dev and prod.
Here is a video:
![textfield](https://cloud.githubusercontent.com/assets/15885467/19733526/ea84bf28-9bac-11e6-9dc9-74fe26301750.gif)

**Comment by caitmuenster** [comment] 2017-02-21 18:22
Hey @aelawson and @cosminbadescuSV -- it looks like neither of you are working on this bug so we're going to go ahead and open it back up for another community member to take on. 

Let us know if you're still interested and would like to be reassigned!

**Comment by jvillalobos** [comment] 2017-02-21 18:24
Mentor @tofumatt

**Comment by harikishen** [comment] 2017-05-12 17:15
i would love to takeup this bug

**Comment by harikishen** [comment] 2017-05-12 17:18
also is the textarea supposed to be resizeable ???

**Comment by muffinresearch** [comment] 2017-05-12 19:23
@harikishen yep - it would be fine to make it not resizable.

**Closed** 2017-05-18 12:27 UTC
Labels: component: legacy frontend, contrib: good first bug, contrib: mentor assigned, priority: enhancement, triaged

**Comment by ValentinaPC** [comment] 2017-05-18 14:33
Verified as fixed for the cases mentioned in this issue, using AMO-dev FF53(Win 7).
Postfix video:
![modals](https://cloud.githubusercontent.com/assets/15685960/26207148/6550b260-3bef-11e7-981f-beb2a203d12a.gif)

There are some other places where maybe we can also apply this fix:
- theme review
- submit collection
- edit collection
![2017-05-18_1732](https://cloud.githubusercontent.com/assets/15685960/26207390/04ec2b92-3bf0-11e7-87d7-3e86016e267a.png)

If no, I'll mark this verified.
Thanks!
