### ISSUE TITLE
as

### ISSUE THREAD

**Issue by alongabay** [mozilla/addons-server#3620] opened 2016-09-27 13:00 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
i cant download it
### What did you expect to happen?
it will download
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment] 2016-09-27 13:03
Hi, please could you provide more details so we can understand what the issue is?

**Comment by EnTeQuAk** [comment] 2016-09-30 07:18
Closing as invalid, if you have more details on the issue please feel free to reopen anytime.

**Closed by EnTeQuAk** 2016-09-30 07:18 UTC
Labels: invalid
