### ISSUE TITLE
Unable to add to some Collections

### ISSUE THREAD

**Issue by MaDonnasPersonas** [mozilla/addons-server#6909] opened 2017-11-13 23:05 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by MaDonnasPersonas** [comment] 2017-11-13 23:07
I have quite a few Collections of my themes and am unable to add themes to some of the Collections. I don't get an error message. The name of the theme I want to add will just not come up. I don't know of any other way of explaining it than this.

**Comment by jvillalobos** [comment] 2017-11-14 17:17
Could you please specify which collection you're trying to add to, and which theme you're trying to add to it? I would like to replicate the steps to try to figure out the problem.

**Comment by MaDonnasPersonas** [comment] 2017-11-14 17:31
I go to My  Collections, choose MaDonnas Animal Collection...Add Ons...hit
the edit (pencil) and try to add African Lion by MaDonna...but it doesn't
show up so I can't add it. It does it on other collections also, holiday,
nature, etc. It has been this way for quite awhile, but before I could
always choose add to collection on the main page where the specific theme
was and just hit add to collection and choose the specific collection.

Hope this makes sense!

MaDonna

**Comment by jvillalobos** [comment] 2017-11-14 20:22
Okay, I tried adding that theme to one of my collections, and the search popup never returned the right result, even when typing the full name. 

Since these are the old pages and are on the way out, I'm closing this as a duplicate of https://github.com/mozilla/addons-frontend/issues/3142. The new pages shouldn't have this problem, I think. It may take a few weeks for them to make it to the live site, though.

**Closed by jvillalobos** 2017-11-14 20:22 UTC

**Comment by MaDonnasPersonas** [comment] 2017-11-14 20:24
Thanks, Jorge. I appreciate it very much.
