### ISSUE TITLE
 Cannot submit a new addon version

### ISSUE THREAD

**Issue by DavidBruant** [mozilla/addons-server#1801] opened 2016-03-01 11:03 UTC
All the relevant information can be found at https://bugzilla.mozilla.org/show_bug.cgi?id=1252394#c0

**Comment by mstriemer** [comment] 2016-03-01 17:41
> I'm trying to submit a new version of my addon [1], but AMO wouldn't let me do so.
> See attachements for xpi and source code .zip that I try to use to submit a new version.
> 
> From what I can see, the upload works (I see data moving from my computer to AMO), but when the upload is finished, I see the following message on my console:
> "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" preload-min.js:3:20118
> 
> I'm using Firefox dev edition 46.0a2 (2016-02-29)

From [1252394#c0](https://bugzilla.mozilla.org/show_bug.cgi?id=1252394#c0).

**Comment by DavidBruant** [comment] 2016-03-01 18:22
I've retried. Same thing.
I had the network panel open. I can see that the POST request to https://addons.mozilla.org/fr/developers/addon/twitter-assistant/versions/add yields a 500 and some HTML page.
I've copy-pasted the page elsewhere and it's indeed the "Oops" page.

**Comment by DavidBruant** [comment] 2016-03-02 11:10
I've had the same problem in Firefox 44 as well as in Chrome so it seems like it's most definitely a server-side issue. The xpi and source .zip can be found at
* xpi https://bugzilla.mozilla.org/attachment.cgi?id=8725161
* sources https://bugzilla.mozilla.org/attachment.cgi?id=8725162

**Comment by mstriemer** [comment] 2016-03-02 21:52
Thanks. I've found a [stack trace](https://sentry.prod.mozaws.net/operations/olympia-prod/group/235686/) in our tracker. Looks like there might be some unrelated bad data or some caching issue. I'll look into it.

**Comment by mstriemer** [comment] 2016-03-02 22:29
I'm getting a 400 with the message: "The submitted file is empty" when I try adding this xpi to an unlisted add-on I created. I don't understand...

Out of curiosity, did you change the versions of Firefox that you support recently?

**Comment by wagnerand** [comment] 2016-03-02 22:35
@mstriemer That is unrelated (https://github.com/mozilla/addons-server/issues/1503) You might want to try in stable or beta.

**Comment by mstriemer** [comment] 2016-03-02 22:41
Thanks, I tried in Chrome and uploading a new version worked.

**Comment by mstriemer** [comment] 2016-03-02 22:53
I looked through the add-on on the devhub and I don't see anything that looks wrong. I'm not really sure how to proceed with this. I'm hoping @diox has some ideas.

**Comment by diox** [comment] 2016-03-03 11:41
Never seen that one before :(

Let's sum up what the sentry trace is telling us:
- It's been happening since Feb 17 (possibly earlier, we don't know if Sentry discarded older events)
- It's happening on multiple addons
- It's always happening inside a specific `@cached_property`, `Version.compatible_apps`. The affected instance is always an `ApplicationsVersions`
- The  `ApplicationsVersions` affected are linked to different `AppVersions`. Not sure if this is relevant information but all of them have a min and a max version, though.
- It's happening because of cache-machine, and the `CachedProperty` class already contains a cache-machine related hack.
- The actual error is a pickle error, when caching the `ApplicationsVersions` instance
- Note that the `__unicode__` for `ApplicationsVersions` is complex and might cause other objects to be loaded. I wonder if we can trust sentry as a result.
- We push on Thursdays so if there weren't any earlier occurrence then it's not push-related. It's definitely not related to the django 1.7 push, which will happen later today - but who knows, it might help fix it.

All that have not helped me find a reproducible test-case yet :( I've been playing with pickle and `ApplicationsVersions` but no luck yet.

**Comment by DavidBruant** [comment] 2016-03-03 16:19
> Out of curiosity, did you change the versions of Firefox that you support recently?

Yes I did. I didn't think it'd matter :-/

I've retried and got the same 500 in the network tab. When I try the xpi without the .zip sources, I get the `The submitted file is empty`.

For bits of history with this addon:
* I submitted a 1.0 and 1.0.1 versions. They were both rejected by AMO review. 
* This rejection left the addon in a weird state were the addon was completely removed from search, even working previous versions.
* I asked for previous versions to be re-enabled which they were.
* I chose to go directly to version 2.0 because of the various changes the addon has gone through (no idea if skipping a version affects the submission, I imagined it didn't).

Not sure whether that helps. In any case, thanks for the investigation. Happy to help finding any solution :-)

> Thanks, I tried in Chrome and uploading a new version worked.

Is this something I can try as well?

**Comment by jvillalobos** [comment] 2016-03-03 16:35
The empty file error is probably #1503. The workaround is to use release or beta to upload the file.

**Comment by DavidBruant** [comment] 2016-03-04 14:48
I've been able to upload the new xpi with release (but no change otherwise). Thanks for the tip!

**Comment by Leoperd87** [comment] 2016-04-15 15:31
Same problem:
preload-min.js?build=97fb6af-570fdecb:3 POST https://addons.mozilla.org/ru/developers/addon/mallonline/versions/add 500 (INTERNAL SERVER ERROR)

**Comment by andymckay** [comment] 2016-04-15 17:33
The last comment is a dupe of #2388, which is resolved, I'm not sure about the rest of this bug though.

**Comment by EnTeQuAk** [comment] 2016-07-05 20:05
I'll add this to the triaged bugs since this looks like it affects multiple add-ons but quite complex so free for someone with enough time to dig deep.

**Comment by EnTeQuAk** [comment] 2016-09-14 04:21
I'm closing this for now, we can't easily reproduce it and the traceback didn't occur again since 6 months now. We upgraded quite a lot of libraries and code since then so with a bit of luck this is actually fixed.

If this happens again to anyone please fee free to re-open anytime.

**Closed by EnTeQuAk** 2016-09-14 04:21 UTC
Labels: triaged
