### ISSUE TITLE
Cannot download old version to compare - Public listing download also fails

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons-server#1167] opened 2016-01-01 18:17 UTC
I'm trying to download the version that is currently available as a public download, but it fails - 

![](http://i.imgur.com/2Znguyp.png)

I had to do this because the "Compare" page is giving me nothing - https://addons.mozilla.org/en-US/firefox/files/compare/380696...290212/

I also tried downloading the Version 1.4.3.1-signed · December 26, 2014  from the public listing - https://addons.mozilla.org/en-US/firefox/addon/email-language-correction-v11/ - but that fails with this:

![](http://i.imgur.com/6d1qa3Q.png)

**Comment by jvillalobos** [comment] 2016-01-04 16:44
The XPI file for 1.4.3.1-signed is 404, so the file was lost, for whatever reason. I suggest you use 1.4.2.1-signed for diffing.

Also, please don't post add-on review history on public sites.

**Comment by Noitidart** [comment] 2016-01-04 18:36
Ah shhot got it, deleted the image from imgur.

Thanks will go ahead with review.

**Comment by EnTeQuAk** [comment] 2016-07-05 21:17
Hmm, I feel like I can't reproduce this so I'm closing for now. Please feel free to reopen anytime if the error occurs again.

**Closed** 2016-07-05 21:20 UTC
Labels: invalid

**Comment by Noitidart** [comment] 2016-07-05 21:21
Thanks will let you know if it happens again. I don't think I encountered this issue since OP.

**Comment by EnTeQuAk** [comment] 2016-07-05 21:32
That's reassuring, thanks a lot!
