### ISSUE TITLE
Redirect loop when downloading file from file-viewer

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11179] opened 2019-04-10 11:29 UTC
STR:

* Open a file in the file-viewer, e.g https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse/253392/
* Click on "download ..." (e.g index.rdf)

Expected:

* The file to be downloaded or presented for download

Result: 

* Redirect loop

This is the redirect loop that is happening when clicking on "Download":

* Redirect to `/en-US/firefox/files/browse/253392/file-serve/install.rdf?token=899c2460-a989-4562-b122-0b04918a9f49` (`reviewers.` domain)
* This now redirects to `https://addons-dev.allizom.org/en-US/firefox/files/browse/253392/file-serve/install.rdf?token=899c2460-a989-4562-b122-0b04918a9f49` (not on `reviewers.` domain)
* That view now redirects to `https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse/253392/file-serve/install.rdf?token=899c2460-a989-4562-b122-0b04918a9f49` (`reviewers.` domain)

And that loop continues.

![Screenshot from 2019-04-10 13-25-35](https://user-images.githubusercontent.com/139033/55875239-e1050200-5b94-11e9-8378-618ec0f7e222.png)

**Comment by EnTeQuAk** [comment] 2019-04-10 11:29
@bqbn @autrilla this sounds like an nginx redirect issue to me. Do you have a moment to look into this and confirm?

**Comment by bqbn** [comment] 2019-04-16 23:09
Has the download ever worked before? Or is it because the `/files/browse/<id>/file-serve/` API started to return X-Accel-Redirect header recently?

I suspect it's the later as the Nginx virtual server for reviewers.a.m.o domain doesn't handle X-Accel-Redirect header.

**Comment by wagnerand** [comment] 2019-04-17 08:45
Yes it worked until recently.

**Comment by bqbn** [comment] 2019-04-23 00:43
When passing `reviewers.addons-dev.allizom.org` Host header to the app, e.g., by running

```
curl https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse/253392/
```

the app returns the following X-Accel-Redirect header, 

```
X-Accel-Redirect: /mnt/efs/addons-dev.allizom.org/shared_storage/tmp/file_viewer/0423/253392/install.rdf
```

Question is, shouldn't the domain part of the value be **reviewers.addons-dev.allizom.org**, instead of "addons-dev.allizom.org"?

We can configure Nginx to work around it, but if the app can return the proper path for X-Accel-Redirect, that'd be better, so that we don't have to add a "hack" to work around it.

@EnTeQuAk any thoughts on this?

**Comment by diox** [comment] 2019-04-23 08:26
@bqbn addons-server does not generate this path using the site URL, it uses the `NETAPP_STORAGE_ROOT` environment variable.

**Comment by bqbn** [comment] 2019-04-24 02:34
That is new to me. Thx @diox.

The nginx fix for this issue is deployed to -dev and -stage. Please test it and once verified, we can deploy it to -prod.

**Comment by wagnerand** [comment] 2019-04-24 09:31
I can confirm that it works on -dev and stage now.

**Comment by AlexandraMoga** [comment] 2019-04-24 10:06
Works for me too. 
Just one observation: when clicking on download, you are not actually prompted to download the selected file. The file contents are opened inside the the browser. I don't remember if this was the case before. You can, however, save a file locally by right clicking on the download link. 

![2019-04-24_12-58-42](https://user-images.githubusercontent.com/31961530/56651481-cac96c80-6691-11e9-928c-61ec4b473412.gif)

**Comment by wagnerand** [comment] 2019-04-24 10:25
>  Just one observation: when clicking on download, you are not actually prompted to download the selected file. The file contents are opened inside the the browser. I don't remember if this was the case before. You can, however, save a file locally by right clicking on the download link.

Yes, it has been like that before.

**Comment by bqbn** [comment] 2019-04-25 16:52
This fix is deployed to -prod. Please test it.

**Comment by wagnerand** [comment] 2019-04-25 16:55
I verified that it works on prod. Thank you for fixing it!

**Closed** 2019-04-25 16:55 UTC
Labels: component: reviewer tools, priority: p3, state: verified fixed, triaged
