### ISSUE TITLE
Appeals sent by a user after being reported didn't land in Cinder 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21949] opened 2024-02-28 15:22 UTC
I could no longer reproduce this issue but I remember testing with rusiczki.ioana+new1@gmail.com in -stage and -dev

-> currently appeals are sent https://stage.cinder.nonprod.webservices.mozgcp.net/job/20cb683b-c7f5-459f-88c7-987429a93051

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-741)

**Comment by eviljeff** [comment] 2024-03-01 11:50
I'm going to close this if it can't be reproduced.  Please reopen/re-file if it happens again.

**Comment by diox** [comment] 2024-03-11 14:34
https://mozilla.sentry.io/issues/5019438966/

**Comment by diox** [comment] 2024-03-11 14:41
There is a flaw in the logic around banned users appeals (which are a bit tricky because when the user is appealing, they are anonymous, since they can't log in anymore). I'll fix it.

**Comment by eviljeff** [comment] 2024-03-11 14:42
> Scenario was simple, user is reported , banned with a [Cinder decision](https://stage.cinder.nonprod.webservices.mozgcp.net/job/2ef80abc-a3fb-42dd-8abb-8bf92dd363bd) then the reported sends an appeal.

@ioanarusiczki To confirm, a user is banned, and then the _reporter_ appeals?  (That shouldn't be possible)

**Comment by diox** [comment] 2024-03-11 14:52
Yeah, reporte**d** not reporte**r**. We should avoid using `reported` when describing behavior as it can be confusing. We tend to use `author` internally, even if that's not entirely satisfying either in the case of users themselves (I guess you can view it as them being the author of their own profile)

**Closed** 2024-03-11 16:56 UTC
Labels: component:abuse_reports

**Comment by ioanarusiczki** [comment] 2024-03-12 13:18
Verified on -dev.

I think initially `reported user` crossed my mind but I went with `reported`, I'm sorry if I created confusion.

**Comment by KevinMind** [comment] 2024-05-04 20:25
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-741
