### ISSUE TITLE
Cannot sort addons from Preliminary Reviews queue by waiting time for romanian editor tools

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1388] opened 2016-01-14 15:42 UTC
Prerequisites:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

Steps to reproduce:
1.Go to https://addons.allizom.org/ro/editors/queue/preliminary
2.Try to sort addons by waiting time (https://addons.allizom.org/ro/editors/queue/preliminary?sort=waiting_time_min)

Expected results:
Addons are sorted by waiting time

Actual results:
"Oops..." page is displayed

NOTES:
This is not reproducible for en-US : https://addons.allizom.org/en-US/editors/queue/preliminary?sort=waiting_time_min

**Comment by eviljeff** [comment] 2016-02-23 12:33
wfm.  can you still reproduce?

**Comment by EnTeQuAk** [comment] 2016-07-05 21:26
![screen shot 2016-07-05 at 23 25 34](https://cloud.githubusercontent.com/assets/139033/16600539/de858e44-4307-11e6-8623-68002de1d4b6.png)

Works for me, closing for now. Please feel free to reopen if this occurs again.

**Closed by EnTeQuAk** 2016-07-05 21:26 UTC
