### ISSUE TITLE
"Delete Theme" button color gets angry-red after "Transfer Ownership" duble-action

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2516] opened 2016-04-27 14:34 UTC
Steps to reproduce:
1. Sign int to AMO-stage https://addons.allizom.org/en-US/firefox/
2. Load any theme edit listing page i.e https://addons.allizom.org/en-US/developers/theme/tiny-creatures-come-moreover/edit
3. Observe the color of the "Delete Theme" button
4. Click "Transfer Ownership" button 2 times 
5. Repeat step 3 

Expected results:
The delete button has the same color.

Actual results:
The color of the delete button is changing from blue to red.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and AMO-dev,
Screencast for this issue: 
![delete theme button](https://cloud.githubusercontent.com/assets/15685960/14855773/1057abbe-0c9e-11e6-8703-be81357efa12.gif)

**Comment by tsl143** [comment] 2016-05-07 11:50
How to start with this ? I get following error
![screenshot from 2016-05-07 17 20 01](https://cloud.githubusercontent.com/assets/5318732/15091934/f70e48b6-1477-11e6-9817-2c850ca2a041.png)

**Comment by tsl143** [comment] 2016-05-10 01:33
@muffinresearch , how to start with this?

**Comment by muffinresearch** [comment] 2016-06-28 17:53
@tsl143 first step would be to try and reproduce it locally by adding a theme on your local install.

**Comment by jvillalobos** [comment] 2016-07-26 17:52
@tsl143 where you able to progress on this? Do you want this issue assigned to you?

**Comment by wagnerand** [comment] 2017-02-21 18:37
@muffinresearch are you ok with mentoring this?

**Comment by wagnerand** [comment] 2017-03-28 16:44
Mentor: @muffinresearch 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by psionikangel** [comment] 2017-04-26 20:28
Hello @muffinresearch and others,

I have prepared a fix for this issue here: https://github.com/psionikangel/addons-server/commit/0bb0bbd92ca84162268433fd578a094998697884

This is a gif showing the fixed behavior in my development environment:

![delete-button-fix](https://cloud.githubusercontent.com/assets/547413/25455291/476a9c88-2a9d-11e7-9685-9b0ab84d454a.gif)

Could you review this when you have a little bit of free time?

Regards,

**Comment by VishalCR7** [comment] 2018-01-12 18:31
@caitmuenster is this issue still open?   I tried reproducing it and it worked exactly like this 
![image](https://user-images.githubusercontent.com/24241258/34889625-b227a85c-f7f4-11e7-929a-b7586942c22b.png)
May be I can revert the color back to angry-red so that it can match with UI/UX

**Comment by muffinresearch** [comment] 2018-02-02 16:02
Looks like this is no-longer an issue. Closing for verification.

**Closed by muffinresearch** 2018-02-02 16:02 UTC
Labels: component: devhub, contrib: good first bug, contrib: mentor assigned, project: style refresh, triaged

**Comment by AlexandraMoga** [comment] 2018-02-05 06:49
Verifed as fixed on AMO dev FF58 (Win10)

![image](https://user-images.githubusercontent.com/31961530/35791590-7f84b402-0a51-11e8-972d-18668e435ea9.png)
