### ISSUE TITLE
Different results after refresh in search API response for relevance

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3571] opened 2016-09-21 13:34 UTC
Steps to reproduce:
1. Make a blank search in AMO-stage https://addons.allizom.org/en-US/firefox/search/?q=&appver=48.0&platform=windows
2. Sort results by "Up & Coming" option 
3. Refresh the page

Expected results:
Same results are displayed.

Actual results:
Different results are displayed.

Notes/Issues:
Verified on FF48.0.2(Win 7). Issue is reproducing on AMO-stage and dev.
Video for this issue: 
![up coming](https://cloud.githubusercontent.com/assets/15685960/18712943/4b93b0a8-8019-11e6-8b4f-8e1423c8c40b.gif)

**Comment by SVSanta** [comment] 2017-06-07 14:24
Issue also reproducible sorting by "Relevance".
Videos for the issue:
![not the same results](https://user-images.githubusercontent.com/28138132/26883455-ece48ea2-4ba5-11e7-9e4a-1224044849a9.gif)

**Comment by EnTeQuAk** [comment] 2018-01-17 16:54
Actually closing this issue since I can no longer reproduce this, neither on -dev nor -stage nor -prod.

Please feel free to reopen at any time though.

**Comment by EnTeQuAk** [comment] 2018-01-24 15:51
Ah, now I can reproduce this. Alrighty, then it's really not fixed. I hope that #7303 fixes this magically but I somehow doubt that.

This might actually be a case where requests are queued to different servers / shards over time and return different results.

**Comment by diox** [comment] 2018-05-25 11:22
@AlexandraMoga can you still reproduce this?

**Comment by AlexandraMoga** [comment] 2018-05-25 11:59
@diox  yes, I can still reproduce the issue with both links:
https://addons-dev.allizom.org/en-US/firefox/search/?sort=relevance
https://addons-dev.allizom.org/en-US/firefox/search/?sort=hotness

Note that `relevance` needs to appear as a sort query in the URL, in order to reproduce the issue. Also, when comparing search results between `relevance` and `hotness`, there doesn't seem to be much of a difference.

**Comment by diox** [comment] 2018-05-25 13:37
Ah, but there is. If the frontend is changing the parameters on its own then yes the results will be different... can you open up a new issue on addons-frontend and link this one? I'm not entirely sure the API side is fixed, but let's at least make the frontend consistent before chasing any server side bugs down...

**Comment by diox** [comment] 2018-05-25 14:03
Err I misread, thought the URL was changing without user interaction from `?sort=relevance` to `?sort=hotness`. If that's not the case then yeah, sorry, no frontend issue to see here :)

**Comment by AlexandraMoga** [comment] 2018-05-25 14:05
Yes, it was always a matter of user interfering with the sort options. Sorry if it wasn't clear in the server bug. I guess this can be closed then.

**Comment by diox** [comment] 2019-09-04 13:14
Closing since #9771 is fixed and #7088 tracks the hotness issue.

**Closed by diox** 2019-09-04 13:14 UTC
Labels: component: api, component: search, priority: p4, triaged
