### ISSUE TITLE
Hovering over an incompatible add-on changes the size of description panel to other add-ons

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2403] opened 2016-04-15 13:05 UTC
Steps to reproduce:

1.Open this firefox add-ons page: https://addons-dev.allizom.org/en-US/firefox/extensions/feeds-news-blogging/?sort=users
3.After the page is loaded scroll down to an add-on that is not available for current version of FF.
4.Hover over the add-on and observe behavior of the other add-ons.

Expected results:
Hover does not change the size of description panel from other add-ons.

Actual results:
Hover changes the size of description panel from other add-ons.

Note/Issues:
Verified on FF45(Win 7). This issue is reproducing in AMO-dev.
Video of this issue:http://screencast.com/t/yvF6scM8H

**Comment by muffinresearch** [comment] 2016-04-15 14:21
Duplicate of #2366

**Closed by muffinresearch** 2016-04-15 14:21 UTC
Labels: style refresh
