### ISSUE TITLE
Pano type images (larger in size and wider) have display issues after upload in dev hub

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8404] opened 2018-05-31 14:15 UTC
STR:
1. Load AMO stage and for a submitted add-on upload as screenshots some images but make sure they are above 3MB in size and wide (as in the attachment)
2.Click the Save Changes and observe the screen

Expected result:
Images are uploaded and displayed.

Actual result:
Images are displayed in continuous loading state for a while and then blank.

Notes:
This issue is intermittent but most of the times reproducible on AMO dev and AMO stage with FF60(Win10).
It is not reproducible on the new frontend in the Screenshot section.
Refreshing page will display the content.

![wider images](https://user-images.githubusercontent.com/33448286/40787087-6aca9a5a-64f5-11e8-8f6e-38d299026187.gif)

These are the samples I used
[cele 2 mai wide.zip](https://github.com/mozilla/addons-server/files/2058546/cele.2.mai.wide.zip)

**Comment by EnTeQuAk** [comment] 2018-07-26 14:23
Duplicate of #8977

**Closed by EnTeQuAk** 2018-07-26 14:23 UTC
Labels: component: devhub
