### ISSUE TITLE
504 errors received when accessing various pages on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9363] opened 2018-09-06 10:06 UTC
Prerequisites: the best way to reproduce this is by clearing your browser cache and than loading AMO stage
Possibly related issue: https://github.com/mozilla/addons-frontend/issues/5825

STR:
1. Open Firefox
2. Clear your browser cache
3. Open your web console - network Tab
4. Load AMO stage - https://addons.allizom.org/en-US/firefox/
5. Check responses in the Network tab

Actual result:
A 504 error is generated for various elements in the page (I've received one for an add-on icon)

Expected result:
No errors are generated

Notes:
- Dev Hub landing page - https://addons.allizom.org/en-US/developers/ - will also generate several 504 errors
- the `.css` was not loaded at all times on the frontend and in dev hub
- AMO -dev doesn't seem affected
- reproduced on AMO stage with FF62, Win10x64

@willdurand also observed the following error in the console:
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons-amo-cdn.allizom.org/amo-2cdcb679693bcba4425e233fc936f40b.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)."

![image](https://user-images.githubusercontent.com/31961530/45150936-a8074800-b1d5-11e8-83a4-8c2f3bbd8afe.png)

![image](https://user-images.githubusercontent.com/31961530/45150956-b2c1dd00-b1d5-11e8-9458-7ff3f85d4b9b.png)

**Comment by bqbn** [comment] 2018-09-06 16:28
I noticed the 504 is intermittent, and saw from the nginx access logs that, only one out of two nginx returns 504 for the asset files. 

I restarted both Nginx processes and now this issue is not reproducible for me on -stage.

Please check and see if that fixes for you or not.

**Comment by eviljeff** [comment] 2018-09-06 16:53
we can't replicate this now after @bqbn's restarts so calling this fixed.

**Comment by vcarciu** [comment] 2018-09-06 16:54
Verified as fixed in Stage

**Closed by eviljeff** 2018-09-06 16:53 UTC
Labels: priority: p1

**Comment by eviljeff** [comment] 2018-09-07 13:01
#9379 is maybe the same issue today

**Comment by bqbn** [comment] 2018-09-07 18:09
I can't reproduce #9379 on -stage.

I also checked Nginx logs, and there were no 50x errors when I accessed the website on -stage.

There is a message in the browser console that says 

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).`

but the website loads fine for me.
