### ISSUE TITLE
cannot upload new version

### ISSUE THREAD

**Issue by blackzhen** [mozilla/addons-server#10949] opened 2019-03-18 06:37 UTC
### Describe the problem and steps to reproduce it:
 When I upload a new version.  Your add-on failed validation with 1 error.

### What happened?
An empty response was received from the server;Status: 504
### What did you expect to happen?
I want to be able to upload new versions
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
 the extension named CNKI E-Study from google .
The version is v4.0.0.10

**Comment by blackzhen** [comment] 2019-03-19 11:17
Today ,I try again. It returns     Received an empty response from the server; status: 500

**Comment by diox** [comment] 2019-03-19 11:52
Were you upload a `.crx` file directly ?

**Comment by blackzhen** [comment] 2019-03-19 23:43
yes,I upload a .crx file. 
https://addons.mozilla.org/zh-CN/developers/addon/submit/upload-unlisted.

**Comment by blackzhen** [comment] 2019-03-19 23:50
And I did Extension Compatibility Test for Firefox on https://www.extensiontest.com/test/f229a0c0-4a34-11e9-90ce-271606e2142a.
It returns 'Great news! Your extension is compatible with Firefox.'

**Comment by diox** [comment] 2019-03-20 00:04
Ah, sorry, `.crx` uploads are currently broken - but good news, I already reported and fixed that issue in https://github.com/mozilla/addons-server/issues/10936, and it will go into production this Thursday around noon Pacific Time.

Closing as duplicate of #10936.

**Closed by diox** 2019-03-20 00:04 UTC

**Comment by blackzhen** [comment] 2019-03-20 00:21
Thank you very much. I'm looking forward to it
