### ISSUE TITLE
Received an empty response from the server; status: 504 after upload a new version

### ISSUE THREAD

**Issue by magicp-github** [mozilla/addons-server#7292] opened 2018-01-14 07:30 UTC
I meet the following error after upload a new version.
![server-error-504](https://user-images.githubusercontent.com/13914314/34913627-dcd539fa-f945-11e7-8279-070de3b2b65d.PNG)

See also: https://github.com/mozilla/addons-server/issues/1519

**Expected results:**
Submit a new version successfully without error.

**Comment by diox** [comment] 2018-01-15 12:41
Can you give more details ? Which add-on/user did the error occur with ? Can you attach the .zip/.xpi maybe ?

**Comment by magicp-github** [comment] 2018-01-20 21:37
**Steps to reproduce:**
1. Go to https://addons.mozilla.org/en-US/developers/addons
2. Click "New Version"
3. Click "Select a file..." button and select a xpi file (Please find the attached file)
4. Uploading...

**Another steps:**
1. Go to https://addons.mozilla.org/en-US/developers/addon/validate
2. Click "Select a file..." button and select a xpi file
3. Uploading...


**Actual results:**
After 100% complete, the following error occur and cannot next step.

Your add-on failed validation with 1 error. Received an empty response from the server; status: 504


**Expected results:**
Cannot upload legacy addon from this year? If not, works fine without error.

**Upload file**  (renamed extension from .xpi to .zip because cannot attach by validation)
[Qute5pp@magicp.jp.zip](https://github.com/mozilla/addons-server/files/1649286/Qute5pp.magicp.jp.zip)

**Comment by magicp-github** [comment] 2018-01-26 13:03
See also: https://github.com/mozilla/addons/issues/622

**Comment by diox** [comment] 2018-01-30 11:34
Closing as duplicate of https://github.com/mozilla/addons/issues/622

**Closed** 2018-01-31 06:14 UTC
