### ISSUE TITLE
AMO embedded links (support site url, eg) are incorrectly mangled upon redirect

### ISSUE THREAD

**Issue by alta88** [mozilla/addons-server#3336] opened 2016-08-24 20:18 UTC
My addon, at https://addons.mozilla.org/en-US/thunderbird/addon/totalquickfilter/, has a support link to:
http://forums.mozillazine.org/viewtopic.php?f=48&t=2626433
but is redirected to:
1. an https url, which is invalid for mozillazine
2. replaces & with url encoded &amp; which is also invalid

Please check, thanks.

**Comment by andymckay** [comment] 2016-08-24 22:41
Dupe of mozilla/addons#146

**Closed** 2016-08-24 22:42 UTC
