### ISSUE TITLE
Unable to run locally 

### ISSUE THREAD

**Issue by Patil2099** [mozilla/addons-server#12015] opened 2019-08-03 06:05 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
When I run docker-compose exec web make initialize
It throws a lot of errors and I am unable to access the server.
{"Timestamp": 1564811299589151488, "Type": "z.devhub.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@None] Resizing preview and storing size: /code/src/olympia/../../storage/shared_storage/uploads/previews/thumbs/0/29.png"}}
{"Timestamp": 1564811299591428608, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IHDR' 16 13"}}
{"Timestamp": 1564811299591940608, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IDAT' 41 1412"}}
{"Timestamp": 1564811299641028096, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Optimizing image: /code/src/olympia/../../storage/shared_storage/uploads/previews/thumbs/0/29.png"}}
{"Timestamp": 1564811299736376064, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Image optimization completed for: /code/src/olympia/../../storage/shared_storage/uploads/previews/thumbs/0/29.png"}}
{"Timestamp": 1564811299739791616, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IHDR' 16 13"}}
{"Timestamp": 1564811299740713472, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IDAT' 41 1412"}}
{"Timestamp": 1564811299765852160, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Optimizing image: /code/src/olympia/../../storage/shared_storage/uploads/previews/full/0/29.png"}}
{"Timestamp": 1564811299866160384, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Image optimization completed for: /code/src/olympia/../../storage/shared_storage/uploads/previews/full/0/29.png"}}
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7fc90d9db0f0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/usr/local/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/code/storage/shared_storage/tmp/tmphhtdgeip'
{"Timestamp": 1564811300701430016, "Type": "z.amo.activity", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 4, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Activity log called with no user: 27"}}
{"Timestamp": 1564811301146786816, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811301443514624, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811301768745472, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811302068508416, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811302312888320, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811302868616704, "Type": "z.addons", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": 
"", "msg": "Changing add-on status [40]: 4 => 0 (no listed version with valid file)."}}
{"Timestamp": 1564811302931459072, "Type": "z.amo.activity", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 4, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Activity log called with no user: 12"}}
{"Timestamp": 1564811303247378432, "Type": "z.addons", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": 
"", "msg": "Version changed from current: None to 1.3 for addon 40: Delicious Sandwich"}}
{"Timestamp": 1564811303438206208, "Type": "z.users", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Not changing 10969.is_public from True"}}
{"Timestamp": 1564811303855694080, "Type": "z.devhub.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@None] Resizing preview and storing size: /code/src/olympia/../../storage/shared_storage/uploads/previews/thumbs/0/30.png"}}
{"Timestamp": 1564811303857729536, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IHDR' 16 13"}}
{"Timestamp": 1564811303858266880, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IDAT' 41 1410"}}
{"Timestamp": 1564811303886069504, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Optimizing image: /code/src/olympia/../../storage/shared_storage/uploads/previews/thumbs/0/30.png"}}
{"Timestamp": 1564811303998443008, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Image optimization completed for: /code/src/olympia/../../storage/shared_storage/uploads/previews/thumbs/0/30.png"}}
{"Timestamp": 1564811304003087872, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IHDR' 16 13"}}
{"Timestamp": 1564811304003958784, "Type": "PIL.PngImagePlugin", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1611, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "STREAM b'IDAT' 41 1410"}}
{"Timestamp": 1564811304029976320, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Optimizing image: /code/src/olympia/../../storage/shared_storage/uploads/previews/full/0/30.png"}}
{"Timestamp": 1564811304123580928, "Type": "z.amo", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Image optimization completed for: /code/src/olympia/../../storage/shared_storage/uploads/previews/full/0/30.png"}}
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7fc90d9ce7b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/usr/local/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/code/storage/shared_storage/tmp/tmppqcgzg7p'
{"Timestamp": 1564811304968480512, "Type": "z.amo.activity", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 4, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Activity log called with no user: 27"}}
{"Timestamp": 1564811305209572864, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811305624658688, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811305846548480, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811306113279488, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
{"Timestamp": 1564811306302307840, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1611, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[1@50/m] Updating review denorms."}}
# These add-ons are specifically useful for the addons-frontend
# homepage. You may have to re-run this, in case the data there
# changes.
python3 manage.py generate_default_addons_for_frontend
/code/settings.py:147: UserWarning: Could not import local_settings module. Traceback (most recent call last):
  File "/code/settings.py", line 141, in <module>
    from local_settings import *  # noqa
ModuleNotFoundError: No module named 'local_settings'

  traceback.format_exc()))
{"Timestamp": 1564811310079662336, "Type": "raven.contrib.django.client.DjangoClient", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1671, "Fields": {"uid": 
"", "remoteAddressChain": "", "msg": "Configuring Raven for host: None"}}
{"Timestamp": 1564811310080061440, "Type": "raven.contrib.django.client.DjangoClient", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1671, "Fields": {"uid": 
"", "remoteAddressChain": "", "msg": "Raven is not configured (logging is disabled). Please see the documentation for more information."}}
{"Timestamp": 1564811310192862208, "Type": "raven.base.Client", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 7, "Pid": 1671, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "Configuring Raven for host: None"}}
{"Timestamp": 1564811310193219584, "Type": "raven.base.Client", "Logger": "http_app_addons", "Hostname": "fd02bf9da1a8", "EnvVersion": "2.0", "Severity": 6, "Pid": 1671, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "Raven is not configured (logging is disabled). Please see the documentation for more information."}}
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W003) debug_toolbar.middleware.DebugToolbarMiddleware occurs before django.middleware.gzip.GZipMiddleware in MIDDLEWARE.
        HINT: Move debug_toolbar.middleware.DebugToolbarMiddleware to after django.middleware.gzip.GZipMiddleware in MIDDLEWARE.
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/landfill/management/commands/generate_default_addons_for_frontend.py", line 80, in handle
    serializer = GenerateAddonsSerializer()
  File "/code/src/olympia/landfill/serializers.py", line 52, in __init__
    self.fxa_id = self._create_fxa_user()
  File "/code/src/olympia/landfill/serializers.py", line 63, in _create_fxa_user
    fxa_account.password)
  File "/usr/local/lib/python3.6/site-packages/fxa/core.py", line 64, in create_account
    resp = self.apiclient.post(url, body)
  File "/usr/local/lib/python3.6/site-packages/fxa/_utils.py", line 335, in post
    return self.request("POST", url, json, **kwds)
  File "/usr/local/lib/python3.6/site-packages/fxa/_utils.py", line 267, in request
    raise fxa.errors.OutOfProtocolError(msg.format(content_type))
fxa.errors.OutOfProtocolError: API responded with non-json content-type: text/html
Makefile-docker:88: recipe for target 'populate_data' failed
make: *** [populate_data] Error 1
### What did you expect to happen?
It throws a lot more errors 
### Anything else we should know?
Can I know how to access the server? Whenever I access the server the Css are not loaded and nothing works

**Comment by EnTeQuAk** [comment] 2019-08-05 07:18
The Firefox accounts integration for local development is currently broken on the fxa-side, that's what the error is about.

afaik @b4jand is aware and looking into it, I'm not sure what the current status of it is.

Benny, is there already a tracking issue maybe I'm bugzilla?

**Comment by jrbenny35** [comment] 2019-08-05 15:10
We just filed an issue here: https://github.com/mozilla/fxa/issues/2074

Could be a good idea to put a ```try/except``` block around the installation addons, but not quite sure as fxa has been fine for a while now.

**Comment by jrbenny35** [comment] 2019-08-05 15:13
@Patil2099 you probably don't need to run the setup for ui-testing locally. You could get rid of this line in this file: https://github.com/mozilla/addons-server/blob/master/Makefile-docker#L97 until the problem is resolved.

**Comment by EnTeQuAk** [comment] 2019-08-06 06:43
The login should be fixed now: https://github.com/mozilla/fxa/issues/2074

**Comment by EnTeQuAk** [comment] 2019-08-06 06:44
> Could be a good idea to put a try/except block around the installation addons, but not quite sure as fxa has been fine for a while now.

Unsure, you won't be able to login too, so there's various things not working for local development in case of fxa being down.

**Closed by EnTeQuAk** 2019-08-06 06:43 UTC
