### ISSUE TITLE
Missing search result

### ISSUE THREAD

**Issue by robsmith11** [mozilla/addons-server#10211] opened 2018-12-13 10:06 UTC
It seems impossible to find this addon with the search bar on addons.mozilla.org:

https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix/

I've tried several combinations of "video background play fix" and none of them will find it.  If I search with Google, I am able to find it easily.

**Comment by EnTeQuAk** [comment] 2018-12-13 10:13
Interesting, I can't reproduce that to be honest.

![screenshot from 2018-12-13 11-08-00](https://user-images.githubusercontent.com/139033/49931564-6fa79200-fec7-11e8-9cd8-312391425d88.png)
![screenshot from 2018-12-13 11-07-44](https://user-images.githubusercontent.com/139033/49931565-6fa79200-fec7-11e8-85a0-fac663fd8b90.png)

What system and firefox version do you use?

**Comment by robsmith11** [comment] 2018-12-13 10:34
Ah.. if I enable "Request Desktop Site", it is then included the in the search results.

I'm using Android 8.1 and Firefox 64b15.  It's strange that it doesn't show up for mobile.. the addon is designed for mobile browsers.

**Comment by diox** [comment] 2018-12-13 12:31
It's not marked as compatible with Firefox for Android, only Firefox Desktop. If it is indeed compatible with Firefox for Android, you should ask its developer to mark it as such (it's possible to do that through the developer hub, when editing the current version properties).

**Closed by diox** 2018-12-13 12:31 UTC

**Comment by robsmith11** [comment] 2018-12-13 13:41
Ok, thanks.  I would expect to be able to search for all plugins though, not just ones marked as compatible with my user agent.  Maybe make the option to filter based on operating system explicit.
