### ISSUE TITLE
Add error::BytesWarning to pytest filterwarnings

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10471] opened 2019-01-21 10:37 UTC
To issue warnings about `str(bytes_instance)` and `str(bytearray_instance)` as well as bytes/str comparisons we need to add `error:BytesWarning` to our `filterwarnings` settings in `setup.cfg`

That'll help make sure to catch those nifty little edge-cases.

**Comment by eviljeff** [comment] 2019-02-07 15:32
#10622 is passing, apart from the ES based tests. But I'm not sure the ES fails are fixable.  This is a sample error:
```
____________ ERROR at setup of TestAddonIndexerWithES.test_mapping _____________
src/olympia/amo/tests/__init__.py:878: in setUpClass
    super(ESTestCase, cls).setUpClass()
.tox/es/lib/python3.6/site-packages/django/test/testcases.py:1042: in setUpClass
    cls.setUpTestData()
src/olympia/amo/tests/__init__.py:883: in setUpTestData
    setup_es_test_data(cls.es)
src/olympia/amo/tests/__init__.py:97: in setup_es_test_data
    es.cluster.health()
.tox/es/lib/python3.6/site-packages/elasticsearch/client/utils.py:73: in _wrapped
    return func(*args, params=params, **kwargs)
.tox/es/lib/python3.6/site-packages/elasticsearch/client/cluster.py:33: in health
    'health', index), params=params)
.tox/es/lib/python3.6/site-packages/elasticsearch/client/utils.py:47: in _make_path
    quote_plus(_escape(p), b',*') for p in parts if p not in SKIP_IN_PATH)
.tox/es/lib/python3.6/site-packages/elasticsearch/client/utils.py:47: in <genexpr>
    quote_plus(_escape(p), b',*') for p in parts if p not in SKIP_IN_PATH)
E   BytesWarning: Comparison between bytes and string (it looks like ES is not running, try starting it or don't run ES tests: make test_no_es)
```
Which is from https://github.com/elastic/elasticsearch-py/blob/5.5.x/elasticsearch/client/utils.py#L47 - `SKIP_IN_PATH` is [defined](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L9) as `(None, '', b'', [], ())` - its a tuple of mixed binary and unicode strings so the generator will _always_ fail, regardless of whether `parts` contains binary or unicode strings.

**Comment by eviljeff** [comment] 2019-02-07 15:34
We could just not run the `es` job with `-bb`, I suppose.

**Comment by eviljeff** [comment] 2019-02-11 08:06
https://github.com/mozilla/addons-server/pull/10622#issuecomment-461866054 this isn't working on Travis after all, so there's an unknown number of failing tests, caused by an unknown number of potentially buggy lines of code and/or 3rd packages.

**Comment by eviljeff** [comment] 2019-02-11 18:19
See #10622 for more details, but closing this because it's not working on Travis, making it pretty useless.

**Closed by eviljeff** 2019-02-11 18:19 UTC
Labels: component: code quality, priority: p3, triaged
