### ISSUE TITLE
[RTL] layout is broken in theme detail page

### ISSUE THREAD

**Issue by atiqueahmedziad** [mozilla/addons-server#3537] opened 2016-09-16 13:50 UTC
### Describe the problem and steps to reproduce it:
1. Go to any theme detail page (https://addons-dev.allizom.org/en-US/firefox/addon/mikink/)

### Actual Result
Buttons are messed up and layout is not in correct way.
![before](https://cloud.githubusercontent.com/assets/8364578/18588061/bd094e9a-7c46-11e6-8938-babaa80c9695.png)
![actual](https://cloud.githubusercontent.com/assets/8364578/18588097/de511e98-7c46-11e6-91e0-7c05021ac61a.png)

### Expected Result
There should not be any layout problem issue in theme detail page.
![after](https://cloud.githubusercontent.com/assets/8364578/18588064/bfef72a6-7c46-11e6-996f-06fc285d5f58.png)
![expected](https://cloud.githubusercontent.com/assets/8364578/18588224/62e84d98-7c47-11e6-9bba-4f6afc316b77.png)

**Comment by muffinresearch** [comment] 2016-09-16 14:06
Duplicate of #3528

**Comment by muffinresearch** [comment] 2016-09-16 14:31
Oops, I jumped the gun on this one, it's not related to #3537 as it appears with JS off too.

**Closed** 2016-09-20 10:44 UTC

**Comment by ValentinaPC** [comment] 2016-09-20 12:23
Verified as fixed on AMO-dev FF48.0.2(Win 7)
Postfix screenshot:
![theme_details](https://cloud.githubusercontent.com/assets/15685960/18669961/24e0bf9c-7f46-11e6-80f2-b4cffcc8e5a8.png)
