### ISSUE TITLE
Firefox Source Code 504 error

### ISSUE THREAD

**Issue by MachopCodes** [mozilla/addons-server#18623] opened 2022-01-14 19:25 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I was submitting an extension that required source code

### What happened?

When I submitted the source code I received a 504 Error

```
504 ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: VWZLK5MsPmbcvg94SI5FhLQ2KRqo9yzFvwhoo0k2mfE4m0QUEhSc7Q==

```

### What did you expect to happen?

I expected the source code to be submitted successfully
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment] 2022-01-14 19:36
Hi,

This is a duplicate of https://github.com/mozilla/addons-server/issues/18105 but I'd be interested in knowing how large your source code zip was. Also, note that in most reported cases despite the error, the source code was successfully uploaded, so you may want to double-check, in that case you won't need to worry about it.

**Closed by diox** 2022-01-14 19:36 UTC
