### ISSUE TITLE
Add-on count in the Pre-approval 'New' queue is not correct

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11171] opened 2019-04-09 08:18 UTC
**STR:**

1. Log in to Rev Tools with a user that has `Addons:Review` permissions
2. Check the add-on count listed next to the 'New' queue
3. Count the actual number of add-ons pending for review

**Actual result:**
The totals do not match - there are fewer add-ons pending for review compared to the queue count 

**Expected result:**
The totals are matching

**Notes:**
- I've also checked with an Admin reviewer, to make sure that the missing add-ons are not actually pending for admin review, but the totals were not matching in this case either
- reproduced on -dev with FF66, Win10x64

![image](https://user-images.githubusercontent.com/31961530/55784352-12100480-5ab9-11e9-8bd0-9de724f12409.png)

**Comment by eviljeff** [comment] 2019-04-15 11:00
are you sure the missing ones aren't just the add-ons that will be auto-approved when the cron job next runs?  (the reviewers prefer that they're included in the count to have a warning if the cron fails)

**Comment by AlexandraMoga** [comment] 2019-04-15 11:26
@eviljeff where can I find out how many add-ons are pending for auto-approval at a given moment? I, for one, haven't submitted any new add-on today so I should't have anything in the auto-approval queue - I'm speaking for -dev.

**Comment by eviljeff** [comment] 2019-04-16 12:39
We don't expose the add-ons pending approval, currently.  I poked around and the difference is due to 4 (broken) add-ons that continually fail auto-approval.  @diox speculates they may be add-ons that are missing Firefox compatablity but we'll have to look more into it.

So it's not an issue with the queues and counts, per-se, but the auto-approval task and/or the add-ons themselves.

**Comment by diox** [comment] 2019-04-16 12:47
They can't be signed because they are missing an application version in our database and therefore are not auto-approved. The underlying problem was fixed in https://github.com/mozilla/addons-server/issues/10693 and other issues but the affected add-ons remained.

I'm going to disable those add-ons to solve this. However, if you find a way to reproduce in the future, let us know and we'll look into that.

**Closed** 2019-04-16 12:50 UTC
Labels: component: reviewer tools, env: dev, priority: p4

**Comment by AlexandraMoga** [comment] 2019-04-18 12:41
The count is correct now on both -dev and stage.

This is from -dev:
![image](https://user-images.githubusercontent.com/31961530/56361582-6a00e680-61f0-11e9-8184-89640fa70cf7.png)
