### ISSUE TITLE
The addon author should have access to statistics for hidden addons

### ISSUE THREAD

**Issue by M-Reimer** [mozilla/addons-server#10757] opened 2019-02-22 16:17 UTC
### Describe the problem and steps to reproduce it:
If an addon is hidden, then the "statistics" link in the developer hub is not available.
In the past, I just "enabled" the addon just to view the statistics.
As the addon in question is "legacy", it is now impossible to enable it again.
--> No access to the statistics.

### What happened?
No way to access statistics of "legacy" addons.

### What did you expect to happen?
Authors should have access to the statistics of their addons.

### Anything else we should know?
The addon, I want to view the statistics for, once was very popular and still is listed with over 2000 users in the "developer hub". I would like to know on which platforms it still is used, as replacements have been developed and users have been informed.

**Comment by eviljeff** [comment] 2019-03-12 18:49
seems we already have this request, so marking as a duplicate of #4092

**Closed by eviljeff** 2019-03-12 18:49 UTC
Labels: component: statistics, priority: p3
