### ISSUE TITLE
Some titles in the promo banner are hard to read 

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2143] opened 2016-04-01 14:41 UTC
Steps to reproduce:
1. Open amo homepage: https://addons-dev.allizom.org/en-US/firefox/
2. Observe the information displayed in the "Build the perfect website" banner.

Expected results:
All the information is easy to read.

Actual results:
Some of the tiles can't be read because they almost the same color as the background.

Notes/Issues:
Verified in FF45(Win7) Issue can be reproduced in addons-dev.allizom.org
Screencast for this issue: http://screencast.com/t/4TCwSgn0a

**Comment by muffinresearch** [comment] 2016-04-01 16:21
Duplicate of #2122

**Closed by muffinresearch** 2016-04-01 16:21 UTC
Labels: duplicate, style refresh
