### ISSUE TITLE
Version with expired delay rejection is not automatically rejected if another version is awaiting review

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15261] opened 2020-08-11 08:20 UTC
### Describe the problem and steps to reproduce it:
1. Open the listed review page of an add-on with a reviewer account
2. Submit a delay rejection for the latest Approved add-on version - consider this as version `1.0`
3. Upload a new version for this add-on
4. Wait for the delay rejection deadline for the first version to expire and check the add-on review page

### What happened?
The first version has not been automatically rejected when the delay rejection period expired - its status is "Approved · Scheduled for rejection in 0 minutes". It looks like this happens when a new version is still Awaiting review.

### What did you expect to happen?
The version should have been rejected automatically when the grace period ended

### Anything else we should know?
Make sure you are not locking the add-on review by keeping the page open as this will prevent the automatic rejection cron to run on your version.
Add-on examples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/delay-reje-approved-version
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/cookie-autodelete23

**Comment by wagnerand** [comment] 2020-08-11 09:29
@AlexandraMoga  I thought the previous version was supposed be disabled immediately?

**Comment by AlexandraMoga** [comment] 2020-08-11 11:15
@wagnerand I believe this was also mentioned in the requirements doc, but it wasn't implemented (not yet at least).

**Comment by wagnerand** [comment] 2020-08-11 12:02
It seems we hold off on the delayed rejection until the next version has been reviewed.

Log output:
```
Skipping rejections for add-on 619699 until version 1691835 has been reviewed
Skipping rejections for add-on 620086 until version 1691814 has been reviewed
```

**Comment by eviljeff** [comment] 2020-08-11 12:23
> 
> 
> It seems we hold off on the delayed rejection until the next version has been reviewed.
> 
> Log output:
> 
> ```
> Skipping rejections for add-on 619699 until version 1691835 has been reviewed
> Skipping rejections for add-on 620086 until version 1691814 has been reviewed
> ```

so, it's by design?  (I guess so we don't reject - and take down the public version - until the next version is reviewed)

**Comment by wagnerand** [comment] 2020-08-11 13:14
@jvillalobos Can you clarify what the expected flow is for this scenario?

**Comment by jvillalobos** [comment] 2020-08-11 15:14
It sounds like it's working as expected. The old version can't be auto-disabled because the new version is still awaiting review. The reason it works this way is that the developer is presumably cooperating, so they shouldn't have their version/listing taken down until there's a resolution of the latest version.

The "Approved · Scheduled for rejection in 0 minutes" message could use some tweaking to make this clearer.

**Comment by diox** [comment] 2020-08-11 17:38
Confirming that this was done by design. Relevant discussion is in https://github.com/mozilla/addons-server/issues/14799

**Comment by diox** [comment] 2020-08-31 08:05
> The "Approved · Scheduled for rejection in 0 minutes" message could use some tweaking to make this clearer.

Can you suggest some copy that we could use instead when the version isn't going to be automatically rejected because another version is awaiting review ?

**Comment by jvillalobos** [comment] 2020-08-31 17:33
How about something like "Approved · Pending Rejection on review of new version".

**Comment by diox** [comment] 2020-09-07 12:18
I filed a new issue for the message, https://github.com/mozilla/addons-server/issues/15429. Closing this one as invalid as this is working as intended.

**Closed by diox** 2020-09-07 12:18 UTC
Labels: component: reviewer tools, state: invalid
