### ISSUE TITLE
No username in "Account Settings" genarates random username in "Contributors & More" tab from edit collection page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1699] opened 2016-02-17 14:23 UTC
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org
2. Go to "Account Settings"
3. Delete the username
4. Load edit page for any collection you created 
5. Click " Contributors & More " tab and observe the username

Expected results:
Maybe the "display name" can be listed here, if there is no username.

Actual results:
A random username is displayed.

Notes/Issues:
Verified on FF44(Win 7). Reproducible in AMO-stage and AMO-dev.
Screenshot for this issue: 
![untitled](https://cloud.githubusercontent.com/assets/15685960/13112169/6e965b8c-d592-11e5-9d86-ceae9d588c96.png)

**Comment by EnTeQuAk** [comment] 2016-07-07 08:55
I don't know if that's the intended behavior for various reasons or an actual bug.

**Comment by tofumatt** [comment] 2016-07-07 14:40
Agreed. “email” is a great username :-)

**Comment by mstriemer** [comment] 2016-07-08 15:22
Since user's aren't required to enter anything on AMO when signing up email is the only field we have from them. It doesn't feel right to expose that to the public without their consent though so that's why they get one of these anonymous usernames.

Jorge is right, this should use the display name if possible and that login is wrapped up in [`UserProfile.name`](https://github.com/mozilla/addons-server/blob/5c99bb1c2cafe62a6d3c9857ce38397fc6e3e532/src/olympia/users/models.py#L347) (and this user would become `Anonymous user 8cf140` if they didn't have a display name or username).

**Comment by andymckay-limited-access** [comment] 2016-07-26 16:03
Last comment sounds good.

**Comment by eviljeff** [comment] 2018-07-06 09:40
we dropped that part of collection editing (and contributors in general) so closing.

**Closed by eviljeff** 2018-07-06 09:40 UTC
Labels: component: collections, component: firefox accounts, priority: p3, triaged
