### ISSUE TITLE
Deleting an add-on prevents account deletion

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1844] opened 2016-03-04 15:57 UTC
STR

1. Create a new user (or use an old one if you really want)
2. Upload an add-on for that user
3. Try to delete the user (you can't you're a developer)
4. Delete the add-on you uploaded (so that you have no add-ons)
5. Try to delete the user (you can't you're a developer... what?)
6. Your "profile" shows that you have 0 add-ons but you have the "add-ons developer" badge on your profile picture

It seems like deleting the add-on doesn't clear the user's association with it, but it does hide it from the user. So there's no way to remove yourself as the author and you can no longer delete your account.

**Comment by EnTeQuAk** [comment] 2016-09-14 05:12
This is a duplicate of https://github.com/mozilla/addons-server/issues/3038 (or the other way around?) but the latter has a possible solution on it so closing this one here.

**Closed by EnTeQuAk** 2016-09-14 05:12 UTC
Labels: triaged
