### ISSUE TITLE
"Next listed version" link will return a 404

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5531] opened 2017-05-31 12:35 UTC
Steps to reproduce:
1.Submit a new add-on and approve it
2.Submit a new version for the add-on 
3.Go to Manage Status & Versions page for this add-on and press the link next to "Next listed version"

Expected results:
We have 2 possibilities here. We can deactivate the link for the next listed version because it is not public and it will always return a 404 or we can display the awaiting review version for edit purposes

Actual results:
A 404 will be returned

Please see video for this bug : 

![nextlisted](https://cloud.githubusercontent.com/assets/1583842/26632063/c4c12dac-4616-11e7-9b76-fc6542b8b544.gif)

**Comment by eviljeff** [comment] 2017-05-31 14:29
I guess this is a dupe of #5531

**Closed by eviljeff** 2017-05-31 14:29 UTC
Labels: state: duplicate
