### ISSUE TITLE
Cannot access file for deleted add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9606] opened 2018-10-08 09:53 UTC
### Describe the problem and steps to reproduce it:

(probably related to https://github.com/mozilla/addons-server/issues/8985)

The add-on with the numerical ID 997516 has been deleted by the author, now I am trying to download the file (ID 1072001) for that deleted add-on.

### What happened

https://addons-internal.prod.mozaws.net/en-US/admin/models/files/file/1072001/change/

Clicking on "Download file"
1. goes to https://addons-internal.prod.mozaws.net/en-US/admin/models/files/file/1072001/download/ 
2. redirects to https://addons-internal.prod.mozaws.net/en-US/firefox/mnt/efs/addons-internal.prod.mozaws.net/files/997516/iridium-0.2.1-an+fx.xpi
3. 404

### What did you expect to happen?

A file download.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment] 2018-10-08 09:59
I fear this may be a duplicate of https://github.com/mozilla/addons-server/issues/8988 from looking at this.

**Comment by wagnerand** [comment] 2018-10-08 10:14
I don't believe it is, changing the domain (https://addons.mozilla.org/en-US/firefox/mnt/efs/addons-internal.prod.mozaws.net/files/997516/iridium-0.2.1-an%2Bfx.xpi) doesn't work either.

**Comment by wagnerand** [comment] 2019-03-20 15:26
Just ran into this again. @diox or @bqbn, any ideas?

**Comment by bqbn** [comment] 2019-03-20 22:57
I'm a little confused. The title of the issue says, "Cannot access file for deleted add-on", if an addon is deleted, isn't a non-issue that you cannot access it?

**Comment by diox** [comment] 2019-03-21 00:48
Add-ons are soft-deleted ; we should keep a database entry and move the files without deleting them for real. Admins should have access through special permissions, our code checks those permissions when viewing, allowing them to access "deleted" content.

**Comment by wagnerand** [comment] 2019-04-03 13:57
@diox @bqbn any ideas here? I keep running into this for add-ons that we are evaluating for blocklisting.

**Comment by diox** [comment] 2019-04-03 14:46
Bumping priority, going to investigate the redirect

**Comment by diox** [comment] 2019-04-03 15:00
The problem doesn't happen with public files, because we redirect to the CDN. For unlisted/disabled/"deleted" files however, we should be checking for permissions and returning the file directly through a 
 `X-Accel-Redirect` header that nginx understands.

@bqbn Are the nginx on the admin instances configured to handle `X-Accel-Redirect` ? The regular instances should, maybe restricted to specific URLs I don't know.

**Comment by EnTeQuAk** [comment] 2019-04-04 09:27
@diox if you're looking at this, mind considering https://github.com/mozilla/addons-server/issues/9302 as well? I do think that they're duplicates but I'm not entirely sure.

**Comment by diox** [comment] 2019-04-04 09:38
Looks like the same issue yes, I'll take a look.

**Comment by diox** [comment] 2019-04-04 11:09
STR:
- Log in as admin on https://addons-internal.prod.mozaws.net/en-US/admin
- Download https://addons-internal.prod.mozaws.net/en-US/admin/models/files/file/1132556/download/

Expected results:
- File is downloaded ; addons-server returns a `X-Accel-Redirect` with the file path when serving that URL, and nginx understands it and returns the file contents.

Actual results:
- Client is redirected to https://addons-internal.prod.mozaws.net/en-US/firefox/mnt/efs/addons-internal.prod.mozaws.net/files/1007316/sd_app-1.2-fx.xpi


Note:
- For this particular file, a workaround exists, which seem to demonstrate that it's an issue with the way addons-internal.prod.mozaws.net is configured:
  Logging in to AMO as admin and going to https://addons.mozilla.org/firefox/downloads/file/1132556/sd_app-1.2-fx.xpi?src=reviewer, which is a different URL intended for reviewers that downloads the same file the same way (using `X-Accel-Redirect`), works. It should serve the same file behind the scenes (`/mnt/efs/addons-internal.prod.mozaws.net/files/1007316/sd_app-1.2-fx.xpi`)

**Comment by bqbn** [comment] 2019-04-04 20:23
The fix for this [[1]](https://github.com/mozilla-services/cloudops-deployment/pull/3082) has been merged and deployed to -dev environment, and can be verified as fixed using this link: https://addons-internal.dev.mozaws.net/en-US/admin/models/files/file/254629/download/

The fix will be pushed to -stage next Tuesday along with a new application tag, and should be verified in -stage afterwards, so that on Thursday it can be pushed to -prod.

(I don't have a link for -stage environment to verify the fix though.)

**Comment by diox** [comment] 2019-04-08 14:26
Closing as it's fixed on dev.

QA: any deleted, unlisted, disabled or regular file should be accessible through the django admin page for the given file.

**Closed by diox** 2019-04-08 14:26 UTC
Labels: priority: p2, triaged

**Comment by ioanarusiczki** [comment] 2019-04-10 11:24
I filed https://github.com/mozilla/addons-server/issues/11178
and marking this issue verifed on AMO dev - FF66(Win10).
