### ISSUE TITLE
Serve JSON update manifests for clients that support it

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7223] opened 2018-01-05 16:30 UTC
Firefox has supported a [JSON add-on update manifest](https://developer.mozilla.org/en-US/Add-ons/Updates) since version 45, but support for the old RDF format can't be dropped until add-ons stop using it. AMO needs to start serving the JSON updates for clients that support it.

The first step is figuring out how to determine which manifest to serve. Is there an `Accept` header that can be used, or is the user agent needed?

**Comment by aswan** [comment] 2018-01-05 17:32
An `Accept` header would have been sensible, but it doesn't look the browser sends one :(
I don't think you need to look at the user agent though, update requests have a bunch of query parameters in the URL including something like `appVersion=59.0a1`

**Comment by kmaglione** [comment] 2018-03-17 02:19
Removing support for the RDF update format is a high priority for us at this point. It would allow us to remove thousands of lines of hard-to-maintain code and tests.

I don't particularly care whether AMO continues to support the RDF format (it seems unnecessary, since we no longer support updating non-WebExtension add-ons), but it definitely needs to serve the JSON format as soon as possible.

**Comment by jvillalobos** [comment] 2018-03-20 16:41
It's currently planned as a Q2 project.

**Comment by kmaglione** [comment] 2018-03-21 04:11
OK. As of today, RDF update manifests are pre-processed and fed to the JSON backend, and cause a deprecation warning to appear in the console. So there are about 10 weeks until those warnings start appearing for release users.

**Comment by aswan** [comment] 2018-03-21 04:25
We should also make an official deprecation announcement for developers who self-host updates.  There is a late June merge/release event at which point 61 will be released and 62 beta will branch from central.  If this will be deployed some reasonable time before merge day, we can announce that 61 will be the last version to support RDF update manifests.

**Comment by diox** [comment] 2018-04-30 14:04
@jvillalobos Since even the oldest supported versions of Seamonkey and Thunderbird are based off Firefox 45 or newer, can we drop support for RDF update manifests entirely? I'd be a lot easier to write and test the patch that way.

**Comment by eviljeff** [comment] 2018-05-02 10:09
@jvillalobos once we've removed legacy xul addons from AMO in Q3 they can't get security updates either, so we're just left with the edge case of very early webextensions from Firefox 42.  Is Firefox 42-44 using alpha quality webextension APIs and addons enough of an edge case to ignore (in Q3)?

**Comment by diox** [comment] 2018-05-02 10:11
Looking at MDN, before Firefox 45 WebExtensions could not do much at all. Firefox 45 is when they started being really able to do interesting things. Before that, they could not intercept requests, manipulate tabs or windows, have actions etc.

**Comment by jvillalobos** [comment] 2018-05-02 19:42
> @jvillalobos once we've removed legacy xul addons from AMO in Q3 they can't get security updates either

That's late August at the earliest, so still some time away.

I agree that early WebExtension add-ons aren't a major concern.

**Comment by diox** [comment] 2018-05-02 23:09
>> @jvillalobos once we've removed legacy xul addons from AMO in Q3 they can't get security updates either
>
> That's late August at the earliest, so still some time away.

But legacy add-ons on Firefox 45+ would still get the security updates if we completely switch to JSON.

The number of add-on authors still maintaining a legacy version of their add-ons is already probably quite small (since it means maintaining 2 versions or giving up on ever getting new users), supporting the even smaller number of people that use an obsolete version of Firefox *and* have one of these legacy add-ons that is somehow still maintained is not worth the extra effort IMHO. Especially for a few months only.

**Comment by diox** [comment] 2018-05-09 11:33
QA: please test that add-on updates still work correctly in Firefox, Thunderbird and Seamonkey supported versions (including ESR).

**Comment by AlexandraMoga** [comment] 2018-05-14 11:05
Verified on AMO-dev, Win10x64 with the following applications:

 **1. Firefox 60.0 release, Firefox 60.0 ESR, Firefox 52.8.0 ESR, Nightly 62.0a1** 
 - check for updates from add-ons manager is working;
 - background (automatic) updates are working

**2. Thunderbird 52.7.0** 
 - works only with legacy add-ons; 
 - check for updates from add-ons manager is working; 
 - background (automatic) updates NOT applied at restart

**3.  SeaMonkey 2.49.3** 
 - works only with legacy add-ons; 
 - I have found just one add-on for which updates were applied - [example](https://addons-dev.allizom.org/en-US/seamonkey/addon/legacy-test/?src=hp-dl-upandcoming); 
 - for the rest of the compatible add-ons available on -dev, updates were NOT applied

@diox, I haven't noticed any issues with updates in Firefox but I'm not sure about the other two, especially SeaMonkey, for which I was able to test with only one add-on. Do you have any solution that would support better coverage?

**Comment by diox** [comment] 2018-05-14 11:08
Can you fully describe what your testing protocol was in seamonkey/thunderbird ? What configuration variables did you change, what add-on were you testing with, what did you click on, etc ?

**Comment by AlexandraMoga** [comment] 2018-05-14 12:14
1. Thunderbird:
- configuration:
extensions.webapi.testing -  true
xpinstall.signatures.required - false
xpinstall.signatures.dev-root - true
extensions.update.url - [pointing to -dev](https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%)
extensions.update.background.url - [pointing to -dev](https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%)
extensions.getAddons.get.url - ponting to dev
extensions.getAddons.search.browseURL - ponting to dev

- method:
  1.downloaded a [Thunderbird compatible add-on](https://addons-dev.allizom.org/en-US/thunderbird/addon/foxclocks/?src=ss) from AMO - dev on my local drive
  2.used the sideloading (install from file) option in thunderbird's add-ons manager to install the add-on
  3.submitted and approved a new version for this add-on on AMO
  4.used the "Check for Updates" option from thunderbird's add-ons manager - updates ARE applied
  5.repeated step 1, 2 and 3 and restarted Thunderbird to see if background updates are applied - they were NOT

2. Seamonkey
- configuration:
extensions.webapi.testing -  true
xpinstall.signatures.required - false
xpinstall.signatures.dev-root - true
extensions.update.url - [pointing to -dev](https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%)
extensions.getAddons.get.url - ponting to dev
extensions.getAddons.search.browseURL - ponting to dev

- method
1.open AMO-dev homepage in Seamonkey
2.Look for a compatible add-on that has more versions available to install ([ex 1](https://addons-dev.allizom.org/en-US/seamonkey/addon/foxclocks/versions/), [ex 2](https://addons-dev.allizom.org/en-US/seamonkey/addon/reminderfox/versions/))
3.Install a previous version
4.Go to add-ons manager in seamonkey and click on "Check for updates" - updates are NOT found even if there are more recent versions available

Note: I could not find or set an 'extensions.update.background.url' pref in Seamonkey, so I was not able to test for automatic updates

**Comment by diox** [comment] 2018-05-14 15:55
@AlexandraMoga also, can you double-check that the behaviour you're seeing on thunderbird and seamonkey is different that what you're getting on stage? That is, make sure that my changes - currently only present on dev - are what's causing your problems.

**Comment by AlexandraMoga** [comment] 2018-05-15 09:00
@diox 
Thunderbird - background updates solved by modifying `extensions.update.interval` to `1`
Seamonkey - I compared -dev with stage by using basically the same add-ons and stage updates were applied while on -dev they weren't. Below are my examples:
STAGE: 
https://addons.allizom.org/en-US/seamonkey/addon/lightning/versions/
https://addons.allizom.org/en-US/seamonkey/addon/reminderfox/versions/
DEV
https://addons-dev.allizom.org/en-US/seamonkey/addon/lightning/versions/
https://addons-dev.allizom.org/en-US/seamonkey/addon/reminderfox/versions/

Note: On -dev, updates worked for this add-on https://addons-dev.allizom.org/en-US/seamonkey/addon/adblock-plus-sm/?src=search

**Comment by diox** [comment] 2018-05-15 09:38
@AlexandraMoga so, only seamonkey is an issue then, and only a specific set of add-ons?

**Comment by AlexandraMoga** [comment] 2018-05-15 10:40
@diox form the set of add-ons I've tested with, only those that were based on the [Adblock Plus](https://addons-dev.allizom.org/en-US/seamonkey/addon/adblock-plus-sm/?src=search) package worked.
Here are some additional examples of add-on that did NOT work:
https://addons-dev.allizom.org/en-US/seamonkey/addon/enigmail/versions/
https://addons-dev.allizom.org/en-US/seamonkey/addon/foxclocks/versions/
https://addons-dev.allizom.org/en-US/seamonkey/addon/enigmail-tb/versions/

**Comment by diox** [comment] 2018-05-15 11:17
I don't understand what's going on, and I have had a miserable time trying to debug this with seamonkey myself, but I can reproduce the issue, so I'll revert my patch before it makes the tag.

**Comment by diox** [comment] 2018-05-15 13:39
Reverting (#8256) definitely fixed the seamonkey issue for me.

**Comment by AlexandraMoga** [comment] 2018-05-15 14:27
I confirm that updates are also working for me in seamonkey

**Closed** 2018-05-17 12:39 UTC
Labels: priority: p3, project: 2018 Q2, qa: extra, triaged

**Comment by AlexandraMoga** [comment] 2018-05-18 11:56
Verified as fixed on AMO-dev, Win10x64 with the following applications:

 **1. Firefox 60.0 release, Firefox 60.0 ESR, Firefox 52.8.0 ESR, Nightly 62.0a1** 
 - check for updates from add-ons manager and background (automatic) updates are working;

**2. Thunderbird 52.7.0** 
- check for updates from add-ons manager and background (automatic) updates are working;

**3.  SeaMonkey 2.49.3** 
 - check for updates from add-ons manager is working
