### ISSUE TITLE
Contributions are failing on prod

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2988] opened 2016-06-23 16:44 UTC
## steps to reproduce:
1. Load https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=search
2. Click on the contibutions button
3. confirm $5 contribution

## observed behavior:
Contribution fails with "There was an error communicating with PayPal. Please try again later."
ERROR HTTP Error: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",) :/data/olympia/src/olympia/paypal/__init__.py:202

## screenshot:
https://www.dropbox.com/s/i9pg6mdrqukmwld/Screenshot%202016-06-23%2009.38.25.png?dl=0

**Comment by muffinresearch** [comment] 2016-06-24 14:37
@kumar303 Was this fixed by https://github.com/mozilla/addons-server/pull/2989 ?

**Comment by diox** [comment] 2016-06-24 14:40
should have been. though we'll need a better long term solution so maybe we can keep that opened?

**Comment by kumar303** [comment] 2016-06-24 20:00
Yes, that prevented the error from happening when the site connects to paypal.com. If there's a way to upgrade certifi again without breaking Contributions, that would be nice.

**Comment by tsl143** [comment] 2016-06-25 14:45
Unable to reproduce the issue
![screen shot 2016-06-25 at 8 14 43 pm](https://cloud.githubusercontent.com/assets/5318732/16357343/7fa66428-3b11-11e6-825f-c7126d6fed1f.png)

**Comment by kumar303** [comment] 2016-06-25 15:17
That's because we already pushed out a hotfix release to production: https://github.com/mozilla/addons-server/compare/2016.06.23...2016.06.23-1

How about we close this issue; @diox can you make a new issue to retry the certifi upgrade?

**Closed by kumar303** 2016-06-25 15:17 UTC
Labels: triaged

**Comment by madalincm** [comment] 2016-06-29 07:08
I successfully completed a contribution in production (Win7, FF47) 
![paypalcontribution2](https://cloud.githubusercontent.com/assets/15685441/16443412/65d06bfc-3de1-11e6-9a42-c9fe7b4a5243.png)
Marking bug as verified fixed.
