### ISSUE TITLE
Add-on submission fails with a server error if the name is too long when urlencoded

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10212] opened 2018-12-13 10:10 UTC
Also reported some way back in https://bugzilla.mozilla.org/show_bug.cgi?id=1193265

**STR:**

1. Upload a new add-on with non-ascii characters in name and summary - see attached extension
2. Try to complete the submission

**Actual result:**
A server error is received when the add-on is submitted

**Expected result:**
Add-on is submitted with no errors

**Notes:**
- in my case, I was using [Amharic](https://en.wikipedia.org/wiki/Amharic)
- reproduced on all AMO server with FF63, WIn10x64
- could probably have the same root cause as  #8923  

[Unicode add-on.zip](https://github.com/mozilla/addons-server/files/2675489/Unicode.add-on.zip)

![2018-12-13_11-46-28](https://user-images.githubusercontent.com/31961530/49931082-c1074f80-fece-11e8-88ae-6fc2fb90c091.gif)

**Comment by wagnerand** [comment] 2018-12-13 13:18
Probably the same issue as #10180, caused by #8923.

**Comment by ajupazhamayil** [comment] 2018-12-14 06:04
Hi @wagnerand and @AlexandraMoga ,
I have gone through the issue #8923 and understood the problem. I have a workaround which may solve this issue temporarily. Please correct if I am wrong.
I have used json package to give a try, Please find my suggestion code below!

![smileyfirefox](https://user-images.githubusercontent.com/14087896/49985959-f4f87880-ff93-11e8-8a7c-6e73e6430c79.png)

**Comment by wagnerand** [comment] 2018-12-14 12:53
I am not sure this is the proper solution to the problem, but I'll defer to @diox. Are client-side workaround would be to remove the emojis until this is properly fixes.

**Comment by diox** [comment] 2018-12-14 12:56
This is essentially an alternative version of the second workaround documented here : https://github.com/mozilla/addons-server/issues/8923#issuecomment-406389289 - but we don't want to do that, for the same reasons described in that comment. The proper fix is to change the charset in MySQL, ops are working on it.

Closing as duplicate of https://github.com/mozilla/addons-server/issues/8923

**Comment by AlexandraMoga** [comment] 2019-01-30 07:55
I see that #8923 has been fixed for AMO -dev, but I'm still reproducing the above scenario (please see the extension example uploaded to the issue).

Based on that, I'm re-opening.

**Comment by diox** [comment] 2019-02-26 13:02
Interesting!

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5286531/?query=is:unresolved

`(1406, "Data too long for column 'referrer' at row 1")`

**Comment by diox** [comment] 2019-02-26 13:08
So this is because we want to store the referrer in `AkismetReport`, and in this instance it's longer than 255 characters, which is the max for this field. So, nothing to do with unicode per se, it's just that it makes the referrer artificially large.

The same problem can probably happen with other fields on `AkismetReport`, such as `user_agent`. We should truncate all data that is meant to be stored in those fields limited to 255 chars.

**Closed** 2019-03-26 10:36 UTC
Labels: component: devhub, priority: p3

**Comment by AlexandraMoga** [comment] 2019-03-27 09:06
Verified fixed on -dev and stage with FF66, Win10x64
Submission can be completed now with the add-on provided in my example. 

![2019-03-27_11-05-21](https://user-images.githubusercontent.com/31961530/55063253-42e74700-5080-11e9-928b-ab4830e21fa3.gif)
