### ISSUE TITLE
Use CDN endpoint for all static assets

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/addons-server#1561] opened 2016-02-01 15:23 UTC
I see two static assets requests on discovery pane that should be using the CDN:

https://addons.mozilla.org/en-US/firefox/jsi18n.js?b=01ef2c4-56a7a899
https://addons.mozilla.org/en-US/firefox/addons/buttons.js?b=01ef2c4-56a7a899

**Comment by muffinresearch** [comment] 2016-02-01 15:38
This was causing problems too for the discovery pane wrt to CSP. If these can be removed we can get rid of the config that explicitly adds https://addons.mozilla.org here: [1]

[1] https://github.com/mozilla/olympia/blob/master/lib/settings_base.py#L1296

**Comment by muffinresearch** [comment] 2016-02-01 16:47
@jasonthomas looking further into this it looks like both of those are localized content. So I think this is by design that they're routed via django.

**Comment by muffinresearch** [comment] 2016-02-01 17:37
I'm going to close this for now since the only way to do this will be to add something to build these files as statics. We may as well cover that when we get to overhauling the frontend.

**Comment by jasonthomas** [comment] 2016-02-01 20:14
The CDN endpoint will pass requests such as these to olympia [1] , so that
https://addons.cdn.mozilla.net/en-US/firefox/jsi18n.js?b=01ef2c4-56a7a899 is cached in CDN.

[1]https://github.com/mozilla-services/puppet-config/blob/master/amo/modules/amo_proxy/templates/nginx.addons.conf.erb#L81-L83

**Comment by muffinresearch** [comment] 2016-02-02 17:30
In that case I'll reopen it.

**Comment by muffinresearch** [comment] 2016-05-25 14:28
The disco pane will be updated by virtue of the new version coming in via addons-frontend. This should be fixed by #2745

**Closed** 2016-05-26 09:59 UTC
Labels: disco pane, triaged
