### ISSUE TITLE
Layout issues for theme description in Disco Pane

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3055] opened 2016-07-07 09:47 UTC
Steps to reproduce:
1. Go to https://addons.mozilla.org/en-US/firefox/addon/marvelous-magnolias-by-madonna/ and install the theme 
2. Go in about:addons and observe theme description from Appearance tab

Expected results:
There are no display or layout issues.

Actual results:
If a link is present in theme description it is not rendered correctly in Disco Pane.

Notes/Issues:
Reproducing also in the new Disco Pane. 
**Installing the theme directly from about:addons returns NO description in Appearance tab.**
Screencast for this issue: 
![theme description](https://cloud.githubusercontent.com/assets/15685960/16649206/7f921328-4440-11e6-99e1-37ce0b6161d8.gif)

**Comment by EnTeQuAk** [comment] 2016-07-11 17:09
hmm, I wonder if this is actually disco pane or a firefox bug. @muffinresearch mind taking a short look to validate what might be the issue here?

**Comment by muffinresearch** [comment] 2016-07-11 17:32
@ValentinaPC The discovery pane is curated content. As such the description is created by editorial.

**Comment by muffinresearch** [comment] 2016-07-11 17:37
Fwiw, the difference is because we create the installation differently and don't use that description. We don't use the same content in the disco pane. 

Not sure if this really matters or if we need to use the description. It's pretty useless if the HTML is escaped in the browser in any case. I'd reckon we should fix this when we update the theme installation in AMO in future.

**Comment by andymckay** [comment] 2016-07-12 16:08
A dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1263610, its a Firefox XUL bug so closing in favour of that.

**Closed by andymckay** 2016-07-12 16:08 UTC
Labels: design decision needed
