### ISSUE TITLE
No way to exit if you click on Write a Review on an add-on you previously reviewed

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#7042] opened 2017-11-28 00:24 UTC
1. Go to the AMO detail page of an add-on you previously reviewed.
2. Realize you've already reviewed it, because the content of your review pre-populates the text field.
3. Find that there is no way to close the overlay.

Expected: there is a way to exit the dialog
Actual: the only way to exit is by clicking Submit Review again
<img width="1360" alt="screenshot 2017-11-27 13 37 14" src="https://user-images.githubusercontent.com/2701092/33296268-70c5e1e6-d38f-11e7-9006-c0226e07e52d.png">

**Comment by ValentinaPC** [comment] 2017-11-28 08:34
@atsay : there is a secret path :) - you must click above or below the review window.
Please see - https://github.com/mozilla/addons-frontend/issues/3691

**Comment by diox** [comment] 2017-11-28 18:42
This is a frontend bug and as @ValentinaPC points out, a dupe of mozilla/addons-frontend#3691

**Closed by diox** 2017-11-28 18:42 UTC
