### ISSUE TITLE
Hide unreviewed versions (if there is at least one reviewed version) on the 'all versions' page

### ISSUE THREAD

**Issue by kuremu** [mozilla/addons-server#3704] opened 2016-10-10 06:58 UTC
### Describe the problem and steps to reproduce it:

Vimperator version (3.15.0) is linking to a missing page.

To reproduce go to https://addons.mozilla.org/en-US/firefox/addon/vimperator/versions/ and click on "Continue to Download" for version 3.15.0
### What happened?

404
### What did you expect to happen?

A download link for the new version

**Comment by wagnerand** [comment] 2016-10-10 11:06
This version has not been approved yet. The download button is different, but we should probably add additional info or hide unreviewed versions from that page.

@jvillalobos Any objections on hiding unreviewed versions on the 'all versions' page?

**Comment by EnTeQuAk** [comment] 2016-10-10 13:49
Hmm, curious if this is a duplicate of https://github.com/mozilla/addons-server/issues/3639

**Comment by jvillalobos** [comment] 2016-10-10 17:56
I'm in favor of hiding them. It's consistent with what we want to do in #3348.

**Comment by kuremu** [comment] 2016-10-11 02:41
@wagnerand I'm sure I had been able to download unreviewed versions like this before, hence the confusion.

**Closed** 2017-01-04 18:08 UTC
Labels: in progress, triaged

**Comment by ValentinaPC** [comment] 2017-01-05 08:44
Verified on AMO-dev FF50.1(Win 7)
- Unreviewed versions are not listed in _all versions_ page
![allversions](https://cloud.githubusercontent.com/assets/15685960/21673689/cb6fd92a-d332-11e6-91f4-fd54b36e6fab.png)
![unreviewed](https://cloud.githubusercontent.com/assets/15685960/21673690/cb9ef2aa-d332-11e6-9bec-b77ec767fd94.png)

- Beta version (from beta channel)- automatically reviewed and signed - is listed in  _all versions development channel_ page under the text "Caution: Development versions of this add-on have not been reviewed by Mozilla."
![dev](https://cloud.githubusercontent.com/assets/15685960/21673779/3514e49c-d333-11e6-8c33-ecd1e9b05e24.png)

@diox : From what you said yesterday on `irc` I understood that beta versions are also not listed in public pages - is this correct?
And second - by who are the beta version reviewed, if not "by Mozilla"?
Thanks!

**Comment by diox** [comment] 2017-01-05 15:03
correct, in a way : beta versions are not listed in the "regular" version list, they are listed on the development channel versions list instead.

beta versions are not reviewed, they are automatically signed.

**Comment by ValentinaPC** [comment] 2017-01-05 15:24
Based on the previous 2 comments I'll mark this as fixed.

**Comment by jvillalobos** [comment] 2017-01-12 20:57
Actually, we do want to show beta versions on the All Versions page. There's a link from listing pages (in the Developer Channel section) pointing to the All Versions page so you can see previous beta versions. I don't know if this should be reopened or a new issue should be filed, since it's already live.

**Comment by jvillalobos** [comment] 2017-01-12 21:19
Never mind. I just realized that, in this particular case I was looking at, there are two links pointing to the different version list pages.

<img width="740" alt="dev-channel" src="https://cloud.githubusercontent.com/assets/62568/21908676/4dbedd70-d8da-11e6-9cbc-6bf0a2cb11f9.png">

The compatibility warning box has a `View other versions` link that points to the normal All Versions page. I suppose we can live with that situation for now.
