### ISSUE TITLE
AMO stage does not load the css content

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#9379] opened 2018-09-07 12:34 UTC
### Describe the problem and steps to reproduce it:
1. Start a new profile.
2. Load https://addons.allizom.org/en-US/firefox/ 
3. Observe the web page.

### What happened?
The css content is not loading.

### What did you expect to happen?
To see the web page  of AMO stage fully loaded.

### Anything else we should know?
This issue is 100% reproducible on a new profile.

Reproduced on AMO stage on FF64.0a1 and FF62.0 under Win 7 64-bit and Mac OS X 10.13.3.

![nocss](https://user-images.githubusercontent.com/15885467/45219374-5af9a380-b2b3-11e8-8149-8e9715b22a34.png)

**Comment by muffinresearch** [comment] 2018-09-12 15:18
Duplicate of https://github.com/mozilla/addons-frontend/issues/5825

**Closed by muffinresearch** 2018-09-12 15:18 UTC
Labels: env: stage, type: bug
