### ISSUE TITLE
/files/browse/ doesn't show all files for some uploads

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#6875] opened 2017-11-09 15:13 UTC
### Describe the problem and steps to reproduce it:
Using [/files/browse/764081/](https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/764081/) (ABP 3.0.1) shows up a very limited set of files (META-INF, _locales and .eslintrc.json)

### What did you expect to happen?
[Source code of ABP 3.0.1](https://addons.mozilla.org/firefox/downloads/file/764081/adblock_plus-3.0.1-an+fx.xpi) contains hundred of files. All those files should appear in /browse/

### Anything else we should know?
Reproducible on both Firefox 56.0.2 and Google Chrome 61.

**Comment by spoji** [comment] 2017-11-13 14:32
Note that I'm not able to reproduce the issue this morning.

**Comment by diox** [comment] 2017-11-15 17:25
Duplicate of https://github.com/mozilla/addons-server/issues/6519

**Closed by diox** 2017-11-15 17:25 UTC
