### ISSUE TITLE
Mysterious "unknown word" error while validating a webextension

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2187] opened 2016-04-04 19:56 UTC
## test webextension:
http://cl.ly/2j0Q2s1B1D1L

## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2. Upload the test add-on
3. Notice the validation errors

## observed behavior:
Mysterious "unknown word" error while validating a webextension which is not listd in the detailed Vaidation results page - https://addons-dev.allizom.org/en-US/developers/upload/e17f0076af664e9abf065e4257563651

## screenshot:
 https://www.dropbox.com/s/q0zgluyzakupvum/Screenshot%202016-04-04%2012.33.40.png?dl=0

**Comment by ValentinaPC** [comment] 2016-04-12 10:15
I've also encountered this issue when uploading the attached web-extension.
Please see the screenshots: 
![2016-04-12_1314](https://cloud.githubusercontent.com/assets/15685960/14456990/86431e3e-00b0-11e6-9719-1980b67b9d78.png)
![2016-04-12_1314_001](https://cloud.githubusercontent.com/assets/15685960/14456997/8b1446d6-00b0-11e6-9c34-bb38e17efcd9.png)


Tested on AMO-dev FF45(Win 7).
[Video-Downloader-professional_.zip](https://github.com/mozilla/addons-server/files/214768/Video-Downloader-professional_.zip)

**Comment by andymckay** [comment] 2016-04-20 22:25
```
CSS_SYNTAX_ERROR   Unknown word              An error was found in the CSS file being processed as a result   __MACOSX/assets/css/._style.css    1      1     
                                             further processing of that file is not possible     
```

And the word is:

```
Mac OS X        	2��ATTR��J�Jcom.apple.quarantineq/0001;569401dd;Google\x20Chrome.app;94CC063B-2A4F-4AEA-99C8-62308D16888E
```

So yeah. It's invalid.

I guess the problem is that "Unknown Word" outside of the context of the filename (CSS) and its location is rather cryptic and we should focus on getting that up to the validation page in a better way.

Any ideas @krupa, @tofumatt, @EnTeQuAk or others?

**Comment by andymckay** [comment] 2016-04-20 22:33
The current validator doesn't seem to parse anything in _DS_STORE and instead raises a hidden folder warning:

https://www.dropbox.com/s/4cfpi460fkne4ny/Screenshot%202016-04-20%2015.31.53.png?dl=0

**Comment by andymckay** [comment] 2016-04-20 22:38
...by _DS_STORE, I meant that __MACOSX is flagged as a warning and .DS_Store and Thumbs.db are also similarly flagged. Should be easy enough to add the linter.

**Comment by muffinresearch** [comment] 2016-04-21 10:03
I noticed this last night working on https://github.com/mozilla/addons-linter/issues/606

We will need to add some exclusions to step over this directory and collect a warning  I'll file an issue on addons-linter and point to this.

**Comment by andymckay** [comment] 2016-04-22 00:19
The CSS for VideoDownloadHelper is broken, it has;

width="100px"; height="60px"

Instead of:

width:"100px"; height:"60px"

So the CSS is broken and the validator stops parsing the file. The validator never even notices this broken CSS.

@wagnerand or @jvillalobos should we do something different when encounter a completely broken CSS file?

**Comment by wagnerand** [comment] 2016-04-22 08:31
We have https://github.com/mozilla/amo-validator/blob/master/validator/testcases/javascript/jsshell.py#L18 for JavaScript syntax errors. It would nice if we had something similar for CSS.

**Comment by andymckay** [comment] 2016-04-22 13:40
And you've got it, this is a CSS error. So if this is fine...

**Comment by andymckay** [comment] 2016-05-06 18:27
I think this will be fixed with the move to make all CSS errors warnings in the validator.

**Closed by andymckay** 2016-05-06 18:27 UTC
Labels: linter

**Comment by vcarciu** [comment] 2016-05-10 12:09
Verified as fixed. The unknown word error is not displayed anymore for both webextensions from above :  
![unknownword](https://cloud.githubusercontent.com/assets/1583842/15145953/23be1ad0-16c1-11e6-8142-26e57b11f99d.png)
