### ISSUE TITLE
[Reviewer Tools] Layout of reviewers-score-bar

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#9028] opened 2018-07-30 16:33 UTC
Recently, due to changes the layout has been affected:
ref: `<div id="reviewers-score-bar" class="c">`
The + 140 is wrapped.

TBH, I think the text is too long and changing "Post-Approval Add-on Review" to "Post-Approval Review" would be fine. Otherwise, a change to `<td class="number">+140</td>` would be needed.

https://screenshots.firefox.com/KSaHRSXP3WxvvseU/reviewers.addons.mozilla.org
![Screenshot](https://screenshotscdn.firefoxusercontent.com/images/9f53ae18-635a-46e3-9615-f2d77056c959.png)

**Comment by shiri1248** [comment] 2018-07-31 09:39
can I work on this issue ?

**Comment by wagnerand** [comment] 2018-07-31 10:03
@shiri1248 Sure, go ahead.

**Comment by shiri1248** [comment] 2018-07-31 16:12
Thanks! @wagnerand  :+1:   but I am unable to  findout the file can you help me with this

**Comment by wagnerand** [comment] 2018-07-31 16:41
@shiri1248 We have a list of good first bugs, where we can provide better guidance. You'll find onboarding material and the link to the list at https://wiki.mozilla.org/Add-ons/Contribute/Code.

**Comment by eviljeff** [comment] 2018-08-08 15:58
mentor: me

hi @shiri1248 this has been added to the list of good first bugs now, if you're still interested in solving this issue.
To shorten the names the constants in https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/reviewers.py#L83:L90 would need to adjusted.  I'm not sure yet whether that would be enough - you'll have to try and see.  If not I can help with finding the appropriate css to adjust.

**Comment by shiri1248** [comment] 2018-08-08 16:30
Thank you very much @eviljeff  , Can I change it to "Post-Approval Review" instead of "Post-Approval Add-on Review"

**Comment by eviljeff** [comment] 2018-08-08 16:51
yeah, it seems clear enough.

**Comment by wagnerand** [comment] 2018-08-08 16:56
I am not so sure. There is "Add-on Review" and "Content Review"

**Comment by eviljeff** [comment] 2018-08-08 17:06
assigning it to @wagnerand to work out what needs changing

**Comment by wagnerand** [comment] 2018-08-08 17:07
I left a comment in the PR

**Comment by anubhavsinha98** [comment] 2018-08-13 15:02
Can I solve this issue?

**Comment by eviljeff** [comment] 2018-08-14 10:46
@anubhavsinha98 I think @shiri1248 is working on this issue already.

**Closed** 2018-08-17 06:01 UTC
Labels: component: reviewer tools, contrib: assigned, contrib: good first bug, contrib: mentor assigned, priority: p4, size: S, triaged

**Comment by erosman** [comment] 2018-08-17 07:17
Off-Topic: @eviljeff looking at  7f8f5ff `_REVIEWED_ADDON_PRELIM: _('Preliminary Add-on Review'),` seems not to be relevant any more, unless it is still in use.

**Comment by AlexandraMoga** [comment] 2018-08-21 14:31
There is no more wrapping in the Recent Points section, with `en-US` at least. Not sure if it's going to be a problem with other languages. Needs to be rechecked when the fields will be translated.

![image](https://user-images.githubusercontent.com/31961530/44407950-02fb3700-a568-11e8-9c7b-3d18ceba53cd.png)

**Comment by shiri1248** [comment] 2018-08-21 14:46
Hi    @AlexandraMoga, is this issue still needs to be  fixed? Actually I didn't get you

**Comment by AlexandraMoga** [comment] 2018-08-21 15:02
Hey @shiri1248 the issue is fixed if the page is visited with `en-US` . I've just made a note to check this fix again after the related fields have been translated. There are locales (i.e German) that could still show some issues.
