### ISSUE TITLE
Collection tool sometimes doesn't recognize content

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#7038] opened 2017-11-27 23:54 UTC
As a manager of Mozilla collections, I use AMO's collection creation tool quite a bit. To add extensions or themes to any collection, you simply start typing the name of the content into the field labelled "Enter the name of the add-on to include" under the "Add-ons" tab. 

As you type you receive smart search returns in a drop-down interface. However, sometimes it won't surface the name of a piece of content even though you've entered the title fully. 

For instance, we have this collection:

https://addons.mozilla.org/firefox/collections/mozilla/mob/

I tried to enter "[Google Search Fixer](https://addons.mozilla.org/android/addon/google-search-fixer/)" but it never emerged as a clickable content item to include into the collection. 

This same phenomenon will happen occasionally with other content but I can't seem to find a patter to it.

**Comment by jvillalobos** [comment] 2017-11-28 20:38
This is a duplicate of https://github.com/mozilla/addons-server/issues/6891

It's a combination of only showing a few results and having less-than-optimal search.

There's a hidden trick, which is that you can use the add-on's numerical ID (in this case 869140) to make the search box give you the right result. That ID is hard to find at the moment, but I can help you in cases like this. Since we're reworking the Collections UX this quarter, we should address this issue.

**Closed by jvillalobos** 2017-11-28 20:38 UTC
Labels: triaged
