### ISSUE TITLE
[AMO-dev] White menu in Editor Tools

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2370] opened 2016-04-14 11:30 UTC
Steps to reproduce:
1. Sign in to AMO-dev with an admin account
2. Load Tools-Editor Tools page https://addons-dev.allizom.org/en-US/editors/
3. Observe the menu

Expected results:
The menu is displayed.

Actual results:
The menu is white on white background.

Notes/Issues:
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue: 
![2016-04-14_1421](https://cloud.githubusercontent.com/assets/15685960/14526651/7640529c-024d-11e6-9810-0c4b5758d1a0.png)

**Comment by wagnerand** [comment] 2016-04-14 13:05
Weird, I cannot reproduce this on local.

**Comment by wagnerand** [comment] 2016-04-14 13:07
This has been fixed in 8f26761.

**Closed by wagnerand** 2016-04-14 13:07 UTC
Labels: style refresh, triaged

**Comment by ValentinaPC** [comment] 2016-04-14 13:36
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-14_1635](https://cloud.githubusercontent.com/assets/15685960/14529837/fe31db24-025e-11e6-9c00-f3e3700007c9.png)
