### ISSUE TITLE
"Review history" multiple rows text is not correctly rendered

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6971] opened 2017-11-21 15:16 UTC
Steps to reproduce:
1. Load "Manage Status & Versions" page for an extension i.e. https://addons-dev.allizom.org/en-US/developers/addon/auto-approval-text/versions
2. Click on "Review history" link and enter a 3-rows developer reply or observe the auto-approval massage if the extension was auto-approved.

Expected results:
There are no display or layout issues.

Actual results:
The text is not correctly rendered on multiple rows.

Notes/Issues:
Verified in AMO-dev FF56(Win 7). Reproducing on all servers.
Screenshot for this issue:
![2017-11-21_1710](https://user-images.githubusercontent.com/15685960/33080000-ab8800e8-cedf-11e7-8232-895d225d6ad5.png)

**Comment by wagnerand** [comment] 2017-11-21 15:36
I am not sure what "correct" should be, just wanted to mention your reply doesn't have the first character in the first word: `This` vs `his`.

**Comment by ValentinaPC** [comment] 2017-11-21 15:40
> I am not sure what "correct" should be, just wanted to mention your reply doesn't have the first character in the first word: This vs his.

Funny.
Better?
![2017-11-21_1739](https://user-images.githubusercontent.com/15685960/33081428-04090c64-cee3-11e7-847b-b62b17f22004.png)

**Comment by muffinresearch** [comment] 2017-11-22 16:55
This is caused by this in the `div.review-entry pre` selector:

```css
word-break: break-all;
```
It should be changed to something like:

```CSS
word-wrap: break-word; 
max-width: 650px;
```

**Comment by wagnerand** [comment] 2017-11-28 18:11
Mentor: @muffinresearch 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by NaturalFractals** [comment] 2017-12-20 03:03
@muffinresearch 

Hello,

This is my first PR with Mozilla, and I have made the changes as suggested. It seems that the Travis CI build has failed for my PR. If you could help point me in the right direction to remedy this, it would be greatly appreciated!

**Comment by prokaktus** [comment] 2017-12-25 22:04
Hi! May I look into this?

**Comment by muffinresearch** [comment] 2018-01-04 09:46
@prokaktus looks like a fix already landed.

**Closed by muffinresearch** 2018-01-04 09:46 UTC
Labels: component: devhub, contrib: good first bug, contrib: mentor assigned, triaged

**Comment by AlexandraMoga** [comment] 2018-01-05 11:04
Verified as fixed on AMO-dev with FF57 (Win10)

![image](https://user-images.githubusercontent.com/31961530/34606592-b09fb7b8-f218-11e7-948b-bf8ca5c2bb5b.png)
