### ISSUE TITLE
Issue Mozilla Account

### ISSUE THREAD

**Issue by lsd23hd** [mozilla/addons-server#3552] opened 2016-09-19 16:08 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.) I create an account for Mozilla in my computer, then I log on on my 2 computer and try to acces my mozilla account, but the system tell an issue, the 2 computer is new with windos 10.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment] 2016-09-19 17:44
It's unclear from this description what the issue is - could you provide more details and clarify that  this is related to logging in to https://addons.mozilla.org?

If this is a more general firefox accounts issue you might find some answers here: https://support.mozilla.org/en-US/kb/im-having-problems-with-my-firefox-account

**Comment by muffinresearch** [comment] 2016-09-20 11:32
I'm going to close this for now, but feel free to re-open it if there's an account issue specific to https://addons.mozilla.org.

**Closed by muffinresearch** 2016-09-20 11:32 UTC
Labels: needs info
