### ISSUE TITLE
Dec 2017 Disco Pane content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#7055] opened 2017-11-29 00:29 UTC
For the Thursday **14 December** push, can we please REMOVE: 

- Search Image
- all three current themes 

… and REPLACE them with LastPass and three new themes:

**Manage passwords** with [LastPass by LastPass](https://addons.mozilla.org/firefox/addon/lastpass-password-manager/)
Simplify and sync all your various website logins across devices with one password to rule them all. 

[Themes]

Owl First Snow by [Candelora](https://addons.mozilla.org/firefox/addon/owl-first-snow/)

Tiffy01 by [Toefftoeff](https://addons.mozilla.org/firefox/addon/color-to-color/)

Evil Robots by [Selby Doll](https://addons.mozilla.org/firefox/addon/evil-robots/)

Full page content lineup should reflect like so: 

Owl First Snow 
uBlock Origin
LastPass
Tiffy01 
Enhancer for YouTube
Emoji Cheatsheet
Evil Robots

**Comment by wagnerand** [comment] 2017-11-30 15:09
@devaneymoz A push for that week is still marked as optional. I set the milestone to the week before (since that is the only confirmed push in December). Would you be ok if those changes went out next week?

**Comment by devaneymoz** [comment] 2017-11-30 17:04
Yes that works beautifully, thank you!

**Closed** 2017-12-01 14:41 UTC
Labels: triaged

**Comment by AlexandraMoga** [comment] 2017-12-08 13:47
Verified as fixed on AMO prod with FF57 (Win10)

![image](https://user-images.githubusercontent.com/31961530/33768167-9a8a0740-dc2d-11e7-9575-259d20b5681f.png)
