### ISSUE TITLE
Allow collection IDs in API URLs

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7529] opened 2018-02-08 23:22 UTC
All of the [collection API](https://addons-server.readthedocs.io/en/latest/topics/api/collections.html) endpoints seem to require a collection slug. Most other endpoints allow a slug *or* ID number. Can collection endpoints allow IDs too?

I'm mostly nervous about the [edit endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#edit) since it's possible to edit the slug. I think it will be fine. Everything will be fine, right? (Right?)

**Comment by eviljeff** [comment] 2018-02-09 15:49
I'm trying to remember if there was a reason support for ID wasn't added too...  and I can't.  Something to do with private collections, maybe?  I suppose it's possible to add, but everything should be fine anyway 😉

**Comment by kumar303** [comment] 2018-02-15 18:15
Well, huh, this is actually pretty difficult to work around. The problem is that we have to change the browser URL after the user edits their slug. This would work fine in a server side application but on a client side application it causes a race condition against how we invalidate/reload data. Anyway, I have a hack in place to avoid the race condition but the whole thing would be simpler if we had a stable URL based on an ID number.

**Comment by kumar303** [comment] 2018-02-28 17:13
> I have a hack in place to avoid the race condition

I think there is a different cache race condition now, which I've seen once or twice. So, yeah, this is definitely something we need. I'll switch to ID urls in https://github.com/mozilla/addons-frontend/issues/4293

**Comment by eviljeff** [comment] 2018-03-02 18:22
If you're waiting to start work on mozilla/addons-frontend#4293 I have a patch for this ready - just need to add some more tests to double check it works okay for all collection endpoints.  Will be ready Monday.

**Comment by eviljeff** [comment] 2018-03-03 15:11
So, I remembered _why_ we only implemented slug lookup for collections, and not id also:
In the Collections update PRD, collections were supposed to lose the private/public switch and effectively a public collection is one that has a url you've shared with people, and a private one is one you've not shared (typically a collection that is intended to be public would have a friendly slug, and a collection intended to be private would be a random uuid).
You make a collection you've already shared publicly "private" by changing it's slug.  Unfortunately this system breaks if the collection is accessible by ID, which won't - and can't - change.  

Admittedly this bypass/fail/attack assumes the user either shares the url with an ID in it, or a inclined user specifically seeks out the ID of a collection they only have the slug for beforehand.  Perhaps unlikely scenarios.

I'm leaning towards a simple implementation and a code comment to fix the hole once/if we remove the public/private switch.  The fix would be to limit access by ID to the edit endpoint, or to the collection owner/contributor, I'm thinking.

**Comment by EnTeQuAk** [comment] 2018-03-05 09:35
So my take on this would be that there's two views on collections:

* The end-user that primarily accesses collections via the web-ui
* The API-view which primarily is being used by addons-frontend directly and I doubt the number of users viewing/modifying collections via the API will be high

(following are my own thoughts without remembering all the details of the collections PRD tbh, sorry if I have conflicts with that)

A public collection is, as @eviljeff said a originally private collection which got shared at some point. Imho, once public, a slug should not be editable anymore and that collection needs to be made private and then re-published again. That's how other systems, e.g Dropbox etc do sharing of resource-data.

Now, assuming that, a collection should **not** have a slug unless public.

That means, we can have the collection-id be allowed for every endpoint and allow a slug-based collection fetching endpoint only for reading collection data for public collections. Everything else is private anyway and not shared or accessible by other individuals.

Obviously, the internal collection-id should never be shared for public sharing so we'll have to make sure the collection-endpoint requires access by slug for public collections.

Does that make sense / help?

**Comment by kumar303** [comment] 2018-03-05 17:56
> In the Collections update PRD, collections were supposed to lose the private/public switch and effectively a public collection is one that has a url you've shared with people, and a private one is one you've not shared

This is not my understanding of [simplified collections](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit#). My read is this: There will no longer be a concept of public/private. All collections will exist at a URL, period. We will not link to user collections anywhere on the site. If someone discovers a URL then they will see the collection.

What you're suggesting sounds really complicated and it defeats the purpose of simplifying the scope of collections. I say we just keep the URLs as is with named slugs and let people edit them. If they change the URL then they will be responsible for updating their friends with the new URL. We could implement a redirect for renamed slugs to make renames easier but I don't think it's a big deal.

For historic collections, we currently show a 404 to non owner users for old collections that are marked private. This seems fine to me.

**Comment by eviljeff** [comment] 2018-03-06 09:23
I was going on "Collections are private unless URL is shared." from the PRD, but with a way of 'unsharing' by simply changing the slug.  Using IDs in the URL/API makes it so can never unshare a collection once the url is out there (and theoretically any collection could be discovered by enumerating through the IDs, though it'd be non-trivial with the username - max 6 million tries)

I wasn't proposing anything to do with redirects - that would defeat the point of renaming a collection's slug to hide it.

Anyway, the patch is finished, and I'll create the PR, just now sure about it.

**Comment by muffinresearch** [comment] 2018-03-06 10:30
So if I'm understanding the [Simplified Collections PRD](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit) correctly I think this will be the way forward:

* Collections marked with the private property will only be visible to the developer that created them (in other words they stay private and are only accessible by the authenticated developer)
* The API can be updated to allow access via the ID. This means if you have the id you'll always get the content so as Andrew points out this makes slug changes for privacy not work. However based on the idea that there are no private collections I think that's ok.
* There is no concept of private collections going forward.

We could optionally provide some kind window for a one-way switch for _old private collections_ at some point but that could be dealt with separately in the future.

I'd propose we shouldn't suggest anywhere that a newly created collection is _"private unless the URL is shared"_ since that would suggest access control that isn't really there - that's the only bit that seems to diverge with what the PRD says.

Redirects would be nice but should be considered out of scope.

@jvillalobos does that sound ok to you? 

Lastly assuming we're not trying to prevent slug changes being used for pseudo privacy should we allow non-API URLs to work by both id and slug too?

**Comment by jvillalobos** [comment] 2018-03-06 18:21
> @jvillalobos does that sound ok to you?

Sounds reasonable.

> should we allow non-API URLs to work by both id and slug too?

I'd prefer to only support the slug, since ID enumeration would be trivial to find existing collections. I know they're all technically public, but I'd favor not making them so easy to find.

**Closed** 2018-03-08 14:04 UTC
Labels: component: api, priority: p3, triaged

**Comment by AlexandraMoga** [comment] 2018-03-12 15:04
Verified on AMO-dev with several collection endpoints and compared results returned by collection slugs and collection IDs.  The results seemed to be consistent and there were no errors observed.

Here is an example:
```
GET https://addons-dev.allizom.org/api/v3/accounts/account/AlexandraMoga1/collections/testing-collection-urlid/
```
works the same as
```
GET https://addons-dev.allizom.org/api/v3/accounts/account/AlexandraMoga1/collections/5496873/
```

In addition, I've looked for regressions in the frontend as suggested in [#4505](https://github.com/mozilla/addons-frontend/issues/4504)
