### ISSUE TITLE
Theme preview missing for some static themes

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#10350] opened 2019-01-09 15:40 UTC
### Describe the problem and steps to reproduce it:
When viewing the detail page for some static themes on stage there is a small preview but no larger preview on the detail page.

https://addons.allizom.org/en-US/firefox/addon/orion-nebula/

This may still be fallout from #10030.

**Comment by eviljeff** [comment] 2019-01-09 15:46
can you point to where you see the small preview - I don't see any previews for that theme

**Comment by mstriemer** [comment] 2019-01-09 15:51
If you search for it you see it, but not on the detail page. https://addons.allizom.org/en-US/firefox/search/?platform=mac&q=orion%20nebula

I just set the API URL to stage as well and I don't see a preview in about:addons for this one but I do for https://addons.allizom.org/en-US/firefox/addon/head-in-the-clouds/. Hopefully if this is fixed then the previews will work in about:addons.

**Comment by AlexandraMoga** [comment] 2019-01-10 07:02
Reading the last example, I still believe that this issue is indeed a duplicate of #10030.

Just by looking at the video I've posted there, you can notice that I encountered the same issue with search.

**Comment by eviljeff** [comment] 2019-02-06 14:12
We fixed this along the way (I forget in which issue/pr exactly) though it's possible it's happened again on a different theme.  If this kind of issue is spotted on prod (addons.mozilla.org) please file a new issue.

**Closed by eviljeff** 2019-02-06 14:12 UTC
Labels: project: static themes, triaged
