### ISSUE TITLE
Horizontal-bar intruder in Statistics page 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2350] opened 2016-04-13 15:27 UTC
Steps to reproduce:
1. Load Statistics page for an add-on with public stats in AMO-stage: https://addons.allizom.org/en-US/firefox/addon/firebug/statistics/?last=30
2. Go to page footer

Expected results:
There are no display or layout issues.

Actual results:
There is a white horizontal bar displayed.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue: 
![2016-04-13_1808](https://cloud.githubusercontent.com/assets/15685960/14499046/5c7f38da-01a5-11e6-9f9a-2bbf238a6a5f.png)

**Comment by muffinresearch** [comment] 2016-04-13 15:31
Duplicate of #2259

**Closed by muffinresearch** 2016-04-13 15:31 UTC
Labels: duplicate
