### ISSUE TITLE
Add to firefox button is not displayed when hovering over a theme preview

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2147] opened 2016-04-01 15:47 UTC
**Steps to reproduce:**
1. Open any themes category:  https://addons-dev.allizom.org/en-US/firefox/themes/music
2. Hover over any theme.

**Expected results:**
The add to firefox button is displayed.

**Actual results:**
The add to firefox button is not displayed.

**Notes/Issues:**
Verified in FF45(Win7) Issue can be reproduced in addons-dev.allizom.org
Screencast for this issue: http://screencast.com/t/Zljf8o9KQKRt

**Comment by krupa** [comment] 2016-04-11 19:35
Let us reduce the number of clicks required for the user to install something. We should bring the install button back.

**Comment by muffinresearch** [comment] 2016-04-12 08:02
I'm assigning this to tofumatt since he knows the hovercard changes better than I do.

**Closed** 2016-04-12 18:05 UTC
Labels: blocks-release, pull-request-ready, style refresh

**Comment by vcarciu** [comment] 2016-04-13 08:31
Verified as fixed : http://screencast.com/t/bDvNPS4Y05

**Comment by vcarciu** [comment] 2016-04-13 14:10
We have a regression in Chrome for this bug, but we will open a separate issue.
