### ISSUE TITLE
All the links to themes are broken

### ISSUE THREAD

**Issue by tchaffee** [mozilla/addons-server#9409] opened 2018-09-12 21:54 UTC
### Describe the problem and steps to reproduce it:
Go to this page (just for example, every theme has this problem)

https://addons.thunderbird.net/en-US/thunderbird/addon/little-flowers/

Click on "Add to Thunderbird"

![selection_276](https://user-images.githubusercontent.com/148813/45455356-2cb60280-b6bd-11e8-8271-f3b613381509.png)

### What happened?
It goes to this page, which says "We're sorry, but we can't find what you're looking for."

https://addons.thunderbird.net/en-US/thunderbird/addon/10900/

### What did you expect to happen?
For it to find the theme and add it to Thunderbird.

### Anything else we should know?
It happens for a every theme I tried.

**Comment by Sancus** [comment] 2018-09-12 23:15
Most themes(lightweight themes) cannot be downloaded, they must be installed from within Thunderbird. This requires Thunderbird 60. [See instructions here](https://github.com/thundernest/addons-server/issues/19#issuecomment-411897770).

Secondly, post bugs for the Thunderbird addons page at https://github.com/thundernest/addons-server

**Comment by tchaffee** [comment] 2018-09-12 23:46
> Secondly, post bugs for the Thunderbird addons page.

I just followed the "file an issue" link from the error page:

https://addons.thunderbird.net/en-US/thunderbird/addon/10900/

Looks like that should be fixed too?

**Comment by Sancus** [comment] 2018-09-13 00:09
> I just followed the "file an issue" link from the error page:
> Looks like that should be fixed too?

It is fixed, I deployed the fix shortly after you filed this I think.

**Comment by eviljeff** [comment] 2018-09-13 06:57
Closing because the issue is in the wrong place.  If it still needs attention please re-file @  https://github.com/thundernest/addons-server

**Closed by eviljeff** 2018-09-13 06:57 UTC
