### ISSUE TITLE
No add-ons present in new development install

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2617] opened 2016-05-11 11:06 UTC
I just did a fresh install of AMO because I switched to Docker for Mac; everything started okay and I seemed to have populated the DB:

<img width="1350" alt="screenshot 2016-05-11 12 04 42" src="https://cloud.githubusercontent.com/assets/90871/15178922/91f0d72c-1770-11e6-9275-7c8aea7cc7fa.png">

But none of those extensions appear on the front page or in search results:

<img width="1350" alt="screenshot 2016-05-11 12 05 31" src="https://cloud.githubusercontent.com/assets/90871/15178943/af198e84-1770-11e6-8bf9-3b9eba7e2cf2.png">

This might be a dupe of #2613, sorry if it is.

**Comment by EnTeQuAk** [comment] 2016-05-12 08:04
hmm, did you also run `make initialize_docker`? This should populate data and start the reindexing process. Is elasticsearch and the `worker` container running properly?

**Comment by tofumatt** [comment] 2016-05-12 09:11
I did, and I even ranreindex. It said it only completed one reindexing
task. Maybe ES is not running? How would I check?

- tofumatt

**Comment by EnTeQuAk** [comment] 2016-05-12 16:34
Hmm, see what `docker-compose ps` is saying and what `docker-compose logs` says about elasticsearch and stuff. Could also be something celery related.

**Comment by EnTeQuAk** [comment] 2016-10-07 14:11
From IRC: This doesn't seem to be happening again and we didn't reproduce the correct issue. It works for me and others, so closing.

**Closed** 2016-10-07 14:10 UTC
Labels: code quality, triaged
