### ISSUE TITLE
Developer Hub page layout issues when using split screen view

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6459] opened 2017-09-20 11:21 UTC
Originally filed as https://github.com/mozilla/addons-frontend/issues/3189

-------

Scenario 1:
Preconditions: User is logged into their AMO account

Steps to reproduce:
1.Log in to AMO stage, desktop view
2.Access Developer Hub while in full screen view
3.Observe the page layout (pay attention to Header Menus and Page Footer)
4.Split your screen (i.e by using START+LEFT KEY)
5.Observe the page layout again

Expected Results:
Page layout in split screen view should include the same options as the full screen view

Actual result:
When in split screen view, the page does not include the following: 
-'My Add-ons' and the Profile Logo in the Header menu
-No vertical scroll bar to reach the Footer menu

Video demonstration - User Logged In:
![devhub login layout](https://user-images.githubusercontent.com/31961530/30637411-ea0b9286-9e00-11e7-969b-62419fad2c66.gif)

Scenario 2:
Preconditions: User has logged  out from their AMO account

Steps to reproduce:
1.Access AMO stage while logged out
2.Access Developer Hub while in full screen view
3.Observe the page layout (pay attention to Header Menus and the Page Footer)
4.Split your screen (i.e by using START+LEFT KEY)
5.Observe the page layout again

Expected Results:
Page layout in split screen view should include the same options as the full screen view

Actual result:
When in split screen view, the page does not include the following: 
-the 'Sign in' or 'Register' links in the Header menu
-The vertical scroll bar does not reach to the Footer menu

Video demonstration - User Logged out:
![devhub logout layout](https://user-images.githubusercontent.com/31961530/30637538-3d8fc300-9e01-11e7-89ee-a5387c2f29fa.gif)

Notes: the issue can be reproduced on AMO-Dev and AMO-Prod as well

**Comment by tofumatt** [comment] 2017-09-20 11:23
I'm not sure this is an actual issue by the way, as it seems like just the mobile styles are appearing, but filing here so devhub folks who know it better can take a look.

**Comment by EnTeQuAk** [comment] 2017-09-20 11:30
Indeed, I'm going to close this issue since that's the mobile view and the updated navigation is exactly how that view was designed. It's not the best thing but since there is absolutely no mobile view for the devhub it should be alright. The most important links are present though.

**Comment by AlexandraMoga** [comment] 2017-10-30 14:44
> Indeed, I'm going to close this issue since that's the mobile view and the updated navigation is exactly how that view was designed. It's not the best thing but since there is absolutely no mobile view for the devhub it should be alright. The most important links are present though.

Actually, for the second scenario (user logged out) you can see that two important links - Register or Log in - are missing from the page header. The users need to easily have access o these links regardless of the view:

See screenshot:

![image](https://user-images.githubusercontent.com/31961530/32176572-ba5b5da0-bd90-11e7-9289-8f177974042f.png)

**Comment by muffinresearch** [comment] 2018-02-02 17:41
This was by design originally - because it was seen that the logged in state wasn't relevant to a mobile user.

**Closed by muffinresearch** 2018-02-02 17:41 UTC
Labels: component: devhub, triaged
