### ISSUE TITLE
Add support for CRX version 3

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15849] opened 2020-10-28 10:52 UTC
Looks like we support CRX version 3 in addons-linter so let's add support for it in addons-server too, see: https://github.com/mozilla/addons-scanner-utils/pull/106#discussion_r513070587

**Comment by diox** [comment] 2020-10-28 10:55
Likely a dupe of https://github.com/mozilla/addons-server/issues/14036 but this is more succinct and explicit so let's keep it opened and close both when we fix it.

**Closed** 2020-10-30 11:18 UTC
Labels: component: devhub, priority: p4

**Comment by ioanarusiczki** [comment] 2020-10-30 14:12
@willdurand Can you add some str for qa?
Thanks!

**Comment by willdurand** [comment] 2020-10-30 14:18
> @willdurand Can you add some str for qa?

cc @diox

**Comment by diox** [comment] 2020-10-30 14:21
@ioanarusiczki try to submit a crx file to AMO, it should work :) You can use the one in https://github.com/mozilla/addons-server/issues/14036 (unzip `dist.zip` to find the crx)

**Comment by AlexandraMoga** [comment] 2020-11-02 13:22
I submitted several `.crx` archives on -dev, including the ones that caused problems in #14036 and https://github.com/mozilla/addons/issues/1243, and the add-ons are correctly validated now. 

I've also noticed a potential regression for which I filed #15889
