### ISSUE TITLE
Travis issues run with tox, local ones don't

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1464] opened 2016-01-21 05:38 UTC
`make test` runs `py.test` so locally you run `py.test`

on Travis tests are run like this:

`RUNNING_IN_CI=True tox -v -e $TOX_ENV --recreate`

We should be running locally the same as on Travis so if anything happens on Travis you've got a chance of recreating it locally.

**Comment by magopian** [comment] 2016-01-21 08:45
We use tox on travis to be able to split the tests easily in different parallel builds (haven't revisited that in a long time, maybe we could do it as easily now with the travis.yml file?).
We don't use it locally because
1/ we don't need parallel builds (I doubt many people run the full test suite locally)
2/ tox adds some complexity to the stack, and makes it that bit more difficult to run a specific test

I think I'd rather try to find a solution to remove tox from travis, rather than adding it to our local dev.

**Comment by andymckay** [comment] 2016-01-21 20:28
Agreed on removing it from travis, I briefly tried last night but it was late and I was tired and so gave up.

**Comment by EnTeQuAk** [comment] 2016-01-22 06:04
I'm against removing tox, it might add a tiny bit more complexity or at least an additional layer but it's also our only way to reproduce errors happening on travis on how to install packages etc.

The way I'm understanding our splitting in tox is that we're running different build-configs, one with elasticsearch turned on, rather than mixing integration, unit and functional tests. That they're executed in parallel is a bonus.

Maybe adding a new `make tox` or `make test-ci` command to execute the same tests as on travis? For simple local development another config is okay imho, debugging test-config errors on travis doesn't happen that often.

**Comment by EnTeQuAk** [comment] 2016-05-12 15:50
I'm going to close this for now unless there are real good arguments against tox. It has it's advantages (e.g good reproducability of our travis builds locally) and we're using it and I don't see any big problems with it.

**Closed by EnTeQuAk** 2016-05-12 15:50 UTC

**Comment by andymckay** [comment] 2016-05-12 22:31
My argument is that what runs on travis is completely different from what runs locally. Every time I've tried to touch something in tox its been a pain because I have to keep sending lots of builds to travis to see if it works, I can't test anything in tox out locally.

**Comment by EnTeQuAk** [comment] 2016-05-13 08:17
Well, all travis does is run tox and that's pretty much it. If we would not have tox there would be absolutely no way to reproduce the exact config we're running imho.
