### ISSUE TITLE
Kabyle locale activation on staging Server

### ISSUE THREAD

**Issue by belkacem77** [mozilla/addons-server#4156] opened 2016-12-18 09:12 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
We would like test our locale (Kabyle) on https://addons.allizom.org/
### What happened?
Kabyle language not available on staging server: https://addons.allizom.org/
### What did you expect to happen?
Select kabyle Language to test localization
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment] 2017-01-04 10:15
This is a duplicate of https://github.com/mozilla/addons-server/issues/4156

closing.

**Closed by EnTeQuAk** 2017-01-04 10:15 UTC
