### ISSUE TITLE
Make sure AMO accepts version strings that follow the "new format" for both MV2 and MV3

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#19809] opened 2022-10-20 08:31 UTC
Once https://github.com/mozilla/addons-linter/issues/4507 has been merged, the linter will start to emit warnings to encourage users to adopt a "simpler version format" (documented on EW later today ([see -stage](https://extensionworkshop.allizom.org/documentation/develop/manifest-v3-migration-guide/))).

The linter will only emit errors for MV3 extensions but that isn't really a problem at the moment because AMO does not accept MV3 submissions.

With the linter PR linked above, there is a small but important change for MV2 extensions: previously, when an extension was not using a toolkit version (e.g. any version string with some letters), each "part" (or number) of the version string had to be between 0 and 65535. That is going to change for consistency purposes. MV2 extensions will be able to use numbers with up to 9 digits (the other rules about the number of parts and leading zeros were already enforced before so that will not change).

This issue is about making sure that AMO will accept MV2 extensions with a version string like `123456789.0` or `999999999.999999999.999999999.999999999` for instance.

**Comment by eviljeff** [comment] 2022-10-20 08:55
Currently AMO will accept any version string in any format up to 255 characters - it doesn't try to process it as a version string on upload, and only carries out a string comparison to see if it's been uploaded previously.  (This will change with https://github.com/mozilla/addons-server/issues/19788).  Where we _do_ compare version strings numerically (e.g. with the blocklist; and on upload after #19788) we max out at 65535 so that's the part that will need changing.

Also, once the linter patch has landed we may be able strip out some of the AMO code that handles non-numeric characters.

**Comment by eviljeff** [comment] 2022-10-20 16:31
Update: from reading the code carefully (which I myself wrote, heh), there was no limit to version part comparison for Add-on versions (only app versions have a limit because we need the value to fit into a mysql BIGINT for database queries*) I.e. we don't apply a `min` or `max` on the numbers; and `*` is always treated as infinity, so any version part number, no matter how large, would correctly be seen as less than `*`.

I made a patch anyway that simplifies some usage of `version_dict` / `version_int` and increased the values we tested for in the blocklist tests to make it clear.

*remember this comment once Firefox 65536 launches 😛

**Closed** 2022-10-20 17:03 UTC
Labels: priority: p3

**Comment by willdurand** [comment] 2022-10-24 10:05
> I also see [mozilla/addons-linter#4507](https://github.com/mozilla/addons-linter/issues/4507) still opened so maybe that's why.

That is why, indeed. I'll ping you when this is done.

**Comment by eviljeff** [comment] 2022-10-24 10:12
@ioanarusiczki no need really - I didn't change anything

**Comment by willdurand** [comment] 2022-10-26 07:15
@eviljeff I updated the milestone since QA should verify this issue with the linter version that has the new format (not released, yet)

**Comment by ioanarusiczki** [comment] 2022-11-01 10:22
@willdurand I re-tested some samples which I used for the linter issue.  

One thing is different on AMO Dev and reproducible for MV2 and MV3: 

when I tried with a longer string such as "123456789.123456789.123456789.123456789" I will get an error 

Version numbers should have fewer than 32 characters.  -> [full validation report](https://addons-dev.allizom.org/en-US/developers/upload/695693cb39bb493fb20731b938843291) would not indicate this error

So it is obvious this comes from the server side -> the linter does not throw this error when I test it locally.

**Comment by eviljeff** [comment] 2022-11-01 10:43
> when I tried with a longer string such as "123456789.123456789.123456789.123456789" I will get an error
> 
> Version numbers should have fewer than 32 characters. -> [full validation report](https://addons-dev.allizom.org/en-US/developers/upload/695693cb39bb493fb20731b938843291) would not indicate this error

😬 you've hit https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L871 (added almost 12 years ago).  Can you file a follow-up?

**Comment by ioanarusiczki** [comment] 2022-11-01 11:13
@eviljeff Done https://github.com/mozilla/addons-server/issues/19842

**Comment by willdurand** [comment] 2022-11-01 14:31
> Version numbers should have fewer than 32 characters. -> [full validation report](https://addons-dev.allizom.org/en-US/developers/upload/695693cb39bb493fb20731b938843291) would not indicate this error

Ha, that's interesting, thanks!

**Comment by ioanarusiczki** [comment] 2022-11-02 08:52
@willdurand MV2 Lang packs and dictionaries can be submitted -> there is no error about their version format but there's a deprecation warning 

![deprecated warning](https://user-images.githubusercontent.com/33448286/199443155-b0432624-643c-4b38-8b0c-5e5d3430b85c.png)
