### ISSUE TITLE
The List Ratings API takes a long time to return grouped ratings

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9293] opened 2018-08-29 20:30 UTC
See mozilla/addons-frontend#5986 for STR.

Something happened recently where the dev API is now taking about 7 minutes to return updated grouped rating counts after submitting a rating. If I run the same frontend code (from master) against the stage API, grouped rating counts are returned nearly instantaneously.

Did something happen on dev? Do these rating counts rely on celery? @EnTeQuAk or could this be related to the new `read committed` level? https://github.com/mozilla/addons-server/issues/7158

**Comment by diox** [comment] 2018-08-29 20:40
It does rely on celery, yes. We have logs showing when the log is added and when the task starts/ends, so we should be able to figure out what's taking so long.

**Comment by diox** [comment] 2018-09-06 18:45
Closing for now as it's by design, it's eventually consistent, just not immediate.

**Closed by diox** 2018-09-06 18:45 UTC
Labels: component: ratings and reviews, priority: p3, triaged
