### ISSUE TITLE
Fix flakey test: test_validate in src/olympia/zadmin/tests/test_views.py

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3585] opened 2016-09-22 16:01 UTC
We've been seeing an increasing amount of this test randomly failing, it would be good to fix it up.

```
src/olympia/zadmin/tests/test_views.py:681: in test_validate
    assert validation['messages'][0]['id'] == ['main', 'prepare_package',
E   AssertionError: assert ['typedetecti...alid_em_type'] == ['main', 'prep..., 'not_found']
E     At index 0 diff: u'typedetection' != 'main'
E     Full diff:
E     - [u'typedetection', u'dictionary_valid_type', u'invalid_em_type']
E     + ['main', 'prepare_package', 'not_found']
```

**Comment by diox** [comment] 2016-09-22 16:05
It's a duplicate of https://github.com/mozilla/addons-server/issues/1828

I've investigated that in the past without finding the root issue - The original failure message was slightly different, I made it more explicit, but we still haven't been able to figure out where it's coming from.

**Closed by diox** 2016-09-22 16:05 UTC
Labels: code quality
