### ISSUE TITLE
`null` custom license `name` and `text` can be set through the addon submissions API

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19120] opened 2022-04-13 12:44 UTC
### Describe the problem and steps to reproduce it:
1. Upload a new add-on through the submissions API
2. Set a custom_license in the request JSON body with values set to `null`: 
`    "custom_license": {
        "name": {
            "en-US": null
        },
        "text": {
            "en-US": null}}
        `
3. Submit the add-on

### What happened?
The add-on is submitted successfully. Both custom_license `name` and the `text` will be `null`

`
   "license": {
        "id": 5144,
        "is_custom": true,
        "name": null,
        "slug": null,
        "text": null,
`

### What did you expect to happen?
`null` custom_license  `name` and `text` should not be accepted 

### Anything else we should know?
- `null` values can be set when sending a PATCH version request as well
- for the `name`, I think frontend has a fallback to 'Custom license' if the field value is `null`; the license text is empty, however
- can be reproduced in all environments
- Example: https://addons-dev.allizom.org/addons/addon/api/v5/621470/versions/1693956/

**Comment by eviljeff** [comment] 2022-04-19 11:24
this seems essentially the same as https://github.com/mozilla/addons-server/issues/19055 - that `null` is a valid value for localized fields

**Comment by eviljeff** [comment] 2022-05-04 09:06
This is already fixed with the fix(es) for #19055 but I'll add a test to prove it

**Closed** 2022-05-05 07:58 UTC
Labels: component: api, priority: p4

**Comment by ioanarusiczki** [comment] 2022-05-06 09:36
@eviljeff I could not reproduce this with POST -> create and new versions, and PATCH on versions api. 
it's a 400 Bad Request -> "A value in the default locale of \"en-US\" is required."
