### ISSUE TITLE
Icloud bookmark issue

### ISSUE THREAD

**Issue by andrewnorcross** [mozilla/addons-server#3139] opened 2016-07-20 23:32 UTC
I installed the iCloud app on my windows 10 machine and it directed me to merge my Safari bookmarks with my Firefox bookmarks (which is what I am looking to do).  When I hit the merge button, the app asks me to download the "iCloud Bookmarks extension for Firefox", but the link takes me to a "page not found" within the Firefox extension page.

Please advise.

Thanks!!

**Comment by andymckay** [comment] 2016-07-21 03:11
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by andymckay** 2016-07-21 03:11 UTC
