### ISSUE TITLE
Allow to retrieve only official language packs from API

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-server#8425] opened 2018-06-04 14:20 UTC
cc @aswan and @zbraniecki

Related to [bug 1429610](https://bugzilla.mozilla.org/show_bug.cgi?id=1429610) and issue #8198.

Right now, the API returns a list of all compatible language packs. For the use in Firefox, we'd only need the list of language packs owned by RelEng, i.e. reviewed and signed-off. The reason is that a language pack can easily generate a YSOD in the user's browser.

Given that Firefox would not be the only user of the API, I suppose there are two possible solutions:
* Add another type, e.g. `language-official`, doing the filtering on AMO side, since Firefox is not the sole user of existing API entry points.
* Add information to the response that would allow Firefox to filter results (e.g. the author ID).

Of the two options, the first seems less brittle.

**Comment by diox** [comment] 2018-06-04 14:33
Dupe of https://github.com/mozilla/addons/issues/730

I wasn't thinking about adding another type, I think I'd rather avoid it, but I can explore that idea a little. My plan was to add a `author=<username>` and have Firefox pass `author=mozilla` - we already use this author elsewhere - but I haven't started working on this yet.

**Closed by diox** 2018-06-04 14:33 UTC
