### ISSUE TITLE
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

### ISSUE THREAD

**Issue by services-ops** [mozilla/addons-server#6725] opened 2017-10-18 16:00 UTC
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/668574/

```
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
(10 additional frame(s) were not displayed)
...
  File "olympia/amo/decorators.py", line 144, in wrapper
    return f(*args, **kw)
  File "olympia/amo/decorators.py", line 131, in __call__
    return self.f(*args, **kw)
  File "olympia/bandwagon/tasks.py", line 91, in collection_meta
    addon_count=addon_count, all_personas=all_personas)

OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**Comment by diox** [comment] 2017-10-18 16:05
Dupe of https://github.com/mozilla/addons-server/issues/6629

**Closed by diox** 2017-10-18 16:05 UTC
