### ISSUE TITLE
Review mails have unescaped HTML characters

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-server#6505] opened 2017-09-26 04:57 UTC
### Describe the problem and steps to reproduce it:
I received a user review mail for my addon that has unescaped HTML `&#39;`.

### What happened?
The user review mail has unescaped HTML entities.

### What did you expect to happen?
The user review mail shouldn't have unescaped HTML entities.

### Anything else we should know?
It works fine on Frontend.
<img width="480" alt="screen shot 2017-09-26 at 10 25 00 am" src="https://user-images.githubusercontent.com/5318732/30843166-0d3448ae-a2a5-11e7-8abb-1068a3d59cca.png">
<img width="411" alt="screen shot 2017-09-26 at 10 25 31 am" src="https://user-images.githubusercontent.com/5318732/30843175-14d911de-a2a5-11e7-8fe0-b79706b48a44.png">

Checked for addon - https://addons.mozilla.org/en-US/firefox/addon/measure-it/

**Comment by diox** [comment] 2017-11-27 14:22
Accidentally fixed by #6817 :)

**Comment by ValentinaPC** [comment] 2017-11-27 14:49
@diox : I know that this issue is only about normal reviews, and that they were fixed because they are no longer listed in the e-mail... but, my question is: do we wanna fix the developer reply and reviewer reply that have the same issue as a normal review?
Please see screeenshot:
![dev_reply](https://user-images.githubusercontent.com/15685960/33272300-5af7e6e0-d392-11e7-9c47-3ddf473a6114.png)

**Comment by diox** [comment] 2017-11-27 15:27
@ValentinaPC mmm yeah, we do.

**Comment by diox** [comment] 2017-11-27 17:48
Actually a dupe of https://github.com/mozilla/addons-server/issues/4962

**Closed by diox** 2017-11-27 17:48 UTC
