### ISSUE TITLE
Add-on remains in Manual queue after being processed

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#20307] opened 2023-02-07 14:30 UTC
I found the add-on with ID mozilla_cc3@internetdownloadmanager.com in Manual queue.
Version 6.4.1 was Approved by the system, I reviewed it and Confirm Approved it, expecting the add-on to disappear from the Manual queue. 
Add-on is still present in the Manual queue.
Another add-on with the same issue: {0ac04bdb-d698-452f-8048-bcef1a3f4b0d}

**Comment by iulianacse** [comment] 2023-02-07 16:13
Another add-on, but this time it was a rejection
Add-on: sti@antaq.gov.br
Details: The last version (1.1.38) was in Awaiting Review state, it was reviewed and Rejected and it's still present in the Manual queue

**Comment by diox** [comment] 2023-02-07 16:24
> Another add-on, but this time it was a rejection
Add-on: [sti@antaq.gov.br](mailto:sti@antaq.gov.br)
Details: The last version (1.1.38) was in Awaiting Review state, it was reviewed and Rejected and it's still present in the Manual queue

Different problem. It still has a version (1.1.36) marked as needing human review with a due date.

**Comment by wagnerand** [comment] 2023-02-07 16:36
But it's still going to be fixed by your patch right?

**Comment by diox** [comment] 2023-02-07 16:44
No, because that one is not a bug, it's by design. For listed:
- Approval implicitly approves past versions in that channel, and removes any `needs_human_review` flags (and therefore due dates - except that was the bug here, we were not doing that. my patch fixes that)
- Rejection only rejects the specific version(s) rejected, and only removes `needs_human_review` flag (and therefore due dates) for those.

**Comment by wagnerand** [comment] 2023-02-07 16:50
> Rejection only rejects the specific version(s) rejected, and only removes needs_human_review flag (and therefore due dates) for those.

Ok that's fair but in this case, there is no way to get the add-on out of the queue. `needs_human_review`/`due_date` was set by a scanner for a version that was not approved and have been newer versions since then, so we can neither confirm an approval (because it didn't happen), nor manually approve (because it's not the latest version), nor reject (because the version/file is already disabled).
@iulianacse sounds like we want to split this off into a different issue. Could you do that?

**Closed** 2023-02-07 17:23 UTC
Labels: component:reviewer_tools, priority:p3

**Comment by AlexandraMoga** [comment] 2023-02-08 11:08
So, if I understand correctly, the STR are as follows:

1. Select an add-on from the Manual review queue that was auto-approved by the system (but still requires human review)
2. Confirm Approval for this add-on
3. Verify that the addon is no longer present in the Manual review queue once Auto-Approval was Confirmed

I've verified, based on the above STR, with a listed and an unlisted add-on, that Confirming Approval for both examples will remove the addon from the Manual review queue.

This is the [listed example](https://reviewers.addons.allizom.org/en-US/reviewers/queue/extension) and this the  [unlisted example](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1008187#review-actions) used; they were auto-approved but were marked by a rule as 'needs human review'.

I'm marking this issue as verified fixed on stage.

**Comment by KevinMind** [comment] 2024-05-04 19:14
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-249
