### ISSUE TITLE
Amazon Off Site Fullment

### ISSUE THREAD

**Issue by GaryHallSr** [mozilla/addons-server#3145] opened 2016-07-21 19:52 UTC
I tried to install 'Amazon Wish from Any Website: Your Wish List Is Universal' Icon (which I have had before) and FF says it can't find it.

Add items from any website to your Amazon List Learn how 
https://www.amazon.com/gp/wishlist/universal/ref=cm_wl_huc_uwl

Thanks.

Gary

**Comment by andymckay** [comment] 2016-07-27 19:34
This is a duplicate of #2991, the author has decided to remove the add-on. Sorry there's nothing we can do about it.

**Closed by andymckay** 2016-07-27 19:34 UTC
