### ISSUE TITLE
[AMO-dev] Error at web-extension submit

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2560] opened 2016-05-05 08:51 UTC
Maybe is related to #2555  

Steps to reproduce:
1. Try to submit the attached web-extension on AMO-dev

Expected results:
The web-extension can be submitted.

Actual results:
The web-extension cannot be submitted because of an error.

Notes/Issue:
**The web-extension can be submitted without problems in AMO-stage.**
Please see the screenshot: 
![2016-05-05_1114](https://cloud.githubusercontent.com/assets/15685960/15039710/a8135cc2-12b7-11e6-93f0-a406ef6bc770.png)

Attaching the web-extension:
[Tab-Wrangler test.zip](https://github.com/mozilla/addons-server/files/250138/Tab-Wrangler.test.zip)

**Comment by muffinresearch** [comment] 2016-05-05 12:31
Looks like a false positive caused by this line: line 129 of background.js

```javascript
window.setInterval(tabmanager.updateClosedCount, settings.get('badgeCounterInterval'));
```

**Comment by andymckay** [comment] 2016-05-05 18:53
@wagnerand, again assuming that although a setInterval could lead to an eval it should be a warning not an error that prevents validation. Its worth noting the new linter is quite a bit smarter than the old one, but want to get the levels right. 

In https://github.com/mozilla/addons-linter/issues/623#issuecomment-217145821 you suggest that only when the add-on is completely broken do we fail the validation with an error.

**Comment by ValentinaPC** [comment] 2016-05-06 13:26
Attaching another web-extension (maybe it helps you) that returns the same error and when accessing the full validation report we can see: 
![2016-05-06_1624](https://cloud.githubusercontent.com/assets/15685960/15074353/2f91da08-13a7-11e6-91a6-880495ca6c10.png)

[Tab-Suspender.zip](https://github.com/mozilla/addons-server/files/252284/Tab-Suspender.zip)

**Comment by wagnerand** [comment] 2016-05-06 13:55
Yes, this should be a warning instead of an error.

A million bonus points if we could update the rule to not trigger if the argument passed is a function. Otherwise, it leads to an awful lot of false positives (we know from experience of the old validator).

**Comment by andymckay** [comment] 2016-05-06 18:45
@wagnerand I think that's what https://github.com/mozilla/addons-linter/blob/master/src/rules/javascript/eval_string_arg.js#L13 is doin and the test is here https://github.com/mozilla/addons-linter/blob/master/tests/rules/javascript/test.eval_string_arg.js#L8.

**Comment by ValentinaPC** [comment] 2016-05-10 12:01
This issue is still reproducing on AMO-dev FF46(Win 7).
Verified with both above web-extensions.
Screenshot for this issue: 
![tabw](https://cloud.githubusercontent.com/assets/15685960/15145680/a98b9f5e-16bf-11e6-8f7c-e10abc43d28a.png)


@andymckay : I can check the "Override failed validation" box and continue with submission. I don't know is this is the intended behavior.

**Comment by andymckay** [comment] 2016-05-10 13:51
Ah the linter changes haven't been merged over yet.

**Comment by tofumatt** [comment] 2016-05-10 14:04
> Ah the linter changes haven't been merged over yet.

https://github.com/mozilla/addons-server/blob/master/package.json#L15 says addons-linter on AMO is up-to-date with out latest release (0.3.1).

Do we need to release a new version of the linter? I can do that ASAP.

**Comment by andymckay** [comment] 2016-05-10 14:20
This fix came right after that tag 😞 , I don't think much else is coming in on the linter right now, another release probably won't hurt.

**Comment by tofumatt** [comment] 2016-05-10 14:29
No prob, I’m on it!

**Closed** 2016-05-10 14:39 UTC
Labels: linter, pull request ready, WebExtensions

**Comment by ValentinaPC** [comment] 2016-05-11 10:37
Verified as fixed on AMO-dev FF46(Win 7) using the above extensions, the validation works as expected.
Please see the screenshots:
![submit](https://cloud.githubusercontent.com/assets/15685960/15178307/76df5eba-177d-11e6-80d9-983b731cf0c5.png)
![report](https://cloud.githubusercontent.com/assets/15685960/15178311/7ace0a12-177d-11e6-9514-7f42ac512964.png)
