### ISSUE TITLE
Release notes only appearing in author locale (en-CA)

### ISSUE THREAD

**Issue by ajayyy** [mozilla/addons-server#13637] opened 2020-02-11 21:37 UTC
### Describe the problem and steps to reproduce it:

The release notes are not appearing on my addon page when viewed from a locale that is not my own (en-CA).

### What did you expect to happen?

I expected that the release notes show the default locale if no translation is available.

### Anything else we should know?

I do have translations setup for the description, but not the release notes.

Locale links:

https://addons.mozilla.org/en-CA/firefox/addon/sponsorblock/ (visible)
https://addons.mozilla.org/en-US/firefox/addon/sponsorblock/ (not visible)
https://addons.mozilla.org/en-GB/firefox/addon/sponsorblock/ (not visible)

**Comment by diox** [comment] 2020-03-04 10:43
Long-standing issue, duplicate of #7535 - https://github.com/mozilla/addons-server/issues/7535#issuecomment-364572845 for an explanation of what's going on, it's not easy to fix.

**Closed by diox** 2020-03-04 10:43 UTC

**Comment by ajayyy** [comment] 2020-03-04 12:41
Is there a way to set my release notes to be in US English?

**Comment by diox** [comment] 2020-03-04 12:50
Easiest way right now is to copy-paste them in the US English locale. 

Go to the version page, you can edit the release notes from there. When editing them, there should be a language selector in the top right corner of the page to change the locale for the translated fields on the page.
