### ISSUE TITLE
iCloud bookmark extension for Firefox

### ISSUE THREAD

**Issue by suuzieg** [mozilla/addons-server#3091] opened 2016-07-13 11:41 UTC
Please could you advise when the iCloud bookmark extension for Firefox will be available to download?  I use Firefox constantly and to have the bookmarks synced with my iPhone is very handy. I don't like IE so I really do not want to have to resort to using it! Please help..
Thank you Sue Smith

**Comment by wagnerand** [comment] 2016-07-13 11:44
Dupe of #3027

The add-on was removed from the site due to stability problems.

**Closed by wagnerand** 2016-07-13 11:44 UTC

**Comment by suuzieg** [comment] 2016-07-13 15:29
Thank you for the prompt reply. Can you please say when this issue will be looked at and resolved as it is for everyone with iCloud and Firefox, an inconvenience, to say the least. 
Thank you, Sue

**Comment by wagnerand** [comment] 2016-07-13 15:39
Unfortunately, we can't do anything about this. The stability issues need to be resolved by the author of the add-on.
