### ISSUE TITLE
Split localization related tests to separate tox environment

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7207] opened 2018-01-04 10:16 UTC
This will allow us to run locale compilation only once for all tests since most of our tests don't depend on correct locales being present.

This will speed every single test-run up by at least 30-60 seconds.

**Comment by diox** [comment] 2018-02-15 23:40
dupe of https://github.com/mozilla/addons-server/issues/7465 which I fixed.

**Closed by diox** 2018-02-15 23:40 UTC
Labels: component: code quality, priority: p3, triaged
