### ISSUE TITLE
If there are no search suggestions, the "Search for <searchterm>" will not work on mouse click

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4690] opened 2017-02-15 14:11 UTC
Steps to reproduce:
1.Go to AMO Stage and enter a search term for which there are no search suggestions(ie. "dasdas")
2.Observe the "Search for <dasdas>" drop down link
3.Hover over it with the mouse and observe that it looks clickable
4.Mouse click on it

Expected results:
Search results are displayed

Actual results:
Nothing happens and search term is deleted from search box

NOTES:
By pressing ENTER on same search term, will return results
Reproducible on prod too

Please see video of the issue : 
![clickdontwork](https://cloud.githubusercontent.com/assets/1583842/22977931/53067fca-f399-11e6-9c7e-921a6ced46a3.gif)

**Comment by muffinresearch** [comment] 2017-02-15 16:23
Duplicate of https://github.com/mozilla/addons/issues/317

**Closed** 2017-02-15 16:23 UTC
Labels: state: duplicate
