### ISSUE TITLE
OpenSearch entries: "Add to Firefox" buttons still active after installation

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#7607] opened 2018-02-20 08:59 UTC
### Describe the problem and steps to reproduce it:
* Visit https://addons.mozilla.org/en-US/firefox/search/?type=search
* Click on any entry.
* Click on the "Add to Firefox" button.

### What happened?
* The "Add to Firefox" buttons are still blue after you have installed them. This shouldn't happen because you cannot install them again. You get this message if your'e trying to install them again. Example:
> Firefox could not install the search plugin from “https://addons.mozilla.org/firefox/downloads/file/412110/bookingcom-20160315.xml?src=dp-btn-primary” because an engine with the same name already exists.

### What did you expect to happen?
The "Add to Firefox" buttons should have a color that indicate that they cannot be used with a transparent color for OpenSearch entries if they have already been installed in Firefox.

**Comment by davidhedlund** [comment] 2018-02-20 09:49
The page uses the old layout with blue background. Is the https://addons.mozilla.org/en-US/firefox/search-tools/ deprecated?

Then I should mention this on another issue I submitted: https://bugzilla.mozilla.org/show_bug.cgi?id=1439514

**Comment by jvillalobos** [comment] 2018-02-20 16:29
Yes, that page is deprecated and will go away when the old front-end is no longer supported. The new page is the one Firefox points to, as you pointed out in the Bugzilla report.

Please specify which version of Firefox you were using that showed the transparent button.

**Comment by davidhedlund** [comment] 2018-02-20 16:31
@jvillalobos 
> Please specify which version of Firefox you were using that showed the transparent button.

Firefox 58.0.2 (64-bit) for GNU/Linux

**Comment by jvillalobos** [comment] 2018-02-20 22:41
I can reproduce the issue:

1) Go to https://addons.mozilla.org/en-US/firefox/search-tools/
2) Click on the Booking.com entry.

Result: the button has some transparency, but still allows installation (for me).

Oddly, if I go to AMO directly and search for "booking.com", I can find the same listing and the button looks right. So, it may have to do with the transition from old to new front end that causes the bug.

**Comment by davidhedlund** [comment] 2018-02-20 22:43
@jvillalobos Thank you for identifying this.

**Comment by AlexandraMoga** [comment] 2018-02-21 09:29
This was also reported a while back in [#4047](https://github.com/mozilla/addons-frontend/issues/4047)

**Comment by davidhedlund** [comment] 2018-02-21 09:34
@alamanda Thank you. @jvillalobos Can you please merge your [comment](https://github.com/mozilla/addons-server/issues/7607#issuecomment-367146522) to the issue she mentioned and close this issue?

**Comment by davidhedlund** [comment] 2018-02-21 09:38
@jvillalobos Well the issue should not be closed. I just removed the issue we discussed from it. The green button issue remains.

**Comment by davidhedlund** [comment] 2018-02-21 09:42
@jvillalobos I merged your comment.

**Comment by davidhedlund** [comment] 2018-02-21 09:56
@jvillalobos Can you please remove your comment https://github.com/mozilla/addons-server/issues/7607#issuecomment-367146522

I think you want to read this issue from the beginning again.

**Comment by jvillalobos** [comment] 2018-02-21 16:26
What's left in this bug is a duplicate of https://github.com/mozilla/addons-frontend/issues/3954

In the future, please try to break down issues into individual parts, so they are easier to track and resolve.

**Closed by jvillalobos** 2018-02-21 16:26 UTC

**Comment by davidhedlund** [comment] 2018-02-21 16:46
@jvillalobos 

> What's left in this bug is a duplicate of mozilla/addons-frontend#3954

Thanks.

> In the future, please try to break down issues into individual parts, so they are easier to track and resolve.

That is what I did.
