### ISSUE TITLE
Incorrect message while trying to save unaccepted changes

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#7060] opened 2017-11-29 13:40 UTC
Steps to reproduce:
1. Load Edit Listing page for an add-on i.e. https://addons.allizom.org/en-US/developers/addon/webext-1b/edit
2. Go to "Support Information" section and click "Edit"
3, Type something unaccepted in any field
4. Click "Save Changes"

Expected results:
Changes are not saved. An error is displayed. 

Actual results:
"Changes saved" green message is displayed even if changes were not saved.

Notes/Issues:
- reproducing for all fields when typing something unaccepted.
Verified on AMO-stage FF57(Win 7).
Video for this issue:
![cs](https://user-images.githubusercontent.com/15685960/33377597-b8a76840-d51a-11e7-821b-fb7074fcab53.gif)

**Comment by muffinresearch** [comment] 2018-02-02 16:39
Duplicate of https://github.com/mozilla/addons-server/issues/3098

**Closed by muffinresearch** 2018-02-02 16:39 UTC
Labels: component: devhub, priority: p4, triaged, type: bug
