### ISSUE TITLE
Diferent results for same empty search

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#6190] opened 2017-08-17 14:26 UTC
Steps to reproduce:

1. Perform an empty search.
2. Perform the same empty search a few more times.

Expected results:
The results are displayed in the same order.

Actual results:
The results are displayed in different orders, this issue also reproduces when refreshing the page after the search is performed.

Notes/Issues:
Verified on AMO-dev FF55(Win 10).
Gif for this issue:
![empty search dif results](https://user-images.githubusercontent.com/28138132/29417238-2e862c82-8371-11e7-99b8-ef8d4ab7af8b.gif)

**Comment by EnTeQuAk** [comment] 2017-08-18 09:13
I'm assigning this to me to re-test once https://github.com/mozilla/addons-server/pull/6171 get's merged, I can't reproduce this with the changes in #6171 anymore.

**Comment by EnTeQuAk** [comment] 2017-08-18 17:23
This seems to have been fixed by https://github.com/mozilla/addons-server/pull/6171, I can't reproduce this anymore on -dev.

Please feel free to re-open in case I missed anything.

**Closed by EnTeQuAk** 2017-08-18 17:23 UTC
Labels: component: search, platform: windows, triaged

**Comment by vcarciu** [comment] 2017-08-21 11:19
@EnTeQuAk 
Please let me know if this should be applied to Collections search , where the issue is still reproducible :  
![searchsearch](https://user-images.githubusercontent.com/1583842/29517004-a5860340-867b-11e7-84e3-03b455c21520.gif)

**Comment by EnTeQuAk** [comment] 2017-08-21 11:43
mhmm, seems like this still fails. But I can't reproduce this anymore with my recent changes for regular add-ons search.

Mind opening a new issue for collections search being random like that?

**Comment by vcarciu** [comment] 2017-08-21 11:45
@EnTeQuAk : sure, thanks

**Comment by SVSanta** [comment] 2017-08-28 13:31
Verified as fixed on AMO-dev FF55(Win 10).
Postfix gif:
![fixed empt search](https://user-images.githubusercontent.com/28138132/29775590-497db1ae-8c0e-11e7-9acc-aa818e60d176.gif)
