### ISSUE TITLE
Release notes are not submittable

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/addons-server#6627] opened 2017-10-09 19:45 UTC
### Describe the problem and steps to reproduce it:

When upgrading Lightbeam, two of the last updates haven't been able to submit release notes.

### What happened?

The following code is there:
```
<div id="trans-releasenotes" class="trans" data-name="releasenotes"><textarea cols="40" id="id_releasenotes_0" name="releasenotes_en-gb" rows="10" style="display: none;" lang="en-gb"></textarea><textarea class="trans-init" cols="40" name="releasenotes_init" rows="10" style="display: none;" lang="init"></textarea></div>
```

### What did you expect to happen?

To see the text field.

**Comment by jvillalobos** [comment] 2017-10-09 21:32
Is this during the new version submission steps? Is the field just missing or do you see some kind of error? Can you add the release notes in the developer hub pages after you're done submitting?

**Comment by jonathanKingston** [comment] 2017-10-09 22:43
> Is this during the new version submission steps?
When viewing the extension version I can see the comments box. I can't when submitting the new version.

I also haven't had this on my own extension like merge windows.

>  Is the field just missing or do you see some kind of error? 

It looked like the field was `display: none;` as the code was above however I didn't see any warnings.

**Comment by jvillalobos** [comment] 2017-10-09 23:07
Tried submitting the latest version on -dev and I can see the Release Notes field.

Was the textarea the only thing that was missing? Was the `Release Notes` text there?

**Comment by diox** [comment] 2017-10-09 23:29
What locale were you using (look in the URL) ?

**Comment by jonathanKingston** [comment] 2017-10-09 23:30
en-GB

**Comment by diox** [comment] 2017-10-09 23:40
Yeah so, I can reproduce, it's tied to how localized fields work.

STR:
- Submit an add-on, make sure its default locale is en-US
- From an en-GB URL, submit a new version (i.e. start from https://addons-dev.allizom.org/en-GB/developers/ if you're on dev)

Expected Results:
- The release notes are editable in version submission

Actual Results:
- The release notes are not editable in version submission. It does work *afterwards* though, when editing the version that was just submitted.

**Comment by diox** [comment] 2017-10-09 23:40
Aaand it's actually a dupe of https://github.com/mozilla/addons-server/issues/4599

**Closed by diox** 2017-10-09 23:40 UTC

**Comment by jonathanKingston** [comment] 2017-10-10 00:15
Thanks for chasing, sorry for the dupe!

**Comment by diox** [comment] 2017-10-10 00:20
No apologies necessary, it was hard to find, it's a pretty obscure (and annoying...) bug :(
