### ISSUE TITLE
Firefox 46 unable to add new version of unlisted, multi-platform Valence add-on

### ISSUE THREAD

**Issue by jryans** [mozilla/addons-server#1503] opened 2016-01-22 20:33 UTC
The DevTools team manages the Valence add-on.

I tried to submit a new version of it today, but the add version form fails when I press the "Add Version" button, and says "The submitted file is empty."

I tested this in Firefox 46. If I use Chrome, it works correctly.

I did not see any errors in the console during this process.

![amo-error](https://cloud.githubusercontent.com/assets/279572/12522229/0ea9d546-c115-11e5-91ce-7749587d19e9.png)

**Comment by jryans** [comment] 2016-01-22 20:45
I tested a fresh Firefox profile in 46, same error. Disabling tracking protection had no effect.

It works in Firefox 45. So, there is something in vanilla Firefox 46 that does not like this page.

**Comment by jvillalobos** [comment] 2016-01-22 20:57
I experienced the same problem earlier today on -dev. I'm also on Nightly.

**Comment by jvillalobos** [comment] 2016-01-25 16:57
Dupe of this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1242231

**Comment by magopian** [comment] 2016-01-26 09:47
So, is this only happening randomly? I just tried uploading a new version using nightly locally and with firefox 44 on -dev, and couldn't reproduce.

What I noticed though is that there's a delay when you click on the "submit" button, with no feedback at all. Maybe clicking several times in a row is what's causing the issue?

I couldn't reproduce the exact same error message (which seems to come from the django FileField) by clicking several times on the button, but another that said "couldn't parse the install.rdf".

Is there a way for me to reproduce this exact same error? In the meantime I'll add some feedback on the button press and prevent the multiple submission.

**Comment by magopian** [comment] 2016-01-26 11:01
Closing for now with the fix in #1520, please reopen if that doesn't do the trick of if there's more info on how to reproduce the issue, thanks!

**Comment by magopian** [comment] 2016-01-26 13:45
Another account of this happening was filed in https://github.com/mozilla/addons/issues/23

**Comment by jryans** [comment] 2016-01-26 13:50
@magopian this is still happening for me.

> So, is this only happening randomly? I just tried uploading a new version using nightly locally and with firefox 44 on -dev, and couldn't reproduce.

You need to use Firefox 46. It only reproduces with that version of Firefox. (Possibly also 47, I have not tried that yet.) I am testing on prod AMO, unsure what the state of things is on the dev instance.

I am not clicking anything multiple times. I use "Select a file..." to choose the add-on file. I wait for validation to complete. Then I click "Add Version", and the error "The submitted file is empty." appears very quickly, like it shows in the image above.

**Comment by magopian** [comment] 2016-01-26 14:05
I also managed to reproduce the issue with the latest nightly, on prod and locally. So nothing related to prod, and it happens with a single click, even when waiting for a couple of minutes before submitting.

**Comment by magopian** [comment] 2016-01-26 16:25
After much investigation, it seems the `FormData` behavior changed from FF 46: https://bugzilla.mozilla.org/show_bug.cgi?id=1241171

The problem is that it's submitting an empty file with a filename (`blob`), and then Django believes it's a real file, and can't read it, thus the error message. This is for the "source" file input.

I've filed another bug to make it clearer what form input is erroring, instead of just dumping the error message at the top of the form: #1525

**Comment by magopian** [comment] 2016-01-26 16:25
I'm going to close this one now, as I don't believe there's anything we can do on our end.

**Comment by dgutov** [comment] 2016-01-30 21:08
I've just had the same problem, and couldn't complete addon submission without attaching the sources archive. With it, submission completed fine. Firefox 46.0 here.

**Comment by jyavenard** [comment] 2016-02-04 09:41
Actually, in my case (bug #1615) the problem was due to the LastPass 4.0 addon. Once I disabled lastpass I could press the "Add Version" button

**Comment by dgutov** [comment] 2016-02-04 09:44
I have KeeFox installed. Will have to try with it disabled next time.

**Comment by krupa** [comment] 2016-02-29 21:25
I still get this error message on 47.0a1 (2016-02-23) when uploading new versions to addons-dev.
https://www.dropbox.com/s/1np5l9acuh929ei/Screenshot%202016-02-29%2013.19.11.png?dl=0

**Comment by eviljeff** [comment] 2016-03-04 18:02
I'm getting this today without lastpass or keefox or anything special installed (adb helper and valance).  Dev and prod.

**Comment by themighty1** [comment] 2016-08-06 20:35
Getting this bug on FF47

**Comment by muffinresearch** [comment] 2017-02-20 17:04
@krupa can you still reproduce this issue?

**Comment by ValentinaPC** [comment] 2017-02-21 08:28
@muffinresearch :
Verified this using FF46 (Win 7) for the following cases:
- new version for a listed add-on
- new version for an unlisted add-on
- new listed version for an unlisted add-on
- new unlisted version for a listed add-on
- new file for unlisted/listed version 
For all mentioned cases I was able to finalize the submission process and the add-on was updated. No error displayed in AMO or in console.

Verified this also on latest Nightly - uploading a new unlisted version for an add-on was made with success. 

One of the examples: https://addons-dev.allizom.org/en-US/developers/addon/twitter-assistant1/versions

I'll attach the used add-on.
[test-addon-multi.zip](https://github.com/mozilla/addons-server/files/789464/test-addon-multi.zip)

If further investigation is required, please let me know. Thanks!

**Comment by muffinresearch** [comment] 2017-02-21 12:09
Based on https://github.com/mozilla/addons-server/issues/1503#issuecomment-281276323 closing

**Closed by muffinresearch** 2017-02-21 12:09 UTC
Labels: triaged
