### ISSUE TITLE
Cannot upload addon sources

### ISSUE THREAD

**Issue by aemdy** [mozilla/addons-server#1995] opened 2016-03-26 10:51 UTC
When uploading sources for my addon https://addons.mozilla.org/en-US/developers/addon/si%C5%ABlyk-antra%C5%A1t%C4%99/versions/1837316, I am getting a server error http://prntscr.com/ak7slf.

**Comment by jvillalobos** [comment] 2016-03-28 17:55
Can you attach them here? If not, can you send them to amo-editors AT mozilla DOT org?

**Comment by aemdy-revel** [comment] 2016-03-28 19:39
Sources sent via email.

**Comment by aemdy** [comment] 2016-03-28 19:40
Sources sent via email.

**Comment by EnTeQuAk** [comment] 2016-04-20 14:40
I can't reproduce the server error anymore, does this still happen for you?

**Comment by aemdy** [comment] 2016-04-25 05:43
@EnTeQuAk, yes. Tried with the same sources on this version https://addons.mozilla.org/en-US/developers/addon/si%C5%ABlyk-antra%C5%A1t%C4%99/versions/1837316

**Comment by andymckay-limited-access** [comment] 2016-05-24 16:22
@EnTeQuAk is this related to the unicode in the slug?

**Comment by andymckay** [comment] 2016-06-03 16:21
Closing in favour of #2828 which @diox says more info.

**Closed by andymckay** 2016-06-03 16:21 UTC
Labels: priority two, triaged

**Comment by diox** [comment] 2016-06-08 12:55
Because of the unicode name in the slug it might atually be a dupe of mozilla/addons#132
