### ISSUE TITLE
Add-on Statistics Are Broken

### ISSUE THREAD

**Issue by JonathonGold** [mozilla/addons-server#3429] opened 2016-09-06 19:19 UTC
https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30

All stats is 0 for the previous 6 days. Please fix!

**Comment by andymckay** [comment] 2016-09-06 19:23
Duplicate of #3406.

**Closed by andymckay** 2016-09-06 19:23 UTC
