### ISSUE TITLE
Add-on Developer Hub logo is displayed with layout issues in some languages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7298] opened 2018-01-15 14:05 UTC
Prerequisites:
User is logged in

Steps to reproduce:
1. Load AMO page and click on Developer Hub
2. Click on My Add-ons
3. Change the language from en-US to Italian 
4. Observe the logo

Expected result:
The Logo is correctly displayed. 

Actual result:
The black text overlaps the white text. 

Notes:
Reproduced on AMO dev and AMO stage with FF57(Win 10).
I reproduced this issue with Spanish, Italian, French, Polish, Portuguese, Bulgarian, Bahasa Indonesia, Romanian.

![developer hub logo](https://user-images.githubusercontent.com/33448286/34945664-b08296a0-fa0c-11e7-8632-c145596c9f49.gif)

**Comment by anweshknayak** [comment] 2018-01-24 16:12
Can I take this up ?

**Comment by muffinresearch** [comment] 2018-01-24 16:40
@anweshknayak hi feel free to go ahead and let me know if you have any questions. Please reference this issue in your PR.

**Comment by caitmuenster** [comment] 2018-02-21 16:38
Hey @anweshknayak, how's it going with this bug?

**Comment by caitmuenster** [comment] 2018-03-07 16:43
@anweshknayak, we're going to open this bug up for other contributions to take since we haven't heard from you in awhile. Please do feel welcome to come back and pick up another bug!

**Comment by anweshknayak** [comment] 2018-03-07 16:44
hey @caitmuenster sorry. I missed this. I am a bit occupied with some stuff lately. So I am not able to look into this. :smile:

**Comment by gponimansky** [comment] 2018-03-16 01:47
Issue stems from the grammar of several languages, [Russian Example](https://github.com/mozilla/addons-server/blob/7013e50e0687b48bbd88c89fb8af867c1eca4843/locale/ru/LC_MESSAGES/django.po#L2847).
A possible fix is adding inline CSS of margin-top: 20px to the <small> tag. 

However that will require the changing several language files, and possibly impact the other [CSS margins](https://github.com/mozilla/addons-server/blob/3bcd6bff14a247d0cf600eaeef49bd051783d617/static/css/restyle/restyle.less#L326).

**Comment by is2ei** [comment] 2018-05-21 00:30
Hi, I'm Issei.
Could I work on this issue?

**Comment by caitmuenster** [comment] 2018-05-21 16:30
Hey @is2ei! Go for it! Feel free to let @muffinresearch know if you have any questions. :)

**Comment by is2ei** [comment] 2018-05-27 04:00
@muffinresearch 
Is this fixed in #7298 ?

**Comment by muffinresearch** [comment] 2018-05-29 15:45
> Is this fixed in #7298 ? 

@is2ei I don't understand the question. The linked issue is this bug. Did you mean to link some other issue or PR?

**Comment by is2ei** [comment] 2018-05-30 00:31
@muffinresearch 
Sorry, the link was wrong. I mean this commit refers this issue #7298 https://github.com/gponimansky/addons-server/commit/7013e50e0687b48bbd88c89fb8af867c1eca4843 
The comment says "Fixed Issue #7298".

**Comment by gponimansky** [comment] 2018-05-30 00:33
Oh @is2ei it's a workaround fix will update it. I suggested where a true fix may take place.

**Comment by is2ei** [comment] 2018-06-11 23:18
@gponimansky 
Thanks for your comment! I confirmed the issue can be reproduced. I will work on this issue.

**Comment by is2ei** [comment] 2018-06-12 13:47
Hi @muffinresearch 
Could I ask you a question?
I tried to run addons server locally.
I got an error. Do I miss any instruction? 
https://pastebin.mozilla.org/9087468

**Comment by muffinresearch** [comment] 2018-07-25 15:38
@is2ei sorry for the slow reply. That should be all you need to reproduce. Just change the locale to see the header in different languages. From the OP the bug was reproducible in the Italian locale.

**Comment by caitmuenster** [comment] 2018-08-08 15:41
Hey @is2ei, are you still interested in working on this bug?

**Comment by andreip** [comment] 2018-08-10 21:47
@caitmuenster @muffinresearch I've got the docker setup and tried to reproduce this, but the header doesn't seem to be translated on my local (see below screenshot), which is similar to what @is2ei posted anyway, notice his url is for italian, but the text is still _mostly_ in english.  Notice that "Documentazione" and the one I selected in the dropdown are translated, but mostly rest is still in english. That's a bit strange, since navigating to https://addons.mozilla.org/it/developers/addons clearly shows you've got translations for a lot more words on the website.

<img width="1111" alt="screen shot 2018-08-10 at 2 43 13 pm" src="https://user-images.githubusercontent.com/721171/43982736-358297aa-9cac-11e8-8fbd-3714ee6b7199.png">

**Comment by EnTeQuAk** [comment] 2018-08-13 09:57
So, from the GIF attached to the bug report the actual layout issue occurs for the `pt-PT` locale, and not Italian.

Maybe that helps reproducing this?

**Comment by andreip** [comment] 2018-08-16 18:20
Thanks! I eventually figured out that the issue was I didn't have the `.mo` files compiled on local. I ran these to fix it:

```bash
$ docker-compose exec web ./locale/compile-mo.sh ./locale/
$ docker-compose restart web
```

**Comment by andreip** [comment] 2018-08-16 19:45
@muffinresearch if you're still the one I should notice, I submitted a PR here https://github.com/mozilla/addons-server/pull/9182

**Comment by caitmuenster** [comment] 2018-08-16 19:51
Thanks @andreip -- @muffinresearch is out on PTO for the next two weeks but @EnTeQuAk might be able to review your PR or find someone else to take a look at it soon. :)

**Closed** 2018-08-17 05:42 UTC
Labels: component: devhub, contrib: assigned, contrib: good first bug, contrib: mentor assigned, priority: p4, triaged

**Comment by ioanarusiczki** [comment] 2018-08-20 09:02
Verified fixed on AMO -dev with FF61(Win10)
Polish
![polish](https://user-images.githubusercontent.com/33448286/44330876-c7ca0c80-a470-11e8-847d-68b3563fd403.png)
Romanian
![romanian](https://user-images.githubusercontent.com/33448286/44330891-cf89b100-a470-11e8-8d20-9141cc0d5305.png)
Spanish
![spanish](https://user-images.githubusercontent.com/33448286/44330901-d44e6500-a470-11e8-9e10-59a975debb56.png)
