### ISSUE TITLE
Version detail pane is cut off

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8272] opened 2018-05-16 15:40 UTC
Example URL: https://addons.mozilla.org/en-US/firefox/addon/har-export-trigger/

<img width="826" alt="screen shot 2018-05-16 at 16 48 04" src="https://user-images.githubusercontent.com/873258/40127608-0fcbae26-5930-11e8-98d7-2a169f878836.png">

Looks like it doesn't happen for all resolutions, but I can definitely reproduce on my monitor.

**Comment by eviljeff** [comment] 2018-05-17 17:51
Can't replicate with that addon any more - a new version has been approved.
Realistically as this is legacy frontend it's a wontfix anyway.

**Comment by wagnerand** [comment] 2018-05-17 17:53
Can still reproduce. As I said, it might depend on your resolution or screen size.

Also I @muffinresearch before I filed this to see whether it's even worth it.

**Comment by eviljeff** [comment] 2018-05-17 18:14
It's a minor UI issue on legacy frontend that only affects certain users with certain monitor resolutions... I stand by my wontfix opinion.

**Comment by muffinresearch** [comment] 2018-05-17 18:30
@wagnerand I can't reproduce either currently. Can you provide details of how to repro e.g. what resolution you're running?

**Comment by wagnerand** [comment] 2018-05-18 11:41
The height of the viewport needs to be large enough so all content fits on the screen when the page is being loaded.

The reason for that seems to be https://github.com/wagnerand/addons-server/blob/master/static/css/impala/footer.less#L13 . Removing `position: absolute` fixes it.

**Comment by EnTeQuAk** [comment] 2018-06-22 16:20
Given that this is the last open issue in our "legacy frontend" label and that we'll eventually end up implementing this in the new frontend I don't think it's worth fixing any edge-cases anymore.

I'm closing this. If anyone objects to it, by all means, please re-open. I also don't think contributions make much sense here.

**Closed by EnTeQuAk** 2018-06-22 16:20 UTC
Labels: component: legacy frontend, priority: p4, triaged
