### ISSUE TITLE
Missing iCloud for windows bookmark extension

### ISSUE THREAD

**Issue by cmhanlon** [mozilla/addons-server#3047] opened 2016-07-05 18:14 UTC
There was an issue with the extension that seems to have been fixed, but the add-on is no longer available. Expecting to see the iCW Firefox Bookmark extension here: https://addons.mozilla.org/en-US/firefox/addon/icloud-bookmarks/

**Comment by wagnerand** [comment] 2016-07-05 18:23
Dupe of #3027

The add-on was removed from the site due to stability problems.

**Closed by wagnerand** 2016-07-05 18:23 UTC
