### ISSUE TITLE
New version notifications will always contain a link to the add-on review page which can't be accessed by users in a different reviewer group

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7446] opened 2018-01-31 10:12 UTC
Follow up from [#7420](https://github.com/mozilla/addons-server/issues/7420)

STR;

Prerequisites: log in with a user that has Review:Content permissions

1. Log into Developer Hub and submit a new listed add-on
2. Wait for the add-on to pass auto approval
3. Go to Reviewer Tools and select the Content review queue
4. Pick an add-on to open its review page
5. Scroll down to More Actions section and mark the 'Notify me about new listed version" option
6. Go back to Dev Hub ans submit a new listed version for your add-on
7. With an Admin account, go to Admin Tools -> Fake email and check the notification sent to the content reviewer

Actual result:
The notification received by the content reviewer contains a link to the Add-on review page, inaccessible by a user with Review:Content permission (i.e. https://addons-dev.allizom.org/reviewers/review/<addon ID>

Expected result:
The notification received by the content reviewer contains a link to the Add-on content review page in the format  https://addons-dev.allizom.org/reviewers/review-content/<addon ID>

Notes:
- reproduced on AMO-dev with FF58, (Win10)

**Comment by wagnerand** [comment] 2018-01-31 11:28
I believe this is a dupe of #6936.

**Closed by wagnerand** 2018-01-31 11:28 UTC
Labels: component: reviewer tools
