### ISSUE TITLE
Dictionary not installable on Firefox Nightly

### ISSUE THREAD

**Issue by Mte90** [mozilla/addons-server#5825] opened 2017-07-03 15:42 UTC
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary/ with Firefox Nightly
Also for:

- https://addons.mozilla.org/it/firefox/addon/united-states-english-spellche/
- https://addons.mozilla.org/it/firefox/addon/us-english-dictionary/

### What happened?
Actually is not installable.

### What did you expect to happen?
Install the dictionary on Firefox

### Anything else we should know?

* https://addons.mozilla.org/it/firefox/language-tools/ the list for all the dictionary suggested
* https://addons.mozilla.org/it/firefox/addon/dizionario-italiano/ this one don't have the problems because is updated by the panel
* @flodolo confirm that the manifest is updated automatically on new firefox release (maintain the italian one)

**Comment by jvillalobos** [comment] 2017-07-03 18:04
It looks like the latest bulk compatibility update didn't include dictionaries, which it apparently did before. @wagnerand, can you look into this?

I'll file a separate issue to give dictionaries the same compatibility behavior as extensions.

**Comment by wagnerand** [comment] 2017-07-04 09:30
There were no changes in the process for the last bulk validation compared to the one before.

Also, both https://addons.mozilla.org/it/firefox/addon/united-states-english-spellche/ and     https://addons.mozilla.org/it/firefox/addon/us-english-dictionary/ have their maxVersion set to 55.*, as expected, so I assume the bulk validation ran correctly.

**Comment by flodolo** [comment] 2017-07-04 10:23
I think the request would be to make them compatible by default with Nightly instead of Beta.

**Comment by wagnerand** [comment] 2017-07-04 10:25
Ah. I suppose that's not a regression but more of a change of process, which I think will be solved in #5830 anyway, so I'm closing this.

**Closed by wagnerand** 2017-07-04 10:25 UTC
