### ISSUE TITLE
Redesign introduces an additional click before the user can install featured extensions

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#6567] opened 2017-10-02 20:33 UTC
### Describe the problem and steps to reproduce it:
1. Compare https://addons.allizom.org/en-US/firefox/extensions/featured/ to https://addons.mozilla.org/en-us/firefox/extensions/?sort=featured
2. Notice that in the redesign, the call-to-action button is not listed and the user actually has to click to navigate to the details page to install the add-on

### What happened?
 In the redesign, the call-to-action button is not listed and the user actually has to click to navigate to the details page to install the add-on

### What did you expect to happen?
We keep the number of clicks required to get the user to install something to a minimum.

### screenshot
<img width="1404" alt="screenshot 2017-10-02 13 31 34" src="https://user-images.githubusercontent.com/301317/31098026-2f375592-a776-11e7-8144-dd6c31bbaee2.png">

**Comment by muffinresearch** [comment] 2017-10-02 20:35
Related and part dupe of https://github.com/mozilla/addons-frontend/issues/3153

**Comment by eviljeff** [comment] 2017-10-03 11:31
Is this an addons-server issue?  I don't see the change in the legacy frontend - https://addons.allizom.org/en-US/firefox/extensions/?sort=featured on legacy frontend still has install buttons for compatible add-ons.

**Comment by eviljeff** [comment] 2017-10-12 15:39
Closing as not an addons-frontend bug.

**Closed by eviljeff** 2017-10-12 15:39 UTC
Labels: triaged
