### ISSUE TITLE
Check for updates fails on time-out

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/addons-server#19837] opened 2022-10-31 20:04 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Click "Check for updates" in the about:addons page.

### What happened?
The check takes about 60 seconds and then it says no updates found. In the browser console when you enable requests logging I can see they all timed out:
```
20:49:27.326 1667245767325	addons.update-checker	WARN	Request for https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id={16cbd87c-eb99-4f5c-9825-83cf13ab7ff8}&version=2.1&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=107.0&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=107.0&updateType=97&compatMode=normal timed out
20:49:27.327 1667245767327	addons.update-checker	WARN	Request for https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=admin@fastaddons.com_Ctrl_GroupSpeedDial&version=2.6&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=107.0&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=107.0&updateType=97&compatMode=normal timed out
20:49:27.328 1667245767328	addons.update-checker	WARN	Request for https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=steam-context-menu@skylark95.com&version=1.2.2&maxAppVersion=*&status=userDisabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=107.0&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=107.0&updateType=97&compatMode=normal timed out
20:49:27.328 1667245767328	addons.update-checker	WARN	Request for https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id={9ea6f004-dfa1-4d80-8cb0-b3f8bfe9004d}&version=1.1.0&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=107.0&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=107.0&updateType=97&compatMode=normal timed out
20:49:27.328 1667245767328	addons.update-checker	WARN	Request for https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=admin@fastaddons.com_SendNoteToDevice&version=2.6&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=107.0&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=107.0&updateType=97&compatMode=normal timed out
20:49:27.328 1667245767328	addons.update-checker	WARN	Request for https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=display-anchors@robwu.nl&version=1.3&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=107.0&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=107.0&updateType=97&compatMode=normal timed out 
```
Or, I've just tried again and it failed with:
```
21:02:29.650 1667246549650	addons.update-checker	WARN	HTTP Request failed for an unknown reason
21:02:29.651 1667246549651	addons.update-checker	WARN	HTTP Request failed for an unknown reason 5
21:02:29.652 1667246549652	addons.update-checker	WARN	HTTP Request failed for an unknown reason 5
21:02:29.653 1667246549653	addons.update-checker	WARN	HTTP Request failed for an unknown reason 8
21:02:29.654 1667246549654	addons.update-checker	WARN	HTTP Request failed for an unknown reason 6
21:02:29.655 1667246549655	addons.update-checker	WARN	HTTP Request failed for an unknown reason 7
21:02:29.656 1667246549656	addons.update-checker	WARN	HTTP Request failed for an unknown reason 6
21:02:29.657 1667246549657	addons.update-checker	WARN	HTTP Request failed for an unknown reason 8
21:02:29.658 1667246549658	addons.update-checker	WARN	HTTP Request failed for an unknown reason 
```

### What did you expect to happen?
Check for updates works on ESR and my release version. But it fails on my Developer Edition at work and also at home. For several days now.

**Comment by Juraj-Masiar** [comment] 2022-10-31 20:41
A lot actually, in the "about:support" page in the "Add-ons" section I can see 54 lines. But some of those are build-in addons, like search providers.

But I do have a lot of disabled addons, I didn't know they are part of the check. Maybe I should remove some of them...

**Comment by diox** [comment] 2022-10-31 20:45
Do you have the same high number of add-ons on your versions where updates are working ?

**Comment by Juraj-Masiar** [comment] 2022-10-31 20:48
Nope, and that seems that's the main cause. I've just removed 10 of my disabled addons and now it works! :)
Thanks!

**Comment by diox** [comment] 2022-10-31 20:48
That's still worrying...

If you open the Browser Toolbox and go to the network tab, then check for updates, on the instance where it's not working, select a request that went into a timeout and check the timings tab on the right, what do you see ?

**Comment by wagnerand** [comment] 2022-10-31 20:50
> That's still worrying...
> 
> If you open the Browser Toolbox and go to the network tab, then check for updates, on the instance where it's not working, select a request that went into a timeout and check the timings tab on the right, what do you see ?

There is no timing information since the request does not succeed.

**Comment by Juraj-Masiar** [comment] 2022-10-31 20:51
Sadly, I can't reproduce it anymore as I've removed those addons which fixed the problem.

**Comment by diox** [comment] 2022-10-31 20:51
Ok, I was hoping the part that worked would still be shown. It would be interesting to figure out what's the exact number that makes it fail, if it is linked to how many requests we're making in parallel. Maybe we can build a testcase using a simple webpage doing XHRs in parallel...

**Comment by Juraj-Masiar** [comment] 2022-10-31 20:57
Well, from the log I've posted in the first comment (the second log, the first was not complete) it made 47 requests in 0.8 millisecond, so that looks like a 47 parallel requests.

**Comment by wagnerand** [comment] 2022-10-31 21:14
I can also reproduce this on Beta and Release.

**Comment by Juraj-Masiar** [comment] 2022-11-01 07:49
So I'm at work where Firefox quickly synced my removed addons but somehow the check for updates still fails, even though I see only 42 addons in my about:support page.
Here are the logs from browser console:

![Screenshot 2022-11-01 084507](https://user-images.githubusercontent.com/6358971/199184539-818dfff9-34e1-4d0c-8a3e-2f5c5b71a37c.png)
![Screenshot 2022-11-01 084632](https://user-images.githubusercontent.com/6358971/199184550-9cf68a69-9559-4b04-a3cd-d8b0fc67b7ab.png)

**Comment by AlexandraMoga** [comment] 2022-11-02 14:51
I've done some exploratory testing on addon updates to see if I can reproduce the issue and here are my preliminary results:

AMO prod (versioncheck prod) with Firefox release, new profiles:
- the update timeout starts to reproduce when 25 addons or more have been installed on a profile; I did try with 24 addons and I could not reproduce the issue. To actually see the requests failing, I had to wait ~ 30 minutes between the first and next update check. The exact steps I've made are as follows: 
1. install 25 addons on a new profile
2.  check for updates => updates were successful, i.e. versioncheck responds with a 200 status code for each of the installed addons
3. wait ~ 30 minutes
4. check for updates again => versioncheck is no longer responding:
![image](https://user-images.githubusercontent.com/31961530/199516637-f198cb24-4d55-4b76-ab0d-4bcc2d03a828.png)
5. wait another ~30 minutes
6. check for updates again => updates were successful, i.e. versioncheck responds with a 200 status code for each of the installed addons

AMO -dev and stage (versioncheck pointed to dev and stage), Unbranded release:
- AMO -dev: using the same test method as above, I've managed to reproduce the issue once
- AMO stage: using the same test method as above, after the first failed update check I wasn't able to trigger updates anymore => all consecutive requests would timeout

I will keep these test profiles open and continue to monitor the update checks to see if the results are changing.

**Comment by AlexandraMoga** [comment] 2022-11-03 12:11
Some updates after having revisited the profiles this morning:

AMO prod and stage, with 25 addons installed, the update check still times out after having left the profile open overnight. I've restarted the profile, checked for updates again and the updates were triggered successfully after the restart. Then, I left the profile open for a short while (under 10 minutes) and the timeout started to reproduce again when I've checked for updates next time. After another profile restart, the updates were working again.

If I uninstalled one of the addons after I received the timeout (so the total number of installed addons was reduced from 25 to 24) and then checked for updates, versioncheck was triggered successfully. I've also left the profile open for a while, then checked for updates and the request was still successful. Finally, I've re-installed one of the addons to go back to 25 and the timeout was reproducing again on the next update check. 

On AMO -dev I can't reproduce the issue  anymore. I have a profile left open with 35 addons installed and so far I haven't received a timeout.

**Comment by ioanarusiczki** [comment] 2022-11-03 12:50
My results: 

On AMO dev:
I started yesterday with 25 addons and waited 30 min or so -> the update failed. I removed an addon and waited 30 more min -> the update was successful
I restarted this morning the profile and after that I tried with 25, 26 and 27 addons at 30 min intervals between each attempt -> all updates were successful 

On AMO prod:
Today with a new profile I installed 25 addons and I immediately tried the update -> failed. 
I started removing addons -> when I was at 22 addons the update worked 
I reinstalled 26 addons and I started waiting longer (not sure it was 30 plus) but the update failed again. It also failed with 25. Then at 24 addons the service worked. 
I reinstalled 26 addons and restarted the browser this time counted for 30 min plus -> the update failed. It failed again for 25 addons and then at 24 addons the service worked.

**Comment by diox** [comment] 2022-11-03 14:43
(For the record, between yesterday and tomorrow we rolled back to the previous CDN for dev)

**Comment by Cade66** [comment] 2022-11-03 18:33
Still facing the issue here on latest Firefox 106.0.4 (x64) / Win7 (x64).

What seems odd is that 
1- Update is sometimes done, though very seldom. There is what appears as a random factor.
2- If the culprit is the number of extensions to update (I have 43 enabled and 2 disabled) then why is it that I encounter the failure when trying to update but one extension? 

Fortunately I landed on a reddit page mentioning the issue together with a link to here. Previously I've spent hours trying to wonder what was going on and when I thought I had found the solution because update succeeded I quickly disenchanted when later on facing the same problem : randomness. It all started with FF 106, but cannot remember if it was 106.0.1/2/3  ... We now check directly on AMO.

**Comment by diox** [comment] 2022-11-03 19:16
> 2- If the culprit is the number of extensions to update (I have 43 enabled and 2 disabled) then why is it that I encounter the failure when trying to update but one extension?

Firefox always updates all add-ons at once. If you look carefully in the add-on manager the menu with the option to check for updates is global, and no per add-on.

We've confirmed that this is related to a CDN change and we're in the process of rolling back to the one we were using previously, it will take up to a few hours for that rollback to be effective for everyone.

**Comment by nicolaasjan** [comment] 2022-11-04 05:14
Updates worked again here. 🙂
67 extensions (including search engines).

**Comment by diox** [comment] 2022-11-04 09:28
Rollback is complete.

**Closed by diox** 2022-11-04 09:28 UTC

**Comment by ioanarusiczki** [comment] 2022-11-04 11:49
Worked for me too, I reached 43 addons, I had no problems updating them at 30 min plus intervals.

**Comment by AlexandraMoga** [comment] 2022-11-04 11:57
It worked for me too on prod. I had a profile with 25 and another one with 50 addons which were both failing yesterday and now the addons are updated on both profiles.
