### ISSUE TITLE
"Activate Contributions" is returning an "Oops..." page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5956] opened 2017-07-20 07:42 UTC
Steps to reproduce:
1. Set up contribution for an add-on i.e. https://addons.allizom.org/en-US/developers/addon/webext-approve-r123/payments

Expected results:
Contributions can be set.

Actual results:
An "Oops..." page is displayed. Contributions cannot be set.

Notes/Issues:
- the "The Mozilla Foundation" option from section "Who will receive contributions to this add-on?" is the only option that works.
Verified on FF54(Win 7). Issue is reproducing on stage and dev.
Screenshots for this issue:
![activate](https://user-images.githubusercontent.com/15685960/28406152-ff026722-6d37-11e7-97ce-1e553e850b43.png)
![2017-07-20_1036](https://user-images.githubusercontent.com/15685960/28406151-fed434e2-6d37-11e7-858b-a530d935d603.png)

**Comment by diox** [comment] 2017-07-20 09:01
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/626607/
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/626606/

This is a problem with paypal's sandbox API not responding. Not much we can do about that :(

**Comment by ValentinaPC** [comment] 2017-07-20 09:11
@diox: we don't use the same paypal sandbox APi for "The Mozilla Foundation" option from section "Who will receive contributions to this add-on?" ? Because that option is working as expected.

**Comment by diox** [comment] 2017-07-20 09:15
I suspect we don't call the paypal API to check that this recipient is valid (since we know it is) and that's why it doesn't fail there.

**Comment by eviljeff** [comment] 2017-07-21 15:19
Is this cause for us accelerating the 'drop contributions and replace with a simple link' [changes](https://docs.google.com/document/d/1DjXQbl_hZlRe4bqE9B-cLPfq64wYFa19TU9DfsOpckQ/edit)?

**Comment by muffinresearch** [comment] 2017-07-21 19:34
Since this is on -dev and relates to the sandbox I think we can downgrade this from a p1.

**Comment by muffinresearch** [comment] 2017-07-21 19:36
> Is this cause for us accelerating the 'drop contributions and replace with a simple link' changes?

I don't think this particular issue is, but the sooner we can move away from the current implementation the better.

**Comment by diox** [comment] 2017-08-01 09:28
We're replacing contributions entirely in #6069, and this was only reproductible on dev anyway, so let's close this.

**Closed by diox** 2017-08-01 09:28 UTC
Labels: component: devhub, triaged
