### ISSUE TITLE
2 Firefox target app add-on with a restricted "maxVersion" returns 500 error page at submission if selected after an unrestricted legacy add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5172] opened 2017-04-13 13:58 UTC
Steps to reproduce:
1. Go to submission page and select a legacy add-on with unrestricted `maxVersion` i.e 51, with Firefox target application -  https://addons.allizom.org/en-US/developers/addon/submit/upload-listed
2. Do not click Continue button or refresh the page
3. Select a second legacy add-on with 2 target applications, both for Firefox, but the second with `maxVersion` restricted i.e 53

Expected results:
Second add-on is blocked at submission.

Actual results:
Second add-on passes validation. When "Continue" button is clicked and "Oops..." page is displayed.

Notes/Issues:
- both legacy add-ons must have same unrestricted Firefox `maxVersions` (this case 51.0)

Verified on FF52 and FF55 under Windows 7.
Attaching used extensions.
[fx51-sc.zip](https://github.com/mozilla/addons-server/files/919781/fx51-sc.zip)
[fx51-sc-double.zip](https://github.com/mozilla/addons-server/files/919782/fx51-sc-double.zip)

#4234

**Comment by diox** [comment] 2017-04-13 14:03
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/393949/

I don't think it's related to the legacy restrictions ; In fact, from the traceback, I think it must be possible to reproduce this with just one specially crafted add-on.

**Comment by ValentinaPC** [comment] 2017-04-13 14:16
There are 2 cases:
1. Is related to legacy add-ons only because if above STR are followed a legacy add-on with a version that should have been restricted, passes validation.

2. Is not related because, the 500 error page is displayed for any add-on, with 2 target applications.

After fixing the 500 error, it should be nice to recheck this scenario.
Thanks Mat, for checking this edgy case.

**Comment by diox** [comment] 2017-04-13 14:22
Looks like it's only related to the second add-on having duplicate target application. We should not 500 in this case. I guess it should be a validation error - Firefox probably does not care, but there is no good reason for accepting this.

**Comment by ValentinaPC** [comment] 2017-04-13 14:29
> Firefox probably does not care

Yes, you are right - Firefox does not care and returns: "1492093683723	addons.xpi	WARN	Ignoring duplicate targetApplication entry for {ec8030f7-c20a-464f-9b0e-13a3a9e97384} in install manifest"

**Comment by diox** [comment] 2017-04-25 08:47
Fixed in amo-validator 1.10.62 that has [just been merged](https://github.com/mozilla/addons-server/commit/3006c08abfc454fac3d15a587b40043f6a4ee9b4).

**Comment by ValentinaPC** [comment] 2017-04-25 15:06
Verified as fixed on AMO-dev FF53(Win 7).
If the submitted add-on has 2 target applications a corresponding error is returned.
Postfix screenshot:
![2017-04-25_1800](https://cloud.githubusercontent.com/assets/15685960/25392567/a5bcc19c-29e1-11e7-99e6-b37e20143c63.png)

@diox : Can #5257 be a regression of this?
ThanKs!

**Comment by diox** [comment] 2017-04-25 15:10
No, a different commit caused that regression in #5257, I'll update the issue.

**Comment by diox** [comment] 2017-04-26 12:46
From https://github.com/mozilla/addons-server/issues/5257#issuecomment-297378992 the original 500 is still happening when overriding validation, so a fix should be made in addons-server as well, not just the validator.

**Closed** 2017-04-26 13:57 UTC
Labels: component: devhub, project: legacy switch off, state: pull request ready

**Comment by diox** [comment] 2017-04-26 13:59
Note: when overriding failed validation because of duplicate target applications, the dupes will now be ignored, so if the min/max versions specified inside are different, well, too bad.

**Comment by ValentinaPC** [comment] 2017-04-26 15:17
> Note: when overriding failed validation because of duplicate target applications, the dupes will now be ignored, so if the min/max versions specified inside are different, well, too bad.

Ok.

Verified as fixed on AMO-dev Ff53(Win 7).
Postfix video:
![overr](https://cloud.githubusercontent.com/assets/15685960/25442054/a21054c0-2aac-11e7-8018-7a480db118d9.gif)
