### ISSUE TITLE
Cannot set Desktop only

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4868] opened 2017-03-07 13:20 UTC
With WebExtensions we don't support versions per operating system. There is just one choice really: Desktop, Android or both. Whilst WebExtensions work in both places, not all the APIs do. Or perhaps the add-on is only relevant to one use case.

However in the status and versions page, the platform choice is a drop down. So what I want to say is it supports Desktop. But I'd have to upload 3 versions of the same file and say one is for OS X, one for Linux and one for Windows, just so I can de-select Android.

<img width="721" alt="screenshot 2017-03-07 05 18 08" src="https://cloud.githubusercontent.com/assets/74699/23658027/b8c537fa-02f5-11e7-8967-c3046f0b8a96.png">

In my case I've removed the compatibility for Android below, hoping that works to hide it from Android users.

**Comment by eviljeff** [comment] 2017-03-10 10:52
When you add the Version (or create the Addon) you can select multiple checkboxes for all the desktop platforms in a single step (it creates the same File 3 times).

I don't think anyone specifically changed the upload step to preselect Android with all platforms, but it's more a consequence of other decisions to say WebExtensions aren't limited to a single application, like Desktop Firefox.

Although this issue references the version edit page the cause is the upload step.  So, do we have a [Desktop] and [Mobile] selection?  Is one or more of them pre-selected?  Should [Desktop] break down further into Mac, Windows, Linux selections?
@jvillalobos

(Potential footguns: `PLATFORM_ALL` is special, so if it was changed to exclude `PLATFORM_ANDROID` expect side-effects;  Application/Platform code is rather old and supports now obsolete things like `PLATFORM_SUN` and `amo.MOBILE` which we don't want to disturb without other clean-up being done.)

**Comment by andymckay** [comment] 2017-03-10 20:03
See also: mozilla/addons#348, #4455, #2830

**Comment by jvillalobos** [comment] 2017-03-13 22:31
We talked about this last week, and concluded we didn't need to support platform-specific files for WebExtensions, since it should be relatively easy to support all platform-specific cases in WebExtensions code. On the other hand, being able to state support for specific platforms (Desktop / Android / both, Windows / Mac / Linux / all) is still useful for developers.

Regarding this particular issue, I'd favor just dropping the platform selection in the dev tools page. We have been removing all file-specific operations after submission because they just lend themselves to causing weird problems, and it's much easier to submit a new version (modulo slow review queues...).

**Comment by eviljeff** [comment] 2017-03-14 12:39
> On the other hand, being able to state support for specific platforms (Desktop / Android / both, Windows / Mac / Linux / all) is still useful for developers.

Right, so what does that look like in terms of UX functionality?

**Comment by muffinresearch** [comment] 2018-02-02 20:23
@pwalm we could use some ux input on hwow to tackle this from a UI perspective.

**Comment by pwalm** [comment] 2018-02-06 23:30
Checkboxes seem to be the appropriate interaction here. Just click the specific platforms you're supporting. Could be an "all" checkbox selected by default (along with all the other platforms), and deselecting one platform would also uncheck "all."

**Comment by eviljeff** [comment] 2018-09-18 07:20
fixed with #9362

**Closed by eviljeff** 2018-09-18 07:20 UTC
Labels: component: devhub, needs: ux, priority: p3, triaged
