### ISSUE TITLE
HTTP 500 when signing into a pre-FxA account when there's already an FxA account under that email

### ISSUE THREAD

**Issue by strugee** [mozilla/addons-server#10811] opened 2019-02-28 04:45 UTC
### Describe the problem and steps to reproduce it:

1. Have an AMO account from before the Firefox Accounts integration under email a@example.com
2. Have an FxA account with b@example.org set as primary, a@example.com set as secondary
3. Sign in using the b@example.org FxA account and notice that it's a brand-new account
4. Set FxA primary email to a@example.com in an attempt to get back into the old AMO account
5. Sign into AMO with the FxA account again

### What happened?

Internal Server Error

### What did you expect to happen?

I should be logged into my old account. Not sure what should happen to the new account - I guess ideally it should be merged? (In my case I logged out right away so it's empty and can just be deleted but I'm assuming that's not true in the general case.)

### Anything else we should know?

Possible duplicate of #8765? I'm not _quite_ sure so I'll let people who know more than me decide. In any case I was asked to file a new issue in IRC, so here we go :-)

**Comment by EnTeQuAk** [comment] 2019-02-28 04:51
Talked on IRC and it's indeed a duplicate of #8765 so I'm closing this here.

**Closed by EnTeQuAk** 2019-02-28 04:51 UTC
