### ISSUE TITLE
500 error for "kanji-named" add-ons when adding an "Source code" file

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3222] opened 2016-08-05 08:58 UTC
Steps to reproduce:
1. Sign in to AMO-prod : https://addons.mozilla.org/en-US/
2. Click Tools -> Manage My Submissions
3. Click "Manage Status & Versions" from an add-on with "kanji name" (i.e. https://addons.mozilla.org/en-US/developers/addon/k-addon%E9%98%AA%E7%86%8A%E5%B2%A1%E9%B9%BF%E6%A2%A8%E9%98%9C%E5%9F%BC%E8%8C%A8%E6%A0%83/edit)
4. Click on any version
5. Go to "Source code" section and add a file
6. Save changes

Expected results:
The file is added and available.

Actual results:
An "Oops..." page is displayed.

Notes/Issues:
Verified on AMO-prod FF47(Win 7 x64). Issue is reproducing on all AMO servers.
Screencast for this issue: 
![500](https://cloud.githubusercontent.com/assets/15685960/17431708/f3bea2f0-5b03-11e6-908a-5ffbbbdce923.gif)

**Comment by wagnerand** [comment] 2016-08-05 09:04
I think this is a dupe of https://github.com/mozilla/addons/issues/132.

**Closed** 2016-08-05 09:19 UTC
Labels: devhub, duplicate
