### ISSUE TITLE
Thunderbird site redirect doesn't work for Thunderbird links without an explicit locale

### ISSUE THREAD

**Issue by Mannshoch** [mozilla/addons-server#9917] opened 2018-11-06 14:59 UTC
### Describe the problem and steps to reproduce it:
Klick on:
![grafik](https://user-images.githubusercontent.com/7795891/48071359-72cda500-e1da-11e8-809d-97cdbdd05a38.png)

### What happened?
![grafik](https://user-images.githubusercontent.com/7795891/48071439-9db7f900-e1da-11e8-8b4b-96f6c16f8f8d.png)
(some domains from github are listet as wrong domain )

### What did you expect to happen?
Find Changelog of lightning

### Anything else we should know?
If I open the Webpage without https this site appear:
![grafik](https://user-images.githubusercontent.com/7795891/48071580-f5eefb00-e1da-11e8-93ab-88a68bf0fa23.png)

**Comment by jvillalobos** [comment] 2018-11-06 16:23
The URL on your screenshots is incorrect. It should only have `/thunderbird/` instead of `/firefox/thunderbird/`. Do you know where you clicked to get to that page?

**Comment by Mannshoch** [comment] 2018-11-06 16:35
As shown on the first image I click on ... `die vollständige Versionsgeschichte.`
It links to: https://addons.mozilla.org/thunderbird/addon/lightning/versions/
and then I get redirected to: https://addons.mozilla.org/de/firefox/thunderbird/addon/lightning/versions/

it also happened If I directly open [https://addons.mozilla.org/thunderbird/addon/lightning/versions/](https://addons.mozilla.org/thunderbird/addon/lightning/versions/)

**Comment by jvillalobos** [comment] 2018-11-06 19:34
Thanks, that was helpful. I can confirm that:

* https://addons.mozilla.org/en-US/thunderbird/addon/lightning/ redirects correctly to https://addons.thunderbird.net/en-US/thunderbird/addon/lightning/, which is right.
* https://addons.mozilla.org/thunderbird/addon/lightning/ redirects to https://addons.mozilla.org/en-US/firefox/thunderbird/addon/lightning/, which is wrong.

The lack of locale in the URL is what appears to be confusing our rules.

**Comment by eviljeff** [comment] 2018-11-06 21:19
This is a dupe of #9836 (close one or the other)

**Comment by jvillalobos** [comment] 2018-11-06 21:40
Thanks, closing as a dupe of #9836

**Closed by jvillalobos** 2018-11-06 21:40 UTC
Labels: component: legacy frontend, priority: p2
