### ISSUE TITLE
Some extensions end up with `Awaiting Review` status after first version approval

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9582] opened 2018-10-03 22:37 UTC
This came up from the archive.org crawling of AMO. There's a number of extensions that end up in an incorrect status after their first listed version is approved. The version is approved correctly, but the status of the add-on is `Awaiting Review`. This makes the listing page not work, and could confuse developers into thinking their add-on is published when it isn't.

[This is a list of some extensions](https://sql.telemetry.mozilla.org/queries/59315/source) brought up that had that problem. I'm manually fixing their status now.

**Comment by eviljeff** [comment] 2018-10-04 10:36
There's nothing special in the activity/review logs; nothing in sentry from the selection of ids/slugs I tried; and the most recent add-on is from March this year, so too old for kibana / raw logs.

I think it's similar to #9040 and #6962 that @diox looked into before - i.e. there's a race condition with database transactions and/or celery tasks that means the status is updated to `Approved` status in one place but then overwritten elsewhere with the old status.  It looks like it was happening every few months before but the last broken addon was from 6 months ago... so, it's fixed already maybe with the changes @diox made then? 🤞   

At the very least we need this to happen again so we can get the logs, even if we can't reproduce reliably.  In the mean time, given we can't diagnose or replicate the problem, I'm closing.

**Closed** 2018-10-04 10:37 UTC
Labels: component: devhub, priority: p2, triaged
