### ISSUE TITLE
"More by artist" section should be aligned with "More <<Category>> Themes"

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2736] opened 2016-05-24 16:02 UTC
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

Steps to reproduce:
1.Go to a theme detail page for which the artist developed more than 4 themes (ie. https://addons-dev.allizom.org/en-US/firefox/addon/dark-fox-18066/)
2.Observe the "More by artist"and "More <<Category>> Themes" sections

Expected results:
The sections should be aligned (same height)

Actual results:
Sections are not aligned

Please see photo for this issue:
![notaligned](https://cloud.githubusercontent.com/assets/1583842/15510878/f22b6c80-21e1-11e6-8a26-f81ad0d015a5.png)

**Comment by tsl143** [comment] 2016-06-16 08:33
Unable to reproduce.
![screen shot 2016-06-16 at 2 03 18 pm](https://cloud.githubusercontent.com/assets/5318732/16110396/1da05178-33cb-11e6-8f54-6b963944827d.png)

**Comment by vcarciu** [comment] 2016-06-16 12:15
@tsl143 : the bug is reproducible at the bottom of 'More by artist' section(see red line from my photo)

**Comment by ValentinaPC** [comment] 2016-06-23 07:31
I think if we fix #2622, this also will be fixed. :smile: (I am talking about the issue from last comment of 2622). Thanks!

**Comment by tofumatt** [comment] 2016-06-30 10:52
Closed by #3029.

**Closed by tofumatt** 2016-06-30 10:52 UTC
Labels: good first bug, style refresh, triaged

**Comment by vcarciu** [comment] 2016-06-30 13:18
Verified as fixed : 
http://screencast.com/t/P3Y0kUY5Y
