### ISSUE TITLE
New add-on version automatically disabled without any feedback

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6587] opened 2017-10-04 18:22 UTC
The problem happened to the [Transparent standalone images](https://addons.mozilla.org/addon/transparent-standalone-imag/) add-on. 

Version 2.0 was submitted and auto-approved. Shortly thereafter, it was manually confirmed approved by a reviewer.

Version 2.0.1 was submitted within an hour or so of 2.0 (presumably after the manual confirmation), and it was just disabled. Nothing appears in the review log and it doesn't look like the developer did anything to change the add-on status or the version status. The developer didn't receive an approval email for that version.

The only thing that stands out is the manual confirmation. It could be that manual confirmation breaks auto-approval for future versions (real bad) or there was some timing issue and the manual confirmation happened around the same time of the new submission and something broke (less bad).

**Comment by msujaws** [comment] 2017-10-04 18:50
I'm the author of the extension. Jorge's description summarizes it well, but feel free to ask me anything else about my setup or steps if needed.

**Comment by diox** [comment] 2017-10-04 20:13
Approval confirmation does almost nothing, so this is quite weird. It should not touch the addon, any version of files, it sets a couple fields on another model and records an activity log, but that's it...

It's too bad this happened before https://github.com/mozilla/addons-server/issues/6516 had landed, since this adds additional logging around version disabling :(

There might be some logs in kibana that show what happened though, we'll check it out.

**Comment by ValentinaPC** [comment] 2017-10-05 13:30
> I'm the author of the extension. Jorge's description summarizes it well, but feel free to ask me anything else about my setup or steps if needed.

Maybe you hit the "Cancel and Disable Version" instead of "Submit Version"  by accident, while submitting the second version?

**Comment by msujaws** [comment] 2017-10-05 13:38
> Maybe you hit the "Cancel and Disable Version" instead of "Submit Version" by accident, while submitting the second version?

I don't believe so, but if I did should the status message not say "Disabled by Mozilla" ?

**Comment by ValentinaPC** [comment] 2017-10-05 13:41
> I don't believe so, but if I did should the status message not say "Disabled by Mozilla" ?

The status for that specific version, yes.
What was your version status?

**Comment by msujaws** [comment] 2017-10-05 13:43
Version 2.0 was marked as "Approved"
Version 2.0.1 was marked as "Disabled by Mozilla"

I seriously doubt I hit a "Cancel and Disable Version" button, but if I did then the UI should be showing something like "Disabled by Author" or something, and allow the author to enable it. I didn't see any way to enable the version once it had been marked as "Disabled by Mozilla".

**Comment by diox** [comment] 2017-10-05 13:48
> I seriously doubt I hit a "Cancel and Disable Version" button, but if I did then the UI should be showing something like "Disabled by Author" or something, and allow the author to enable it. I didn't see any way to enable the version once it had been marked as "Disabled by Mozilla".

Unfortunately, no, that particular button does result in "Disabled by Mozilla" and then you can't re-enable the version.

**Comment by ValentinaPC** [comment] 2017-10-05 13:55
> I seriously doubt I hit a "Cancel and Disable Version" button

I tried to reproduce your issue, using different scenarios, and couldn't, from where my assumption... :(

@diox : maybe we can add the re-enable option for this case, too? Or a "request review" link like it is while canceling submission for the first version of an add-on?

**Comment by msujaws** [comment] 2017-10-05 14:13
Yes please, a "re-enable" option or a "request review" would be good. As of right now, authors who get stuck in this state have no recourse.

**Comment by diox** [comment] 2017-10-05 17:08
Submitting a new version should work as a workaround in the meantime.

**Comment by diox** [comment] 2017-10-11 10:27
Going to close this as we have not enough clues to work on what happened. I do suspect that @ValentinaPC's assumption is right, and now that #6516 has landed we should have more logging to verify what the developer did if that happens to someone else in the future.

**Closed by diox** 2017-10-11 10:27 UTC
Labels: project: auto approval, triaged

**Comment by diox** [comment] 2017-10-11 10:38
I also filed https://github.com/mozilla/addons-server/issues/6646 which in turn might lead to being able to re-enable the version.
