### ISSUE TITLE
Reviewed (unlisted) file, what next?

### ISSUE THREAD

**Issue by jastrzebiec** [mozilla/addons-server#1708] opened 2016-02-17 23:42 UTC
Hello,
         I have submitted 2 plugins for review today.
They were submitted as unlisted, because they are bundled in my apps.
I do not know what to do next.
If I should download them back then I cannot, because there is not download option on the page.
What should be my the next step?
/jas

**Comment by wagnerand** [comment] 2016-02-18 00:10
Closing as this is not a bug report. Github issues are not a support forum. Moreover there is already a discussion on the amo-editors mailing list going on. Please stick to that.

**Closed by wagnerand** 2016-02-18 00:10 UTC
