### ISSUE TITLE
Addon validation fails with unexpected error if the manifest contains some invalid JSON syntax

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#18483] opened 2021-12-09 15:56 UTC
### Describe the problem and steps to reproduce it:
1. Upload an add-on with invalid JSON syntax in the manifest, for example missing comma (`,`) separators, closing brackets (`}`) or quotes (`"`) etc
2. Check the validation results

### What happened?
A "Sorry, we couldn't load your WebExtension" error is received

### What did you expect to happen?
An "invalid JSON" validation error should be received

### Anything else we should know?
So far, I've run into this error only on -dev and it is most likely the root cause for the errors I've noticed while verifying https://github.com/mozilla/addons-linter/issues/4061#issuecomment-988775248

**Comment by diox** [comment] 2022-01-14 11:45
This is a duplicate of https://github.com/mozilla/addons-server/issues/18612. It was filed before, but I missed this at the time.

**Closed by diox** 2022-01-14 11:45 UTC
Labels: component: devhub
