### ISSUE TITLE
Theme automatically applied when switching tabs

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5790] opened 2017-06-29 15:13 UTC
Steps to reproduce:

1. Press the "Alt" button and navigate to: "Tools>Add-ons".
2. Click on the theme "preview image".
3. Go to any other page in the browser.
4. Go back to the "about:addons" page.

Expected results:
The selected theme is not active.

Actual results:
The selected theme is active.

Notes/Issues:
Verified on AMO-dev FF54(Win 10)
Video for this issue:
![disco pane bug1](https://user-images.githubusercontent.com/28138132/27695022-760dc7be-5cf6-11e7-8b59-8ae2c84f26d3.gif)

**Comment by eviljeff** [comment] 2017-07-05 14:35
new disco pane is served by addons-frontend - can you re-log under that repository?

**Comment by muffinresearch** [comment] 2017-07-05 15:19
Dupe of https://github.com/mozilla/addons-frontend/issues/2651

**Comment by muffinresearch** [comment] 2017-07-05 15:22
> Related to mozilla/addons-frontend#2651 I think we can add to that bug.

Actually scratch that, it's not that similar after-all.

**Comment by SVSanta** [comment] 2017-07-06 15:07
Closing, moved issue to addons-frontend, [#2697](https://github.com/mozilla/addons-frontend/issues/2697)

**Closed** 2017-07-06 15:14 UTC
Labels: component: disco pane, platform: desktop
