### ISSUE TITLE
"+Keep it" theme button label has layout issues for Spanish on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2671] opened 2016-05-16 07:09 UTC
Steps to reproduce:
1. Load AMO-dev on your Android device
2. Go to "Other Languages" and change the lang to "Espanol"
3. Tap o any theme 

Expected results:
There are no display or layout issues.

Actual results:
The label of the installation button has layout issues.

Notes/Issues:
Verified on FF46(Android 5.0.1). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![2016-05-12_1125](https://cloud.githubusercontent.com/assets/15685960/15282763/00e2f4d6-1b4e-11e6-9ad5-85fd822c9908.png)

**Comment by eviljeff** [comment] 2016-05-17 17:29
mentor @muffinresearch 
Can you add some steps to get started for a contributor?

**Comment by wagnerand** [comment] 2016-07-26 17:55
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by muffinresearch** [comment] 2016-07-27 09:14
Since we've started on overhauling the mobile pages currently with a view to replacing them entirely this might not be worth spending time on unless it's a very small patch which is unlikely to cause any regressions.

**Comment by muffinresearch** [comment] 2016-11-08 12:19
Closing this since the new mobile pages are incoming.

**Closed by muffinresearch** 2016-11-08 12:19 UTC
Labels: Android, good first bug, triaged
