### ISSUE TITLE
Investigate speeding up the language tools API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6850] opened 2017-11-06 15:47 UTC
### Describe the problem and steps to reproduce it:

* Load this page in a desktop browser https://addons.mozilla.org/en-US/firefox/language-tools/

### What happened?

It requests GET https://addons.mozilla.org/api/v3/addons/language-tools/?app=firefox&lang=en-US

The response time is 1.5 seconds on average and has gotten slower after the release (possibly due to increased load).

<img width="824" alt="screenshot 2017-11-06 09 41 29" src="https://user-images.githubusercontent.com/55398/32449467-42f9bf94-c2d7-11e7-8ba6-66051d031bf2.png">

### What did you expect to happen?

This API should respond quicker

### Anything else we should know?

**Comment by diox** [comment] 2017-11-08 20:11
Main problem is that is contains a lot of stuff, so it's bound to be somewhat slow. The legacy view wasn't loading fast either, at some point some caching was added to mitigate this, maybe this is a good idea (as long as we keep it simple).

Of course, before doing that, we need to look at what we can trim and whether the queries it does can be optimized.

**Comment by eviljeff** [comment] 2018-02-01 18:17
Stripping out `current_version` has cut the response down from about 1.75 seconds to about 1 second.  It's pretty good IMO - is it good enough to close the issue?

**Comment by diox** [comment] 2018-02-01 18:33
Our OKR is under 500ms, so we'll have to do more work :)

**Comment by diox** [comment] 2018-02-01 18:40
I think the next step is to cache this heavily, since it does not change often. Maybe even pre-build it on deploy.

**Comment by eviljeff** [comment] 2018-02-02 19:27
@jvillalobos @wagnerand fyi the language tools response is cached for up to 24 hours now so bear that in mind if you add/remove any addons by changing `target_locale`.

**Comment by AlexandraMoga** [comment] 2018-02-06 11:41
My average response time for https://addons-dev.allizom.org/en-US/firefox/language-tools/ is somewhere at 1.2s.
@eviljeff I'm not sure what was the final target eventually.

**Comment by diox** [comment] 2018-02-06 11:46
@AlexandraMoga : it's 500ms. But dev is not very reliable for this, and furthermore because of the caching strategy it needs more traffic to achieve a better average speed. We'll monitor this ourselves using datadog as it's a OKR for this quarter. You can verify that this does not cause any regressions (besides the obvious fact that changes need up to 24h to propagate)

**Comment by AlexandraMoga** [comment] 2018-02-08 12:57
There were no other regressions spotted around the language tools page. 
Marking this as verified fixed

**Comment by eviljeff** [comment] 2018-02-09 15:13
re-opening this as datadog shows... basically no change.  Still averaging just less than a second which seems bizarrely high if every response after the first didn't have to hit the database at all for 24 hours.
Possibilities:
A) bug in the code and memcache isn't being used;
B) we're still sending too much data and we should consider pagination.

**Comment by diox** [comment] 2018-02-09 21:41
Random guess, would need some logging or cache stats to check: not enough requests to language tools so the cached data is evicted out of the cache before being useful. That'd be wild...

**Comment by eviljeff** [comment] 2018-02-10 07:31
According to datadog it's getting an average of 38 requests every 30/min.  We don't know what combination of `lang` and `application` they were, but that's 1,824/day so at least _some_ of them have got to be duplicates that should have been returned from memcache.  The cache expiry was supposed to be 24 hours... so if it's happening more frequently than that then why?

**Comment by diox** [comment] 2018-02-10 11:54
Memcached will evict things from its cache long before they have reached their expiration date, if there is not enough memory to store everything, following a Least Recently Used algorithm. It's therefore perfectly possible that the language tools cached data gets evicted since its usage is quite low for all the things we store in memcached (all cache-machine data)

That's why we'd need logging (to see cache misses) or cache stats (to see eviction rate) to find out. We should already have cache stats somewhere.

**Comment by eviljeff** [comment] 2018-02-12 12:18
After looking into cache stats and discussing on IRC we've decided to stop work on this until after cache-machine is removed.  Cache-machine fills up memcache with frequent requests that mean less frequently requested data - like the lang tools response - is evicted before being used.

**Comment by diox** [comment] 2018-03-05 15:31
For reference, a datadog dashboard with the eviction and cache miss stats: https://app.datadoghq.com/dash/569624/amo-prod-memcached-stats

**Comment by diox** [comment] 2018-03-07 16:53
#7676 should have helped, will monitor the situation.

**Closed** 2018-03-08 10:56 UTC
Labels: component: api, priority: p3, qa: not needed, triaged

**Comment by diox** [comment] 2018-03-08 18:47
Just beautiful:

![language-tools-api-perf](https://user-images.githubusercontent.com/187006/37169863-6e4cfb06-2309-11e8-9db7-4a6f93d69077.png)

**Comment by eviljeff** [comment] 2018-03-09 06:43
That's an amazing reduction!
