### ISSUE TITLE
missing extension for iCloud Bookmarks

### ISSUE THREAD

**Issue by kvandrunen** [mozilla/addons-server#3186] opened 2016-07-27 16:16 UTC
this extension is not found as an Add-on for Firefox:
iCloud Bookmarks

**Comment by jvillalobos** [comment] 2016-07-27 16:29
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.

**Closed by jvillalobos** 2016-07-27 16:29 UTC
