### ISSUE TITLE
Content review list - extra reviews

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#14441] opened 2020-05-29 13:49 UTC
Hello,
in the content review list Modern Deck (https://reviewers.addons.mozilla.org/en-GB/reviewers/review-content/moderntdeck) is present and when we watch in details this add-on has been content approved
on version 6.5.3 on April 18, 2019. 
It should not appear or did I miss something about the workflow?

Also Shortcuts for search (https://reviewers.addons.mozilla.org/en-GB/reviewers/review-content/shortcuts-for-search) is present as well despite that the add-on as been content approved 2 times.

Regards,
Hubert LAFONT

**Comment by eviljeff** [comment] 2020-06-01 09:22
content review gets re-triggered if the developer changes the metadata (name or summary in any locale) via developer hub.

@wagnerand

**Comment by wagnerand** [comment] 2020-06-02 09:30
If the name or summary change is the cause, then I think we can close this issue. Please reopen if that's not the case.

**Closed by wagnerand** 2020-06-02 09:30 UTC
