### ISSUE TITLE
Allow SVG in Edit Product Add-on icon

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#19106] opened 2022-04-11 11:20 UTC
Many addons use SVG as their icon but AMO Edit Product doesn't support SVG.

> PNG and JPG supported. Icons will be resized to 128x128 pixels if larger.

**Comment by eviljeff** [comment] 2022-04-11 13:02
dupe of https://github.com/mozilla/addons-server/issues/4161

**Closed by eviljeff** 2022-04-11 13:02 UTC
