### ISSUE TITLE
Update mysql transaction level to "read comitted"

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7158] opened 2017-12-19 13:38 UTC
Since https://github.com/django/django/commit/f01ad1cb6a27669fd44b2079089e14f9dc4d3ca3 (thus django 1.11) it's finally possible to set a proper isolation level.

We have a workaround in form of `safer_get_or_create` on our models which is very rarely used though.

And with Django 2.0 it switches the default to a more safe `read committed`.

Are we using any server settings that are different from mysql's `repeatable read` default? @bqbn 

cc @diox to chime in on this discussion. I'd argue that it's a very good idea to do but there might be reasons why we don't want to do it. It also means that we'll have to re-test a hell lot of stuff if we land a change like that.

**Comment by diox** [comment] 2018-01-03 10:58
Switching to `read committed` seems like a good idea, if only to try to reduce potential deadlocks... I don't think it should have much negative impact - we don't do much real deletes, and any weird inconsistencies caused by data depending on multiple tables etc are already happening potentially because of how we use cache-machine/transforms.

**Comment by bqbn** [comment] 2018-01-03 19:15
@EnTeQuAk , to your question, the answer is no. Our RDS server uses the default value for `tx_isolation`, which is `REPEATABLE-READ`.

**Comment by EnTeQuAk** [comment] 2018-01-04 10:54
sweet, let's do this then after we land django 1.11

**Comment by EnTeQuAk** [comment] 2018-05-31 06:33
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/3272326/

Linking this deadlock problem to this issue, since this might help solve it.

**Closed** 2018-08-21 17:07 UTC
Labels: component: code quality, priority: p3, triaged

**Comment by AlexandraMoga** [comment] 2018-08-30 14:17
There were no regressions found during our release testing.  Marking the issue as verified fixed in -dev and stage.
