### ISSUE TITLE
Content review queue contains all add-ons

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#11791] opened 2019-07-04 18:56 UTC
The content review queue now has many hundreds of thousands of entries, it looks like all the add-ons.

In addition, content reviewers can no longer reject add-ons in content review. It works fine in technical review.

**Comment by jvillalobos** [comment] 2019-07-04 19:26
Duplicate of https://github.com/mozilla/addons-server/issues/11792 (I know this one came first, but the other one has better tags :P)

**Closed by jvillalobos** 2019-07-04 19:26 UTC
Labels: component: reviewer tools, priority: blocks release
