### ISSUE TITLE
Allow manual version range setting for multi-blocks

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12936] opened 2019-11-22 10:11 UTC
The current multi-block interface shows the version range disabled and locked to 0-*. It would be good for multi-block interface to show textboxes for the min and max version instead so admins can manually enter a version range if needed. We don't need to validate those values or provide a dropdown of all valid versions. Admins can figure out the right versions, but having a way to manually set a range would be quite useful.

**Comment by jvillalobos** [comment] 2019-11-22 19:37
The admin is designed to be somewhat strict around version numbers because v3 of the blocklist would essentially be a list of guids and versions being blocked, so it'd be good that version ranges are easy to map out into a list. If this change doesn't interfere with that, I'm okay with it.

**Comment by wagnerand** [comment] 2019-11-22 22:39
I am not sure what you mean by "map out into a list", but all I am asking for is not to hard-code 0-*, but to allow admins to enter a value manually. I don't think that changes anything for the blocklist v3, since the entries would be exactly the same, except that wouldn't necessarily have 0-*, but whatever was specified in the admin.

**Comment by eviljeff** [comment] 2019-11-25 09:35
The versions specified in a block as min and max are always supposed to correspond to actual versions on AMO, because they'll be expanded to a list of addon+versions in v3.  But, the decision made in https://github.com/mozilla/addons-server/issues/12452#issuecomment-542325152 was to rely on the version string for comparision so it doesn't strictly matter if a min or max version corresponds exactly to a version - it'll still work.

It does, however, add some complications.  If a min/max version range is specified that doesn't fix _any_ versions for an add-on in the multi-block input, then nothing will be blocked for that add-on, even though it'll appear that there is a block present in the list.  And for the UI, the edit view for a single block currently shows the list of versions, so that will be inconsistent if value is specified outside of the list (there are options to address that, like selecting the "closest" version that fit).

If the likely scenario is a bunch of near identical (in terms of versions and version numbers) add-ons being blocked, it's low risk.  If you're blocking a list of disparate add-ons and manually supplying a min/max version then it's introducing the same kind of fragility you have right now with the kinto admin ui - what will and won't be blocked is difficult to be sure of, and it's easy to make a mistake.

**Comment by jvillalobos** [comment] 2019-11-25 22:23
> If the likely scenario is a bunch of near identical (in terms of versions and version numbers) add-ons being blocked, it's low risk.

That's my understanding, so I'm okay with moving forward with this.

**Comment by eviljeff** [comment] 2019-11-26 14:31
I'm mid-implementation and I'd like to try to match the min/max versions entered to valid versions on the affected add-ons.  
Min and max are valid versions (or are `0`/ `*`) is the trivial case; when other values are specified I was thinking we need to iterate through the versions on the addon and chose the closest that fit the range.  It would mean shortening the range though.  Also, it's not clear what to do when they _aren't_ any valid versions in the range.

E.g.
addon_a.versions = ["1.1", "2.2", "6"]
addon_b.versions = ["1.1", "2.2", "5"]
addon_c.versions = ["1.1", "1.2"]
A multi block with min_version="2.2" and max_version="6" is specified.

For addon_a the block would be min_version="2.2", max_version="6";  (Trivial case)

For addon_b the block would be min_version="2.2", max_version="5".  This is valid, but if the developer subsequently creates a version="6" it **won't** be blocked.

And for addon_c?  
- Don't block anything so don't add the Block for that GUID?
- Add the Block with "0" - "*" ?  (which would affectively be blocking "1.1", "1.2" and any future versions)
- Add the Block with min_version="2.2", max_version="6" as specified.  If won't block _any_ current versions so will be kinda misleading.

**Comment by wagnerand** [comment] 2019-11-26 14:34
If we do

> Add the Block with min_version="2.2", max_version="6" as specified. If won't block any current versions so will be kinda misleading.

can the system warn the user for those cases?

**Comment by eviljeff** [comment] 2019-11-26 15:35
> If we do
>
>>    Add the Block with min_version="2.2", max_version="6" as specified. If won't block any current versions so will be kinda misleading.
>
> can the system warn the user for those cases?

The problem is: warn _when_ exactly?  We won't know what versions you'll enter until the values and press submit, and at that point it's handed off to a celery task to create the Blocks, etc.  For bulk blocks we don't even query the versions the addons have until the celery task to allow for minimal database queries for the very large lists of guid specified in the PRD/issues.

**Comment by wagnerand** [comment] 2019-11-27 10:44
Hm, I was expecting we would have a validation step for at least the GUID even for bulk blocks. Wasn't the idea that we should show a confirmation step for high-profile add-ons anyway?

**Comment by eviljeff** [comment] 2019-11-27 12:34
See the PRD and the drawings, in particular #12458.  The page where you would be able to define the min/max versions _is_ the confirmation step.

**Comment by wagnerand** [comment] 2019-11-27 13:53
Let's

> Add the Block with min_version="2.2", max_version="6" as specified.

for now. The scenario is the low-risk one your pictured, so I am not very concerned.

For accessing the single/edit block for such an add-on afterwards, let's clear show the history with the information specified in the block, but have the version-selects an empty or invalid value to avoid an admin accidentally just hitting "Submit" and thus overriding the existing block before double-checking (by manually changing the version range).

**Closed** 2019-12-03 10:27 UTC
Labels: component: admin tools, priority: p3, state: pull request ready, triaged

**Comment by AlexandraMoga** [comment] 2019-12-04 12:41
@eviljeff I've tried manually input some min - max version ranges but for any value other than `0 - *`   https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/multiblocksubmit/add/ responds with a 500 server error.

A specific example:
I took 3 GUIDs from -dev: 
{57bd783b-7eb6-47ff-80ea-7468894373d4} -  version strings: `1.0`
{5ee01a1e-589f-4f3d-ad96-477772b6ec0a} - version strings: `1.0, 1.0.3`
{acd14912-7a3e-4703-a8c7-0bd11c8583ae} - version strings: `1.0, 1.7, 1.1.1-signed`

In `/multiblocksubmit/add/ ` I've added the following min - max version range: `1.0 - 1.7`

**Comment by eviljeff** [comment] 2019-12-04 15:16
Looks like I forgot to land the migration.  https://github.com/mozilla/addons-server/pull/13036 will fix it.

**Comment by AlexandraMoga** [comment] 2019-12-05 14:12
I repeated the scenario described above and the manual version input worked this time. The results were the following:
- {57bd783b-7eb6-47ff-80ea-7468894373d4} - version `1.0` and any subsequent versions `<= 1.7`  were blocked; max version set to `(invalid)`
- {5ee01a1e-589f-4f3d-ad96-477772b6ec0a} - same as above
- {acd14912-7a3e-4703-a8c7-0bd11c8583ae}  - versions `1.0` to `1.7` were blocked, since the add-on had both a min and max version string equal to the range provided

Notes:
- if both min and max versions turn out to be `(invalid)`, none of the add-on versions are blocked

Admins are able to spot and correct `(invalid)` versions on the change block page:
![image](https://user-images.githubusercontent.com/31961530/70242581-bbf37e00-1779-11ea-8fd7-e9a8ab2bf10e.png)
